### ISSUE TITLE
Editor Default Resources

### ISSUE THREAD

**Issue by pvloon** [Unity-Technologies/PostProcessing#1]
As Installation mentions, Editor Default Resources folder has to be in root of your project. I'd love to keep an active checkout in my project however and doing that in the root is not viable. 
Right now there doesn't seem to be a clean way to do this and the problem would need to be solved if this gets moved to Standard Assets anyway. So I feel like either:

A. Unity fixes it so Editor Default Resources can be anywhere in the hierarchy (like they have been doing with other special folders)
or 
B. Post processing system uses a different system to load these assets (AssetDatabase.Load potentially? still would need to deal with relative paths).

Thanks!

**Comment by Chman** [comment]
Fixed in 3e34079.

To upgrade from previous versions you should remove PostProcessing and Editor Default Resources from your project first.
