### ISSUE TITLE
AO fail in some particles systems. 

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#104]
I use particles with the default Unity shader "FX/Glass/Stained BumpDistort" for a Heat Distortion effect and the AO effect fail and darken this particles horribly, this type of particles dont need AO, is possible that AO effect ignore all or selected particle systems?, thanks.

**Comment by Chman** [comment]
AO relies on the existing depth & normal buffers. It has no knowledge of particles or geometry. So this is not an issue with AO but with the shader you're using.

I just took a quick peek at the stained glass shader you're referring to, you probably want to change line 15:

`Tags { "Queue"="Transparent" "RenderType"="Opaque" }`

To:

`Tags { "Queue"="Transparent" "RenderType"="Transparent" }`

**Comment by nestg** [comment]
This resolve the problem, thank you very much.
