### ISSUE TITLE
USer Lut Issue

### ISSUE THREAD

**Issue by RichardRubina** [Unity-Technologies/PostProcessing#105]
Hi,

I downloaded the Post Process Stack and it works good in Editor however, when I try to build a PC platform

I get this problem:

![userlut - build pc version](https://cloud.githubusercontent.com/assets/11243097/23339690/923aa8f2-fc62-11e6-93d0-03aad8691a48.jpg)

This is the Editor Version:

![userlut - editor](https://cloud.githubusercontent.com/assets/11243097/23339699/b432e0dc-fc62-11e6-91e5-93d143d028f4.jpg)

Even if I use the default LUT textures (NeutralLUT_16 and NeutralLUT_32) that come with the Post Process Stack it still has that problem.

Thanks!

**Comment by JacobSmaga** [comment]
Have this issue too https://github.com/Unity-Technologies/PostProcessing/issues/86

**Comment by RichardRubina** [comment]
Hi Jacob,

Thanks for that. Yup it solved the issue. I'll just close this one now.
