### ISSUE TITLE
Screen Space Reflection Doesnt work with Standard Fade Shader

### ISSUE THREAD

**Issue by deodatopr** [Unity-Technologies/PostProcessing#106]
If you use Satandard Shader Opaque, Sreenspace reflection works good, but if I change the Opaque to Face or any transparent or cutout, the reflections gone of the near obj
![captura](https://cloud.githubusercontent.com/assets/16979750/23527163/726417d4-ff5a-11e6-8c89-0909f0cfd418.PNG)
ets.

**Comment by Kink3d** [comment]
Screen Space Reflections only work on objects rendered in deferred. Even in the deferred rendering path transparent objects (transparent and fade in Standard shader) are still rendered in forward after the deferred passes are finished and therefore wont be used for SSR.

However, I dont think this should be the case for Cutout shaders so I'll look into it.

**Comment by Kink3d** [comment]
![image](https://cloud.githubusercontent.com/assets/11135817/23850034/b416015a-07d5-11e7-81cc-f3e0af76d9e3.png)

Hi, above is a screenshot of SSR working with Opaque (left) and Cutout (right) in 5.5. I also checked in latest 5.6 beta just to be sure. If you continue to have problems with Cutout and SSR and want us to take a look at it, you can reopen this and send a small reproduction project.

**Comment by deodatopr** [comment]
Hey,

THanks for post... thanks about it.... but the problem is not use transparent in the meshes above, the problem is when you use transparent material in the reflected mesh, in this case the floor is using just opaque not transaparent material.... but in this case the plane and the box use it, and you could see in the floor reflection color white accumulation in the reflection, this is a little bit wrong, because this is the color of the mesh and add it the background, but the background doesnt appeare in the reflection just blue color.
