### ISSUE TITLE
TAA makes opacity objects look smaller

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#110]
Without TAA:
![2](https://cloud.githubusercontent.com/assets/18855621/23694177/59e4a418-0413-11e7-9af1-1b9cf9d221cc.PNG)

TAA enabled:
![1](https://cloud.githubusercontent.com/assets/18855621/23694203/7848d14a-0413-11e7-9b09-2dbf9c37426a.PNG)

The orange lines in second image have offset with transparent glass.
Unity version 5.6.0b10, asset was downloaded from asset store.

**Comment by Chman** [comment]
This is probably linked to #103. We fixed it in master but it hasn't reached the asset store yet. Any chance you could grab the latest version from master and try it?

**Comment by silentlamb1991** [comment]
I just try the latest version and it's OK!

**Comment by Chman** [comment]
Good to know, thanks 👍
