### ISSUE TITLE
Enable Fog error: Invalid pass number (1) for Graphics.Blit (Material "(Unknown material)" with 1 passes)

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#111]
Enable Fog output error: Invalid pass number (1) for Graphics.Blit (Material "(Unknown material)" with 1 passes)
And fog has no effect, and if doesn't exclude skybox screen becomes magenta.
Unity version 5.6.0b10, asset was downloaded from asset store.

**Comment by imGua** [comment]
I'm having this error in Unity 5.6f3, how did you fixed it?
