### ISSUE TITLE
[V1] Animating and blending effects

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/PostProcessing#117]
Hello,

I was wondering if you had in mind a process to animate / blend effects together.

The main use case I have in mind, is when you enter a specific zone (trigger) and you want to change the ambiance. You will then modify your color correction.

Right now the only way, would be to store the new CC somewhere (other scriptableObject ?), and blend all the parameters in the CC programmatically.

Maybe if the stack behavior could have multiple entries of stack scriptableobject, and maybe a blend value between each ? and only applying the ones that are checked ?

Not sure I was clear, but it's something done a lot in game, and I think "Amplify Color" has something like that.

Thanks

**Comment by LKGames** [comment]
+1, transition support would be neat

**Comment by Kink3d** [comment]
Hey, we are working on a solution for this but its a big job so its taking a while. Ill leave this open for others to see the response.

**Comment by Ziboo** [comment]
Thanks for the quick response.

Found this: https://github.com/keijiro/PostProcessingUtilities

But I know that keijiro is already working on the PostProcessing Stack and Unity Team (I think)

I guess it was more a test.

Do you already have feedback on this implementation ? just by curiosity

**Comment by Ziboo** [comment]
What about having a nested ScriptableObject for each categories ? (DOF, Fog, ...)

Like that we could just change one of them, like:

`SetFog(Resources.Load<FogDefinition>("fog.asset"));`

Even better, add a blending time:

`SetFogBlending(Resources.Load<FogDefinition>("fog.asset"), 2f);`
