### ISSUE TITLE
[V1] Black artefacts with DoF

### ISSUE THREAD

**Issue by alastaira** [Unity-Technologies/PostProcessing#123]
I'm getting occasional black artefacts in my scenes when using the DoF effect - see picture below (in this screenshot, the character is a 2D sprite, and the caves are a 3d mesh). They always appear around the same parts of a mesh and appear to move in worldspace with it. The size of the artefact increases with the size of the kernel although doesn't particularly seem related to the distance of the mesh from the camera - it maintains the same size in screen space at all distances until the mesh becomes vary far away, at which point the artefact simply disappears completely. 

Any ideas what's causing this and, I suppose even more usefully, is there anything I can do to solve it?!
Thanks :)

![dof artefact](https://cloud.githubusercontent.com/assets/901056/24081779/c243c6f0-0cb1-11e7-8d65-3aaac1fc7804.jpg)

**Comment by Chman** [comment]
Hey,

Do you use custom shaders or only the standard one? Also, do you have any other post-processing effects applied to the camera?

**Comment by alastaira** [comment]
The sprite is using a custom shader but the mesh in the background is the standard shader. I just tried disabling the sprite and the artefact remained, so I think that can safely be ignored. I also tried changing the mesh material on the rocks to use Unlit/Texture but the artefact remained.

There are no other camera effects, and only Depth of Field is enabled in the post-processing stack. The artefacts are not showing up in depth or normals debug view. It remains in both forward and deferred rendering,

**Comment by Chman** [comment]
Any chance you could send us a repro-project so we can debug it and find out what's wrong?

**Comment by alastaira** [comment]
Thanks for the reply. I'll need to check whether we can create a trimmed down repro version for you (current project is 8Gb!) - is there a private/secure respository we can use to transfer to you?

Meanwhile, I have made some further investigations - the problem seems related to some conflict between the Depth of Field effect and the Skybox we're using. Indeed, setting the clear flags of the camera to "Solid Color" rather than "Skybox" fixes the issue completely. 

We're using a procedural skybox shader with atmospheric scattering that's been hacked together from various places; I've just tried to have a quick look through it to identify what could be causing the problem but it's very scrappy. I do remember having issues with renderqueues with it some time ago though (in order to render a transparent moon drawn over the skybox), so this could be related, although it's been having fine in all other places - just not with the DoF effect on certain meshes.  Will carry on looking!

**Comment by alastaira** [comment]
And the artefacts only occur when the camera is set to HDR...

**Comment by Chman** [comment]
> a procedural skybox shader with atmospheric scattering

If you have atmospheric scattering I'm guessing you have a post-processing effect to back this up as well, right? This is the reason I ask this question earlier:

> Also, do you have any other post-processing effects applied to the camera?

This black splotch looks like a NaN pixel went through the blur filter in DoF (which is why it looks so big). The best way to check would be to do a [RenderDoc capture](https://docs.unity3d.com/Manual/RenderDocIntegration.html) in Unity and look for this NaN pixel before the DoF pass actually happens. If it's there, then something's wrong with your shader for atmospheric scattering. If it only appears during the DoF pass then it's a DoF issue.

As for sharing a trimmed down project, you can send it to me via [email](mailto:thomashourdel@unity3d.com). Or if it's too much work, at least send me a RenderDoc capture so I can check if DoF is the issue or not (you can save RenderDoc captures, it'll be way smaller than a complete project) :)

**Comment by alastaira** [comment]
Thankyou again for your continued help. There's no post-processing effect - it's all just done in the skybox shader. I'm not familiar with RenderDoc, but having just read up on it, it certainly sounds like it would be a pretty helpful tool to have anyway :) I'll try downloading and attaching it to the project and will let you know how I get on!

**Comment by Arhurullo** [comment]
Hi!
The same thing happened to me, and that was because I'am using an atmospheric scattering effect.
Remove the atmospheric scattering solves the problem.

This is the atmosferic effect in particular: https://www.assetstore.unity3d.com/en/#!/content/14557

I hope this may help you.

**Comment by cuah123** [comment]
Hello 

Just downloaded Unity 5.6, I had 0 graphic artifacts using the old scripts system.  When I add the Post process profile I see black spheres, but only through parts of Trees.  I am using 0 custom shaders, completely Vanilla out of the box.  The Trees the default trees created in Speed Tree and placed there using the Terrain Editor.

**Comment by Kink3d** [comment]
Hi,

Like @Chman said previously this is likely a NaN pixel going through the blur filter, this time in speedtree somewhere. I will talk to the terrain/speedtree team on Monday to try to look into this for you

**Comment by Kink3d** [comment]
@cuah123 Could you provide a small reproduction project of this? I cant get any artefacts using Speedtree with DoF.

Which platform/operating system/graphics API are you using?

**Comment by cuah123** [comment]
Windows 10 64 bit Updated as of 4/5/2017
Nvidia 1080 GTX Updated drivers
Vanilla Unity, "straight out of the box"
I'm using the new Post Process Profile provided by Unity 5.6.0f3
When I place the DOF or Bloom in there, I see black or white artifacts respectively
More Details:
Look towards a Dynamic Light set as Sun and the tree between you.
I have a flare on the sun and a flare layer on the player camera

**Comment by dorodo95** [comment]
Any updates on this issue? This has just appeared to me while adding DOF for our cinematics. Only DOF and AO are enabled. As mentioned above, this issue does not happen if HDR is turned off in the camera settings.

https://image.prntscr.com/image/9aea53287d8f48179dfd8f8150e8629a.png

**Comment by FGoset** [comment]
I found the problem disappears when you ser the Rendering Path to deffered

**Comment by dorodo95** [comment]
Unfortunately, so are we. We've turned off HDR in the camera settings for now as a quick fix, which is unfortunate as our project uses a lot of emission for our effects.

**Comment by Chman** [comment]
In all the repro cases we could get our hands on it was never an issue with DOF but with another effect or object shader happening before the DOF pass. The fact that you see these as square-ish shapes means DOF is trying to blur a NaN pixel. Send us a repro-project or a RenderDoc capture showing the artifact and we'll be able to tell you where it's coming from.

**Comment by FGoset** [comment]
![screenrenderdoc](https://user-images.githubusercontent.com/29255659/28012702-f0d1bbf4-6566-11e7-99f9-7d9e0025c495.png)

[RenderDocLog.zip](https://github.com/Unity-Technologies/PostProcessing/files/1135095/RenderDocLog.zip)

**Comment by FGoset** [comment]
This bug does not seem to appear on Mac

**Comment by Chman** [comment]
Hey @FGoset thanks for the capture. You can see the NaN is already there in the input texture passed to DOF. Unfortunately this capture is missing a lot of debug information and makes it hard to track down the issue. Any chance you could do another capture from the editor ([like this](https://docs.unity3d.com/Manual/RenderDocIntegration.html)) this time so it comes with all the debug info?

**Comment by FGoset** [comment]
Here is a capture in the editor. As you say, it seems that the NaN pixel is in the objet before the DOF effect. But I don't know why it works on Mac. By the way, I use this script to load my model: https://www.assetstore.unity3d.com/en/#!/content/49547

[RenderDocLog2.zip](https://github.com/Unity-Technologies/PostProcessing/files/1135257/RenderDocLog2.zip)

**Comment by Chman** [comment]
![image](https://user-images.githubusercontent.com/849090/28016466-bb1dd6ba-6574-11e7-9268-0fb700414c30.png)

Yep, right where my cursor is on the screenshot. Let's dig into the mesh itself then...

![image](https://user-images.githubusercontent.com/849090/28016561-34f2e890-6575-11e7-9571-519d34804020.png)

Here you go. You can see zero'd normals. This is bound to fail at some point. Not sure if it comes from your importer or not, but this is where your problem is :)
