### ISSUE TITLE
Force No motion object still has motion blur effect

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#124]
![-1](https://cloud.githubusercontent.com/assets/18855621/24152983/301488a4-0e88-11e7-9c95-c47e875bd535.png)
Unity 5.6.0f1

**Comment by Kink3d** [comment]
Hi, 
This works fine for me in simple tests. Are you using Frame Blending? Which platform/API? Reproduces in editor/player/both? Its easier if you can send a simple reproduction project.

Thanks

**Comment by Kink3d** [comment]
Closed for inactivity

**Comment by silentlamb1991** [comment]
I made a small project to reproduce this bug, but can't upload it. Could you please give me an e-mail so I can send the project to you? @Kink3d
