### ISSUE TITLE
[V1] Manipulating effects via C# script

### ISSUE THREAD

**Issue by pedro15** [Unity-Technologies/PostProcessing#127]
i tryed to modify the effects by code and i only get an nullreference exeption and black screen. 

```
            var PostProcess = GameCamera.Instance.GetComponent<PostProcessingBehaviour>();
            ColorGradingModel.Settings settings = new ColorGradingModel.Settings();
            ColorGradingModel.BasicSettings basicSettings = new ColorGradingModel.BasicSettings();

            basicSettings.saturation = c / t;

            settings.basic = basicSettings;

            PostProcess.profile.colorGrading.settings = settings;


```
So there are offcial support to modify the settings in runtime via code or simply not ?  if not i will still using the 'Cinematic image effects'.

**Comment by malvakian** [comment]
Hi pedro, try this.

PostProcessingBehaviour filters = GetComponent<PostProcessingBehaviour>();
// Profile from scratch
//PostProcessingProfile profile = ScriptableObject.CreateInstance("PostProcessingProfile") as PostProcessingProfile;
// Or modify current profile
PostProcessingProfile profile = filters.profile;

profile.vignette.enabled = true;
VignetteModel.Settings g = profile.vignette.settings;
g.intensity = 1;
profile.vignette.settings = g;

**Comment by Kink3d** [comment]
Hi,

Here is our recommendation for best practices when editing current post-processing at runtime:

https://github.com/Unity-Technologies/PostProcessing/wiki/Runtime-Post-Processing-Modification

You'll notice the difference between this example and the code @malvakian posted above (thanks for that :))  is that we instantiate the profile currently applied to the Behaviour component. This means we have a duplicate internal copy of the profile to modify at runtime without modifying the source profile.
