### ISSUE TITLE
Bloom is slightly offset in Single Pass Stereo.

### ISSUE THREAD

**Issue by SteffanPoulsen** [Unity-Technologies/PostProcessing#128]
After upgrading from Unity 5.6.0b5, I noticed that the bloom fx is now offset on the screen x axis - when single pass stereo is toggled. I have tried various of the newer beta versions, but can't seem to solve the issue unless I roll back to beta 5.

**Comment by Kink3d** [comment]
Thanks for reporting this,

I'll look into this and get back to you.

**Comment by Podden** [comment]
Beeing on the newest commit, it looks more than slighly off to me :).
Single Pass Off:
![singlepassoff](https://cloud.githubusercontent.com/assets/3932988/25277174/e00d67c6-269d-11e7-8025-7ae9810fb5f8.jpg)
Single Pass On:
![singlepasson](https://cloud.githubusercontent.com/assets/3932988/25277175/e00d84c2-269d-11e7-82a4-ac3beaf4c8cc.jpg)

**Comment by SteffanPoulsen** [comment]
Yeah definitely :), don't know why my title underplayed the issue - its actually keeping us from upgrading past a pretty early (and unstable) 5.6 beta. Would love for it to gain a bit more attention and hopefully get solved soon!

**Comment by Podden** [comment]
Can someone please fix this? Release date is almost here and this is the only problem keeping me from using single pass. My knowlege of shaders is too limited to get this going myself :(.

**Comment by Chman** [comment]
It's an engine regression in 5.6, the VR team is aware of it and is working on a patch for 2017.1 and 5.6+. We'll update this issue once we know more.

**Comment by Podden** [comment]
Seems to be fixed. I'm on 2017.1p3. Thanks a bunch!
