### ISSUE TITLE
Does not work with SteamVR

### ISSUE THREAD

**Issue by jcowles** [Unity-Technologies/PostProcessing#13]
I'm getting major artifacts when running in VR, I assume because it's not aware that the single camera is doing double duty (left/right eye renders).

Is there already a way to make it aware that there are actually two camera passes?

**Comment by Chman** [comment]
Assuming you're using Single Pass Stereo Rendering, some effects don't work with it yet. See [the known issues list](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues) in the quickstart guide.

**Comment by jcowles** [comment]
We are not suing single-pass stereo rendering.

**Comment by Chman** [comment]
Good to know, I'll try and look into it asap.

**Comment by jcowles** [comment]
Oh, we work in decimeter scale, could that be messing up the reprojection?

**Comment by Chman** [comment]
It shouldn't. What effect do you make use of exactly ?

**Comment by jcowles** [comment]
Our rendering setup is a little funky, we have a component on the camera that does a render to a render target and then copies it over to the main camera's target texture. Then that gets passed down the main camera's post effect chain (to work around Unity LDR/bloom limitations and to adjust the viewport scale dynamically). Other than that, it's a pretty simple setup with bloom and fxaa.

Does that make sense?

**Comment by jcowles** [comment]
Oh, if you meant what components from PostProcessing -- I'm just trying to use TAA, nothing else.

**Comment by Chman** [comment]
I'm not sure I understand the part about:

> to work around Unity LDR/bloom limitations

Other than that, a setup like this will break any effect that requires depth information if it's not done on the first pass (TAA requires depth to work properly).

**Comment by cameronoltmann** [comment]
I'm also seeing issues with TAA in OpenVR.  Using 5.5.0b6 and 5.5.0b10, not using SPSR, when I enable TAA I see the following:
* A ghosted image overlaid to the left of the main image
* Worldspace text and particles moved to the left by an amount similar to the ghosted image displacement

Notes:
* This happens with no other image effects in play.
* If I set the camera Eye Target to left or right rather than both, the issue disappears.

gif of issue (TAA toggled on/off multiple times during recording): https://gyazo.com/cc469cf4bf88ddec5f7908b19cd9d212

**Comment by Chman** [comment]
TAA doesn't work at all in VR at the moment (we don't have proper support for motion vectors in VR yet).

**Comment by Kink3d** [comment]
Known issue:
https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues

Closing

**Comment by jcowles** [comment]
Is there any ETA on when it will be supported?

**Comment by Chman** [comment]
Probably not until we get proper motion vector support for VR. With 5.5 being just around the corner I'd say not until 5.6.
