### ISSUE TITLE
Black screen on Android device using various effects

### ISSUE THREAD

**Issue by HariSomani** [Unity-Technologies/PostProcessing#130]
i used post processing behaviour script in camera,effect work fine with ios build but not work with Android build.when i run on any android device,i found black screen.  
any one have the idea about it.
i used the Antialiasing,Colorgarding,Vignette effects.

**Comment by Kink3d** [comment]
Hi,

What device are you running on? 

Color Grading requires RGBAHalf texture format which may not be supported on this device (such as Galaxy S5 with Mali-T628). In this case it is recommended to use https://docs.unity3d.com/ScriptReference/SystemInfo.SupportsTextureFormat.html to determine whether the device supports Color Grading and resort to User Lut effect is it does not.

Also which AA are you using? TAA is not recommended on mobile as most devices do not support it.

**Comment by HariSomani** [comment]
thank's...it's really help for me.

**Comment by Kink3d** [comment]
Youre welcome :)

Thanks for getting back to us and letting us know!
