### ISSUE TITLE
[New Feature] Add a Blur Effect

### ISSUE THREAD

**Issue by tbg10101** [Unity-Technologies/PostProcessing#133]
A general blur effect is needed, to replace the blur from the old Standard Assets effects package.

**Comment by Chman** [comment]
This is a highly specific effect outside of the scope of this stack. We only intend to add most important, commonly used post-processing effects.

**Comment by Votrubec** [comment]
The Unity team is strongly recommending to move to the PostProcessing stack. Yet, Blur has been left out. For mobile, I was able to successfully use blur to simulate DoF cheaply. Blur (Optimised) was also used to blur the game view during menu popups. This is hardly what I would call a "highly specific effect". Yet, Motion Blur is added. I'm not saying Motion Blur shouldn't be added, but Blur (Optimised) is a fantastic and almost necessary effect to have. At the moment, I'm having to import the legacy effects, which in 5.6.1 are now throwing all sorts of warnings -
Tiled GPU perf. warning: RenderTexture color surface  (378x283) was not cleared/discarded, doing <run with profiler for info>
UnityEngine.Graphics:Blit(Texture, RenderTexture, Material, Int32)
UnityStandardAssets.ImageEffects.BlurOptimized:OnRenderImage(RenderTexture, RenderTexture) (at Assets/Standard Assets/Effects/ImageEffects/Scripts/BlurOptimized.cs:65)

And I believe it could also be the cause of this error being spammed and filling the console window within seconds -
TLS Allocator ALLOC_TEMP_THREAD, underlying allocator ALLOC_TEMP_THREAD has unfreed allocations

Certainly don't want to come across as argumentative. But from where I'm sitting, this one dropped effect would round out the PostProcessing stack, and allow us to truly ditch the legacy effects that I suspect are causing issues in 5.6 and onwards.

**Comment by laurentopia** [comment]
chman you have 8 thumb down and 5 confused smileys so I think it is time you reconsider your life's choices 
go add blur to the stack and don't you stomp your feet on me, young man or you won't get any desert!

**Comment by JimmyCushnie** [comment]
Wow, three years later and still no updates?

Blur is a very important effect that I use in basically all my games. The fact that it doesn't come standard with new post-processing is ridiculous.

Unless it's in PPv3. I haven't used v3 yet at all because I haven't had time to port all my custom post-processing effects to it.
