### ISSUE TITLE
Post-Processing filters don't work anymore in Scene View, Unity 5.6.0f3

### ISSUE THREAD

**Issue by OrtOfOn** [Unity-Technologies/PostProcessing#136]
##### What happened?

Since Unity 5.6.0 beta1 the post-processing filters are not rendered in the scene view anymore. This is really annoying to finetune effects. There are working fine in 5.5.x

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 5.6.0f3 (and other 5.6 betas)
Windows 10 (64bit)

**Comment by Kink3d** [comment]
This is a known bug and we are working on it, please see #71 

Thanks for your time

**Comment by OrtOfOn** [comment]
Thanks for your quick reply.
