### ISSUE TITLE
Chromatic Aberration

### ISSUE THREAD

**Issue by pechaut** [Unity-Technologies/PostProcessing#137]
##### What happened?
Has no effect in VR, only apply to the preview window

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5,5,2 on Oculus

**Comment by rsodre** [comment]
Since it's applied to the edges of the frame, seems to me that in VR it's outside our eyes' field of view.

**Comment by Kink3d** [comment]
Hi,

@rsodre is correct. Chormatic Aberration is never strong enough to be noticeable in your actual field of view when wearing the headset. You could adjust the values to be much higher in code if you really wanted to but I wouldnt recommend it, especially considering you already get chromatic aberration from the headsets lenses. Heres a frame debugger capture of Chromatic Aberrations at full just to prove this...

![ca1](https://cloud.githubusercontent.com/assets/11135817/24765641/787f9a74-1af0-11e7-9016-64eedfb7a698.PNG)
