### ISSUE TITLE
Bloom broken on Android and iOS with 5.6.0.f3

### ISSUE THREAD

**Issue by JohannesDeml** [Unity-Technologies/PostProcessing#139]
##### What happened?
Bloom is not working for the target platforms android and iOS with unity 5.6.0f3. No problems with Unity 5.5.2p4 however.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3
Windows 10 64bit
Target: Android and iOS (Standalone works)

![android](https://cloud.githubusercontent.com/assets/4518980/24757884/d27f9fd4-1ae0-11e7-8ab3-fdd5b5a9550e.PNG)
![windows](https://cloud.githubusercontent.com/assets/4518980/24757885/d27fe840-1ae0-11e7-8c6b-5728869a2685.PNG)

Project can be found here (It's just a sphere with emission from the standard shader): https://drive.google.com/file/d/0ByTO3RP9DQI0aEhTVXVzZmh2a1U/view?usp=sharing

**Comment by Kink3d** [comment]
Hey,

It turns out that "Use HDR" is disabled by default in all 3 Graphics Settings tiers in these platforms (Project Settings > Graphics Settings) in 5.6. Enabling these fixes this problem. Ill go ask around as to why the tiers are like this.

Thanks for bringing it to our attention :)

**Comment by JohannesDeml** [comment]
Ah! Okay very interesting, I was already wondering if the HDR was really active. Thanks for the quick response!
