### ISSUE TITLE
Changing camera viewport size creates streaks on temporal effects 

### ISSUE THREAD

**Issue by jorgecid** [Unity-Technologies/PostProcessing#14]
Calling PostProcessingBehaviour.ResetTemporalEffects() doesn't solve it. 

Digging deeper into Temporal AntiAlias shows that maybe "ResetTemporalEffects" doesn't even need to be directly invoked. "Render" already has a check for "m_HistoryTexture.width != source.width" or "m_HistoryTexture.height != source.height" that would trigger a restart for the effect.

![screen shot 2016-11-04 at 14 30 19](https://cloud.githubusercontent.com/assets/2310418/20009223/9390baa0-a29b-11e6-952f-402eda662723.png)
![screen shot 2016-11-04 at 14 30 38](https://cloud.githubusercontent.com/assets/2310418/20009285/c6aae38e-a29b-11e6-9b29-275d436856c5.png)

**Comment by Kink3d** [comment]
Hey,

So far I've been unable to reproduce this issue. Is it possible for you to provide a project that displays the issue? (preferably a small reproduction case)

Also it should be noted that ResetTemporalEffects is for use cases such as cutting a camera between two positions (therefore you need to clear the history buffer of frames from the previous camera position). You are correct that the check you noted is designed to catch cases like yours.

**Comment by jorgecid** [comment]
OK, I'll do a simple scene first thing Monday morning. 

The camera is static when I swap between those two screens, but I do change the Field of View to keep the framed objects with the same size. Maybe that's what creates the streaks and explains why the ResetTemporalEffects doesn't work for this scenario, if it only deals with changes in position.

**Comment by jorgecid** [comment]
Simplified test project with some cubes. 

https://www.dropbox.com/s/ugsm9urlgcpnbzv/__TemporalEffectsBugReport__.zip?dl=0

Press T to toggle. I also tried ResetTemporalEffects with yield new WaitForEndOfFrame and similar approaches. 

![screen shot 2016-11-21 at 14 33 29](https://cloud.githubusercontent.com/assets/2310418/20486899/5a622cbc-aff9-11e6-8935-fc4704a4918a.png)
![screen shot 2016-11-21 at 14 33 45](https://cloud.githubusercontent.com/assets/2310418/20486902/5a7cc716-aff9-11e6-9781-7700f8056ce9.png)

**Comment by jorgecid** [comment]
Also, if I don't change the field of view, I still get streaking. But as the change horizontal, of course:

![screen shot 2016-11-21 at 14 58 43](https://cloud.githubusercontent.com/assets/2310418/20487426/2769d3f8-affb-11e6-95b3-ec7a4deb66aa.png)
![screen shot 2016-11-21 at 14 58 55](https://cloud.githubusercontent.com/assets/2310418/20487428/27847898-affb-11e6-9d7a-601a757a6cd9.png)

Tested with Unity 5.4.2.f2 and 5.5.0b9

**Comment by inikitin** [comment]
I've had a similar problem, but with orthographic camera. Strangely, the solution was to bring far clipping plane closer, or push near plane further back. Not sure if that's intended behavior, but it can be easily reproduced on an empty project with all default camera values and Post Processing Behaviour with only Motion Blur and Debug Views: Motion Vectors enabled. 

![screen shot 2016-11-21 at 1 51 00 pm](https://cloud.githubusercontent.com/assets/870643/20498317/51d1ed0a-aff2-11e6-89fb-da3c3d54c227.png)

**Comment by Kink3d** [comment]
So what you're seeing here is actually 2 different things.

With regards to TAA you're resetting the history buffer then pausing without giving it a chance to converge.  If you disable motion blur on your test you can see this. TAA needs 8 frames to converge (the length of the history buffer).

`public int wait = 1;
    int waited = 0;

    void Update()
    {
        if (Input.GetKeyUp(KeyCode.T))
        {
            Camera.main.GetComponent<PostProcessingBehaviour>().ResetTemporalEffects();
            Camera.main.rect = new Rect(0, .25f, 1, .5f);
            StartCoroutine(WaitAndPause());
        }
    }

    IEnumerator WaitAndPause()
    {
        while (waited < wait)
        {
            waited++;
            yield return new WaitForEndOfFrame();
        }
        UnityEditor.EditorApplication.isPaused = true;
    }`

Try this code with `wait` as values between 1 and 8. You can see TAA convergence process.

This "streaking" that youre seeing is actually the result of a blank previous frame in motion blur. Motion blur is calculated essentially by `movecs = thisFrame - previousFrame`. You are resetting both then pausing on the next frame. If you disable motion blur and wait for another frame (with TAA on so movecs are written) this frame isnt drawn (where previous is empty) and the next frame drawn is fine.

`IEnumerator WaitAndPause()
    {
        while (waited == 0)
        {
            waited++;
            beh.profile.motionBlur.enabled = false;
            yield return new WaitForEndOfFrame();
        }
        while (waited == 1)
        {
            waited++;
            beh.profile.motionBlur.enabled = true;
            yield return new WaitForEndOfFrame();
        }
        UnityEditor.EditorApplication.isPaused = true;
    }`

Dirty example code but you get the idea.

**Comment by Kink3d** [comment]
So what you're seeing here is actually 2 different things.

With regards to TAA you're resetting the history buffer then pausing without giving it a chance to converge.  If you disable motion blur on your test you can see this. TAA needs 8 frames to converge (the length of the history buffer).

```public int wait = 1;
    int waited = 0;

    void Update()
    {
        if (Input.GetKeyUp(KeyCode.T))
        {
            Camera.main.GetComponent<PostProcessingBehaviour>().ResetTemporalEffects();
            Camera.main.rect = new Rect(0, .25f, 1, .5f);
            StartCoroutine(WaitAndPause());
        }
    }

    IEnumerator WaitAndPause()
    {
        while (waited < wait)
        {
            waited++;
            yield return new WaitForEndOfFrame();
        }
        UnityEditor.EditorApplication.isPaused = true;
    }```

Try this code with `wait` as values between 1 and 8. You can see TAA convergence process.

This "streaking" that youre seeing is actually the result of a blank previous frame in motion blur. Motion blur is calculated essentially by `movecs = thisFrame - previousFrame`. You are resetting both then pausing on the next frame. If you disable motion blur and wait for another frame (with TAA on so movecs are written) this frame isnt drawn (where previous is empty) and the next frame drawn is fine.

``` IEnumerator WaitAndPause()
    {
        while (waited == 0)
        {
            waited++;
            beh.profile.motionBlur.enabled = false;
            yield return new WaitForEndOfFrame();
        }
        while (waited == 1)
        {
            waited++;
            beh.profile.motionBlur.enabled = true;
            yield return new WaitForEndOfFrame();
        }
        UnityEditor.EditorApplication.isPaused = true;
    }```

Dirty example code but you get the idea.

**Comment by jorgecid** [comment]
Thank you for looking into it.

So, for a quick fix I should wait 8 frames before re-enabling TAA and 1 frame for Motion Blur?

If the filters can't give accurate results before the end of that cool down period, shouldn't they implement that build-up by default after ResetTemporalEffects being called?

**Comment by jorgecid** [comment]
For people coming to this with the same problem: as a temporary workaround I set all parameters of TAA to 0 for a couple of frames instead of disabling it. It's ugly code but not 100% free of artefacts, but better than those streaks.
