### ISSUE TITLE
SSAO over fog in forward rendering

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#142]
When use forward, and SSAO have wrong result

https://gyazo.com/a4b6d55455b6bcef0d5cbe5fa95ae1ee

need add posability to engine, like RenderOpacityObjectsWithouFog to resolve this! And use fog After apply ssao

**Comment by Kink3d** [comment]
Yea this reproduces,

Thanks for reporting. Will look into a fix.

**Comment by Kink3d** [comment]
Fixed in latest master. Please update.

Thanks for reporting!
