### ISSUE TITLE
Setting Camera target texture to null flips game view in Forward

### ISSUE THREAD

**Issue by Hamed1984** [Unity-Technologies/PostProcessing#144]
when i enable bloom effect screen flipped vertical and i don't now how to fix it

Unity 5.6, windows 10, android

**Comment by fdsagizi** [comment]
have the same bug, appears if Forward rendering and  render2Texture == null

i think this but in unity it self

**Comment by Teshla** [comment]
Yup, Y coordinates flip on direct3d.

**Comment by Kink3d** [comment]
Hi,

https://fogbugz.unity3d.com/f/cases/876045

This is a known bug when setting the target texture of the camera to null. Are you doing some kind of manual rendering/screen shots/other image effects that do this?

As you can see the bug is on its way to a 5.6 patch.

**Comment by Teshla** [comment]
Yup, target texture switch was the culprit, thx! That saved a lot of time on troubleshooting attempts on my end! Since we're not shipping anytime soon I'll just wait for the patch.  Can't check the case on fogbugz, because direct link requires account, but I'll take your word for it.

**Comment by Kink3d** [comment]
Ok great, ill leave this here so people can see it until the patch lands.

**Comment by Teshla** [comment]
alright https://xkcd.com/1822/

**Comment by Kink3d** [comment]
Hey all,

This fix is now in queue for a patch, It should make 5.6.0p2 but I will update here either way.

**Comment by Kink3d** [comment]
Update: Im afraid this fix didnt make patch 2. Should be in p3.

**Comment by artofcode** [comment]
I've noticed that this is still an issue in 2017.1.0b5, are there plans to get this fix integrated in the beta branch as well?

**Comment by vincentmmc** [comment]
Is it fixed now?

**Comment by vincentmmc** [comment]
@Kink3d

**Comment by Kink3d** [comment]
Hi all,

Sorry for the lack of communication. This is now fixed as of 2017.1.0b9.
