### ISSUE TITLE
Everything dark,

### ISSUE THREAD

**Issue by TSchindlinger** [Unity-Technologies/PostProcessing#145]
When I added the Post Processing Behaviour Script to my camera and created a profile, my whole game scene went really dark, not completly black but like really dark. The flashlight my FPS Controller has, is almost not visible anymore.
![screenshot_6](https://cloud.githubusercontent.com/assets/16342236/24833626/1631cf14-1ccf-11e7-91ed-93b1b1e378cb.png)

**Comment by malvakian** [comment]
Hi TSchindlinger, try to select your profile and open the first Tab "Debug", be sure that "none" is selected. I think, they have let "Depth" by default.

**Comment by Kink3d** [comment]
Hey,

As @malvakian pointed out this looks like you have a debug mode enabled. Can you confirm?

Also, @malvakian we checked and found no evidence that we ever left any debugs on by default :/

**Comment by malvakian** [comment]
Hi Kink3d,

Yes, is my fault, I was talking about a file stored in "Post-processing Stack 1.0.1". Its name is "ExampleProfile.asset", and wasn't set to "Depth" but "Motion Vectors".

Regards

**Comment by Kink3d** [comment]
Ah yes. This is the example profile used for the example scene for custom motion vector texture.

**Comment by TSchindlinger** [comment]
I solved the problem. Seems like it is not working with the standard image effects. At least with "Screen Space Ambient Occlusion". This + The new Post Processing Stack makes everything dark. So i just deactivated the normal Screen Space Ambient Occlusion and everything works fine. Odd that it's working with all other image effect. Thanks for your help anyway.
