### ISSUE TITLE
[Enhancement] Lerp / Transition between 2 profiles

### ISSUE THREAD

**Issue by alkoclick** [Unity-Technologies/PostProcessing#148]
Hey guys and girls,

I wrote up some scripts to transition between 2 PostProcessingProfiles. Essentially you choose 2 profiles and you can interpolate between them however you like. I also added some base classes to do such a transition based on time or distance. 

https://github.com/alkoclick/PostProcessing

Would you be interested in me preparing it for a pull request and add it to the features of this repo, or do you think it better remain separate?

**Comment by DuckyDuckling** [comment]
Heck yeah.

**Comment by Chman** [comment]
Hey!

It's great to see the community do things like that :)

> Would you be interested in me preparing it for a pull request and add it to the features of this repo, or do you think it better remain separate?

We're currently working on a more flexible solution (among other things) so you should probably keep it separate from the main repo. Feel free to promote your code on the forums though!
