### ISSUE TITLE
Eye Adaptation huge performance degradation on iOS

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#149]
##### What happened?

 if **just** enable Eye Adaptation. from 56 Fps  move to 18 Fps  
Older versions, work more fast!

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

iOS, iPhone 5s

**Comment by Chman** [comment]
> Older versions, work more fast!

Which version specifically? Can we get more detail on that?

For what it's worth, Eye Adaptation isn't meant to be used on mobile at the moment.

**Comment by Kink3d** [comment]
Closed due to inactivity
