### ISSUE TITLE
Ambient Occlusion affecting transparency/speedtree

### ISSUE THREAD

**Issue by jorgecid** [Unity-Technologies/PostProcessing#15]
The Cinematic Effects version of Ambient Occlusion seems to get around this problem.
![screen shot 2016-11-04 at 16 28 46](https://cloud.githubusercontent.com/assets/2310418/20013754/43784ffe-a2ac-11e6-86a1-2e2b9538c70e.png)

**Comment by Chman** [comment]
Can I get more information about :
- Unity version
- Rendering path used (deferred/forward)
- Ambient Occlusion settings

**Comment by jorgecid** [comment]
5.4.2.f2
forward rendering
![screen shot 2016-11-07 at 10 51 46](https://cloud.githubusercontent.com/assets/2310418/20055268/340ea490-a4d8-11e6-9df7-08ffd2fc7c10.png)

settings of screenshot are defaults + intensity 4 + high precision (forward).

**Comment by Chman** [comment]
AO is computed using the depth & normal buffers provided by Unity. The issue here has to do with how the Forward rendering path deals with normals and cutout materials. Here's a view of the normal buffer in Forward:

![image](https://cloud.githubusercontent.com/assets/849090/20060413/5443ead6-a4fb-11e6-8fd6-ff1b8a0b8748.png)

And here's the same view in Deferred:

![image](https://cloud.githubusercontent.com/assets/849090/20060422/5ee0584e-a4fb-11e6-87e8-5bdec41a2e00.png)

You can try it yourself using debug views in your post-processing profile.

As you can see the Forward rendering path is missing some information... It's a current limitation of this path and there isn't much the AO effect can do to work around that. I'll close this issue as it's not post-processing related and will bring up this issue internally.

**Comment by jorgecid** [comment]
Current AO in the unity cinematic effects doesn't seem to have that problem. Is there a plan to bring them together?

**Comment by Chman** [comment]
It does have the exact same problem when used with the same settings (defaults between the two versions are different, downsampling is enabled by default on the newer AO for performance reasons but makes the effect more visible, you can try it). This is using the version in the Cinematic Image Effects package:

![image](https://cloud.githubusercontent.com/assets/849090/20061627/dd74e6f2-a500-11e6-9563-dc433b717013.png)

**Comment by jorgecid** [comment]
As much as I push the settings around I don't get that effect on the cinematic effects version from the asset store.
![screen shot 2016-11-07 at 14 57 01](https://cloud.githubusercontent.com/assets/2310418/20062311/3232b684-a4fb-11e6-87c6-bb3a54810932.png)
![screen shot 2016-11-07 at 14 58 57](https://cloud.githubusercontent.com/assets/2310418/20062312/3243f5b6-a4fb-11e6-98e3-c38032701220.png)
![screen shot 2016-11-07 at 15 00 38](https://cloud.githubusercontent.com/assets/2310418/20062313/3244aa56-a4fb-11e6-8654-4af0ca1c0570.png)
![screen shot 2016-11-07 at 15 00 57](https://cloud.githubusercontent.com/assets/2310418/20062314/32482276-a4fb-11e6-834e-280b96b34cbd.png)

**Comment by Chman** [comment]
Would you happen to have a sample scene to send me that exhibits the issue ? Because I can't get the Cinematic Image Effects version to work well in Forward. I can get close (with the new Post-FX too) but it's not really working when you look closely.

Could you post a "debug" view of this screenshot:

![](https://cloud.githubusercontent.com/assets/2310418/20062311/3232b684-a4fb-11e6-87c6-bb3a54810932.png)

**Comment by jorgecid** [comment]
I think it has something to do with the occlusion source. 

![screen shot 2016-11-07 at 15 25 50](https://cloud.githubusercontent.com/assets/2310418/20063306/9392f7f6-a4fe-11e6-8e11-4315f98bef04.png)
![screen shot 2016-11-07 at 15 26 07](https://cloud.githubusercontent.com/assets/2310418/20063305/93927182-a4fe-11e6-956c-a6e2de689a47.png)

Depth Normals probably means something different on both of them.
If I change line 126 in Ambient Occlusion Component
            cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 3);
to 
            cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 1);
or
            cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 2);

I get something closer to the cinematic effects package on the asset store. But not quite right, which makes sense, as I really don't know what I am changing in there :)

**Comment by Chman** [comment]
The Occlusion source is chosen automatically in the new AO whereas it was explicit in the old one. Other than that, the code is identical. `Depth Normals` points to the same buffer in both cases.

> If I change line 126 in Ambient Occlusion Component
> cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 3);
> to 
> cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 1);
> or
> cb.Blit(rtMask, rtBlur, material, occlusionSource == OcclusionSource.GBuffer ? 4 : 2);

Don't do that, this is the first blur pass and changing the `3` value to anything else will just break the effect (`1` and `2` are AO passes, so you're essentially telling the effect to render AO twice and skip the first blur pass).

Do you have a sample scene I could use to debug this issue ?

**Comment by jorgecid** [comment]
https://www.dropbox.com/s/w9yaryn1h3b78dn/AO.zip?dl=0

While making a clean scene I found a clue to the differences.

On the same Camera of the Cinematic Effects AmbientOcclusion you need an empty Post Processing Profile. I am guessing that's actually breaking the cinematic effects AO, not fixing it.

**Comment by Chman** [comment]
Yep the empty profile will override the camera flags, and thus breaking the Cinematic AO effect (so although it looks like it's working, it's not really, and the AO in debug view is all wrong). Disabling the `Post Processing Behaviour` with the empty profile clearly shows that the Cinematic AO effect isn't working any more than the new one. So there isn't any difference between the old AO and the new one, it's about a limitation of the Forward rendering path.

**Comment by jorgecid** [comment]
Thanks for checking it out. Does it mean it's also breaking other image effects or is it just the cinematic effects?

**Comment by Chman** [comment]
It will probably break any image effect put _before_ the `PostProcessing Behaviour` component that requires depth, normal or motion vectors unfortunately. Others will be fine.
