### ISSUE TITLE
Exclude canvas from motion blur (fix or enhancement)

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#150]
Hi, i use a canvas in screen space camera for put a targeting crosshair image (in screen space because my game is a third person shooter and if i use overlay mode the crosshair is show above (in front) of the character) but the motion blur affects the canvas and have bad results, is not possible setup the motion vectors of canvas elements then please implement some to fix this issue, thanks.

**Comment by Kink3d** [comment]
Hi,

It is not possible to "mask" objects for motion blur, In this case you should use a separate camera to render this UI (with no post-processing applied). Setting this camera's culling to only render the UI and setting clear flags to "None" should fix this problem. In this case the objects rendered by the second camera will still be able to test depth against objects rendered by the first camera.

Thanks.

**Comment by Chman** [comment]
You can also set the render mode of your canvas to `Screen Space - Overlay`, that way it won't be affected by post-processing effects.
