### ISSUE TITLE
Can TAA work with FXAA at the same time?

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#151]
TAA looks good in static screen, but not good in dynamic screen. Can TAA work with FXAA at the same time, blend their results due to quality of TAA?

**Comment by Kink3d** [comment]
It is not possible to use multiple anti-aliasing methods. It is possible something is wrong with your TAA setup as in our extensive tests it always gets better results than FXAA in motion (and static for what its worth).

- Have you adjusted TAA settings? (default settings should work in 99% of cases, and are recommended)
- Are you using MSAA? This prevents TAA from working correctly. You can disable it in Quality Settings (or per camera in 5.6)
- Which version of Unity and what is the target platform?

Please do fill in the information in the template when filing a bug report. This is vital for us to debug issues quickly.

**Comment by silentlamb1991** [comment]
I use default settings like this:
![taa settings](https://cloud.githubusercontent.com/assets/18855621/25006826/fc4d8c12-2090-11e7-9156-59585adb5315.PNG)

**Comment by silentlamb1991** [comment]
I had disabled MSAA both in camera and Quality Settings:
![qs](https://cloud.githubusercontent.com/assets/18855621/25007195/24602150-2092-11e7-8372-b14c7cecf47b.PNG)
![camera](https://cloud.githubusercontent.com/assets/18855621/25007204/2b0a0070-2092-11e7-99ed-8bf62fee6189.PNG)

**Comment by silentlamb1991** [comment]
Unity version: 5.6.0f3.
Screenshot with FXAA:
![fxaa](https://cloud.githubusercontent.com/assets/18855621/25007314/9cb67d16-2092-11e7-8c33-f4d2a24d7ec3.png)

Screenshot with TAA (when rotate camera):
![taa](https://cloud.githubusercontent.com/assets/18855621/25007331/af1bc010-2092-11e7-9f93-350f9b5d968e.png)

**Comment by silentlamb1991** [comment]
Please click the screenshots show it in full size.

**Comment by Kink3d** [comment]
Ok, thanks for the details.

What platform is this? Does it reproduce in editor and player? Which graphics API are you using?

There may be a problem with TAA and something else in your project. I notice you are using volumetric lighting, does it still reproduce with this all disabled?

It is likely we will need a reproduction project to look at this properly.

**Comment by silentlamb1991** [comment]
Unity 5.6.0f3, Win10 pro 1607, target platform windows.
I removed volumetric lighting but it still looks bad, I made a reproduction project before for Motion Blur bug report but it can reproduce this too. (maybe all bugs I reported)
[BugReport.zip](https://github.com/Unity-Technologies/PostProcessing/files/919942/BugReport.zip)
Please open 0.scene and play it.

**Comment by Kink3d** [comment]
Hey,

So I checked your scene and this is indeed one of the worst scenarios for TAA. As with almost everything in game development, post-AA is a case by case choice and in this (rare) case FXAA is likely the better choice.

It should be noted that you are two major updates for TAA behind. If you update to latest it does look a lot better in the project provided, but still not perfect.

Thanks for your time and thanks for providing a project! :)

**Comment by larssteenhoff** [comment]
http://www.livenda.com/ctaa/

mike drop :)
