### ISSUE TITLE
5.6 Post Processing Behavior does not work

### ISSUE THREAD

**Issue by rbmcginnis** [Unity-Technologies/PostProcessing#154]
Just some noise when I press play then everything is back to normal. None of the effects work.

Dell laptop with 34" Samsung monitor.

Any ideas.

**Comment by Arugin** [comment]
@rbmcginnis Did you place PostProcessing folder in the root of Assets folder? Any errors in console?

**Comment by rbmcginnis** [comment]
I did put the PostProcessing folder in the root of Assets. I do not have any errors. The effects show up in the editor, but the only effect I see is a bit of visual noise when I start the scene and some very low level noise. Using 5.60f3. I started a new scene and the results were the same. I will try on another computer later today.

**Comment by Kink3d** [comment]
Hi,

Im afraid we wont be able to assist you without a reproduction project. Please upload one and we will be glad to look at it for you.

Regards

**Comment by rbmcginnis** [comment]
Hi Matt:

 

I now understand my problem.

 

I was using the Debug Mode: Motion Vectors. This seems to turn off all of the effects. And even persists into the build process. I assumed the debug mode would be turned off in the build. I was wrong.

 

The reason I ended up with the Motion Vectors is because it is the only example installed  with the effects.

 

Finally, this discovery was exasperated due to problems with Unity’s multi-display features. I find them extremely buggy and unreliable. 

 

Best regards,

 

Bob

**Comment by Kink3d** [comment]
Hi,

This example profile is designed for showing the `CustomMotionVectorTexture` utility that ships with the package. This profile has now been renamed so its less likely people will try to use it but well keep an eye on whether this happens again.

Thanks for letting us know!
