### ISSUE TITLE
TAA blurs the skybox when when moving the camera

### ISSUE THREAD

**Issue by drewcassidy** [Unity-Technologies/PostProcessing#156]
##### What happened?

when moving the camera round (not rotating) TAA blurs the skybox. this is really obvious in my game since I have a star field, and all the smaller stars disappear when zooming in or out.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
macOS Sierra, Unity 5.6.0f3

**Comment by Kink3d** [comment]
Hi,

Im afraid this is likely to be just a side effect of the way TAA works. Its hard to tell without seeing the size of the lost detail in question but TAA will appear to remove small details as it converges.

Ill close the issue as its unlikely we can do anything about this, but if you want to reopen it with video/images/project so we can check that this is indeed not fixable please do.

Thanks.

**Comment by drewcassidy** [comment]
even though the skybox isn't actually changing position on the screen at all?
