### ISSUE TITLE
Ambient Occlusion doesn't work with forward rendering

### ISSUE THREAD

**Issue by michael-nischt** [Unity-Technologies/PostProcessing#16]
Ambient Occlusion doesn't work with forward rendering. Looks kinda like the debug view since all I see is the ambient occlusion part if enabled. Option like force forward compatibility doesn't help. 

Note that I'm using the Experimental Unity3D Editor for Linux (5.5.b5 which is the latest available atm). So it might the issue doesn't appear with a newer version of the 5.5 beta.

**Comment by Chman** [comment]
Do you have [MSAA enabled](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues) ?

**Comment by michael-nischt** [comment]
Yes, I did.. thanks for the quick reply!

**Comment by LKGames** [comment]
I just switched my side-project to forward rendering to test this (I use the Linux editor as well). MSAA seems to break HDR, meaning that out-of-range colors will appear as white when tonemapped (which could be what you are referring to), but I'm not seeing any issues with the ambient occlusion specifically, even with MSAA enabled.

**Comment by Chman** [comment]
> MSAA seems to break HDR

That's because MSAA + HDR isn't supported in Unity at the moment so HDR will simply be disabled. The editor should display a warning about that on the camera component when both are enabled at the same time.
