### ISSUE TITLE
Most of the Post Processing effect does not work at Unity 5.6.0f3

### ISSUE THREAD

**Issue by optimisez** [Unity-Technologies/PostProcessing#161]
##### What happened?
It shows error message and the whole Camera screen into pink color.   
![image](https://cloud.githubusercontent.com/assets/7009368/25261869/0db23920-2687-11e7-98a2-a1ad4733c2b5.png)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3 Editor

**Comment by Chman** [comment]
Select the `PostProcessing` folder in your project panel, right-click and select `Reimport`. That should fix it.

**Comment by Kink3d** [comment]
If it does not feel free to reopen this issue

Thanks

**Comment by optimisez** [comment]
Thank you @Chman. The issue has been solved but why this bug happens?

**Comment by Chman** [comment]
I'm not sure. Seems to be a Unity issue with the import pipeline and/or the shader compiler losing reference to shader include files :/
