### ISSUE TITLE
Ambient Occlusion and issue with animating in vertex shader

### ISSUE THREAD

**Issue by pavelkouril** [Unity-Technologies/PostProcessing#162]
##### What happened?

I have an issue with AO effect, by creating "ghots"; the AO in following screenshot is intentionally "boosted", for better vision of the said ghost effect.

![image](https://cloud.githubusercontent.com/assets/636912/25277975/23e4784c-26a1-11e7-9262-797e71f84fd4.png)

I'm animating the vegetation in VS in a surface shader; the vertex function is as follows:

```
void vert(inout appdata_full v) {
  v.vertex.x += (cos(_Time * 4 + v.vertex.x) * sin(_Time * 4 + v.vertex.x) * (v.vertex.y)) / 2;
}
```

The ghost position is the standard position before animating, so it seems while the object moves, the AO effect doesn't respect the new position and calculates the AO based on the old position.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3, latest master of post-processing stack (44b7431), Windows 10 64bit. 

EDIT: Forgot to mention I'm using a forward rendering with MSAA and HDR.

**Comment by Kink3d** [comment]
Hi,

I just used that vertex snippet and Ambient Occlusion is updating correctly.

The problem must be elsewhere. Can you upload a reproduction project, or at least the full shader?

**Comment by Kink3d** [comment]
Apologies, that last message (deleted) is incorrect (I was in Deferred). If you check the Normals or Depth debugs on the post-processing stack youll see that they do not reflect your vertex changes.

Im afraid in forward rendering there is simply no way to do this unless you write your own version of DepthNormals texture to write this data in to, and this is a far less than trivial task.

Sorry to be the bearer of bad news...

**Comment by pavelkouril** [comment]
Oh well. I was afraid it's something with the Depth/DepthNormals texture and I didn't realize I could look at them in the debug view. So, at least thanks for confirming the source of the issue and that it's not easily fixable.

I wish I could use deferred, but unfortunately, this being a VR app, I'm limited to Forward due to the MSAA requirement. So I'll probably just turn off the SSAO.
