### ISSUE TITLE
Serious Proplam that i couldn't fix anyway 

### ISSUE THREAD

**Issue by DovahXR4** [Unity-Technologies/PostProcessing#165]
![unity proplam](https://cloud.githubusercontent.com/assets/27960507/25340011/0f9ed846-290d-11e7-90d0-203bb3f64ef4.PNG)

can anyone help pls?

**Comment by fdsagizi** [comment]
This just a warning :)

**Comment by DovahXR4** [comment]
but i can't use it on (Add Component) in the main camera inspector for some odd reason.
i'm talking about the PPS file of course..

**Comment by Chman** [comment]
This warning is harmless and has been fixed more than a month ago. Make sure you're working with the latest version.

> but i can't use it on (Add Component) in the main camera inspector for some odd reason.
i'm talking about the PPS file of course..

What can't you add to the camera? What does `PPS` means?

**Comment by DovahXR4** [comment]
the (Post Processing Stack) from the asset store

**Comment by Chman** [comment]
Ok, but what can't you add to the camera? What did you try exactly? Did you read the [quickstart guide](https://github.com/Unity-Technologies/PostProcessing/wiki)?

**Comment by Kink3d** [comment]
Closed due to inactivity
