### ISSUE TITLE
DOF effect blurs transparent special effects that should be crisp

### ISSUE THREAD

**Issue by mgeorgedeveloper** [Unity-Technologies/PostProcessing#168]
Due to special effects (particles, etc.) not writing to a depth buffer, the new DOF effect will blur these effects based on the underlying solid geometry distance. This screenshot demonstrates it clearly:

[http://farflunggames.com/download/dof1.jpg](url)

While I'm not sure this problem can be address directly, it sounds like something that multiple cameras should resolve quite easily. However, this is not possible at the moment, because multiple deferred cameras do not work correctly with this new post processing system. I will log this separately shortly to explain the various problems with multiple cameras.

- Unity 5.5.2.
- Deferred + HDR + linear.
- Post processing effects 1.01.
- Affects editor play mode or any build target.
- Windows 64-bit used.

**Comment by mgeorgedeveloper** [comment]
Whoops! It seems the previous post already raised this same issue! Apologies - please ignore / delete. But, please see my following Issue regarding multiple camera problems, as multiple cameras would have easily resolved this DOF problem, but simply doesn't work correctly at all.

**Comment by Chman** [comment]
> it sounds like something that multiple cameras should resolve quite easily.

Not entirely, no, it would reverse the issue, really.

Transparent objects will be drawn on top of the underlying blurred picture, near-blur included (even if the transparent object is behind it, you'll see weird bleeding edges), and it will look bad as well. With that said, if you know transparent objects will be drawn on top and will never go in between the two blur planes, then yes, it _could_ be a workaround. But you'll have to be very careful with your level design and transparent object placement.

> I will log this separately shortly to explain the various problems with multiple cameras.

Please do!

**Comment by mgeorgedeveloper** [comment]
@Chman 

The issues with multiple cameras have been resolved by using U5.6 and PP1.02, so that's cool :)

Then, I was able to resolve the transparent / DOF issue using two cameras, seemingly without any artefacts:

http://farflunggames.com/download/dof2.jpg

Let me know if you want to know more details about my camera setups.

**Comment by Chman** [comment]
Great, thanks for letting us know :)

A dual camera setup will work fine in your case indeed, as your particles are on top anyway.
