### ISSUE TITLE
WorldToViewportPoint behaves improperly caused by TaaComponent

### ISSUE THREAD

**Issue by chwan1** [Unity-Technologies/PostProcessing#169]
##### What happened?
* create a empty scene and add post processing component, enable anti-aliasing (TAA)
* rotate the camera a little bit
* add a script with following code

```
public Camera cam;
void Update () {
        cam.fieldOfView = 30;

        Vector3 p = Vector3.zero;

        Vector3 screenPoint = cam.WorldToViewportPoint(p);
        Debug.Log("screenPoint: " + screenPoint);

        cam.fieldOfView = 60;

        screenPoint = cam.WorldToViewportPoint(p);
        Debug.Log("screenPoint: " + screenPoint);
}
```
* compare the result with TAA on and off

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5.6.0f3, win10 x64, editor

The behavior is normal if you comment out line 63 in ```TaaComponent.cs```
i.e. ```context.camera.projectionMatrix = context.camera.orthographic ? GetOrthographicProjectionMatrix(jitter) : GetPerspectiveProjectionMatrix(jitter);```

**Comment by Kink3d** [comment]
Hi,

This is due to TAA's jittered projection matrix (which you are commenting out in your example, which makes TAA not work correctly).

If I understand what you are trying to do correctly, you should use two cameras instead of switching a camera's FoV during a frame. You can use a disabled camera as a secondary "state" camera if it is disabled. It is essentially just a matrix then.

**Comment by chwan1** [comment]
Hi,

Basically what we like to do is camera morphing like the Cinemachine, which use virtual cameras (or camera states) to control the target camera. The fix-matrix property make it impossible to morph fov across time. 

Maybe there's a compromised solution to achieve this? For example, a slightly delayed change of projection matrix, or temporally disabling taa during fov change?

**Comment by Kink3d** [comment]
Hey,

Sorry for the delay. I'm afraid that short of generating two projection matrices (at 30 and 60 FOV), multiplying by current view matrix then doing `WorldToViewportPoint` manually the solution I posted previously is the only one we can offer at this time.

Thanks.
