### ISSUE TITLE
Feature request: Proper height depth based fog.

### ISSUE THREAD

**Issue by tdbe** [Unity-Technologies/PostProcessing#170]
I can't take this stack seriously without all of the basic main industry standard effects implemented.

Unity is a huge company with hundreds of graphics programmers around the planet. Surely one of them can take one afternoon off and add proper volumetric exponential height based fog to this. You know, that hot new thing from 10 years ago.

Sorry but there's so many things like this about unity's "released" features that pile up and make me a very unhappy/frustrated customer.

PS: "The old image effects have been deprecated" -  Thanks broseph, but you haven't ported them. Real smooth move.
PPS: maybe add that volumetric raymarched atmospheric scattering in as well. The one you were teasing a year ago.

**Comment by Kink3d** [comment]
Please be more constructive in your posts. We do not appreciate being antagonised and this "issue" is little more than an insult.

Closing
