### ISSUE TITLE
Request: SMAA

### ISSUE THREAD

**Issue by JacobSmaga** [Unity-Technologies/PostProcessing#172]
SMAA is known as a really good type of AA, Is PostProcessing team going to add it and maybe also some other AA types like MLAA, CSAA or EQAA? I know that @Chman made implementation of SMAA for Unity so it should be easy to add it to the stack. Thank you.

**Comment by Chman** [comment]
"Maybe". We're considering SMAA as an alternative as it can be useful in some specific cases where TAA doesn't work well but it's a lot of code to maintain on all platforms, which means less time to dedicate to other features (our team is _very_ small). Note that if it fits your game, our TAA implementation is faster than SMAA, especially on consoles.

> and maybe also some other AA types like MLAA, CSAA or EQAA

SMAA is MLAA, with "subpixel" in front of it ;) CSAA (Nvidia) and EQAA (AMD) are basically traditional MSAA with extra coverage samples added, so they don't register as post-processing effects.

**Comment by JacobSmaga** [comment]
Also any info about other AO variants like SSAO,  HBAO, HDAO or VXAO?

**Comment by Kink3d** [comment]
Weve been investigating other AO methods but results so far are inconclusive. We will only add others if we feel they offer distinct advantages as, like Chman said, we have very limited resources for support and dont want to waste them :)

**Comment by Kink3d** [comment]
Hey,

Just a note. We have added SMAA into V2. However, it will not be added into V1.

Thanks
