### ISSUE TITLE
can't build target to android

### ISSUE THREAD

**Issue by jiangzhen3s** [Unity-Technologies/PostProcessing#174]
##### What happened?
![postprocessing_bug](https://cloud.githubusercontent.com/assets/317738/25789723/6d65cf4c-33e5-11e7-819e-29ec57ff1014.png)

cpu 100%  , a lot of shader process

![postprocessing_bug2](https://cloud.githubusercontent.com/assets/317738/25789762/b360cf74-33e5-11e7-8ea0-87aca3cb9f78.png)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version : 5.6.0f3 & 5.6.0p3
operating system win10  
target platform android
Unity-PostProcessing-1.0.2

**Comment by s5g** [comment]
I've observed the same problem building for Android.

**Comment by Chman** [comment]
See #81 and #39 :)

We're working on improving the first build time by a wide-margin for future versions.

**Comment by Hamed1984** [comment]
i have same problem in 5.6.1 and can not build my game.

**Comment by rsodre** [comment]
My first android build in 5.6 took hours, also stuck at this stage.
I left it building during the night, finished (no idea how log it took) and never had the problem again.

**Comment by Kink3d** [comment]
Non-issue. Like previously stated, first build just takes a long time due to variants. Will be improved.
