### ISSUE TITLE
OnGUI waste CPU in PostProcessingBehaviour

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#175]
PostProcessingBehaviour have OnGUI witch always called but in real game newer used

as result on low cpu device  it waste cpu resouces - because OnGUI  called several times and Unity make staff like layout 

need to-be like this

`class PostProcessingBehaviour
{

    class OnGuiDebug : MonoBehaviour
    {
        void OnGUI()
        {
            // on gui staf ... 
        }
    }

    OnGuiDebug on_gui_debug;

    void SetDebugEnabled(bool set) {
        if (set && !on_gui_debug) {
            var go = new GameObject("PostProcessingBehaviour OnGUIDebug");
            go.hideFlags = HideFlags.HideAndDontSave;
            on_gui_debug = go.AddComponent<OnGuiDebug>();
        }
        if (!set && on_gui_debug) {
            Destroy(on_gui_debug.gameObject)
            on_gui_debug = null;
        }
    }

}`

**Comment by Kink3d** [comment]
This method returns immediately unless you are rendering a debug view. The cost of calling this empty method is minimal to the point of irrelevant. Closing.
