### ISSUE TITLE
2 cameras, one for 3d, on for UI, Bloom seems to be applied twice

### ISSUE THREAD

**Issue by pechaut** [Unity-Technologies/PostProcessing#177]
Create a regular camera, attach a post process file and activate Bloom, exclude UI from culling
Create a second camera, set Depth to 1, exclude everything but UI from culling

If you activate / deactivate the second camera, you see a big difference on the bloom applied by the first cam.

**Comment by pechaut** [comment]
HDR enabled was not activated on the first camera. Activated it, played with on/off, and it works properly.

**Comment by pechaut** [comment]
Nope.. Still there

Enable HDR on both cam and bloom is doubled when second camera is enabled.

**Comment by pechaut** [comment]
Not reproduced using a fresh project..

**Comment by YaserAlOsh** [comment]
I'm facing a similar problem with the new post-processing stack (v2).
What I have done is as follows:
  Create an empty GameObject and assign its layer as UI
  Add a Post Process Volume component to it and make it global.
  Assign the post process profile to it.
  Then add a Post Process Layer component to a camera which renders UI only, and set the layer mask of 
    the Post Process Layer component to exclude everything excepts UI.
What happens is that the post process effect is applied to all objects in the scene regardless of their assigned layer, but what is expected is that the effect would only be applied to objects with UI layer.

**Comment by Chman** [comment]
Layer masking in post-processing is not for "object filtering", it's for volume filtering per camera (so you can have volumes that only affect a given camera and not the others). So if you want to "exclude" or "include-only" objects in post-processing you need to use a multi-camera setup and do proper compositing.

**Comment by YaserAlOsh** [comment]
Thanks for your response.
I have a camera for everything excepts UI, and another camera for UI only, and I have the post-process layer component on the UI camera.
Could you please elaborate more on how to do proper compositing?

**Comment by Chman** [comment]
Well, you'll need to render both of your cameras to separate render textures and then blit one on top of the other (generally UI over the game). That's basically how it works, think of it like Photoshop's layers. You'll need to make sure to use a render texture with alpha for the UI target.

You can do it by code, or you can use a third camera that would only draw two full screen quads, each with the result of the previous two cameras. That's should do the trick.

**Comment by YaserAlOsh** [comment]
Thanks for responding.
I'm trying it but it just seems that I didn't get it:
I have assigned a render texture for each camera, then created another camera with a quad child and a material that just shows the render texture, but I can't make the quad full screen and resize it based on the screen.
What about UI input registration? it doesn't seem that the event system is receiving inputs.
I'm obviously missing something.

**Comment by Chman** [comment]
> but I can't make the quad full screen and resize it based on the screen.

You don't have to do it in 3D, you can use two UI/RawImage for it (one for each render texture). Using the rect transform makes it easy to "scale to fullscreen" in a pixel perfect fashion.

> What about UI input registration? it doesn't seem that the event system is receiving inputs.

I'm not an UI expert by any mean sooo I'm not sure to be honest. There's probably a way to make it work, at this point I'd ask on the forums as they'll probably be more helpful than I'll be on this subject.

**Comment by YaserAlOsh** [comment]
Thanks.
I tried using an Image but the problem is the dimensions of the renderTexture, I will try different dimensions and see what works best.
Did you mean the Unity Forums? I will try there.
Also, I wonder: Could this feature be added? filtering objects affected by post-processing based on layers? just like volume blending but for the global volume case.
That would be a great help!

**Comment by Chman** [comment]
> I tried using an Image but the problem is the dimensions of the renderTexture, I will try different dimensions and see what works best.

Yeah you'll probably need a custom script to create your render textures based on the current screen size.

> Did you mean the Unity Forums? I will try there.

Yep!

> Also, I wonder: Could this feature be added? filtering objects affected by post-processing based on layers? just like volume blending but for the global volume case.

Unfortunately no, this won't be a feature of this package as it's a render pipeline feature more than a post-processing one. Adding something like that has quite a lot of implications and it's not easy to make it perfectly suitable for all uses. We would need a proper compositing framework (hopefully one day).

**Comment by YaserAlOsh** [comment]
Ok.
To be honest this seems like a lot of work for a simple idea to implement (add bloom to UI objects).
So I will probably search for a solution other than the post-processing package.
Thanks again for sticking with me so far!
