### ISSUE TITLE
Color Correction not work on Samsung Galaxy J7 

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#179]
Color Correction not work on Samsung Galaxy J7 

in our game: https://play.google.com/store/apps/details?id=com.MadOut.BIG

**Comment by Kink3d** [comment]
Hi, sorry for late response.

It seems that device doesnt support the texture format used for Color Grading.  Howwever I dont see it on this list http://opengles.gpuinfo.org/gles_listreports.php?extensionunsupported=GL_EXT_color_buffer_half_float (maybe its just too obscure).

Can you please try `SystemInfo.SupportsTextureFormat(TextureFormat.RGBAHalf)` on this device? If it returns false then you will need to use the User LUT effect as a fallback. 

Thanks.

**Comment by Kink3d** [comment]
ARGB32 has been added as a fallback format for Color Grading. This fixes this issue in our test cases. Please respond if it doesnt fix it in your case.

Thanks
