### ISSUE TITLE
Screen is Black when turns on Post Processing behavior on Android 5.0.2

### ISSUE THREAD

**Issue by iamtov** [Unity-Technologies/PostProcessing#183]
Hi,

Unity 5.5.2 p2 / Android 5.0.2

When turns on Post Processing behavior on Android, camera rendered nothing & screen is Black.
(Checked on FAA, Bloom, Color Grading)

iOS or other Android version (6.0.1) works fine.
So I guess this is an issue of android version compatibility.

How can I solve this?

**Comment by Kink3d** [comment]
Hi,

Is this a different android version on the same device or different devices? If the latter can you please post info on the devices? Its likely that Color Grading is unsupported due to requiring support for RGBAHalf texture format.

Thanks

**Comment by iamtov** [comment]
I'm using two components - Color grading and Bloom.

Galaxy S6 (Android 5.1.1) -> Doesn't work ColorGrading and Bloom.
(Same Device on Android 6.0.1 -> both components works fine.)

In Color Grading case,
I have found what you said. so I changed RenderTextureFormat to Default, and It works fine.

[ColorGradingComponents.cs / void GenerateLut()]

RenderTextureFormat fmt = SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.ARGBHalf) ?
					RenderTextureFormat.ARGBHalf : RenderTextureFormat.DefaultHDR;
				fmt = SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.DefaultHDR) ?
					RenderTextureFormat.DefaultHDR : RenderTextureFormat.Default;

				model.bakedLut = new RenderTexture(k_InternalLogLutSize * k_InternalLogLutSize, k_InternalLogLutSize, 0, fmt) {

But In Bloom case, It still doesn't work. check this please.

**Comment by CosmosTbear** [comment]
We seem to have the same issue with the bloom effect (screen is black) on a Macbook Pro 2017 (Intel Iris Plus Graphics 640) Any update on the matter?

**Comment by mangax** [comment]
am getting black screen on pixel phone.. android 7.1.2

**Comment by Kink3d** [comment]
Hi,

We have added a fallback to ARGB32 for Color Grading to fix that issue. It loses some precision but it acceptable in most cases.

The bloom issue is a separate one and, as Cosmos notes, is the same as #207 . Will close this issue. Follow #207 for updates.

**Comment by Nrjwolf** [comment]
Have same problem with bloom on Iphone 5s
