### ISSUE TITLE
SSR Doesnt work with Transparent Material

### ISSUE THREAD

**Issue by edankwan** [Unity-Technologies/PostProcessing#184]
SSR Doesnt work with Transparent Material

5.6, Win10

**Comment by Kink3d** [comment]
Hi,

SSR only works with objects rendered in deferred. Transparent objects always render in forward (regardless of the chosen rendering path) therefore this is expected. It should be noted that "cutout" shaders will still work (as long as youre in the deferred rendering path) as they will still render in deferred.

Thanks
