### ISSUE TITLE
 SSR invalid material pass number on 5.6.1

### ISSUE THREAD

**Issue by ssameng** [Unity-Technologies/PostProcessing#185]
SSR effect when enabled breaks on Unity 5.6.1 and throws:
Invalid pass number (6) for Graphics.Blit (Material "(Unknown material)" with 6 passes)

Error goes away when disabling SSR

Using PostProcessing stack 1.0.2

**Comment by Kink3d** [comment]
Hi,

Confirmed issue. I get the following errors:

```
GLSL compilation failed:
ERROR: 0:140: Swizzle component 'z' indexes beyond end of input vector (length 2)
ERROR: 0:141: Swizzle component 'w' indexes beyond end of input vector (length 2)

Invalid pass number (6) for Graphics.Blit (Material "(Unknown material)" with 6 passes)

Invalid pass number (8) for Graphics.Blit (Material "(Unknown material)" with 6 passes)
```

Looking into it. Thanks.

**Comment by Kink3d** [comment]
No longer repros in 5.6.2p1

**Comment by DooblyNoobly** [comment]
Still experiencing this bug in 5.6.3p3
