### ISSUE TITLE
Ambient Occlusion Flickering on low spec machine

### ISSUE THREAD

**Issue by LitchiSzu** [Unity-Technologies/PostProcessing#188]
##### What happened?

On some lower spec machines (i3, GTX460), AO is flickering a lot (turning on/off really quickly).
Manually changing the sampleCount fixes the issue. Even if it's changed back to its initial value then.

Trying to change it in code on the first frame to a different value and then setting back to the correct value on the second frame doesn't work (and would be a weird work around!). Any clue what's happening ? Please : D

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3, Standalone builds on Windows 7 on a machine with a i3 and GTX460. Does that on a few other machine with same kind of spec. Doesn't do it on our usual work machines.

**Comment by LitchiSzu** [comment]
Note that our current work around for that is to set the _SampleCount to a const int in the shader instead of having a variable one sent from the CPU.

**Comment by AlexandreFiset** [comment]
Note: The flickering also occurs on some of our machines, which aren't "low-end" (i7 + 970 GTX).

Thanks for the workaround, we'll try that as the flickering is pretty annoying.

**Comment by keijiro** [comment]
I also observed this issue with my GTX 1070 card, so I think "low spec" is not a prerequisite for the issue.

There are two possible workarounds for the issue.

- Downgrading the driver version; In my case the issue disappeared when I downgraded the NVIDIA driver to 378.49 (January 24, 2017).
- Modifying `AmbientOcclusion.cginc` slightly; Please apply the following change to `AmbientOcclusion.cginc` in your project.

https://github.com/keijiro/PostProcessing/commit/f8913b77cb4a813118133f5e9f574a59dd60314e

Or download the modified version of the post-processing stack from [here](https://github.com/keijiro/PostProcessing/archive/ao-nv-fix.zip) and replace it within your project.

Any feedback would be welcomed. I'll merge this change into master if it actually fixes the issue not only on my cases but also with your projects.

**Comment by Kink3d** [comment]
Hi,

Just an update on this. Found a few cards that reproduce this issue. Will be doing a proper test pass on the fix Keijiro posted above and see if we can push to master.

**Comment by Chman** [comment]
Workaround in f27e035

**Comment by GuSoder** [comment]
Hi, I experience this flickering very clearly with Unity 3018.3 and a gtx 670. 
Sorry if I misunderstand, but should the Workaround mentioned on 7 August be included in my version of Unity?
I tried to find the mentioned .cginc file, but turn up empty handed, sorry for posting this without proper understanding, but i can't figure out how to avoid the flickering.

**Comment by AnomalousUnderdog** [comment]
> Hi, I experience this flickering very clearly with Unity 2018.3 and a gtx 670.
> Sorry if I misunderstand, but should the Workaround mentioned on 7 August 2017 be included in my version of Unity?
> I tried to find the mentioned .cginc file, but turn up empty handed, sorry for posting this without proper understanding, but i can't figure out how to avoid the flickering.

@GuSoder: The fixes mentioned here are applied already. If you got PostProcessing stack from the latest commit of v2 branch, or if you got it using Unity Package Manager, then the fixes are applied already. From what I can see, the .cginc mentioned is now `ScalableAO.hlsl`.

What AO mode are you using? The only time I experience bad flickering is in a Linux build when running in OpenGL and only when using MultiScale Volumetric Obscurance (doesn't happen in Windows, and doesn't happen in Linux when running in Vulkan).
