### ISSUE TITLE
Disable effects on behaviour

### ISSUE THREAD

**Issue by Wahooney** [Unity-Technologies/PostProcessing#189]
An enabled override on the PostProcessingBehaviour would be handy for individually setting effects on and off at run-time, the alternatives are:
* Have a ton of individual effects stacks for all permutations (stupid)
* Change the enabled state on the stack asset (changing the stack asset is not great as it's destructive)

So being able to set each effect on or off on the behaviour itself is the only really viable solution.

**Comment by Kink3d** [comment]
Actually you can make clones of your profile assets to edit them at runtime. Please check this wiki page:

https://github.com/Unity-Technologies/PostProcessing/wiki/Runtime-Post-Processing-Modification

However we appreciate this is far from a perfect solution. We are working on a much better solution to this but its going to take a while still.

Thanks
