### ISSUE TITLE
Fog cannot be disabled

### ISSUE THREAD

**Issue by TJHeuvel** [Unity-Technologies/PostProcessing#192]
##### What happened?
In our project we have made a custom fog solution that we would like to keep using. Right now we cannot disable the Post processing's Fog component in the profile, and it gets reset on start too. 

https://streamable.com/9tgpg

The component misses the Enabled checkmark, it can only be set in Debug mode.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.5.3, Windows 10, Standalone Windows, Mac, PS4, x1

**Comment by Kink3d** [comment]
Fixed by referenced PR. Its worth noting that this was a conscious decision as now fog essentially has two enable checkboxes, which isnt the best UX. I wonder how long it will take for someone to submit an issue for that :)
