### ISSUE TITLE
Ambient Occlusion makes the scene low rez in VR when using single pass rendering

### ISSUE THREAD

**Issue by jonarnold** [Unity-Technologies/PostProcessing#193]
When using Ambient Occlusion and when VR stereo rendering is set to single pass, all objects in the scene become unacceptably low rez. 

(Unity 5.6.1, Windows 10, standalone Windows for HTC Vive)

**Comment by ddoubledeuce** [comment]
I'm seeing the same thing - 5.6.1p1.

In addition, I'm seeing artifacts which seem to be coming from the shadow buffer.  Does not occur in multi pass stereo.

**Comment by andybak** [comment]
Same here. Related question - is SSAO going to be added to v2? I tried that thinking it might have improved things.

**Comment by Chman** [comment]
I'm not able to reproduce this in 5.6.1 in a few test scenes I have, even when I enable AO downsampling. Would you have a simple project that exhibits the issue I can look at?

> is SSAO going to be added to v2?

Yes.

**Comment by Kink3d** [comment]
Still unable to repro this. Ill close the issue (>4 weeks inactivity). If anyone can offer a reproduction project we will reopen.
