### ISSUE TITLE
I couldn't get it work well in Unity 5.5 with Version 1.0.2

### ISSUE THREAD

**Issue by lovelyapple** [Unity-Technologies/PostProcessing#195]
Hello , I tried to install this PostProcessing Version 1.0.2.
But I couldn't get it work in my Env.
# Failed at 1.0.2

When I select opened these shader selection:
* Ambient Occlusion     
* Depth OF Field            
* Motion Blur                  
* User Lut  
                     
I get a white screen in both Screen and Game Window.
![2017-05-30 21 00 49](https://cloud.githubusercontent.com/assets/17754568/26582179/1d7b195e-457b-11e7-8e3c-3fc28464b56d.png)

# My Env 
* MacBook Pro 2012
* 8GB,
* IntelHD4000
* Unity : 5.5.2f1.

By the way,1.0.0 and 1.0.1 worked well.

I'm sorry I couldn't figure out where is wrong,but I think it might be helpful if there's a table show  all versions of Unity requied by each version of  PostProcessing.

**Comment by Kink3d** [comment]
Hi,

Are you using Forward/MSAA? There is a bug in Camera in 5.5 when using the effects you listed (specifically Ambient Occlusion and Motion Blur) with this setup.

Thanks

**Comment by lovelyapple** [comment]
well,I'm useing the Forward,and Iafter I truned it to deffered,everythings worked well.

**Comment by lovelyapple** [comment]
I watched the video about the PostProcessing in the Unit2017,and learned it more.
Thanks so much.

**Comment by Kink3d** [comment]
Youre welcome. Glad you got it working :)
