### ISSUE TITLE
SSR does not reflect skybox

### ISSUE THREAD

**Issue by chingwa** [Unity-Technologies/PostProcessing#2]
This iteration of the Unity SSR effect is really looking nice, however it does not calculate the scene skybox into reflection data which severely hampers the visual results in open-air/outdoor scenes.  It would be great if this can be added to the SSR calculation, either the current skybox specifically, or whatever the camera clear flag setting is (color, skybox etc).

**Comment by Chman** [comment]
SSR can't reflect the skybox, it should be done using Reflection Probes or Planar Reflections (which can be used at the same time as SSR). There's no way around it as the skybox is rendered after SSR is applied (which would be after the final geometry pass in deferred lighting).

Also keep in mind that SSR is a screen-space effects, meaning it has no way of knowing about something that's not currently on screen. It's not meant to provide complete reflections but to fake "contact" reflections.
