### ISSUE TITLE
When building for android process freezes 

### ISSUE THREAD

**Issue by MateiGiurgiu** [Unity-Technologies/PostProcessing#20]
The building process freezes at the packaging stage when building for android. The CPU goes 100%.

**Comment by Kink3d** [comment]
Hi,

Could you provide Unity Version? Does it build correctly without Post Processing in the project? Are you deploying straight to phone through ADB or just building an APK?

I have recently been testing Android deployments and haven't seen this issue yet so information is very much appreciated.

Thanks

**Comment by MateiGiurgiu** [comment]
Hey again,

I wasn't able to reproduce it. When the problem occurred I was using unity 5.4.2 and I was just building an APK. After that I deleted the post-processing folder and the build went fine. Now I re-imported the post-processing folder and the building process doesn't freeze anymore.

**Comment by Kink3d** [comment]
Hey,

Thanks for letting us know anyway. If you manage to reproduce the issue please get back in contact!

**Comment by jiangzhen3s** [comment]
i use unity 5.6.0f3
build target android ,editor freeze in "packaging assets xxxxxx" , cpu use 100% (many unity shader process runing )
i fixed this problem .   menu-> assets-> reimport all
