### ISSUE TITLE
Unity 5.6.1f1 , compile error , lost reference?

### ISSUE THREAD

**Issue by jejelite** [Unity-Technologies/PostProcessing#204]
I cant seem to import the stack process into ur folder , it generate those error : 
![image](https://user-images.githubusercontent.com/20047579/27104818-5a877212-505b-11e7-92e0-ee996765770f.png)

At first glance , it seem there's a lost of reference somewhere.

![image](https://user-images.githubusercontent.com/20047579/27105119-65852fb4-505c-11e7-8488-85d945bf8a9f.png)

What i already try : 
- reimport
- Dowload again and reinstall 

Importante to note that it working in a new project but i cant find what cause such error.

**Comment by Chman** [comment]
Hi,

This error is quite baffling and I can't think of a reason why it would happen. What's your build target?

**Comment by Chman** [comment]
Just curious... Do you have a class named "Action" in your project? Because that would be the issue here. Overriding standard C# class names is generally not a good idea :)

**Comment by EnricoMonese** [comment]
I also had this problem when I tried it some weeks ago. And if I remember correctly that was exactly the problem. So I just wrapped the other class (which was from a node-editor-graph thing) in it's own namespace to fix it.
