### ISSUE TITLE
Depth of field artifacts

### ISSUE THREAD

**Issue by billowper** [Unity-Technologies/PostProcessing#205]
Artefacts caused by having HDR enabled on camera and using depth of field.

Unity 2017.1.0b9

Exacerbated when using SSR

https://files.facepunch.com/billowe/2017/June/16/Unity_2017-06-16_20-36-30.jpg

https://files.facepunch.com/billowe/2017/June/16/2017-06-16_20-34-35.mp4

https://files.facepunch.com/billowe/2017/June/16/Unity_2017-06-16_20-40-38.jpg

https://files.facepunch.com/billowe/2017/June/16/Unity_2017-06-16_20-46-55.jpg

Frame debugger
https://files.facepunch.com/billowe/2017/June/16/Unity_2017-06-16_20-47-54.jpg

Camera setup
https://files.facepunch.com/billowe/2017/June/16/Unity_2017-06-16_20-54-10.jpg

**Comment by DuckyDuckling** [comment]
Unrelated question, what's the post stack setup on this like? It looks really sweet.

**Comment by Chman** [comment]
This is the result of a NaN pixel from a previous pass that survived until DoF and got expanded by it. It's not a DoF issue, but it may very well be a SSR issue.

At this point the best way to go is to use [RenderDoc](https://docs.unity3d.com/Manual/RenderDocIntegration.html), capture a frame that exhibits the issue and track down the pass where the NaN appeared for the first time (RenderDoc makes it easy to track the life of a single pixel through a single frame). This will tell you precisely what's responsible for it. Looking at the list of command buffers on your camera, I would start by looking at each of them in order.

If you have trouble with RenderDoc you can export a capture from there and send it to me, I'll look at it and track down the NaN.

**Comment by billowper** [comment]
I'll check out RenderDoc, thanks!

In meantime I've found that it seems to caused by some of the geometry in the scene, and specifically after  I've baked lightmaps. So a couple of bad vertices here and there seem liable to produce this. I guess I have my sloppy ProBuilder usage to thank!
