### ISSUE TITLE
Using two depth cameras with TAA doesnt work

### ISSUE THREAD

**Issue by JVasica** [Unity-Technologies/PostProcessing#21]
When having two cameras with clear flags set as depth only and TAA on, than the lower one is not rendered. FAAA and other effects seems to be working as expected with this set up.

![good](https://cloud.githubusercontent.com/assets/23481891/20320156/29263f9e-ab71-11e6-898c-e7204bbcd06c.PNG)

![wrong](https://cloud.githubusercontent.com/assets/23481891/20320178/3e5aa652-ab71-11e6-8b25-94a4507aafc0.PNG)

**Comment by Kink3d** [comment]
Hi,

Thanks for reporting the issue. Unfortunately I haven't been able to reproduce this. Could you attach a small project that displays this issue?

Thanks

**Comment by JVasica** [comment]
Hi,
I have created small project which displays that problem. While creating this project I discovered another weird behaviour with this set up, which occurs only rarely. Usually when I pressed play the green floor disappeared, but twice it displayed content of both cameras, but when I rotated/moved content of the lower camera(green floor) it moved only in the scene view, but not in the game view and when I moved the cube, which is rendered with the upper camera the result was not cleared.  Screenshot of how it looked like: 
![bug](https://cloud.githubusercontent.com/assets/23481891/20394746/e6add1ec-ace0-11e6-8dcd-e6cb07b9b2c5.PNG)

The project can be downloaded here: 
https://ufile.io/52814

**Comment by Chman** [comment]
We did a big refactor on framebuffer & backbuffer management and it fixes a lot of issues with multi-camera issues like this one. Unfortunately this won't make it in Unity 5.5 so it'll be in 5.6. @Kink3d tested your scene in 5.6 and confirmed that it's been fixed.
