### ISSUE TITLE
Bloom + Color grading not working in GearVR (Samsung S6)

### ISSUE THREAD

**Issue by Alexandros1313** [Unity-Technologies/PostProcessing#210]
Hi,
I've set Bloom + Grading Effects for my project (space simulation). In editor and on desktop everything works great, but when I build it for GearVR (Samsung S6), post effects seems not working at all.
Is there any particular setting to be applied to make it work? 
thx

Info: Unity 5.6.1 - Windows 10 - GearVR (Samsung S6)

**Comment by Chman** [comment]
Have you tried the latest build we pushed a few days ago (not yet on the Asset Store)?
You'll find it [here](https://github.com/Unity-Technologies/PostProcessing/releases) (1.0.3).

**Comment by Alexandros1313** [comment]
I'll try it today and I'll give you a feedback.

Thx a lot.

**Comment by Alexandros1313** [comment]
[FIXED!]
I've enabled Use HDR in Graphics Settings and now it works! :-D
