### ISSUE TITLE
Unity 5.6.2f1 MSAA broken in SinglePass Stereo Rendering

### ISSUE THREAD

**Issue by Gruguir** [Unity-Technologies/PostProcessing#212]
MSAA don't work if Stereo rendering method is set to single pass and 'Post Process Layer' script is checked (even with all effects disabled in 'Post process volume' script).

Unity 5.6.2f1, Windows x86_64, DX11

**Comment by Chman** [comment]
Thanks for reporting this bug, but V2 is still in development, and as the Readme reads:

> This branch is under active development, it is considered somewhat unstable and shouldn't be used in production. Do not use the issue system to report bugs from this branch. Use at your own risk.

VR support in this branch isn't finished at this point and is only barely tested.
