### ISSUE TITLE
Can't find SSR in v2

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#215]
I just try new v2 and feel awesome! But can't find SSR, Is it rewriting now? When we can see the new SSR? The old SSR has big performance issue in our game, we can't use it.

And, is there a document to explain how priority work in Volume? What's the relationship between priority and weight?

**Comment by JacobSmaga** [comment]
https://forum.unity3d.com/threads/new-post-processing-stack-pre-release.435581/page-12#post-3133709

**Comment by Chman** [comment]
SSR is being reworked. It will be integrated in v2 once it's usable.

As for documentation / quickstart guides... It's right there [on the front page](https://github.com/Unity-Technologies/PostProcessing/tree/v2).
