### ISSUE TITLE
Error at compiling: "Graphics" does not contain a definition for "Blit"/"Draw texture"

### ISSUE THREAD

**Issue by TheStr3ak5** [Unity-Technologies/PostProcessing#216]
##### What happened?
Well, I decided to import post processing stack in my unity proyect and i had these compile errors.
![23](https://user-images.githubusercontent.com/30004048/27986536-620686dc-6400-11e7-8299-2b980cff9303.PNG)
I hadnt done nothing strange and all the features apart are working well, is just this problem.
Thanks for the attention and thanks in advance.
(sorry if my english is not that good, is not my first language)
(in the image can be seen a lot of warnings, i reviewed this warnings and no one is related to post processing stack)
 
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version: 5.6.1f1 Personal(64 bits)
OS: Win 10
Target platform: PC,Mac & linux standalone (dx11)

**Comment by Chman** [comment]
`Graphics` is a standard class in the `UnityEngine` namespace. This means that you probably have another class called `Graphics` somewhere in your project that isn't namespace'd (which is, needless to say, a _very_ bad idea), either from your own code or an asset downloaded from the store. So you'll have to find it and either rename it or put it in a namespace that isn't global.
