### ISSUE TITLE
Depth of Field not working on Android

### ISSUE THREAD

**Issue by vJoeyz** [Unity-Technologies/PostProcessing#217]
##### What happened?
In the editor the depth of field effect seems to working fine. On Android (4.1) however even with the focus distance at 1, there is no depth of field effect visible whatsoever.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version: 5.6.2f1
OS: Windows 10 Pro 64bit
Target platform: Android

**Comment by Kink3d** [comment]
Hi,

Thanks for the report. We have regression tests running on several Android devices and haven't seen this so it might be related to the device. Can you please tell us:

- The device model number (as exact as possible, sometimes devices can have multiple GPU options)
- The Android OS version on the device (I assume this is 4.1 like you mention?)
- The minimum Android OS set on the project (Player Settings)
- The graphics API(s) you're using (Player Settings)

Thanks a lot

**Comment by vJoeyz** [comment]
Hi there,

The information you requested can be found below:

- Samsung Galaxy S3 (GT-I9300)
- Android version 4.3
- Minimum OS is 4.1
- Graphics API is set to auto

I will test today on my Galaxy S8 too to check if it works there. ;)

**Comment by Kink3d** [comment]
Hey,

Thanks for the info. That S3 has a Mali 400 GPU which doesnt support the texture format (ARGBHalf) required for Depth of Field. Im going to test a fallback format for this case but I wouldnt hold your breath, CoC requires good precision.

**Comment by Chman** [comment]
This has been fixed a few weeks ago (in v1 and v2). Mind you, it's more of a workaround than a fix. Due to the lack of good precision textures on these platforms you'll only get depth of field for the far plane, not the near plane.
