### ISSUE TITLE
Can't edit effects on v2 stack, using Mac 2017.1, OpenGL4

### ISSUE THREAD

**Issue by bfod** [Unity-Technologies/PostProcessing#218]
##### What happened?
I can add the new post effects stack to my cameras and create post effects volumes, and they work well enough in play mode, but if I go to edit the effects in the inspector, every field is greyed out and not interactable. 
No errors are thrown.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1f3
Mac OS 10.12.5
Editor machine: Macbook Pro 15" with Touch Bar (2016)
Target platform: Mac and Windows

**Comment by Chman** [comment]
I'm not sure I understand to be honest. I'm using v2 on a MBPro and I can edit fields just fine. Could you post a screenshot of these greyed out fields?

**Comment by bfod** [comment]
Ah, ok I did some more experimentation. The issue is that all options are greyed out unless you check the override box next to them. I was confused by the fact that the 'All' and 'None' buttons look like column headers instead of buttons, and the checkboxes are so dark in the pro skin that they look like bullet points instead of checkboxes. So I guess this isn't a bug, but I think still a UX issue. My recommendations:

1) If I click the title of a parameter field (e.g. 'Sample Count') toggle the override on that property. There'll never be a case where someone clicks a disabled field and does not want to interact with it.
2) Make it more obvious that 'All' and 'None' are buttons, and do not position them so they perfectly match the horizontal positions of the checkboxes and label columns. For example, you might want to make 'override none' a checkbox at the top of the list of properties, matching the convention in other areas of Unity (e.g. static flags, occlusion layers)
3) Find some way to make the disabled checkboxes look more like checkboxes and less like bullet points. If you had 'Override none' as a checkbox that was checked by default, then it would be completely obvious.

**Comment by Chman** [comment]
>  The issue is that all options are greyed out unless you check the override box next to them.

It's an override stack, so yes, it's by design.

> If I click the title of a parameter field (e.g. 'Sample Count') toggle the override on that property. There'll never be a case where someone clicks a disabled field and does not want to interact with it.

That's not good though, as in Unity the title of a field is used to tweak the value when it's enabled (for instance click & drag on float fields to tweak its value instead of having to type a number). So UX-wise I don't see how we could put two different behaviors on the same element.

> Make it more obvious that 'All' and 'None' are buttons, and do not position them so they perfectly match the horizontal positions of the checkboxes and label columns. For example, you might want to make 'override none' a checkbox at the top of the list of properties, matching the convention in other areas of Unity (e.g. static flags, occlusion layers)

I agree that they need to be more explicit but using a checkbox doesn't really work in this case, it's not a state at all (and completely different from the game object flags). It's a "quick select all" function. That's all it does, toggle them all for you.

**Comment by bfod** [comment]
Sure, these are reasonable points. I'm just enumerating the things that confused me. I've been using unity for around 5 years and I got totally stuck with these controls even after about half an hour of experimenting. It's possible my experience will turn out to be unique but I doubt it.

**Comment by antdavies** [comment]
Wow thanks! I was also head-scratching over this. On the Pro skin the buttons All and None are *very* easy to miss...

**Comment by HECer** [comment]
I can agree, i had also the problem for a half an hour, and i am a advanced unity user :D
All and None i missed out.
The checkboxes are looking like they are greyed out also.
