### ISSUE TITLE
Will you allow users to roll-out their own effects ?

### ISSUE THREAD

**Issue by aybe** [Unity-Technologies/PostProcessing#221]
The new post-processing stack is really great and easy to use :)

Do you have plans to allow end-users to implement their own effects ?

Thank you !

**Comment by Chman** [comment]
Yes. There's a link about that in the readme: [Writing custom effects](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Writing-custom-effects).

**Comment by aybe** [comment]
Sorry, I didn't see the updated documentation, thank you 😃
