### ISSUE TITLE
[v2] Breaks transparent fresnel rim shader

### ISSUE THREAD

**Issue by OhiraKyou** [Unity-Technologies/PostProcessing#224]
##### What happened?
When I add v2 to a project, it breaks a transparent fresnel rim shader, causing it to become invisible unless a post processing layer is added to the camera. Also, it flickers in and out of existence unless ambient occlusion is enabled and takes on the color of objects between it and the camera. None of these things happen before v2 is added to the project.

For example, the globe in this screenshot should be white, but it has taken on the color of the foreground object:
![fresnel problem](https://user-images.githubusercontent.com/7255919/28501233-78dad31c-6fa5-11e7-8334-19b217a16cad.jpg)

Example project (before importing v2): [Fresnel Problem Without PP Stack.zip](https://github.com/Unity-Technologies/PostProcessing/files/1168223/Fresnel.Problem.Without.PP.Stack.zip)

#### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3 (64-bit)
Windows 10

**Comment by Kink3d** [comment]
Hi,

Thanks for the reproduction project, this was essential in working out your issue :)

You have not defined `_MainTex` in your property block but are using it in your second pass. So it will basically hold anything that ends up being bound to _MainTex at that point.

Defining `_MainTex` in the property block fixes the issue.

**Comment by OhiraKyou** [comment]
That solved it, thanks! Weird that it hadn't bit me until this point.
