### ISSUE TITLE
Impossible to use camera depth texture with post processing stack

### ISSUE THREAD

**Issue by Phantomx2** [Unity-Technologies/PostProcessing#225]
##### What happened?
- Forward rendering mode
- Have a script that enable depth texture on camera with depthTextureMode = DepthTextureMode.Depth;
- Have soft particles or any other shader that uses depth texture
- Put post processing stack on the camera
- Add a behaviour with nothing enable or nothing that uses camera depth texture
- Observe the soft particles are not working anyore.
- Even if I enable the depth texture every frame it gets override by post processing stack and is never available.

- Noticed sometimes that it is breaking only when I turn Off shadows on the light.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Tested on Unity 5.5 and 5.6

**Comment by Kink3d** [comment]
Hi,

Unless I'm mistaken this bug is the same as #33 which was fixed by #173 ?

Are you using an older version of the package (previous to https://github.com/Unity-Technologies/PostProcessing/releases/tag/1.0.3)?

**Comment by Phantomx2** [comment]
humm yes I think this is it, I'm on unity 5.6, I think only version 1.0.2 is available on this version.

**Comment by Kink3d** [comment]
You are correct. We submitted 1.0.4 to the Asset Store yesterday so that will be up soon. Until then you can grab latest from Github and it should fix your issue.

Thanks
