### ISSUE TITLE
Targetting build to Android failed

### ISSUE THREAD

**Issue by thargy** [Unity-Technologies/PostProcessing#228]
##### What happened?
Targeting Android with v2 of the stack, downloaded on 30 July.
Error building Player: Shader error in 'Hidden/PostProcessing/Debug/Waveform': 'StructuredBuffer' : syntax error syntax error at line 8 (on gles)

Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_MOBILE UNITY_HARDWARE_TIER2 UNITY_COLORSPACE_GAMMA

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3, Android (Gradle/Internal), Development Build

**Comment by Chman** [comment]
Fixed in c9a03a4.
