### ISSUE TITLE
Grain not working properly on macOS Metal

### ISSUE THREAD

**Issue by EnricoMonese** [Unity-Technologies/PostProcessing#229]
Unity 2017.2.0b5 
macOS High Sierra Beta
Target Pm, Mac & Linux

In the editor with metal support enabled grain looks like this (both v1 and v2)
![grain](https://user-images.githubusercontent.com/19847464/28937964-d077270c-788c-11e7-82a3-8c68305797c3.jpg)

<sup>Yeah I know beta software on beta OS</sup>

**Comment by Kink3d** [comment]
Hi,

I just tried and cannot reproduce this on 10.12.5. Its likely that this is some sort of driver bug in High Sierra. I will try to look into this.

Thanks

**Comment by EnricoMonese** [comment]
Yeah that's what I though, reported anyway. Cloud be related to Metal2 API

**Comment by Kink3d** [comment]
Hi,

Tried to reproduce this on a High Sierra beta with no luck. Possibly a Metal2 bug. I'll speak to someone at Apple about it.

**Comment by EnricoMonese** [comment]
Newer macOS beta was released, appears to be fixed
