### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by coreyx** [Unity-Technologies/PostProcessing#230]
##### What happened?

Cannot get a successful build with PostProcessing Stack V2 (Latest commit df8259f  7 days ago). Seeing the following build errors:

Shader error in 'Hidden/PostProcessing/Debug/Waveform': in ps_3_0 uints can only be used with known-positive values, use int if possible at line 30 (on d3d9)

Compiling Fragment program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP

Shader error in 'Hidden/PostProcessing/AmbientOcclusion': unable to unroll loop, loop does not appear to terminate in a timely manner (322 iterations) or unrolled loop is too large, use the [unroll(n)] attribute to force an exact higher number at Assets/Third Party/PostProcessing/Shaders/Builtins/AmbientOcclusion.hlsl(212) (on d3d9)

Compiling Fragment program with UNITY_COLORSPACE_GAMMA
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP

UnityEditor.BuildPlayerWindow+BuildMethodException: Build failed with errors.
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x001b9] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:162 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEditor.HostView:OnGUI()

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2017.1.0f3, Windows 10 64-bit, standalone Windows build

**Comment by coreyx** [comment]
Workaround for now: Go to Build Settings->Player Settings->Resolution and Presentation, uncheck "Auto Graphics API for Windows" and remove Direct3D9 from the Graphics API for Windows list.

I tried some code workarounds as well, including changing the int to uint in the WaveForm shader code and adding the [unroll(n)] attribute to the Ambient Occlusion shader code, but I ran into other errors when doing so and I figure since I'm not using D3D9, the workaround will do for now.

**Comment by Chman** [comment]
Fixed in c9a03a4 & ff50b5f.
