### ISSUE TITLE
Grey Game Screen on Mac

### ISSUE THREAD

**Issue by henrysneed** [Unity-Technologies/PostProcessing#233]
##### What happened?
The instant I add the PostProcessLayer script to my camera, the game screen goes grey. I can still see the scene on the scene screen and when adding volumes I can see the effects take place on both the scene and on the grey of the game screen. But on the game screen I can't see anything but grey.

--I believe this could be the same issue as Elringus.
https://github.com/Unity-Technologies/PostProcessing/issues/226

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Using unity 5.6.2
OSX 10.11.6

**Comment by Kink3d** [comment]
Hi,

Can you confirm that youre using Forward Rendering path with both MSAA and HDR turned off?

If so this is a known bug and we are working on fixing it. For now you can enable either MSAA or HDR as a workaround.

Thanks

**Comment by henrysneed** [comment]
I had HDR turned on and MSAA turned off. And for rendering path I just had "Use Graphics Settings". Turning MSAA on worked.

**Comment by Chman** [comment]
Should be fixed in 8ebad26.
