### ISSUE TITLE
Neutral tonemapping + contrast over 1.4 causes weird oscillations on highlights

### ISSUE THREAD

**Issue by CustomPhase** [Unity-Technologies/PostProcessing#234]
Basically subj. When having Neutral tonemapping active and setting the contrast slider to anything higher than 1.4 causes weird oscillations on specular highlights. Using latest version of the V1 stack. Heres the screenshot showing the problem (highlight on the top of the red car in the center):
![issue](https://user-images.githubusercontent.com/10864826/29043771-08671270-7bd6-11e7-9d84-38356dc6babf.PNG)

**Comment by Chman** [comment]
Hi, any chance you could send us your project or a small repro case?

**Comment by CustomPhase** [comment]
Sure, was able to reproduce it fairly easy. Just open the main scene and you'll see the same behavior on the cube in the game view right away. Moreover, driving the contrast slider in the post process profile further increases the amount of artifacts with the specular.
https://drive.google.com/file/d/0B5bjv5FhKSIoWUJkTWloLWVobzQ/view?usp=sharing

**Comment by Chman** [comment]
Thanks for the repro, that helped.

It's a color space issue and has to do with how color grading is implemented in v1 (mind you, this issue doesn't happen in v2). We do have a local fix for it, but it affects the output of the neutral tonemapper slightly which means that anyone who relied on this tonemapper until now and tweaked color grading to match what they needed won't see the exact same result after updating... And this is quite a problem for us. That said, the fix also makes the highlights look much better when the neutral tonemapper is in use.

We're currently looking into it, I'll leave this issue opened until then.

**Comment by Chman** [comment]
PR pushed #236.

Feel free to try it and let us know.

**Comment by CustomPhase** [comment]
Thanks, that solved it
