### ISSUE TITLE
[V2][Android] GLES2 GLSL link error

### ISSUE THREAD

**Issue by thargy** [Unity-Technologies/PostProcessing#235]
##### What happened?
Shader error in 'Hidden/PostProcessing/Copy': 'isnan' : no matching overloaded function found; 'any' : cannot resolve function call unambiguously (check parameter types) 'isinf' : no matching overloaded function found; 'any' : cannot resolve function call unambiguously (check parameter types) at line 34 (on gles)

Compiling Vertex program
Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER SHADER_API_MOBILE UNITY_HARDWARE_TIER1 UNITY_COLORSPACE_GAMMA

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3, Android (Gradle/Internal), Development Build

**Comment by Chman** [comment]
Should be fixed in be16139. Could you please double-check that it fixes the issue?

**Comment by thargy** [comment]
It did build and deploy, but on running on a HTC One I get the following errors over remote debug:

<i>AndroidPlayer(HTC_HTC_One_M9@172.16.51.201)</i> -------- GLSL link error: Warning: barrier used in non-uniform control flow
Stacktrace is not supported on this platform. 
(Filename: ./Runtime/GfxDevice/opengles/ApiGLES.cpp Line: 657)
0x00000001409897FB (Unity) StackWalker::GetCurrentCallstack
0x000000014098CD5F (Unity) StackWalker::ShowCallstack
0x0000000140D35030 (Unity) GetStacktrace
0x0000000141079D56 (Unity) DebugStringToFile
0x000000014107A52C (Unity) DebugStringToFile
0x00000001411EE544 (Unity) EditorConnection::HandleLogMessage
0x00000001411F0BB3 (Unity) GeneralConnection::Poll
0x00000001411F339E (Unity) EditorConnection::PollWithCustomMessage
0x000000014013089D (Unity) Application::TickTimer
0x0000000141A87E5D (Unity) MainMessageLoop
0x0000000141A89827 (Unity) WinMain
0x0000000141CEC8BC (Unity) __tmainCRTStartup
0x00007FF9D2FC8364 (KERNEL32) BaseThreadInitThunk
0x00007FF9D3F65E91 (ntdll) RtlUserThreadStart

[Error] (2) <i>AndroidPlayer(HTC_HTC_One_M9@172.16.51.201)</i> ERROR: Unable to link compute shader!
Stacktrace is not supported on this platform. 
(Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 2454)
0x00000001409897FB (Unity) StackWalker::GetCurrentCallstack
0x000000014098CD5F (Unity) StackWalker::ShowCallstack
0x0000000140D35030 (Unity) GetStacktrace
0x0000000141079D56 (Unity) DebugStringToFile
0x000000014107A52C (Unity) DebugStringToFile
0x00000001411EE544 (Unity) EditorConnection::Hand
...

[Error] <i>AndroidPlayer(HTC_HTC_One_M9@172.16.51.201)</i> -------- GLSL link error: Warning: barrier used in non-uniform control flowWarning: barrier used in non-uniform control flow
Stacktrace is not supported on this platform. 
(Filename: ./Runtime/GfxDevice/opengles/ApiGLES.cpp Line: 657)
0x00000001409897FB (Unity) StackWalker::GetCurrentCallstack
0x000000014098CD5F (Unity) StackWalker::ShowCallstack
0x0000000140D35030 (Unity) GetStacktrace
0x0000000141079D56 (Unity) DebugStringToFile
0x000000014107
...

I could see a vignetted screen, but there was no scene rendered behind it.  Removing the Post Processing volume & layer fixes.

**Comment by Chman** [comment]
What effects did you enable on this build?

**Comment by thargy** [comment]
Here's the profile, it's in YAML so it's human readable and I guess it's most helpful?

[PostProcessor Profile.asset.txt](https://github.com/Unity-Technologies/PostProcessing/files/1207729/PostProcessor.Profile.asset.txt)

**Comment by Chman** [comment]
Are you by any chance using any of the debug views (waveform, histogram etc)?

**Comment by thargy** [comment]
Not knowingly.  All I did was add a layer and a single global volume as per the quick start.  I then created the preferences as attached above.

**Comment by thargy** [comment]
Is there a workaround for this?

**Comment by Kink3d** [comment]
Hi,

Sorry for the late reply. Can you please try this again as weve made a number of changes in this area. Thanks!

**Comment by Chman** [comment]
Fixed in b270f67, verified in #470.
