### ISSUE TITLE
[V2] Single Pass Stereo uses half width texture

### ISSUE THREAD

**Issue by Pawige** [Unity-Technologies/PostProcessing#237]
##### What happened?
I'm attempting to get the Post Processing v2 stack working in a VR project. It seems to work okay with multipass:
![ppv2_multipass](https://user-images.githubusercontent.com/12035468/29084436-32f2a498-7c29-11e7-8369-fe4ddc03ce51.jpg)

But when I switch to Single Pass Stereo it looks like this:
![ppv2_singlepassbug](https://user-images.githubusercontent.com/12035468/29084455-39e478c6-7c29-11e7-87e0-3ee8eab83845.jpg)
It appears to be rendering both eyes to a small quad just floating in space a fair distance away, and the rest of the screen doesn't seem to be refreshing at all.

It seems to be an easily reproducible bug, even in a fresh project.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2017.1.0f3
Windows 10
Standalone Windows & Oculus VR
GeForce GTX 1080

**Comment by robbiesri** [comment]
Which effects are you using in your stack?  The expectation is that most effects work in  VR, except TAA and Motion Blur.

**Comment by Pawige** [comment]
It always happens, even without any effects enabled in the stack at all.

**Comment by robbiesri** [comment]
Ok, I repro'd it locally with the mock HMD in SPS.  I'll take a look.

**Comment by robbiesri** [comment]
I have an idea of what's going on.  There's a few parts that need fixing.  I'll keep the thread updated.

**Comment by Chman** [comment]
7f1301a fixes the issue on our side. Could you double-check?

**Comment by Pawige** [comment]
First off, thanks so much for the quick replies and turnaround on this issue! It looks like it's very close to fully fixed, I'm now just seeing what looks like some odd horizontal resolution loss:
Multi-pass zoomed to 2x:
![mps](https://user-images.githubusercontent.com/12035468/29228656-e7ab9e06-7e97-11e7-8e22-f8a6e1116e70.jpg)
Single-pass zoomed to 2x:
![sps](https://user-images.githubusercontent.com/12035468/29228660-e9fe1724-7e97-11e7-94d4-ef4b6846eb22.jpg)
As before, this seems to be unchanged by turning effects on and off. It's even present with all effects disabled.

**Comment by robbiesri** [comment]
Ah, so this is tricky.  Right now, the default implementation for Single Pass on PC is to use a double-wide texture (left half = left eye, right half = right eye).  So if you are running single-pass, it should basically work if just double the width when the temp RT is allocated (https://github.com/Unity-Technologies/PostProcessing/commit/7f1301a0d036935bf66e0dbd32ef590df423b719#diff-869d014a2b0b382a8ed965585f10d0ebR354)

But there's currently no way to know what the stereo rendering path is during run time.  You can query the Player Settings (PlayerSettings.stereoRenderingPath), but this is only in Editor.  There's some newer functionality in a future version of Unity that allows us to query the texture format being used for XR rendering, but...it doesn't exist in a publicly available version of Unity.

**Comment by Pawige** [comment]
So just to confirm that I'm understanding this correctly: To hard-code in an SPS fix for this, I'd need to go through and change `context.width` to `context.width * 2` in every instance in the post processing code? I went ahead and tried it and it seems to have worked. Unless there are any further gotchas it looks like this problem is solved for my use case.

**Comment by Chman** [comment]
That won't solve it as it'll break a few of the effects that rely on the knowing what the current resolution is, without taking the fact that it could be a stereo-view into account. I'll look into a potential workaround for this issue in the coming days.

**Comment by m4ff** [comment]
I think I may have a workaround. _Camera.activeTexture.width_ will return the correct width for both single-pass and multi-pass stereo. It is only available in the _OnPostRender_ callback, which isn't triggered until the first frame is rendered. The width could be initially set to _Camera.pixelWidth_ in _OnEnable_, and then updated in _OnPostRender_.

_Camera.activeTexture.width_ will return the correct width for the packed render texture, which is slightly more than _Camera.pixelWidth * 2_ because of the extra padding between the two eye textures for stereo separation. So technically it is still wrong to simply double the width, but since the difference is tiny the stretching should be unnoticeable.

This could also be a way of knowing if single-pass stereo is being used during run time. If _Camera.activeTexture.width != Camera.pixelWidth_ then single-pass stereo should be enabled. I can't think of any other reason for those values to differ.

**Comment by robbiesri** [comment]
You can actually use XR.XRSettings.eyeTextureWidth for the width of a single eye.  I have a couple branches that are WIP of porting (most of) the effects over to XR, sit tight.

https://docs.unity3d.com/ScriptReference/VR.VRSettings-eyeTextureWidth.html

**Comment by Chman** [comment]
@robbiesri Isn't this fixed already in current v2?

**Comment by robbiesri** [comment]
Yes, thanks for looping back to this.  This is fixed in 2017.2+.  There's probably some future workarounds to support pre-2017.2, but basically, it would require some manual switch in the Post-processing Stack to specify Single-pass support, along with explicit RenderTexture size manipulation.

**Comment by Chman** [comment]
Fixed in 2017.2+. Considering that a lot of VR features require 2017.2 to work properly we currently don't have plan to add complete support for VR in 2017.1.
