### ISSUE TITLE
All effects were disabled when added

### ISSUE THREAD

**Issue by rico345100** [Unity-Technologies/PostProcessing#238]
##### What happened?
I just created new post processing layer and post processing volume components and add new effect on it. But every effect that I added were disabled every properties and I can't turn it on.

It saids it's turned on, but every option were disabled. I just followed doc here:
https://github.com/Unity-Technologies/PostProcessing/wiki/(v2)-Quickstart

No error or warning found.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5.6.1f1, Windows 10, Standalone Windows.

**Comment by Kink3d** [comment]
From the guide:

>>>Each field has an override checkbox on its left, you'll need to toggle the settings you want to override for this volume before you can edit them. You can quickly toggle them all on or off by using the small All and None shortcuts at the top left.

Unless the individual property checkboxes arent working for you?

**Comment by rico345100** [comment]
This is my view.

![all-disabled](http://photon.modernator.me:/album/rico345100@gmail.com/others/unity/all-disabled.png)

Every option was disabled.

**Comment by Kink3d** [comment]
Hi,

I see the confusion. The circular graphics to the left of each property are checkboxes to enable an override on that property. Also, directly below the title bar for the effect, where it says "All" and "None", those are buttons to enable and disable all of the property overrides.

We will look into what we can do to make the UI clearer.

**Comment by rico345100** [comment]
Oh, I see. Looks like I was just confused. I thought that those checkboxes were disabled, and some reason, when I clicked them, it won't activated(maybe I clicked wrong position).

Thank you for helping me.

**Comment by Kink3d** [comment]
You're welcome :)
