### ISSUE TITLE
(v2) No easy way to access custom user Post Process Resources

### ISSUE THREAD

**Issue by ben-perry** [Unity-Technologies/PostProcessing#239]
There doesn't seem to be a way to easily access custom resources from a custom post process effect.
It would be nice if there was some sort of user resources field on the PostProcessRenderContext you can access.
There is a "userData" property on PostProcessRenderContext, but I can't find a way to set that from outside a PostProcessEffectRenderer that does't resort in using reflection.

I can always edit PostProcessResources.cs of course, but I'd like to avoid editing the source of a plugin If I can.

**Comment by Chman** [comment]
When it comes to custom post-processing effects you're expected to manage your shaders & resources yourself. See this [quick guide](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Writing-custom-effects), the shader is simply retrieved via `Shader.Find()` (although optimally it should be done once at init time and cached for later use - you can override `Init()` in `PostProcessEffectRenderer` to do that).

`userData` in `PostProcessRenderContext` is mainly there in case you need to pass around data in-between custom effects, but its use is quite limited right now and should probably be handled differently.

**Comment by ben-perry** [comment]
Ah ok, I'll just use Shader.Find once then cache it. 
I just like to avoid setting paths in code and I have a natural aversion to any function called "Find" due to performance concerns.

**Comment by Chman** [comment]
Simply don't forget to put your shaders somewhere in a `Resources` folder so it's bundled at build-time and you should be fine.
