### ISSUE TITLE
(v2) Adding PostProcessLayer component via C# requires reflection

### ISSUE THREAD

**Issue by ben-perry** [Unity-Technologies/PostProcessing#240]
Adding a PostProcessLayer component requires a lot of systems to instantiated and m_Resources can only be set via the use of reflection.

Here is what I had to write to add the PostProcessLayer to a gameobject.

```
var postProcessLayer = _gameObject.AddComponent< PostProcessLayer >();
postProcessLayer.volumeTrigger = _gameObject.transform;
postProcessLayer.volumeLayer = LayerMask.GetMask( "Default" );

postProcessLayer.temporalAntialiasing = new TemporalAntialiasing();
postProcessLayer.subpixelMorphologicalAntialiasing = new SubpixelMorphologicalAntialiasing();
postProcessLayer.fastApproximateAntialiasing = new FastApproximateAntialiasing();
postProcessLayer.ambientOcclusion = new AmbientOcclusion();
postProcessLayer.fog = new Fog();
postProcessLayer.dithering = new Dithering();

var field = postProcessLayer.GetType().GetField( "m_Resources", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance );
field.SetValue( postProcessLayer, _config.PostProcessingResources );
```
It would be great if this process was made a lot simpler.

**Comment by Chman** [comment]
That's an oversight. Thanks for reporting, you shouldn't have to do all of this to spawn a `PostProcessLayer`, we'll streamline it.

**Comment by Chman** [comment]
Sorry I forgot to notify you when I pushed it, there's cleaner way to initialize a new post-process layer now. You'll still have to provide a resource file, but at least you don't have to do everything manually now:

```csharp
var pplayer = gameObject.AddComponent<PostProcessLayer>();
pplayer.Init(resources);
```

**Comment by lwwhb** [comment]
how to create PostProcessLayer componet manual
