### ISSUE TITLE
Motion Blur and TAA artifacts when rotating camera OnPreCull

### ISSUE THREAD

**Issue by StaffanWidegarnAhlvik** [Unity-Technologies/PostProcessing#241]
I'm using a standard FPS controller, doesn't matter which one, and then I rotate the camera again in a OnPreCull method so that it rotates after all Updates/LateUpdates etc have been run. 

I then reset the camera rotation back to the state before the OnPreCull rotation using a Coroutine after a `yield return new WaitForEndOfFrame();` to make sure the camera has the FPS controller rotation before the next frame starts.

Using TAA i get ghosting, that looks like this: 
![taa-ghosting](https://user-images.githubusercontent.com/23382755/29306150-62a424be-819c-11e7-9aa8-64abae32f258.png)

Using Motion Blur it seems to always blur with the rotation between Update/LateUpdate and OnPreCull instead of between frames:
![motionblur](https://user-images.githubusercontent.com/23382755/29306149-62a20aee-819c-11e7-8568-aa9809fb1658.png)

Reproduced on Unity version 5.6.0f3 on Windows 10 64-bit, also present on other unity versions.

**Comment by Kink3d** [comment]
Hi,

I'm afraid this simply will not work due to when in the execution order the motion vectors are calculated. Essentially your motion vectors are built using the movement between the two camera rotations.

Its worth noting that we really don't recommend you use these scene rendering methods to do things like camera rotation.

**Comment by StaffanWidegarnAhlvik** [comment]
Thank you for the answer!

Where and how exactly are the motion vectors built? Would it be possible to access that method with reflection?
