### ISSUE TITLE
(v2) BlitFullscreenTriangle always copy white color

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#242]
##### What happened?
I wrote a blur effect before and worked fine, but after replacing the last version of v2 now screen becomes white. I do a simple test, Blit source to destination directly, and show the same result. I guess something wrong when copy.
`
public override void Render(PostProcessRenderContext context)
{
	context.command.BlitFullscreenTriangle(context.source, context.destination);
}
`

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3, win10 pro 1703. target standalone.

**Comment by Chman** [comment]
I pushed a fix to the [blit-copy-fix](https://github.com/Unity-Technologies/PostProcessing/tree/blit-copy-fix) branch that should fix the issue. Could you try it out and let me know how it goes?

**Comment by silentlamb1991** [comment]
I just tried, it fixed, but there's a warning:
`Shader warning in 'Hidden/PostProcessing/CopyStd': value cannot be NaN, isnan() may not be necessary.  /Gis may force isnan() to be performed at line 57 (on d3d11)`

**Comment by silentlamb1991** [comment]
I just found another bug, a black screen occurs at the moment of turning on the effect. 

`		public override bool IsEnabledAndSupported(PostProcessRenderContext context)
		{
			return enabled.value;
		}

		public override void Render(PostProcessRenderContext context)
		{
			context.command.BlitFullscreenTriangle(context.source, context.destination);
		}`

**Comment by Chman** [comment]
> I just tried, it fixed, but there's a warning:
Yeah don't mind that warning, it's expected.

Do you have any sort of antialiasing method enabled? Does it still happen when you have no AA? I know there's currently a "black frame flash" when AA is enabled, that would be unrelated to the current issue.

**Comment by Chman** [comment]
Ok, turns out the black frame bug happens with custom effects as well (it's not isolated to AA). It did happen before the the code that broke `BlitFullscreenTriangle` and its fix, so it's an unrelated issue.

**Comment by Chman** [comment]
I'll close this issue as the original problem as been fixed. I've taken note of the first-black-frame issue, but feel free to open a specific issue for that one if you want to track it in the future.
