### ISSUE TITLE
(v2) NullReferenceException for custom effects when restarting Unity

### ISSUE THREAD

**Issue by spraycanmansam** [Unity-Technologies/PostProcessing#244]
Hi guys, 

I'm in the process of integrating the new post processing stack into our workflow and noticed that everytime I restart Unity it will throw a NullRef when selecting a Post Processing Volume. The volume editor and profile editor fails to display any effects. Re-importing the custom effects scripts on start up each time fixes the issue.

Using Unity 5.6.3f1 on Windows 10.

> NullReferenceException: (null)
UnityEditor.SerializedObject..ctor (UnityEngine.Object obj) (at C:/buildslave/unity/build/artifacts/generated/common/editor/SerializedPropertyBindings.gen.cs:69)
UnityEditor.Rendering.PostProcessing.PostProcessEffectBaseEditor.Init (UnityEngine.Rendering.PostProcessing.PostProcessEffectSettings target, UnityEditor.Editor inspector) (at Assets/PostProcessing/Editor/PostProcessEffectBaseEditor.cs:31)
UnityEditor.Rendering.PostProcessing.EffectListEditor.CreateEditor (UnityEngine.Rendering.PostProcessing.PostProcessEffectSettings settings, UnityEditor.SerializedProperty property, Int32 index) (at Assets/PostProcessing/Editor/EffectListEditor.cs:88)
UnityEditor.Rendering.PostProcessing.EffectListEditor.Init (UnityEngine.Rendering.PostProcessing.PostProcessProfile asset, UnityEditor.SerializedObject serializedObject) (at Assets/PostProcessing/Editor/EffectListEditor.cs:59)
UnityEditor.Rendering.PostProcessing.PostProcessVolumeEditor.RefreshEffectListEditor (UnityEngine.Rendering.PostProcessing.PostProcessProfile asset) (at Assets/PostProcessing/Editor/PostProcessVolumeEditor.cs:42)
UnityEditor.Rendering.PostProcessing.PostProcessVolumeEditor.OnEnable () (at Assets/PostProcessing/Editor/PostProcessVolumeEditor.cs:29)

**Comment by Kink3d** [comment]
Hi,

I cant reproduce this with custom effects on my side. Can you supply a custom effect that reproduces this for you?

Thanks

**Comment by spraycanmansam** [comment]
Sure. I've attached a basic script. 

Steps to reproduce:
- Create a new project.
- Add a PostProcessingLayer and PostProcessingVolume component to the main camera.
- Add the custom effect to the PostProcessingVolume.
- Save and restart Unity.
- Click on the main camera. 

The NullRef will be thrown. Reimporting the custom effect script will fix the issue, but it's inconvenient to have to do this everytime the editor is started. 
I also noticed when testing this that changing the namespace affected the result. Reimporting did not fix the issue if a namespace is changed.

`using System;
using UnityEngine.Rendering;
using UnityEngine.Rendering.PostProcessing;

[Serializable]
[PostProcess(typeof(CustomEffect), PostProcessEvent.AfterStack, "Custom/Custom Effect")]
public sealed class CustomEffectSettings : PostProcessEffectSettings
{

}
    
public sealed class CustomEffect : PostProcessEffectRenderer<CustomEffectSettings>
{
    public override void Render(PostProcessRenderContext context)
    {
        CommandBuffer command = context.command;
        command.Blit(context.source, context.destination);
    }
}`

**Comment by Chman** [comment]
That's probably because you haven't named your source file `CustomEffectSettings`. Because of the way serialization works in Unity, whenever you have a `ScriptableObject` (which `PostProcessEffectSettings` is) that you want to be serialized properly you need to put it in a file with the same name as your class.

There's actually a warning in the console when you try to add a misnamed custom effect to a volume:

> No script asset for CustomEffectSettings. Check that the definition is in a file of the same name.

I'll add a note to the doc about that.

**Comment by spraycanmansam** [comment]
@Chman Thanks for the advice. I renamed the source file to match the class name and still no luck. I also don't get any console warnings.

**Comment by Chman** [comment]
Your previously faulty serialized data is still in the profile, either delete and recreate the profile or switch the inspector to Debug mode and remove it explicitly from the list.

**Comment by spraycanmansam** [comment]
@Chman, Thanks. I can confirm that that has fixed the issue.
