### ISSUE TITLE
Bloom lens dirtiness texture should not change aspect ratio with screen

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#246]
##### What happened?
![11](https://user-images.githubusercontent.com/18855621/29325517-8eff9b00-821a-11e7-8b9c-4b17814b02b6.JPG)

It should keep its' aspect ratio like this:
![s](https://user-images.githubusercontent.com/18855621/29325835-c8c6b00c-821b-11e7-9db2-2900b541d66f.png)

If don't do that, we have to make many textures with different aspect ratio, and can't allow user resize window freely.

**Comment by Chman** [comment]
Fixed in c472db4.
