### ISSUE TITLE
(V2) How can I know which volume render now?

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#247]
##### What happened?
I'm writing a height-fog effect, if the volume is global the height should be world space, or it should base on volume transform position, so when the scene moved the height needn't modify.

I just realize that also affects Interp of ParameterOverride, which space of from & to relative to and which space Interp result will used to...

Maybe just world space is fine...

**Comment by Chman** [comment]
I'm not sure I fully understand your post. But to answer the question in the title, you can use `PostProcessManager.instance.GetActiveVolumes(...)` ([method signature](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/PostProcessManager.cs#L94)) to grab all the current active volumes for a given `PostProcessLayer`.

**Comment by silentlamb1991** [comment]
It's very peculiar situation:
A custom effect needs a transform position, but it's stored in a scriptable asset, not in scene.

**Comment by Chman** [comment]
That's a limit of the volume framework. It's optimized & meant to be used for tweening of pure post-processing effects only. Fog isn't a post-processing effect, it's a volumetric/lighting effect and as such doesn't really fit into the current design of the stack.

With that said, assets can't currently hold scene-object references unfortunately. There may be something coming to alleviate this issue at some point in the future, but for now this won't work.
