### ISSUE TITLE
When will SSR be added to V2?

### ISSUE THREAD

**Issue by nicobella** [Unity-Technologies/PostProcessing#249]
##### What happened?
I was working on a project with V1, I really love the new features and modularity of the V2, but my project visual quality is highly dependant on SSR to get the eyecandy, do we have any ETA or rough approximation (say 2018 Q3) on when the  SSR new implementation will arrive to V2 of the stack?

##### Post-processing stack version (v1, v2)?
version 2

**Comment by Chman** [comment]
Summer 2017. So roughly in-between now and 5/6 weeks.

**Comment by nicobella** [comment]
thanks!

**Comment by silentlamb1991** [comment]
awesome!

**Comment by Ziboo** [comment]
Still not here ? :(
Any ETA ? 

Thanks

**Comment by JacobSmaga** [comment]
It's already in V2.

**Comment by Kink3d** [comment]
Yes, new SSR has arrived :) (although still subject to alterations)
