### ISSUE TITLE
App crashes on i-phone when i add post processor to camera

### ISSUE THREAD

**Issue by AdhikSharma** [Unity-Technologies/PostProcessing#250]
I have a camera in a scene with post processor on it.When i load the scene app crashes in iPhone.If I remove the post processsor from the camera app works fine.

##### Post-processing stack version1.0.4

App is crashing only on iPhone. Works fine in android and windows build.Using metal graphic Api when compiling for ios.

**Comment by Chman** [comment]
Would you happen to have a crash log?

**Comment by AdhikSharma** [comment]
this is the console log information of my device:

Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemTimeJumpedNotification \M-b\M^F\M^R 2.000000s
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPQueuePlayer rate changed: 1.000000 -> 0.000000
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 1.00 \M-b\M^F\M^R 0.00
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPAVController _setState: 2 -> 1
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemDidPlayToEndTimeNotification
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: -[MPAVController pause]
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay for pause
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 0.000000
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 0.000000
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 0.000000, setting.
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 0.000000
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:50 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 0.00 \M-b\M^F\M^R 0.00
Aug 19 11:44:50 sapnas-iPad routined(libcoreroutine.dylib)[30] <Debug>: caching CMMotionActivity, <private>, RTMotionActivity, <private>
Aug 19 11:44:51 sapnas-iPad locationd[58] <Notice>: message 'kCLConnectionMessageWatchdog' received from client 'com.apple.AssistantServices'
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Committing time change: 0.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPAVController _setState: 1 -> 2
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000, setting.
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 0.00 \M-b\M^F\M^R 1.00
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Enabling autoplay
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Likely to keep up or full buffer: 1
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000, setting.
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 1.000000
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 1.00 \M-b\M^F\M^R 1.00
Aug 19 11:44:51 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemTimeJumpedNotification \M-b\M^F\M^R 0.000000s
Aug 19 11:44:52 sapnas-iPad locationd[58] <Info>: HARVEST: dominant motion activity changed from type, <private>, confidence <private>, to, type, <private>, confidence, <private>
Aug 19 11:44:52 sapnas-iPad routined(libcoreroutine.dylib)[30] <Debug>: caching CMMotionActivity, <private>, RTMotionActivity, <private>
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemTimeJumpedNotification \M-b\M^F\M^R 2.000000s
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPQueuePlayer rate changed: 1.000000 -> 0.000000
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 1.00 \M-b\M^F\M^R 0.00
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPAVController _setState: 2 -> 1
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemDidPlayToEndTimeNotification
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: -[MPAVController pause]
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay for pause
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Disabling autoplay
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 0.000000
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 0.000000
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 0.000000, setting.
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 0.000000
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:53 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 0.00 \M-b\M^F\M^R 0.00
Aug 19 11:44:54 sapnas-iPad WadhwaPanoramaHD(UIKit)[1040] <Notice>: Received memory warning.
Aug 19 11:44:54 sapnas-iPad WadhwaPanoramaHD(UIKit)[1040] <Notice>: Received memory warning.
Aug 19 11:44:54 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Committing time change: 0.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N MPAVController _setState: 1 -> 2
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000, setting.
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 0.00 \M-b\M^F\M^R 1.00
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Enabling autoplay
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Likely to keep up or full buffer: 1
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on player: <MPQueuePlayer: 0x1701497f0> to 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Finished preparing item: <MPAVItem: 0x123e441c0> for rate: 1.000000, setting.
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: Setting rate on AVQueuePlayer: 1.000000
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% rate
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-b\M^D\M-9\M-o\M-8\M^N _rateDidChange 1.00 \M-b\M^F\M^R 1.00
Aug 19 11:44:55 sapnas-iPad WadhwaPanoramaHD(MediaPlayer)[1040] <Notice>: \M-p\M^_\M^N\M-% AVPlayerItemTimeJumpedNotification \M-b\M^F\M^R 0.000000s
Aug 19 11:44:55 sapnas-iPad SpringBoard(KeyboardArbiter)[769] <Info>: HW kbd: currently com.CubeDots.WadhwaPanoramaHD ((null) < (null))
Aug 19 11:44:55 sapnas-iPad SpringBoard(KeyboardArbiter)[769] <Error>: HW kbd: Failed to set (null) as keyboard focus
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreAudio)[26] <Notice>: HALS_IOContext.cpp:1496:IOWorkLoop_HandleOverload:  HALS_IOContext::IOWorkLoop_HandleOverload: Overload on context 100 current time: 484451 deadline: 484416
Aug 19 11:44:55 sapnas-iPad mediaserverd(AudioToolbox)[26] <Notice>: 94: sid:0x1a37b, WadhwaPanoramaHD(1040), 'prim'
Aug 19 11:44:55 sapnas-iPad mediaserverd(AudioToolbox)[26] <Notice>: 274: CMSession retain count > 1!
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetDiscoveryMode: CMSession: 'AVSC FigPlayer - 1040' com.CubeDots.WadhwaPanoramaHD(pid = 1040) requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMRoutingMgr- CMRoutingMgr_SetDiscoveryMode: CMSession: Session requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad CommCenter[73] <Notice>: #I CTServerConnection from pid 1040 has closed (conn=0x131dd69d0)
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreAudio)[26] <Notice>: HALS_IOContext.cpp:1496:IOWorkLoop_HandleOverload:  HALS_IOContext::IOWorkLoop_HandleOverload: Overload on context 100 current time: 487170 deadline: 487140
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMRoutingMgr- CMRoutingMgr_SetDiscoveryMode: CMSession: NULL requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetDiscoveryMode: CMSession: 'WadhwaPanoramaHD-1040' com.CubeDots.WadhwaPanoramaHD(pid = 1040) requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMRoutingMgr- CMRoutingMgr_SetDiscoveryMode: CMSession: Session requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetIsPlaying: CMSession: 'WadhwaPanoramaHD-1040' with category/mode AmbientSound/Default stopping playing
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetIsActive: CMSession: 'WadhwaPanoramaHD-1040' going inactive
Aug 19 11:44:55 sapnas-iPad mediaserverd(VirtualAudio)[26] <Info>: 228: Client request to get virtual format ([ 32/24000/2; flags: 0x29; bpp: 4; fpp: 1; Bpf: 4 ]) on virtual audio stream 111.
Aug 19 11:44:55 sapnas-iPad mediaserverd(VirtualAudio)[26] <Info>: 228: Client request to get virtual format ([ 32/24000/2; flags: 0x29; bpp: 4; fpp: 1; Bpf: 4 ]) on virtual audio stream 111.
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetDiscoveryMode: CMSession: 'FigPlayer - 1040' com.CubeDots.WadhwaPanoramaHD(pid = 1040) requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMRoutingMgr- CMRoutingMgr_SetDiscoveryMode: CMSession: Session requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsSetDiscoveryMode: CMSession: '' (pid = 1040) requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMRoutingMgr- CMRoutingMgr_SetDiscoveryMode: CMSession: Session requesting to set the discovery mode to DiscoveryMode_None
Aug 19 11:44:55 sapnas-iPad locationd[58] <Notice>: Client com.CubeDots.WadhwaPanoramaHD disconnected
Aug 19 11:44:55 sapnas-iPad mediaserverd(CoreAudio)[26] <Notice>: HALS_IOContext.cpp:1496:IOWorkLoop_HandleOverload:  HALS_IOContext::IOWorkLoop_HandleOverload: Overload on context 100 current time: 489254 deadline: 489224
Aug 19 11:44:55 sapnas-iPad mediaserverd(AudioToolbox)[26] <Notice>: 370: AQME device AQDefaultDevice: client stopping: <RemoteIOClient@0x10111d400(@0x10111d610); output; sid:0x1a37b, WadhwaPanoramaHD(1040), 'prim'>; running count now 0
Aug 19 11:44:55 sapnas-iPad locationd[58] <Info>: CLGyroBiasEstimator removing client <private>
Aug 19 11:44:55 sapnas-iPad locationd[58] <Info>: CLGyroBiasEstimator,SPUEnabled,<private>,BuildingGYTT,<private>,NumClients,<private>
Aug 19 11:44:55 sapnas-iPad backboardd[768] <Notice>: Turning off orientation events.
Aug 19 11:44:55 sapnas-iPad UserEventAgent(MemoryMonitor)[22] <Notice>: jetsam: kernel termination snapshot being created
Aug 19 11:44:55 sapnas-iPad locationd[58] <Info>: HARVEST: dominant motion activity changed from type, <private>, confidence <private>, to, type, <private>, confidence, <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Stopping orientation updates
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:55 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Stopping orientation detection.
Aug 19 11:44:55 sapnas-iPad backboardd[768] <Notice>: Effective device orientation changed to: unknown
Aug 19 11:44:55 sapnas-iPad backboardd(BaseBoard)[768] <Error>: Unable to get short BSD proc info for 1040: No such process
Aug 19 11:44:55 sapnas-iPad backboardd(BaseBoard)[768] <Error>: Unable to get proc info for 1040: No such process
Aug 19 11:44:55 sapnas-iPad mediaremoted[27] <Notice>: Client with pid 1040 invalidated.
Aug 19 11:44:55 sapnas-iPad mediaremoted[27] <Notice>: Removing registered custom origins (0 total) for client with pid 1040.
Aug 19 11:44:55 sapnas-iPad mediaremoted[27] <Notice>: Removing now playing info client for pid 1040
Aug 19 11:44:56 sapnas-iPad ReportCrash(CrashReporterSupport)[935] <Notice>: Saved type '298(298)' report (9 of max 25) at <private>
Aug 19 11:44:56 sapnas-iPad mediaremoted[27] <Notice>: Removing client with PID 1040
Aug 19 11:44:56 sapnas-iPad backboardd[768] <Info>: [BKEventFocusManager] Setting foreground application to: (none) (-1)
Aug 19 11:44:56 sapnas-iPad backboardd[768] <Info>: [BKEventFocusManager] Setting foreground application to: (none) (-1)
Aug 19 11:44:56 sapnas-iPad backboardd[768] <Info>: New client is com.apple.springboard, events enabled? YES
Aug 19 11:44:56 sapnas-iPad SpringBoard[769] <Notice>: Process exited: <FBApplicationProcess: 0x100ccdf60; WadhwaPanoramaH; pid: -1> -> <FBApplicationProcessExitContext: 0x17505f8f0; exitReason: jetsam; terminationReason: (none)>
Aug 19 11:44:56 sapnas-iPad UserEventAgent(AppleAwatchd-plugin)[22] <Notice>: 386281822851: id=com.CubeDots.WadhwaPanoramaHD pid=1040, state=0
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: setting object for key=SBDefaultStatusBarStyleKey bundleID=<private> object=(null)
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: updating cache key=SBDefaultStatusBarStyleKey bundleID=<private> object=(null)
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: setting object for key=SBDefaultStatusBarHiddenKey bundleID=<private> object=(null)
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: updating cache key=SBDefaultStatusBarHiddenKey bundleID=<private> object=(null)
Aug 19 11:44:56 sapnas-iPad SpringBoard[769] <Info>: The top thing is com.apple.springboard (fallback) and he wants orientation events: YES _wantsOrientationEvents: YES
Aug 19 11:44:56 sapnas-iPad mediaserverd(CoreMedia)[26] <Notice>: -CMSessionMgr- cmsmHandleApplicationStateChange: CMSession: Client com.CubeDots.WadhwaPanoramaHD with pid '1040' is now Terminated. Background entitlement: NO
Aug 19 11:44:56 sapnas-iPad backboardd[768] <Notice>: Turning on orientation events.
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Starting orientation updates
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: hwType, 43
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: isPad 4
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: fOrientationGyroTimeout,600.000000,fEnableGyroTimeout,1,fMaxAccelerationVarianceForStability,0.000200
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: fHasSeenACaseLatchCoverOnce, 0
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: gyroFrequency,20.000,gyroBufferSize,5,gyroMeanBufferSize,3,zRotBufferSize,5,minRequiredZrots,3
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Starting orientation detection with accelFrequency 25.000000, isIpad, 4, decimationRate, 2
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Received deviceOrientationBlocking
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Waiting for the first orientation to come in
Aug 19 11:44:56 sapnas-iPad routined(libcoreroutine.dylib)[30] <Debug>: caching CMMotionActivity, <private>, RTMotionActivity, <private>
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: conditionally invalidating cache key=SBDefaultStatusBarStyleKey bundleID=<private> object=<private>
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: objects don't match, invalidating
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: conditionally invalidating cache key=SBDefaultStatusBarHiddenKey bundleID=<private> object=<private>
Aug 19 11:44:56 sapnas-iPad SpringBoard(FrontBoard)[769] <Info>: objects don't match, invalidating
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: IOHIDServiceClientSetProperty() successfully set property for event <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Property for usage pair {<private>,<private>}: {<private> = <private>} was set <private>
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Notify from, Unexpected -> FaceUp
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Info>: Sending orientation changed notification
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Received orientation. (Ambiguous to FaceUp) Timestamp 16095.124681
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Updating client handler: Orientation FaceUp, Callback mode: -1
Aug 19 11:44:56 sapnas-iPad backboardd(CoreMotion)[768] <Notice>: Got latest sample: 5 @ 16095.124681
Aug 19 11:44:56 sapnas-iPad backboardd[768] <Notice>: Effective device orientation changed to: faceUp
Aug 19 11:44:56 sapnas-iPad SpringBoard[769] <Notice>: Running <SBAppExitedWorkspaceTransaction: 0x10e696930> for transition request:
<SBMainWorkspaceTransitionRequest: 0x170af4b00; display: Main; source: Unspecified> {
    applicationContext = <SBWorkspaceApplicationTransitionContext: 0x1702cf650; background: NO> entities = {
        SBLayoutPrimaryRole = <SBWorkspaceHomeScreenEntity: 0x170e51af0; ID: com.apple.SpringBoard.builtin.HomeScreen; layoutRole: primary>;
    };
}

**Comment by AdhikSharma** [comment]
This issue has been fixed.Ty for the help
