### ISSUE TITLE
(v2) bloom issue

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#255]
##### What happened?
Gif:
![ddd](https://user-images.githubusercontent.com/18855621/29483958-cff86ac8-84e6-11e7-88f8-c20b23f0005a.gif)
I disable all other effects except bloom issue still exists, but disable bloom the issue disappears, so I guess it's a bloom issue.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3, win10, standalone

**Comment by Chman** [comment]
See #123 and #219.
