### ISSUE TITLE
(v2) default settings should be "no effect" so it will be blended correctly

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#256]
Some default settings mean "work fine" not "no effect", for example, lens-Intensity in bloom, default value should be zero, so if a local volume value 3 means final effect would be 0 to 3 not 1 to 3. May you can provide "default value" and "normal value" in a right popup menu for every parameter.

Other question: a value only be overridden in a local volume, it will replace a "default value" or blend with the "default value"?

**Comment by Chman** [comment]
> Some default settings mean "work fine" not "no effect", for example, lens-Intensity in bloom, default value should be zero, so if a local volume value 3 means final effect would be 0 to 3 not 1 to 3. May you can provide "default value" and "normal value" in a right popup menu for every parameter.

Most have a default "0 intensity" state already when applicable (e.g. having a zero state in DOF is complicated) but we may have forgotten some. Have you spotted any other than `Lens Dirt Intensity`?

> Other question: a value only be overridden in a local volume, it will replace a "default value" or blend with the "default value"?

It will be blended against the default value.
