### ISSUE TITLE
[V2] Removing and importing new PPS from inside Unity causes serialization failure in PostProcessVolume

### ISSUE THREAD

**Issue by JacobSmaga** [Unity-Technologies/PostProcessing#262]
After deleting old PPS build, import new one while your game scene is open. You will notice that only Post Process Layer (AO) started working again, PostProcess Triggers doesn't work, disabling and enabling them doesn't fix it, you need to open scene again to fix it.

**Comment by Chman** [comment]
Hmm I do this all the time (as much as several times a day actually) and I've never encountered this issue. Could it be that you updated from a very old version to a new one? Were you in play mode? Unity version?

**Comment by JacobSmaga** [comment]
-Updating from the latest versions (commits from github to the newest ones)
-Edit mode
-2017.2.0b9

**Comment by JacobSmaga** [comment]
Update: Removed old build (The one from this commit; 5 days ago: https://github.com/Unity-Technologies/PostProcessing/commit/ec0c9ee9fc4b2c6852e983814e5ea9694d79503e) to the newest one with Xbox One fixes, problem still happens, It gives some error in the console and also I've found that setting Volume Layer to nothing and then to Post-Processing one fixes the problem.

**Comment by Chman** [comment]
Hmm interesting. I'll have to look into this. FWIW, I just had to redo it again (clean branch switch) on a test project. I don't delete the `PostProcessing` folder from Unity though, I remove it from my file explorer and replace it with the new one (which is basically what a package update would do - no database refresh between removal/add). That way when I go back to Unity it rebuilds it cleanly. Next time I have to do that again I'll do it from Unity.

**Comment by JacobSmaga** [comment]
Since I've switched to the Package Manager version and it's not happening anymore I think that the case can be closed.
