### ISSUE TITLE
(V2) AO & Linear Fog not working

### ISSUE THREAD

**Issue by derwodaso** [Unity-Technologies/PostProcessing#263]
After updating from [ac8dfc8](https://github.com/Unity-Technologies/PostProcessing/commit/ac8dfc8a0bebb852bb6f9ffd06fce2f8bd763ddb) to the latest v2 commit I have an issue with AO:

When fog mode is switched to "Linear" in the Lighting tab, AO is disabled / not visible. Changing the PostProcessLayer DeferredFog settings does not change this.

However I can temporarily fix it, by switching the Camera's rendering path to "Forward" and back to "Use Graphics Settings" / "Deferred". It works until I reload the assembly / hit play / open a new scene.

Happens in Windows Editor running Unity 5.6.2p1

**Comment by Chman** [comment]
Should be fixed in ec0c9ee.
