### ISSUE TITLE
Color gradient of post processing gives black screen in mobile which has MALI GPU

### ISSUE THREAD

**Issue by AdhikSharma** [Unity-Technologies/PostProcessing#264]
When i attach post processing on my camera,all I can see is black screen on MALI GPU.Working good on other mobiles.On trying different cases i find out that color grading is causing this issue
 Post-processing stack version v1

**Comment by deepak8krishna8** [comment]
The devices with mali gpu does not support RGBAHalf Texture Format which is used for the internal colour correction calculations. Even that is not supported on OpenGLEs2.0. Color Grading used that texture format. Check this lick to see unsupported devices

http://opengles.gpuinfo.org/gles_listreports.php?extensionunsupported=GL_EXT_color_buffer_half_float

**Comment by Chman** [comment]
Seems to me that you're using an older version of the post-processing stack... Could you update to the latest one (1.0.4)? We handled that case in 1.0.3.

**Comment by deepak8krishna8** [comment]
Thanks Chman for reply. I will update Post Processing stack and after testing i will get back to you.
Thanks for help...

**Comment by AdhikSharma** [comment]
Thanks Chman. Its working with 1.0.4. Ty for your help.
