### ISSUE TITLE
No effects on screen. (V2)

### ISSUE THREAD

**Issue by erherhh4herh** [Unity-Technologies/PostProcessing#265]
##### What happened?
I imported v2 into my project, added the layer component to my camera, setup my volume (global), ported my custom shaders from v1 (looked over the wiki to make sure i was doing it right). Nothing changes in-game, or in the editor. Not even if I remove my custom shaders entirely.... No errors, no information. Did everything from the quickstart guide, still nothing.

EDIT:
Added my volume to it's own layer, set my layer on my layer component accordingly, nothing.
##### Post-processing stack version (v1, v2)?
using latest v2 commit. https://github.com/Unity-Technologies/PostProcessing/commit/ec0c9ee9fc4b2c6852e983814e5ea9694d79503e
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.0p4, windows 10, standalone windows DX11.

**Comment by igniuss** [comment]
Are you sure you selected the right layer to scan for your volumes?

**Comment by erherhh4herh** [comment]
So... got my custom shader to work.... yay. But everything else except AA and AO doesn't XD

**Comment by igniuss** [comment]
What if you try overwriting the default settings for the other effects?

**Comment by erherhh4herh** [comment]
Okay... had my weight at 0. Changed to 1 and now everything works except my shader... LOL! Changed all settings, still black. I ported this shader STRAIGHT from v1... It's a tonemapper, not entirely sure how it's breaking :(

**Comment by erherhh4herh** [comment]
Here is my stuff. https://pastebin.com/ubA9SfEJ

Thanks for all the help!

**Comment by Chman** [comment]
It's an issue with your shader, the maths you are doing in there are very suspicious (why are you mixing Hable's and a pre-exposed ACES Approx tonemappers? Why is the exposure applied post-tonemapping...?). If I return a basic color in your shader it works so you should probably debug your maths :)

**Comment by erherhh4herh** [comment]
I add ACES later on to correct Hable's, in my opinion, poor color management. I then add something called "Spherical Tonemapping" (used in watch dogs) to correct underexposed high ranges, and finally contrast (currently don't need, already removed.) and exposure for final touching up. i do this in one equation for performance reasons. This worked perfectly before with the same settings I have entered now. Considering this is just math, I fail to understand how anything is different. Thanks for all your help.
