### ISSUE TITLE
(V2) PostProcessLayer should not break scene view when no effects are enabled/supported [Fix included]

### ISSUE THREAD

**Issue by DigitalSalmon** [Unity-Technologies/PostProcessing#267]
Line 653 'else'

Should read 'else if (count > 1)'

Since no action should be taken if the count = 0.

Currently the scene view will not render properly (Either a freeze or pure black). Changing this line fixes the issue.

**Comment by Kink3d** [comment]
Hi,

Can you provide an example project or further instructions on this? I cannot get anything like this to reproduce.

Thanks

**Comment by Chman** [comment]
`RenderList()` isn't called when there's no effect to render. Please provide an example project that reproduces the issue you're seeing so we can take a look.

**Comment by Kink3d** [comment]
Closed for inactivity
