### ISSUE TITLE
[V2][PS4] Motion Blur artifacts

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#271]
##### What happened?
![192 168 1 177-20170904-00112](https://user-images.githubusercontent.com/18855621/30025202-e8104ee4-91a9-11e7-8cb4-d4156db39945.jpg)

##### Post-processing stack version (v1, v2)?
V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.0f3, win10, PS4,

**Comment by Kink3d** [comment]
Hi,

Sorry for the late response. We cannot repro this at all. All our PS4 tests are fine.
Is it possible for you to send us a reproduction project? Otherwise I'm afraid we cant help you.

**Comment by Chman** [comment]
Inactive & not reproducible.
