### ISSUE TITLE
How to manually create PostProcessLayer component?

### ISSUE THREAD

**Issue by lwwhb** [Unity-Technologies/PostProcessing#273]
##### What happened?
How to manually create PostProcessLayer component? how to create PostProcessResources obejct?
##### Post-processing stack version (v1, v2)?
V2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
all

this is my code:
PostProcessLayer postProcessLayer = cameraObject.AddComponent<PostProcessLayer>();
            if (postProcessLayer != null)
            {
                ## postProcessLayer.Init(new PostProcessResources());//////??????
                postProcessLayer.volumeTrigger = cameraObject.transform;
                postProcessLayer.volumeLayer = LayerMask.GetMask("PostProcessing");
                postProcessLayer.ambientOcclusion.enabled = true;
            }

**Comment by Chman** [comment]
You don't create the `PostProcessResources` asset yourself, it's already created. It's in the `PostProcessing` folder. Pass its reference to `postProcessLayer.Init()` and that's it.
