### ISSUE TITLE
green blotches in HDR linear with dof ON

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/PostProcessing#276]
##### What happened?
multiple lights of intensity 10 cause green blotches in HDR linear with dof ON

![bug with blotch](https://user-images.githubusercontent.com/26075468/30075481-68b333c4-922a-11e7-9469-a581f8972e16.PNG)

##### Post-processing stack version (v1, v2)?
both
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5.6.3 and 2017.2b9

**Comment by Chman** [comment]
In v2, do you have `Stop NaN Propagation` enabled in the `PostProcessLayer` component?

**Comment by Kink3d** [comment]
Closed for inactivity
