### ISSUE TITLE
Glow Effect PostProcessing

### ISSUE THREAD

**Issue by WeCode4Fun** [Unity-Technologies/PostProcessing#277]
Enhancement request: What I really miss from Unity is a Glow Effect. It can be used for highlighting selected objects or dedicated glow. Currently it's not possible to make good glow except with Bloom, but that affects everything, even e. g. the skybox lights up. The glow should be like an outer rim effect which fades from opaque to transparency.

There are assets on the store (e. g. MKGlow, Indie Glow, TOZ Glow, ...) but I think this could fit perfectly into the PostProcessing stack.

I'm not aware if it's possible in v2 or how to create a Glow Effect with a custom effect, since these are supported in v2. So if it's possible already, having an example would be great.

**Comment by Kink3d** [comment]
Hey,

We wont be adding a Glow effect to the built in effects that ship with the stack, hopefully you understand we cannot possibly ship and maintain every effect that anyone might want. 

However we will be creating another repository where users can upload their custom effects towards release time (we need to make sure our custom effect API is set in stone before we do this). Also our hope is that Asset Store publishers (like those you mentioned) will port their effects to our framework.

Thanks
