### ISSUE TITLE
ArgumentException: Invalid shader (null) thrown by PropertySheetFactory

### ISSUE THREAD

**Issue by AlexGustafsson** [Unity-Technologies/PostProcessing#279]
##### What happened?
An ArgumentException began to be thrown on every `OnValidate()` (?) for as long as Anti-aliasing was on. No matter what mode was being used. `Mobile Optimized` is off, as is `Keep Alpha`. `Stop NaN Propagation` however is on. I.e. the defaults when first adding the `Post Process Layer`.
```
ArgumentException: Invalid shader (null)
UnityEngine.Rendering.PostProcessing.PropertySheetFactory.Get (UnityEngine.Shader shader) (at Assets/PostProcessing/PostProcessing/Runtime/Utils/PropertySheetFactory.cs:28)
UnityEngine.Rendering.PostProcessing.ScalableAO.DoLazyInitialization (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/PostProcessing/Runtime/Effects/ScalableAO.cs:67)
UnityEngine.Rendering.PostProcessing.ScalableAO.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context, UnityEngine.Rendering.CommandBuffer cmd, Int32 occlusionSource) (at Assets/PostProcessing/PostProcessing/Runtime/Effects/ScalableAO.cs:96)
UnityEngine.Rendering.PostProcessing.ScalableAO.RenderAfterOpaque (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/PostProcessing/Runtime/Effects/ScalableAO.cs:156)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/PostProcessing/Runtime/PostProcessLayer.cs:314)
```

__Note: When `Stop NaN Propagation` was turned off and then on again, the error seized to occur.__
##### Post-processing stack version (v1, v2)?
[v2 (Beta 2)](https://github.com/Unity-Technologies/PostProcessing/tree/2.0.0-b2)
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.0f3 Personal
Windows 10 x64
(Target platform: in editor)

**Comment by Chman** [comment]
A shader probably failed to compile. Could you check in `/PostProcessing/Shaders/Builtins/` if any of the shader has error? Looking at your error, I would start with the `ScalableAO` shader.

**Comment by Kink3d** [comment]
Closed for inactivity
