### ISSUE TITLE
Error CS0117 "Application" does not contain a definition for 'isPlaying'

### ISSUE THREAD

**Issue by Mariolegend** [Unity-Technologies/PostProcessing#281]
##### What happened?
In a clean project, Post Processing doesn't have any issues but when I import it into my other RPG project, it gives me error CS0117 - which doesn't make any sense. 

Assets/PostProcessing/Editor/Monitors/WaveformMonitor.cs(210,29): error CS0117: `Application' does not contain a definition for `isPlaying'
for all monitor scripts

##### Post-processing stack version (v1, v2)?
v1 and v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.0f3 on Windows 7 64bit
![screenshot 2017-09-07 03 35 04](https://user-images.githubusercontent.com/31724401/30151541-db5044e0-937d-11e7-88f6-fc8032b9979e.png)

**Comment by Chman** [comment]
`Application` is a standard class in the UnityEngine namespace. This means that you probably have another class called `Application` somewhere in your project that isn't namespace'd (which is, needless to say, a very bad idea), either from your own code or an asset downloaded from the store. So you'll have to find it and either rename it or put it in a namespace that isn't global.

**Comment by Mariolegend** [comment]
..... Oh boy.... Is there a way I can do a keyword search instead of opening every single script?

**Comment by Chman** [comment]
You can run a search in the project panel (top search bar), assuming the `Application` class is in a file with the same name. Else you can use your IDE (Visual Studio, MonoDevelop or whatever) to search for a type/symbol.

**Comment by Mariolegend** [comment]
Thanks!

So, I found it! and you won't believe where... lol 

Standard Assets folder package lol On the SampleScenes folder specifically the SceneAndURLLoader.cs script xD

**Comment by Chman** [comment]
That `SceneAndURLLoader` file doesn't contain any `Application` class, so it can't be it.

**Comment by Mariolegend** [comment]
I remember now earlier I was learning how to redo the reset scene script from 4.6 to 5.x since it changed and made things obsolete. So annoying. And Visual studio suggested something that I tried to see if that solved it, but instead messed with something else entirely. Eventually I got the reset script to work, but then found it not to be compatible to a third party asset store package way of doing it.

![screenshot 2017-09-07 05 05 26](https://user-images.githubusercontent.com/31724401/30155464-e2face56-938a-11e7-8c62-6efd8db2e20b.png)

**Comment by Chman** [comment]
Yeah I still don't see any `Application` class being defined in this script, it's only calling a method on `Application` which is fine :)

**Comment by Mariolegend** [comment]
yeah but that was it when I did the good old "take it out of the asset folder" elimination test lol
I also found the previous version in which it had "public class SceneAndURLLoader : monobehavior" instead of Application. That solved the issue. 
I didn't know visual studio could just jump and change things. I'll be more careful next time.
