### ISSUE TITLE
Callbacks for Settings being added to a Profile

### ISSUE THREAD

**Issue by pete-campo** [Unity-Technologies/PostProcessing#283]
(post stack v2 enhancement suggestion)

Would be super useful to add callbacks when PostProcessEffectSettings are added & removed from a PostProcessProfile.

We have some settings which generate a lookup texture when their properties are edited, and we use this callback to create/destroy the LUT Texture2D and add/remove it as a sub-asset of the Profile asset.  

Something like this added to `PostProcessEffectSettings`:
```
        public virtual void OnAddedToProfile(PostProcessProfile profile) { }
        public virtual void OnRemovedFromProfile(PostProcessProfile profile) { }
```

And a diff like this to `EffectListEditor`:
```@@ -201,6 +201,8 @@
             // Store this new effect as a subasset so we can reference it safely afterwards
             AssetDatabase.AddObjectToAsset(effect, m_Asset);

+            effect.OnAddedToProfile(m_Asset);
+
             // Grow the list first, then add - that's how serialized lists work in Unity
             m_SettingsProperty.arraySize++;
             var effectProp = m_SettingsProperty.GetArrayElementAtIndex(m_SettingsProperty.arraySize - 1);
@@ -230,7 +232,7 @@
             m_SerializedObject.Update();

             var property = m_SettingsProperty.GetArrayElementAtIndex(id);
-            var effect = property.objectReferenceValue;
+            var effect = property.objectReferenceValue as PostProcessEffectSettings;

             // Unassign it (should be null already but serialization does funky things
             property.objectReferenceValue = null;
@@ -247,6 +249,8 @@

             m_SerializedObject.ApplyModifiedProperties();

+            effect.OnRemovedFromProfile(m_Asset);
+
             // Destroy the setting object after ApplyModifiedProperties(). If we do it before, redo
             // actions will be in the wrong order and the reference to the setting object in the
             // list will be lost.
@@ -268,7 +272,7 @@
             m_SerializedObject.Update();

             var property = m_SettingsProperty.GetArrayElementAtIndex(id);
-            var prevSettings = property.objectReferenceValue;
+            var prevSettings = property.objectReferenceValue as PostProcessEffectSettings;

             // Unassign it but down remove it from the array to keep the index available
             property.objectReferenceValue = null;
@@ -286,6 +290,9 @@
             // Create & store the internal editor object for this effect
             CreateEditor(newEffect, property, id);

+            newEffect.OnAddedToProfile(m_Asset);
+            prevSettings.OnRemovedFromProfile(m_Asset);
+
             m_SerializedObject.ApplyModifiedProperties();

             // Same as RemoveEffectOverride, destroy at the end so it's recreated first on Undo to
```

Callbacks also need to be fired when a profile is cloned, didn't do that part yet but can provide a patch if you'd like.

**Comment by Chman** [comment]
I quite like the basis of this idea but it's also a risky one (as a single instance of `PostProcessEffectSettings` could be added to several profiles, so you'd have to be careful). It also opens a direct channel between settings and profiles, which I'm not sure is a good thing to do (you'd lose this cross-reference free, clean & safe abstraction - they shouldn't need to know about each others).

Do you really need a reference to the profile from inside the settings object? I'm asking because adding `OnAddedToProfile()` instead of `OnAddedToProfile(profile)` would keep it clean and safe.

**Comment by pete-campo** [comment]
Hmm... I'm not actually aware how the same Settings could be added to multiple Profiles!  What's the process where that happens?  I only know how to add them via the button in the GUI, and the created Settings themselves already are (HideInInspector | HideInHierarchy) sub-assets of the Profile so I can't get at them via drag and drop to add somewhere else.  But certainly if this happens then there is some possible confusion.

Unfortunately adding a sub-asset to a sub-asset (trying to add my LUT Texture2D as a sub-asset to the Settings) does not work and makes Unity unhappy, so I need that reference to the Profile I can `AddObjectToAsset(LUT, profile)` like is done for the settings.

**Comment by Kink3d** [comment]
Im afraid after some discussion weve decided that, for the reasons above, this is just too dangerous to implement. Hopefully you understand.

**Comment by pete-campo** [comment]
Is it possible to elaborate?

The "unsafe" situation you are afraid of is already happening, as far as I
can tell.
PostProcessEffectSettings is already a sub-asset of PostProcessProfile.  I
am asking to be able to add more sub-assets to PostProcessProfile that are
associated with PostProcessEffectSettings.  How is it possible that you
imagine the PostProcessEffectSetting will be referenced by multiple
PostProcessProfiles?  (and if they are, you already have the case where a
Profile references an asset from another Profile)
