### ISSUE TITLE
(v2) Resolution problem with Single Pass Stereo

### ISSUE THREAD

**Issue by m4ff** [Unity-Technologies/PostProcessing#286]
When using single-pass stereo and the post-processing stack v2 at the same time, the resolution of the display is reduced considerably and the result is unacceptable.

I first thought MSAA was being disabled somehow, but then I realized the resolution of the image was the real problem. It looked like the image was rendered at a much lower resolution and then stretched. I had a look at the source code and found that the width of the render textures is set using _Camera.pixelWidth_, which returns only half the width of the packed render texture when single pass stereo is enabled. I replaced the _width_ getter in _PostProcessRenderContext.cs_ with the following:

```
// Current camera width in pixels
public int width
{
    get { return VR.VRSettings.isDeviceActive ? camera.pixelWidth * 2 : camera.pixelWidth; }
}
```

This seems to have solved the issue for me, but it will unnecessarily double the width when using multi-pass stereo. I can't think of any way of checking what stereo rendering path is being used at runtime.

**Comment by Chman** [comment]
We're aware of that problem, it's being discussed in #237 :)

`camera.pixelWidth * 2` will work fine in most cases but some of the effects rely on knowing what the current resolution is so they won't work correctly. I haven't had the time to look into it yet, but it's on the TODO list.
