### ISSUE TITLE
Is there a equational relation between depthOfField and focalLength?

### ISSUE THREAD

**Issue by lpp1216** [Unity-Technologies/PostProcessing#291]

**Comment by Chman** [comment]
I'm not sure I understand your question. Are you looking for the maths behind depth of field? Wikipedia is a [good resource](https://en.wikipedia.org/wiki/Depth_of_field#DOF_vs._focal_length), or if you want something easier to digest [this guide](https://en.wikipedia.org/wiki/Depth_of_field#DOF_formulae) is good.

**Comment by lpp1216** [comment]
Thank you very much！I need to set the focalLength dynamically at unity runtime, All I can get is the depthOfField distance , so I want to do something with the post's Depth of field module by the depthOfField distance data to make my camera to simulate a SLR.
