### ISSUE TITLE
PPv2: asset bundle including ALL effects everytime

### ISSUE THREAD

**Issue by brmassa** [Unity-Technologies/PostProcessing#292]
When using Layer and Volume in any scene, **all** the shaders from all effects, including the debug Histogram/Vectorscope/Waveform is included in the final assembly/assetbundle, according to Unity's AssetBundles-Browser (https://github.com/Unity-Technologies/AssetBundles-Browser)!

**Comment by Chman** [comment]
You can filter the ones you don't need by removing them from the `PostProcessResources` file. Unfortunately there's no automatic way to do this reliably with the way the Asset Database works in Unity currently.

**Comment by brmassa** [comment]
@Chman (Thomas), thanks for the reply.

it is not a way to use Reflection to map existing/available effects/shaders/etc instead a ScriptableObject containing the whole list?

**Comment by Chman** [comment]
It's a build time dependency issue. When you build your game Unity will strip any asset that isn't referenced in any of your scenes. We can only track effects that are being used / setup in the editor, but we can't possibly know if an effect will only be created via scripting at runtime, which means that if we were to aggressively strip unused effects at build time your game would crash as soon as you add an effect via scripting that has been previously stripped.
