### ISSUE TITLE
Near/Far plane for DoF

### ISSUE THREAD

**Issue by rikimaru0345** [Unity-Technologies/PostProcessing#304]
##### What happened?
The settings for the "depth of field" effect are harder to get right than earlier.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Windows.

In earlier versions (before the new post processing stack) you could set the distance of the near and far-plane. Also falloff and blur size for each plane.

That was WAY easier to setup than dealing with aperture and focal length.

1) Are there any plans to introduce this much easier workflow again?
2) Is it possible to calculate focus distance, aperture and focal length manually from a given near/farplane + falloff ? If so, how?

**Comment by Chman** [comment]
> Are there any plans to introduce this much easier workflow again?

No. We're moving toward a photographic workflow as it makes the most sense (and is required for good looking, accurate depth of field and the upcoming physical camera behavior). Some would argue that it's actually easier to use now as it's optically and physically correct, especially for artists and technical artists with standard camera knowledge.

> Is it possible to calculate focus distance, aperture and focal length manually from a given near/farplane + falloff ? If so, how?

Not really, because you'd probably end up giving it invalid near / far plane / falloff data that wouldn't map to any focus distance / aperture / focal length values.

**Comment by rikimaru0345** [comment]
That is pretty unfortunate. :(
I certainly understand that physical accuracy is a popular thing nowadays; with the advent of PBR etc...
(but don't most people use unity to develop games (as in going for what looks good) instead of simulations?)

I don't want to question your decisions but I would image that much fewer people will be able to reliably deal with the new parameters.  I mean everyone can easily understand near and far planes, but not everyone is versed (well enough that is!) in how camera lens based metrics interact with each other.

Is there really no way to restructure this a bit?
I imagine that it wouldn't be too hard to have a flag somewhere in order to calculate values in a different way, no? In the end there's gotta be some common values since both types calculate a similar thing in the end.


> Some would argue that it's actually easier to use now as it's optically and physically correct, especially for artists and technical artists with standard camera knowledge.

I very much doubt that. However I think a simple forum poll could easily show how many people feel comfortable with each approach. Maybe I'll give that a try :)
