### ISSUE TITLE
V2 unusable with release candidate 2017.2 f0

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/PostProcessing#305]
##### What happened?
https://forum.unity.com/threads/latest-release-candidate-latest-v2-post-from-github-bug.497084/

(reflection errors and broken unusable post processing profiles).

> ReflectionTypeLoadException: The classes in the module cannot be loaded.
> System.Reflection.Assembly.GetTypes () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
> UnityEditor.Rendering.PostProcessing.EffectListEditor.<Init>m__0 (System.Reflection.Assembly a) (at Assets/Plugins/PostProcessing/Editor/EffectListEditor.cs:43)
> System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].ToList () (at <11c1c8f1ba1046b191f565f88728429e>:0)
> System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <11c1c8f1ba1046b191f565f88728429e>:0)
> UnityEditor.Rendering.PostProcessing.EffectListEditor.Init (UnityEngine.Rendering.PostProcessing.PostProcessProfile asset, UnityEditor.SerializedObject serializedObject) (at Assets/Plugins/PostProcessing/Editor/EffectListEditor.cs:48)
> UnityEditor.Rendering.PostProcessing.PostProcessProfileEditor.OnEnable () (at Assets/Plugins/PostProcessing/Editor/PostProcessProfileEditor.cs:13)
#
##### Post-processing stack version (v1, v2)?
V2 Latest as of this date.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.2 f0 (also happens on 2017.1.1 for me) - honestly quite depressing, would love some advice.

**Comment by hippocoder** [comment]
Upon further investigation this is due to having Scripting Runtime Version set to 4.6 experimental. 
![image](https://user-images.githubusercontent.com/264410/30774029-486418a6-a074-11e7-9256-ce9c5a05d64d.png)

**Comment by Chman** [comment]
I just tried in 2017.2.0f1 and 2017.1.0p4 and I can't reproduce it. So far I'm not sure why this would fail (FWIW, even with this error profiles aren't broken so you should lose anything, it's purely an editor issue).

**Comment by Kink3d** [comment]
Cant reproduce and inactive

**Comment by artyom-zuev** [comment]
This can also be reproduced on Unity 5.6.x by setting API compatibility level to NET 2.0 Subset (which is a default setting for new projects!).

**Comment by artyom-zuev** [comment]
Also reproduced on 2017.3.0f1 with NET 2.0 Subset API compatibility level.
