### ISSUE TITLE
(v2) The type or namespace name `XRSettings' does not exist in the namespace `UnityEngine'

### ISSUE THREAD

**Issue by sviridoff** [Unity-Technologies/PostProcessing#306]
Unable to build the project for android platform because `XRSettings` namespace doesn't exist. It seems that there is misspelling in the file `Runtime/Utils/RuntimeUtilities.cs` at the line number `239`. Should be `UnityEngine.XR.XRSetting ...`.

In the post pocessing v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version 2017.2.0f1, target platform Android

**Comment by Chman** [comment]
Fixed in 88a5c33.
