### ISSUE TITLE
(v2) some effects have issues on mac

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#307]
##### What happened?
Without Color grading, AO, SSR:
<img width="505" alt="tim 20170926025540" src="https://user-images.githubusercontent.com/18855621/30829189-c560fd92-a272-11e7-8267-721a0244ac7b.png">

Color grading enabled:
<img width="597" alt="tim 20170926025545" src="https://user-images.githubusercontent.com/18855621/30829243-e59d016e-a272-11e7-99cc-f855b0b75fa9.png">

AO enabled:
<img width="602" alt="tim 20170926025550" src="https://user-images.githubusercontent.com/18855621/30829305-01763c48-a273-11e7-8d45-def5a705ef05.png">

SSR enabled (log error):
<img width="605" alt="tim 20170926025557" src="https://user-images.githubusercontent.com/18855621/30829339-1886dc58-a273-11e7-91ff-3c1f4fffef08.png">

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
unity 2017.1.f1, mac os.

**Comment by Chman** [comment]
Metal? OpenGL?
For the last picture, see #290.

**Comment by silentlamb1991** [comment]
I remember using auto api for mac, I will do a test tomorrow.

**Comment by silentlamb1991** [comment]
I'm sure these issues only occur when using Metal.

**Comment by Kink3d** [comment]
Hi, what version of OSX are you running? We have had some problems reported on High Sierra beta due to Metal2 API.

**Comment by silentlamb1991** [comment]
![default](https://user-images.githubusercontent.com/18855621/31325296-fb9ae186-aced-11e7-862f-4060bec765be.PNG)

**Comment by Chman** [comment]
Tested and working on recent versions of Unity.
