### ISSUE TITLE
[V2] Support for Windows UWP target

### ISSUE THREAD

**Issue by demonixis** [Unity-Technologies/PostProcessing#308]
##### What happened?
The stack can't be built with the Windows UWP target. There are some errors

![image](https://user-images.githubusercontent.com/1017126/30845196-94907826-a292-11e7-8b6b-a9bcb5652e49.png)

##### Post-processing stack version (v1, v2)?
For the V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2f1

**Comment by Chman** [comment]
V2 isn't currently compatible with UWP as it requires some .NET types and methods that aren't available in the very restricted .NET scripting backend used by UWP.

**Comment by demonixis** [comment]
Have you plans to make it compatible? I was able to compile my project using IL2CPP btw.

**Comment by Chman** [comment]
IL2CPP would be recommended in this case as we have a lot of dependencies on these missing UWP .NET features. I can't say for sure if v2 will be compatible with UWP/.NET in a near future.

**Comment by demonixis** [comment]
OK, but if it's fine with IL2CPP it's good for me. It's maybe a good idea to indicate that in the doc.
Thanks for you time.

**Comment by demonixis** [comment]
Hi again,
 We maybe have a solution for .Net compatibility. I wrote a shym allowing us to compile a project to Windows UWP. You can [take a look at here](https://gist.github.com/demonixis/a8436f4ebe18764f167ced3bcdb1a13f). It requires only one modification `PostProcessEffectSettings.cs`.

However it doesn't work for one thing, the `GetAssembliesAsync()` function is asynchrone. It's called in 
 the `PostProcessManager.cs` file in the `ReloadBaseType()` method. As you know this function is very important because it populates the `settingsTypes` dictionary.

We can start this method using `async` / `await` and some Preprocessors BUT we need to block this call until the `settingsTypes` dictionary populated. That's the problem, if I make an async call to this method, other objects try to access it resulting to some exceptions.

I don't know if it is easy or not, but if the object reponsible to the creation of the `PostProcessManager` object can wait that it's fully initialized, we can get it working on Windows UWP.

**Comment by rikimaru0345** [comment]
You should be able to wait for the result of async methods by calling .GetAwaiter().GetResult(); on the returned Task<T>.

`GetAssembliesAsync().GetAwaiter().GetResult();`
maybe that helps?

**Comment by demonixis** [comment]
The call is blocked but nothing happens. I've a black screen

![image](https://user-images.githubusercontent.com/1017126/30920889-635e5dcc-a3a5-11e7-9864-24a4e4ebfad2.png)

The CPU is almost not used.

**Comment by Chman** [comment]
Adding a shim for UWP would be a good idea indeed 👍
I'll keep this around until I can get to it.

**Comment by DigitalDNAGames** [comment]
I made this code work with some fairly minor changes. It all has to do with reflection. It would really be a good idea for you to do this considering IL2CPP is not supported on the Xbox creators program, and a lot of people are going to be running into this.

**Comment by demonixis** [comment]
@DigitalDNAGames can you share your changes? Or is it too instable? That's true I had to use another solution (I use Amplify + the cinematic antialiasing ported to work with Single Pass Rendering).

**Comment by demonixis** [comment]
Any news about a working polyfill? @DigitalDNAGames @Chman

**Comment by TautvydasZilys** [comment]
@DigitalDNAGames that is not true. You can ship using IL2CPP on Xbox creators program - I have no idea where you got the idea it's not supported. Besides, .NET scripting backend is going away in near future anyway.

**Comment by demonixis** [comment]
@TautvydasZilys it was not supported, it's supported since [the version 1802]. Or by using the [raw Xbox Live API](https://github.com/Microsoft/xbox-live-api), that's what I do.

**Comment by Fragilem17** [comment]
+1 for UWP support without having to resort to IL2CPP

**Comment by stonstad** [comment]
OK -- I spent the better part of a day trying to get this to work.  Does anyone know which version .NET Core Unity is compiling for UWP when Mono scripting is chosen?  This would help -- as it seems the above code is hung on up on getting a list of assemblies loaded into the AppDomain.   The shim code is close -- but it returns an empty list of Assemblies.  

I would use IL2CPP but I am using Unity as a UserControl in an embedded manner.  Shouldn't this be a bug instead of an enhancement?  Not sure why UWP support is optional.

**Comment by stonstad** [comment]
@demonixis ... do you have Post-Processing V2 working w/ UWP and the Mono scripting backend?

**Comment by demonixis** [comment]
@stonstad nothing, I use IL2CPP. The .Net backend is deprecated in Unity 2018.3 and will be removed from Unity 2019.1, so I don't think it's a good idea to spend too much time on it.

**Comment by stonstad** [comment]
That's disappointing to hear.  For anyone who stumbles on this thread requiring the Mono scripting backend (you know who you are -- automotive, transportation, architecture applications _**_which performs C# interop into the Unity runtime_**_)...  v1 of the post-processing stack still works.  

The reason post-processing v2 does not work with UWP/Mono is that reflection code was added to the library to iterate through assemblies and types, and said code requires a different API surface area.  You'll need to revert to post-processing v1.    

There was no communication from @chman on this topic, as the Unity team felt they didn't need to support an existing capability prior to its future removal.

**Comment by stonstad** [comment]
Hi @yacuzo.  I appreciate your thinking here.  I hope this works!
