### ISSUE TITLE
Plan to add Fisheye correction?

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#309]
For more real lens effect, Fisheye correction is very necessary, especially on a high FOV camera.

**Comment by DuckyDuckling** [comment]
I think it's a bit more complicated to do that in post, and do it well without malforming stuff.

You should take a look at these:

http://tksharpless.net/vedutismo/Pannini/

https://forum.unity.com/threads/released-camera-projection-rendering-toolkit-non-linear-perspectives-oblique-projections-ssaa.483347/

**Comment by silentlamb1991** [comment]
It looks like fisheye need super-sampling for better result, but some post-effect need apply before the correction (ao, ssr, etc. any need depth) and some need apply after the correction (color only effects), so it must be done in the post-stack for correct order.

**Comment by DuckyDuckling** [comment]
https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Writing-custom-effects

**Comment by Kink3d** [comment]
Hey,

We wont be adding a Fisheye effect to the built in effects that ship with the stack. However we will be releasing the traditional Distortion effect (as per Cinematic Image Effects) as part of another repository where users can upload their custom effects towards release time (we need to make sure our custom effect API is set in stone before we do this).

Thanks
