### ISSUE TITLE
SteamVR Troubles

### ISSUE THREAD

**Issue by boeremak** [Unity-Technologies/PostProcessing#31]
Hi,

I've been testing your new post processing stack with Unity version 5.4.2f2 and I've been getting some weird results.

First off, if using SteamVR where do you put the behaviour? If I put it on the Camera (head) object nothing gets rendered even though it looks good in the viewport. I've been testing with Bloom and AA.

Secondly: If I put the behaviour on the Camera Rig prefab my controllers get stuck, they seem to float in front of me and I can't use them. Removing the behaviour does not fix it, I need to create a new rig for everything to reset properly. This took awhile to figure out.

Removing the Post Processing stack, creating a new Rig, adding Post Processing to the CameraRig Object breaks it again.

Versions:
Unity version 5.4.2f2
SteamVR 1.1.1 From the asset store
Post Processing Beta 4

Don't know if I need to file this with you guys or Valve.  If you need more information please let me know.

On a positive note, what gets rendered looks awesome! ;)

**Comment by Chman** [comment]
I just ran a few tests with SteamVR. You need to put the `PostProcessingBehaviour` component on `Main Camera (eye)` for it to work properly. This way it seems to work perfectly fine (except for [known issues](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues)) and I couldn't reproduce the stuck controller issue.

**Comment by boeremak** [comment]
Well, putting the postprocessing on Main Camera (eye) seems to have done the trick. Thanks! It looks really good!

Can't believe I did not figure to put it lower in the hierarchy..... Thanks.  The other problem might be something on my machine though.

**Comment by Kink3d** [comment]
Glad to hear it!

If you can recreate the second issue in a small project that you can send to us I would be glad to look at it for you.

**Comment by boeremak** [comment]
I've created a sample file, but it is too large for Github. It clocks in at 48mb. 

From my limited understanding in figuring this out: Do you take a fully rendered image in your postprocessing stack, update it with effects and then send it out again to the headset? It seems that attaching the postprocessing to the wrong camera ( head or the rig itself ) creates a different perspective so that everything sent to the headset is seen from the wrong perspective. Attaching the stack to the Camera (eye ) is the right one and keeps the right perspective.

Sounds plausible ;)
