### ISSUE TITLE
[V1] Mac High Sierra - Slow down and screen tearing in play and editor

### ISSUE THREAD

**Issue by jmguillemette** [Unity-Technologies/PostProcessing#317]
##### What happened?
with post processing enabled (but all modules disabled) the editor screen and game halts for several seconds at a time and screen tearing can be seen in the game and editor displays

##### Post-processing stack version (v1, v2)?
1.0.4
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.1f1

**Comment by Kink3d** [comment]
Hi,

Thanks for your patience. Can you please try switching to GLCore graphics API and see if the problem persists? This is likely an issue with Metal2. It would also be really helpful if you could try V2 of the stack (https://github.com/Unity-Technologies/PostProcessing/tree/v2) and see if the issue reproduces there as I am unable to update my Mac to High Sierra at this time.

Thanks!

**Comment by jmguillemette** [comment]
will do and ill let you know the results.

j.

**Comment by Chman** [comment]
Any news on this one?
