### ISSUE TITLE
(v2) Exclude Layers

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/PostProcessing#318]
##### What happened?
Hi, 
I have a 3d scene with a 3d UI Canvas.
What I would like is to have PostProcess on the 3d but not the UI.
It is not possible to exclude the UI layer from the PostProcess.

Is it something that would be possible ?

Thanks

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.1p2, Windows 10, Standalone PC

**Comment by Kink3d** [comment]
Hi,

Im afraid its impossible for us to exclude Layers from Post Processing. However, you can solve your problem by rendering your UI with a separate camera at a higher depth (using layers to exclude rendering everything else). Either that or you can use the "Screen Space Overlay" mode on the UI Canvas (which is not affected by Post-processing).

Thanks

**Comment by DaveAccenture** [comment]
Does this work in VR? I have the same issue, app target Oculus Go. Need me world-space text (TextMeshPro) not affected, background (skybox and other objects) affected.
Any other recommendations how to accomplish this effect, even if it involves NOT using post processing?
