### ISSUE TITLE
[V2] Toolkit 'Select all active volumes' breaks global volume settings

### ISSUE THREAD

**Issue by gregharding** [Unity-Technologies/PostProcessing#319]
##### What happened?

I made a simple test scene with a global volume (priority 0) and a local volume (priority 1, sphere collider with radius 10 + blend distance 5). In the editor while editing or playing, when moving the main camera (which is the volume blending trigger) in and out of the local spherical blend volume, using the Toolkit 'Select all active volumes' seems to copy the current blended settings to the global volume settings, overwriting them.

In playmode, the blending stops working properly and the weight seems to need to be inverted to see the proper blend again. At editor time, the global volume settings are overwritten and the original settings are lost (but can be undone depending on the reliability of the undo stack).

##### Post-processing stack version (v1, v2)?

v2 (v2 tagged 2.0.0-b3).

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2017.1.1p1, MacOS 10.12.6, in the editor using MacOS desktop target.

**Comment by Chman** [comment]
Fixed in 242330e. Multi-edit in general can be quite painful to get right.
