### ISSUE TITLE
v1 Doesn't support 2017.2 single pass rendering for VR

### ISSUE THREAD

**Issue by capitaljmedia** [Unity-Technologies/PostProcessing#322]
##### What happened?
The image is rendered as black if I have post processing behaviour on my VR camera and have single pass rendering. If I turn off the behaviour then the image renders correctly, same if I switch to multi pass rendering.

##### Post-processing stack version (v1, v2)?
v1

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.2f02
windows standalone, HTC Vive steamVR

**Comment by robbiesri** [comment]
I haven't investigated v1 in a while personally, but I don't think there are plans for full XR support on v1.  I'm working on v2 support now.

**Comment by Kink3d** [comment]
Hi,

Yes, I'm afraid we simply cant support SPS in V1 as we arent actively developing that version anymore and there is a lot of work involved in maintaining SPS (it did "work" in previous versions).

I would recommend switching to V2 as we now have feature parity (different versions of effects but no effects are missing) between the two versions (also there is significant improvements, specifically in XR).

Thanks
