### ISSUE TITLE
[V2] Eye texture format in single-pass stereo

### ISSUE THREAD

**Issue by olavrv** [Unity-Technologies/PostProcessing#323]
In singlepass rendering / VR there is a bright line to the right of the screen when post processing stack is enabled.

WIndows x64, Unity 2017.1.2f1

Post processing stack v2 (latest commit 10.10.2017)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
# #

**Comment by olavrv** [comment]
Setting Viewport Rect from width 0.999999 fixes this issue (hack solution)

**Comment by robbiesri** [comment]
Wait, is this V1 or V2?  The title says V1, but your comment says V2.

**Comment by olavrv** [comment]
v2, typo - my bad

**Comment by robbiesri** [comment]
I'm working on general XR support in v2 right now.  But it can only really work with 2017.2+, because we can't query the backing eye texture format before that version of the Unity Engine.

**Comment by Chman** [comment]
We merged a big XR PR a while back, I just tried it again and the bright line is gone.
