### ISSUE TITLE
[V2] Multi editing volumes overrides the profile

### ISSUE THREAD

**Issue by ArthurBrussee** [Unity-Technologies/PostProcessing#324]
##### What happened?

When editing say two post processing volumes, A and B, with different profiles, the profile of A gets set to volume B. 

Looking at the PostProcessVolumeEditor, there is code such as:

```C#
using (var scope = new EditorGUI.ChangeCheckScope())
{
    m_Profile.objectReferenceValue = (PostProcessProfile)EditorGUI.ObjectField(fieldRect, m_Profile.objectReferenceValue, typeof(PostProcessProfile), false);
    assetHasChanged = scope.changed;
}
```

Which doesn't handle multi editing.

**Comment by Chman** [comment]
Fixed in 242330e. You'll only be able to multi-edit if the same profile is set. Else you'll get the expected "mixed value" display for the profile field.
