### ISSUE TITLE
(v2) Screen Space Reflection render texture error

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#327]
##### What happened?
If I enable screen space reflection I got this error:
`RenderTexture.GenerateMips failed: render texture does not have mip maps (set useMipMap to true).`
no line number in the error...
![](https://i.imgur.com/T7jcGjo.png)

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.1p2
windows 10 64 bits

**Comment by ghiboz** [comment]
oops, is the same of #290, does anybody knows if some new patch of `2017.1` will solve this?

**Comment by Kink3d** [comment]
Tracking down backports for the issue. Will post updates in #290
