### ISSUE TITLE
[V2] Update inspector when enabling from C#

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#328]
##### What happened?
if I enable an effect with this code: 
```csharp
var set = (ColorGrading)item;
set.enabled.value = enable;
```
it works, but the button results in a wrong state... and is not enabled/disabled yet

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.1.1p2 - windows 10 64

**Comment by Chman** [comment]
If you click the inspector after your code got executed you'll see the UI update (unless you're using an in-memory copy of a profile). With the way things are handled in the editor right now for volumes & profiles it's a bit of a pain to make the inspector auto-refresh on property change. I do agree it's a bit annoying not to get immediate feedback though...
