### ISSUE TITLE
How to capture pictures with transparent channels when PostProcessing is enabled.

### ISSUE THREAD

**Issue by lam-by** [Unity-Technologies/PostProcessing#332]
##### What happened?
Use the following method if do not use PostProcessing can capture picture with transparent channel, use PostProcessing can not.

    private static Texture2D ScreenShot(Camera camera, Rect rect)
    {
        RenderTexture rt = new RenderTexture((int)rect.width, (int)rect.height, 0);
        Color color = camera.backgroundColor;
        camera.backgroundColor = Color.clear;
        camera.targetTexture = rt;
        camera.Render();
        RenderTexture.active = rt;
        Texture2D screenShot = new Texture2D((int)rect.width, (int)rect.height, TextureFormat.RGBA32, false);
        screenShot.ReadPixels(rect, 0, 0);
        screenShot.Apply();
        camera.targetTexture = null;
        camera.backgroundColor = color;
        RenderTexture.active = null;
        UnityEngine.Object.Destroy(rt);
        return screenShot;
    }

![qq 20171014101421](https://user-images.githubusercontent.com/32784141/31571594-7f41bc16-b0c8-11e7-9ec0-70e0932ba8b5.png)

##### Post-processing stack version (v1, v2)?
v1
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.3, Windows 10, Standalone Windows

**Comment by Kink3d** [comment]
Hi,

This problem (not preserving alpha) has been rectified in V2 of the stack (I just tested and it works). However, I'm afraid this cannot be simply be backported to V1. Please update your project to use V2 if you wish to composite like this.

Thanks!
