### ISSUE TITLE
Compiler Errors 

### ISSUE THREAD

**Issue by BonesNotSafe** [Unity-Technologies/PostProcessing#335]
##### What happened?
I'm getting "`error CS1660: Cannot convert 'lambda expression' to non-delegate type 'Action'`" from EffectListEditor.cs, ColorGradingEditor.cs, and VignetteEditor.cs.
Also "`error CS0119: Expression denotes a 'variable', where a 'method group' was expected`" from EditorUtilities.cs.
I haven't made any changes to the scripts, they just show these compiler errors as soon as they're brought into the project.
##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.2, Windows 7, standalone windows

**Comment by Kolezka326** [comment]
I have that problem too and I've tried v1 and v2, only difference is that on v1 there is 17 errors like that.

**Comment by Chman** [comment]
You probably have a class named `Action` in your project / global namespace which overrides the `System.Action` delegate in the standard C# library. Either you need to rename it or namespace it properly.
