### ISSUE TITLE
Temporal Anti-aliasing not working with single pass VR

### ISSUE THREAD

**Issue by Phantomx2** [Unity-Technologies/PostProcessing#34]
Temporal Anti-aliasing not working with single pass VR, tried to use UnityStereoScreenSpaceUVAdjust on the uv, but I can't get it to work. The screen shows the render of both eyes on each eye.

**Comment by Kink3d** [comment]
Hi,

Unfortauntely TAA is currently unavailable in VR due to a lack of motion vector support for VR. See our known issues list [here](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues)

We are working on adding this support soon. Thanks for submitting the issue anyway :)
