### ISSUE TITLE
V2 Missing (Screen Edge Mask) Intensity option in Screen Space Reflection

### ISSUE THREAD

**Issue by CosmosTbear** [Unity-Technologies/PostProcessing#344]
If I remember there was a (Screen Edge Mask) Intensity option in V1 so you could mask the edge of the screen. Without it you get large glitched smear from the edge of the screen on large glossy surface.

V2

Unity 2017.2.0f3 Windows

**Comment by Chman** [comment]
It's coming back as a "vignette" setting (see #353).

**Comment by Chman** [comment]
Added with #358.
