### ISSUE TITLE
[V1.0.4] FindKernel error on OpenGL | Only with Eye Adaptation

### ISSUE THREAD

**Issue by TBDEV** [Unity-Technologies/PostProcessing#345]
##### What happened?
Screen goes black when Eye Adaptation is turned on under OpenGL.
Console gives FIndKernel not found error
Tested from OGL 3.3 to 4.5. It works under DX11.
##### Post-processing stack version (v1, v2)?
Version 1.0.4
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.1f1 64-bit
Windows 10 Pro 64-bit
Desktop Cross-platform Win, Linux, osX

**Comment by Chman** [comment]
This was a shader compiler bug. I just ran a quick test on Unity 2017.2 and 2017.3 and it works as expected there (GL4.5/windows). I'm not entirely sure what version the fix got pushed to though...

(note that OpenGL 3.3 doesn't support compute, so it's not expected to work there)
