### ISSUE TITLE
Fog - Atmospheric Scattering 

### ISSUE THREAD

**Issue by Ziboo** [Unity-Technologies/PostProcessing#348]
Any ETA for a better Fog / Atmospheric Scattering / Height Fog ?

Thanks

**Comment by JacobSmaga** [comment]
https://github.com/Unity-Technologies/ScriptableRenderPipeline - HD Render Pipeline

**Comment by Chman** [comment]
Volumetrics aren't post-processing effects, they're lighting effects. More volumetric goodness will come with scriptable render pipelines. Follow @JacobSmaga's link for more information.
