### ISSUE TITLE
SSR black spots in HDR

### ISSUE THREAD

**Issue by Elgen** [Unity-Technologies/PostProcessing#35]
Kudos on a fantastic post stack!
I have a problem with SSR however, in combination with HDR. Causes black spots to appear with certain images. Linear space and deferred.

Have tried turning off everything, including scene lights and reflection probes, and flipping every setting in the post stack, and the only thing that makes them disappear is by turning off HDR or SSR.

![ssr-hdr](https://cloud.githubusercontent.com/assets/775105/21043609/f8379f7e-bdf7-11e6-8b2b-875645b69f7a.png)

**Comment by Elgen** [comment]
And it only happens with DX 11, not DX9

**Comment by Chman** [comment]
Are you running this on an AMD GPU ?

**Comment by Elgen** [comment]
Nope, it's a GTX980. Tried updating drivers too, with no effect.

**Comment by Kink3d** [comment]
Hi, is there any chance you can provide a (preferably small) scene that reproduces this issue? As of yet we have only been able to reproduce this on AMD GPUs (as you probably gathered from Chman's reply).

Thanks

**Comment by Elgen** [comment]
Sorry for the late reply. I tried to create a small example project, but had trouble recreating the problem. In the end i found out this is a bug in relation to the Uber Standard Shader Ultra (https://www.assetstore.unity3d.com/en/#!/content/39959). So I guess it's up to that developer to fix, not you guys.

**Comment by Kink3d** [comment]
Ok thanks for the info :)
