### ISSUE TITLE
[V2] Namespace Conflict with internal bloom

### ISSUE THREAD

**Issue by Baccanno** [Unity-Technologies/PostProcessing#351]
##### What happened?
had to add bloom namespace in order to compile
```
    [PostProcessEditor(typeof(UnityEngine.Rendering.PostProcessing.Bloom))]
    public sealed class BloomEditor : PostProcessEffectEditor<UnityEngine.Rendering.PostProcessing.Bloom>
```

##### Post-processing stack version (v1, v2)?
V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Win 10 Unity 2017.2.0f3

**Comment by Chman** [comment]
What's "internal bloom"? I just checked and all Bloom scripts that Unity had (legacy image effects, cinematic image effects, stack v1) are properly namespaced and shouldn't collide with v2.
