### ISSUE TITLE
NullReferenceException SetLegacyCameraFlags

### ISSUE THREAD

**Issue by aaronjbaptiste** [Unity-Technologies/PostProcessing#352]
##### What happened?

Mouse over anywhere on the editor view, console is spammed with:

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Libs/PostProcessing/Runtime/PostProcessLayer.cs:494)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Libs/PostProcessing/Runtime/PostProcessLayer.cs:551)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/Libs/PostProcessing/Runtime/PostProcessLayer.cs:307)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/Libs/PostProcessing/Runtime/PostProcessLayer.cs:278)

##### Post-processing stack version (v1, v2)?

Lastest v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

macOS, Unity 2017.1.2f1

**Comment by Chman** [comment]
I can't reproduce this, but we pushed a bunch of bug fixes in the past days so it may have been fixed. Does it still happen for you?
