### ISSUE TITLE
Question : where did nice bloom procedural flares went?

### ISSUE THREAD

**Issue by nicobella** [Unity-Technologies/PostProcessing#354]
##### What happened?

this is more a question than an actual issue or bug, but why the post processing stack doesn't have the nice procedural flares in the bloom effect, similar to unreal ones, we had this effect in the old deprecated Bloom post effect from the Unity's standard assets, does it have natural problems to be implemented in the current workflow of post processing stacks or something like that?

I can see a branch here called "flares" but I have no idea if that is related to my question.

Flares in the bloom would and an extra step of photorealism to the stack, and it would be amazing if you guys add it as an option to bloom effect as you did with the dirtiness option.

**Comment by JacobSmaga** [comment]
They are working on it; Physically based lens flare.

**Comment by nicobella** [comment]
thanks, amazing! in that case you lets close this issue and wait :)

**Comment by Chman** [comment]
Flares are indeed coming. I can't give an ETA at this point as I'm helping with other features in Unity but it's definitely on the roadmap.

**Comment by IgnisIncendio** [comment]
Any updates on this?
