### ISSUE TITLE
attributes used in all models not found

### ISSUE THREAD

**Issue by shaderbytes** [Unity-Technologies/PostProcessing#355]
The type or namespace name `Min' could not be found. Are you missing an assembly reference?
also
The type or namespace name `Trackball' could not be found. Are you missing an assembly reference?

spammed errors to console.. Unity 2017.3.0b6 upon coping folder to my project directory

v2

 Unity 2017.3.0b6  windows10 64bit desktop

**Comment by Chman** [comment]
I just put v2 in an empty project on 2017.3.0b8 and it works fine here. Make sure you're not missing any file.

**Comment by shaderbytes** [comment]
Very Weird, I just coped the entire "postporocessing" directory into my project , overwriting the current one.. The folder comes from a fresh download of V2 stack a few day back? Unless Unity got into some state i cant see how I can be missing any files. I pasted the errors above, what files do presume im missing? Pasting V1 back over this does NOT cause this issue. These errors comes from the various Model Files, This is an attribute it cant find. I will try again again report back thanks

**Comment by Chman** [comment]
Can you do a search in your project panel for `MinAttribute`? See if it returns anything...

**Comment by xiefuhao** [comment]
using UnityEngine.Rendering.PostProcessing; in compile error file
looks like the namespace is not used

**Comment by khalv** [comment]
I am still getting this issue? Replaced the entire PostProcessing folder with the newest release, reimported, reimported, upgraded Unity, still doesn't workk. These are also the only errors i get, and the project worked fine a few weeks ago.
