### ISSUE TITLE
PostProcessRenderContext.Reset() always creates new userData

### ISSUE THREAD

**Issue by dfitt** [Unity-Technologies/PostProcessing#357]
##### What happened?
PostProcessRenderContext.Reset() first sets userData to null, and then creates a new dictionary if it is null. This then creates garbage every frame.

##### Post-processing stack version (v1, v2)?
v2

The problem code looks like this:
userData = null;
if (userData == null) userData = new Dictionary<string, object>();

**Comment by Chman** [comment]
Good catch. Fixed in e680f54.
