### ISSUE TITLE
[v2]UnityEngine.TextureFormat' does not contain a definition for `DXT1Crunched

### ISSUE THREAD

**Issue by larssteenhoff** [Unity-Technologies/PostProcessing#360]
##### What happened?
Compile error when building for tvOS
Assets/PostProcessing/Runtime/Utils/TextureFormatUtilities.cs(39,33): error CS0117: `UnityEngine.TextureFormat' does not contain a definition for `DXT1Crunched'

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
tvOS

**Comment by Chman** [comment]
Fixed with #364.
