### ISSUE TITLE
v1.0.4 causes builds to fail

### ISSUE THREAD

**Issue by hedgefield** [Unity-Technologies/PostProcessing#361]
##### What happened?
Ever since 2017+ I've been having trouble building my projects. Whenever I try, it hangs on building resources.asset. The CPU goes to 90-100% usage, the memory Unity generates goes up to the 1-2 GB range, and after 5 or 10 minutes there is no progress, and sometimes it crashes to a Blue Screen Of Death.

I tried ruling out other asset packages, switched between DX11 and DX9, Linear and Gamma, Forward and Deferred, X86 and X64, but the only thing that fixes it is removing the Postprocessing folder completely from the project.

I don't get any errors, since it never finishes the build, but after I remove the postprocessing folder and build again I get these errors (build fails). The next builds after that succeed (until I reimport the stack).

![screenshot_1](https://user-images.githubusercontent.com/6073772/32703289-f2a1f396-c7f3-11e7-8b9d-5c2dccb064d7.png)
![screenshot_2](https://user-images.githubusercontent.com/6073772/32703291-f2bff8d2-c7f3-11e7-9e65-e0670ff7a8dd.png)

##### Post-processing stack version?
1.0.4 from the Asset Store.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2.0f3, Windows 10 up-to-date, Asus Rog G551JW gaming laptop, building to Windows platform.

**Comment by InderdeepSinghM** [comment]
I also have the same issue

**Comment by hedgefield** [comment]
I've managed to fix this by going into each scene, turning off auto generate in the lighting panel, unchecking all the GI checkboxes in that same panel, hitting Generate Lightmap so a lighting folder gets created, and turning off auto graphics API for windows and removing everything in that list except DX11.

**Comment by lordvard** [comment]
turning off auto graphics api and removing dx9 made it build for me.

**Comment by hedgefield** [comment]
Seems like the problem isn't completely fixed with this. Building to Linux still hangs, and a different project couldn't build to Windows, even though I applied the same method that fixed my other project. Building from Mac to Mac also doesn't work.

**Comment by hedgefield** [comment]
Seemingly fixed by turning off `auto graphics API` for all platforms, and removing Metal from MacOS.
