### ISSUE TITLE
Shader error in GaussianDownsample.compute

### ISSUE THREAD

**Issue by dev-chee** [Unity-Technologies/PostProcessing#365]
##### What happened?
* Shader error in 'GaussianDownsample.compute': '' : compilation terminated at kernel KMain at line 68 (on vulkan)
* Shader error in 'GaussianDownsample.compute': 'assign' :  cannot convert from 'temp highp float' to 'temp highp int' at kernel KMain at line 68 (on vulkan)

##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2.0f3, Windows 7 64bit, standalone windows <OpenGL ES 3.1 AEP>

**Comment by slime73** [comment]
Unity 2017.2.0p1 has a fix for this, I believe (f16tof32 and f32tof16 were not getting translated correctly from HLSL to GLSL/SPIR-V).

**Comment by Chman** [comment]
@dev-chee Can I mark this as fixed? Did updating to 2017.2.0p1+ fixed it for you?

**Comment by AhmadSF** [comment]
2017.2.0p1 Fixed it For me, Thanks

**Comment by sunxdc15** [comment]
I also met this error on Unity5.6.5f1(64bit), please help
