### ISSUE TITLE
Motion Blure don`t work correct with SteamVR

### ISSUE THREAD

**Issue by ViktorCor** [Unity-Technologies/PostProcessing#37]
If use motion blur with VR > all blur by a horizontal.
Without motion blur:
http://f4.s.qip.ru/8eyNv8Qp.jpg
With MotionBlur:
http://f6.s.qip.ru/8eyNv8Qq.jpg

Maybe because of camera move from left eye to right eye from one Update for render two eyes...?

**Comment by Chman** [comment]
Motion blur isn't supported with VR yet. See the [known issues](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues) list.
