### ISSUE TITLE
Tonemapping?

### ISSUE THREAD

**Issue by Claytonious** [Unity-Technologies/PostProcessing#371]
Since there is no longer any standalone tonemapping "effect" to choose, I've been guessing that this is simply automatic now whenever HDR rendering is done. Is that correct? Are there any options we can tweak? Is there any documentation I'm overlooking about how tonemapping is done/controlled in v2 stack?

Thanks!

**Comment by Chman** [comment]
It's part of the Color Grading effect when working in HDR.

![image](https://user-images.githubusercontent.com/849090/33085296-9a33d59c-cee4-11e7-92ca-1a1c3ca43416.png)

Documentation on v2 is a bit sparse right now as we haven't got the time to get to it, but in the meantime we put some info and quick-start guide on [the wiki](https://github.com/Unity-Technologies/PostProcessing/wiki).
