### ISSUE TITLE
Can't add 'PostProcessingBehaviour' to SceneCamera

### ISSUE THREAD

**Issue by AdrienVR** [Unity-Technologies/PostProcessing#374]
Hello,

I am using Unity Pro 5.6.4f1 on Windows 10 and Unity-PostProcessing-1.0.4 (from unitypackage).
My Scene View doesn't work anymore (and previously I had very low perfs in editor because of PostProcessing) after I closed my scene view and opened it again.
As a user I don't need PostProcess in the scene view, only in the game view.

I got this log in the console while resizing the scene view :
[Editor.log](https://github.com/Unity-Technologies/PostProcessing/files/1500200/Editor.log)
    "Can't add 'PostProcessingBehaviour' to SceneCamera because a 'PostProcessingBehaviour' is already added to the game object!"
And the following error :
    "ArgumentNullException: Argument cannot be null.
Parameter name: Argument 'dest' is null"

My only fix is to remove the whole PostProcessing folder...

**Comment by Chman** [comment]
Does it work in an empty project? You may have a broken or corrupted post-processing profile assigned in your scene or the package didn't import properly and some references are broken.

As for disabling post-processing in the scene-view, you can toggle them off in the scene view control bar.
![image](https://user-images.githubusercontent.com/849090/33485628-5c8e25c4-d6a7-11e7-8375-5ee9987c6a8d.png)

**Comment by AdrienVR** [comment]
Thanks for your reply. 
Disabling Image Effects in the scene-view removed the error.
But I found the origin of the issue : the Camera in my scene had 2 PostProcessingBehaviour components, and looking in my git history this impossible thing happened when I integrated Wwise (it automatically adds AkAudioListener and stuff to the main camera), my camera is a prefab so I guess that's how you can have multiple components even if they have the DisallowMultipleComponent attribute like PostProcessingBehaviour has :D

**Comment by AdrienVR** [comment]
Also I added Unity 5.5 Effects package to use Tilt Shift Effect. Is there any other way to achieve Tilt Shift or is it a good solution ?

**Comment by Chman** [comment]
> my camera is a prefab so I guess that's how you can have multiple components even if they have the DisallowMultipleComponent attribute like PostProcessingBehaviour has

Sounds like an actual Unity bug to me as this should definitely not be possible... Might be worth reporting it.

> Also I added Unity 5.5 Effects package to use Tilt Shift Effect. Is there any other way to achieve Tilt Shift or is it a good solution ?

It's a "solution", as we don't provide any other Tilt Shift effect. To be honest I don't remember what it looks like, but if it works for you then go ahead, you can use it alongside the post-processing stack it should work fine :)
