### ISSUE TITLE
[V2] Image flipped vertically on Switch hardware (2017.x)

### ISSUE THREAD

**Issue by WillBarr** [Unity-Technologies/PostProcessing#375]
Hi, noticed that using any post effect (using v2 stack) causes the image to flip vertically (with the exception of motion blur, which when included in the post processing layer ensures image is orientated correctly) when running on Nintendo Switch hardware. (issue in 2017.x versions, 5.6 works fine)

Also, have to comment out all the references to XR/ VR settings to build as Switch has the same issues as [this one](https://github.com/Unity-Technologies/PostProcessing/issues/311). (all versions, 5.6+)

Keep up the good work chaps! 😀

**Comment by AlexandreFiset** [comment]
+1 - Image is flipped and mirrored + XRSettings do not compile on Switch.

**Comment by robbiesri** [comment]
I'm guessing that some header in the compilation chain should be setting UNITY_UV_STARTS_AT_TOP to 1 (which is what issue #384 is jamming in with the Vulkan.hlsl header).

**Comment by Chman** [comment]
Could you try with the latest version? I don't have a switch devkit at hand right now but f38a1e4 should fix this. See #384.
