### ISSUE TITLE
[V2] Can we get back artistic AO with MSVAO?

### ISSUE THREAD

**Issue by nicobella** [Unity-Technologies/PostProcessing#379]
Hi, what I'm asking is if we can get back the option to enable or disable the MSVAO affecting only ambient light or creating just a black shadow, because although the current version is physically correct some would say that the original SSAO that just darkens areas is better artistically speaking, and it is, in my scenes MSVAO barely contributes any change to the final image, and for it's costs it doesn't make sense to add it at all, while the old AO that darkens areas no matter if these areas are ambient, diffuse or direct lightened, works great and gives more artistic look.

I've seen that I got back the old behaviour when I switch the camera to forward instead of deferred, but I cant use forward in my project for multiple reasons.

I suggest having even a slider with range 0-1 to lerp between physically correct AO and Artistic AO in any amount we  want, if that is even possible.

cheers

**Comment by Chman** [comment]
It's already there. Uncheck "Ambient-only" and it'll apply AO the way you want it (same as the original SSAO).

**Comment by nicobella** [comment]
Note: I realized why it was not showing in my project, it was because 1) it seems that I had an older version of the v2 stack that either had a bug or didn't had this implemented.
2) I downloaded latest version from github and it is only shown when there is a camera with deferred path enabled in the scene, in my case I was editing the profile in a scene with a camera in forward mode (regardless I use the profile in other cameras in other scenes)

I think the inspector should show the option independently of the current active camera in scene, since the very concept of volumes and profiles is to get decoupled from cameras, the setting could be shown always but as "Ambient Only (only deferred)" and a tooltip saying "On deferred path you can choose if AO affects only ambient or uses the more artistic approach. this option does nothing on Forward".

maybe you should consider in your inspector design the use case for people editing profiles indepently of the final cameras that will use them, the active camera could or not suffice the requirements for the profile inspector to show certain settings (active camera is forward but profile is supposed to run on deferred cams) and this should not affect the profile editing experience, at least from my point of view, I've spent several hours to realize how to set the profile to the non-default value of Ambient-only = false.

cheers
