### ISSUE TITLE
Vignette, Grain and Chromatic Abberration also affect editor camera

### ISSUE THREAD

**Issue by BitteWenden** [Unity-Technologies/PostProcessing#38]
The three effects mentioned in the title also affect the editor camera in "Shaded" mode.

**Comment by Chman** [comment]
That's expected if you've enabled image effects in the scene view.

![image](https://cloud.githubusercontent.com/assets/849090/21095958/0cadde4c-c05e-11e6-80be-d280a054f023.png)
