### ISSUE TITLE
[V2] Depth of Field shows inverted transparent objects on Switch

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#380]
Context: PostProcessing V2 & Tested on 2017.2p2
The image below explains it all. The top image is taken from the editor while the bottom is a screenshot on Switch.
![dof-invert](https://user-images.githubusercontent.com/850692/33488793-d667fc26-d67f-11e7-931d-478b7e1694b7.png)
All transparent objects are flipped and move the opposite side of the camera direction.

**Comment by AlexandreFiset** [comment]
It looks like it might be due to the combination of the stack and the fog. Turns out the Stack flips the screen upside down while the fog (both built in and Stylized from the Asset Store) are rendered on the correct size.  On the above screenshot, I had a script to flip the screen back to normal, so the actual Opaque Geometry objects are the ones flipped; not the other way around. I think we should close this issue as I'll write something new and more detailed (including workaround to make it work on Switch).

**Comment by Chman** [comment]
Could you try with the latest version? (f38a1e4). See #384.

**Comment by AlexandreFiset** [comment]
Hi @Chman ! 

Just tried it out, and it won't compile on build if you do not include the "defined" in "defined(SHADER_API_SWITCH)". See the image below. 

![image](https://user-images.githubusercontent.com/850692/34126095-707d0138-e406-11e7-8009-65cdc8de04cf.png)

I do not know if there's any logic in my workaround, but at least it works, so ;p

**Comment by Chman** [comment]
Ah right, fixed in 76763ce!

**Comment by AlexandreFiset** [comment]
I confirm the fix, this can be closed :) Cheers!
