### ISSUE TITLE
[V2] [Switch] StdLib.hlsl API Macros #include selection for Switch is incompatible with NVN

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#384]
The PostProcessing Stack is currently not compatible with the Nintendo Switch, but there is an easy workaround and most likely an easy fix to it, too. 

By adding the following code in the API Macros section of the the StdLib.hlsl file, compatibility issues such as [upside down rendering](https://github.com/Unity-Technologies/PostProcessing/issues/375) will just vanish (hurray!)
```
#elif defined(SHADER_API_SWITCH)
#include "API/Vulkan.hlsl"
```
It's rather unclean to use Vulkan file on NVN, but it works, so I'm happy with it (and now anyone running into the same issues can be too).

Cheers!

**Comment by Chman** [comment]
Thanks, I pushed f38a1e4. I don't have a Switch devkit at hand at the moment though so this is widely untested at this point.
