### ISSUE TITLE
GLSL linker error on Android

### ISSUE THREAD

**Issue by jokthefoo** [Unity-Technologies/PostProcessing#385]
This appears to be almost the same issue as this: [issue 97](https://github.com/Unity-Technologies/PostProcessing/issues/97)
Unity 2017.2.0f3
 -------- GLSL link error: Warning: barrier used in non-uniform control flowWarning: barrier used in non-uniform control flow
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.314 26389 26443 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/ApiGLES.cpp Line: 657)
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.314 26389 26443 E Unity   : ERROR: Unable to link compute shader!
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.314 26389 26443 E Unity   : (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 2507)
12-07 04:07:58.314 26389 26443 E Unity   :
12-07 04:07:58.360 26389 26443 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 26443 (UnityGfxDeviceW)
12-07 04:07:58.471 26530 26530 I crash_dump32: obtaining output fd from tombstoned
12-07 04:07:58.472  4539  4539 I /system/bin/tombstoned: received crash request for pid 26389
12-07 04:07:58.476 26530 26530 I crash_dump32: performing dump of process 26389 (target tid = 26443)
12-07 04:07:58.477 26530 26530 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-07 04:07:58.477 26530 26530 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus3/OnePlus3:8.0.0/OPR6.170623.013/10250816:user/release-keys'
12-07 04:07:58.477 26530 26530 F DEBUG   : Revision: '0'
12-07 04:07:58.477 26530 26530 F DEBUG   : ABI: 'arm'
12-07 04:07:58.477 26530 26530 F DEBUG   : pid: 26389, tid: 26443, name: UnityGfxDeviceW  >>> com.EAETeam8.Slimy2 <<<
12-07 04:07:58.477 26530 26530 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
12-07 04:07:58.477 26530 26530 F DEBUG   : Cause: null pointer dereference
12-07 04:07:58.477 26530 26530 F DEBUG   :     r0 00e9bba4  r1 00000000  r2 000000e1  r3 00000004
12-07 04:07:58.477 26530 26530 F DEBUG   :     r4 c9bc5010  r5 c0087b50  r6 c29c9520  r7 c29c9500
12-07 04:07:58.477 26530 26530 F DEBUG   :     r8 00000000  r9 00000000  sl c9bc88fc  fp 00000001
12-07 04:07:58.477 26530 26530 F DEBUG   :     ip 00020000  sp c8fff310  lr cccd9ff4  pc cccb6268  cpsr 200f0010
12-07 04:07:58.497 26530 26530 F DEBUG   :
12-07 04:07:58.497 26530 26530 F DEBUG   : backtrace:
12-07 04:07:58.497 26530 26530 F DEBUG   :     #00 pc 00985268  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN13GfxDeviceGLES16SetComputeBufferE15ComputeBufferIDi20ComputeBufferCounterbb+1712)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #01 pc 00989ce0  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN13GfxDeviceGLES22UpdateComputeResourcesEjPK9TextureIDPK16TextureDimensionPKijPKjjPK15ComputeBufferIDS7_PK20ComputeBufferCounterjSC_S2_S5_S9_SF_+744)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #02 pc 00967f84  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN15GfxDeviceWorker10RunCommandER20ThreadedStreamBuffer+34700)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #03 pc 009689e0  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN15GfxDeviceWorker6RunExtER20ThreadedStreamBuffer+32)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #04 pc 0095f7d4  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN15GfxDeviceWorker18RunGfxDeviceWorkerEPv+108)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #05 pc 00729390  /data/app/com.EAETeam8.Slimy2-ekOU5lRESGY7OmaMLOu-sg==/lib/arm/libunity.so (_ZN6Thread16RunThreadWrapperEPv+84)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #06 pc 000483ff  /system/lib/libc.so (_ZL15__pthread_startPv+22)
12-07 04:07:58.497 26530 26530 F DEBUG   :     #07 pc 0001b53d  /system/lib/libc.so (__start_thread+32)

**Comment by hkr** [comment]
Which effects are you actually using to get this crash?

**Comment by hkr** [comment]
I was able to reproduce the crash in Unity 2017.3. Probably earlier versions are also affected.
It happens if a compute shader doesn't compile and is later being used, and only if multithreaded-rendering is on (otherwise the error is caught and the compute shader is not dispatched).

Without a fix in Unity the only way to work around this is to remove the compute shader.

It is already fixed in 2018.*
