### ISSUE TITLE
[V2] Shader compiler error on WebGL

### ISSUE THREAD

**Issue by Marbl70** [Unity-Technologies/PostProcessing#386]
This shader causes an error when building for WebGL as a target:
/Assets/PostProcessing/Shaders/Debug/Overlays.shader

Unity 2017.2.0p4, latest v2 post processing stack.

**Comment by Chman** [comment]
What's the error?

**Comment by Marbl70** [comment]
Shader error in 'Hidden/PostProcessing/Debug/Overlays': 'isnan' : no matching overloaded function found; 'any' : cannot resolve function call unambiguously (check parameter types) 'isinf' : no matching overloaded function found; 'any' : cannot resolve function call unambiguously (check parameter types) at line 172 (on gles)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_COLORSPACE_GAMMA

**Comment by Chman** [comment]
Fixed in 0e583be. This commit also makes the `Stop NaN Propagation` option work on WebGL and older mobiles.
