### ISSUE TITLE
[V2]ReflectionTypeLoadException 

### ISSUE THREAD

**Issue by KumoKyaku** [Unity-Technologies/PostProcessing#389]
When add some plugin .dll  in project, lambda throw Excepthons, it isn't work....

(bug version : Post-processing Stack 2.0.0-Beta4 )

![qq 20171208173656](https://user-images.githubusercontent.com/15962980/33759809-98776982-dc3e-11e7-8d22-be9edb03b537.png)

![1](https://user-images.githubusercontent.com/15962980/33759712-46108cc8-dc3e-11e7-9ded-3746831ec7d2.png)
![2](https://user-images.githubusercontent.com/15962980/33759713-4643b6c0-dc3e-11e7-8a2a-526e1c9dc566.png)
![3](https://user-images.githubusercontent.com/15962980/33759714-4677f976-dc3e-11e7-874b-999b6953994d.png)

**Comment by Chman** [comment]
This generally happens when you have a version conflict between dlls. Unity expect .NET 3.5 compatible DLLs by default, if yours was compiled with a newer version it'll fail. Can you try changing `Scripting Runtime Version` to `4.6 (Equivalent)` in Player Settings and see if it works any better?

**Comment by Chman** [comment]
I pushed a fix (ugly hack for now) in a110177. Also fixes an issue with abstract classes.
