### ISSUE TITLE
[v2] Legacy vs SRP fix causing null reference exceptions

### ISSUE THREAD

**Issue by gregharding** [Unity-Technologies/PostProcessing#390]
##### What happened?

In Unity 2017.2.0p4 using the latest commits, in PostProcessLayer.cs there's a legacy vs SRP check that has been moved to OnPreCull(). During builds we are using scene post processing callbacks and OnDisable now has a null reference exception on line 232, causing builds to fail.

`if (!RuntimeUtilities.scriptableRenderPipelineActive)
            {
                m_Camera.RemoveCommandBuffer(CameraEvent.BeforeReflections, m_LegacyCmdBufferBeforeReflections); // line 232, null ref during build`

##### Post-processing stack version (v1, v2)?

v2 (commit [76c0a8f](https://github.com/Unity-Technologies/PostProcessing/commit/76c0a8f3c94b0af5a87737ed68014d3d794d6bea))

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

2017.2.x Editor.

**Comment by Chman** [comment]
Could you test the linked branch/commit? (f3ad0f2)

**Comment by gregharding** [comment]
Thanks. Yep, sure - will remove my quick hack, test and let you know...

**Comment by gregharding** [comment]
Looks good. The commit seems to load and unload scenes in the editor ok, and has no trouble when building and post-processing the scenes.
