### ISSUE TITLE
Backwards compatibility with popular assets

### ISSUE THREAD

**Issue by beardordie** [Unity-Technologies/PostProcessing#395]
Using Unity 2017.2 with PostProcessing v2 Latest commit 1c63912  2 days ago, with Unity asset Aquas 1.4.2, there were several issues with their implementation of PostProcessing which makes it incompatible with PostProcessing v2, mostly in the namespace being UnityEngine.PostProcessing rather than UnityEngine.Rendering.PostProcessing and also several references to items that have been renamed, such as PostProcessingProfile (to PostProcessProfile), and PostProcessingBehaviour (to PostProcessingVolume, I think?)

All that is to say that several assets in the store will need to implement renaming changes to support v2, and I cannot find a document that clearly explains the changes that would need to be made. I did some guesswork, renaming and copying of v1 files into v2 and I was able to get Aquas to run in my game with no Errors, but I don't know if all features carried over.

So, is there an Upgrade Guide for asset authors, or tinkerers who just want third part asset errors/warnings to go away when upgrading to v2?

**Comment by Chman** [comment]
v2 isn't compatible with v1 which is one of the reasons why the namespace and naming scheme is different (so you could theoretically have them both in the same project although it's not recommended but can be helpful if you upgrade your project from v1 to v2).

We don't have any reliable upgrade path from v1 to v2 as they are conceptually quite different (and 2018.1 will make deploying features like post-processing a lot easier for users and more integrated), even the effects themselves have mostly been rewritten and thus settings don't react in the same way.

Right now asset developers can do two things: either test for `UNITY_POST_PROCESSING_STACK_V2` (which is automatically defined if v2 is in the project) or package v1 and v2 specific code in unitypackages and extract one or the other automatically in the project if `PostProcessingProfile` (v1) or `PostProcessProfile` (v2) exists. That's how Cinemachine does it. We do have a much better system coming to handle dependencies, but it'll have to wait for 2018.1+.

Other than that, official documentation is being written for v2 but in the meantime we have [a set of quick guides](https://github.com/Unity-Technologies/PostProcessing/wiki) to help you get started with v2.
