### ISSUE TITLE
[V2] Low framerate

### ISSUE THREAD

**Issue by mikorigames** [Unity-Technologies/PostProcessing#396]
Post Process Layer causes a huge drop of framerate.

**Comment by rikimaru0345** [comment]
Doesn't cause a huge drop for me.
What platform are you running it on?
Did you look into the profiler to see what part exactly causes the slowdown?

**Comment by Chman** [comment]
Unity version? Target platform? Editor or runtime? Effects in use? Unless you provide us with more details we won't be able to help you out.

**Comment by mikorigames** [comment]
Unity 2017.2.1f1, Windows, editor and runtime. If i disable “Post Process Layer” i gain 20-25 fps. Even if i select “Trigger: none” “Layer: nothing” “No-Antialiasing” or disabling “Post Process Volume”, the frame drop is the same. Only disabling the Post Process Layer give me those 20-25 fps more. In the Profile i can see that the cause is “Camera.Render - Culling - PostProcessLayer.OnPreCull() - PostProcessLayer.BuildCommandBuffers() - PostProcessLayer.UpdateSettingsIfNeeded() - etc.

**Comment by Chman** [comment]
What's the target platform? Windows desktop? On what GPU? Also, 20-25fps doesn't mean much as a performance metric as it doesn't scale linearly (20fps starting from 400 or starting from 30 isn't the same... Use millisecond).

**Comment by mikorigames** [comment]
Windows desktop, Nvidia 1080 and Ati 7900. I have almost 100 fps (nvidia 1080) with Post Process Layer disabled and 80 fps with PPL activated.

**Comment by mikorigames** [comment]
adding to the previous post:
9 ms without PPL
13 ms with PPL

**Comment by Chman** [comment]
9ms without PPL / 13ms with PPL... That's 4ms. 100 fps to 80 fps is 2.5ms. So these ms timings are taken on an Radeon7900?

So if I understand correctly, with no effect, no antialiasing, just a post-process layer enabled on your camera you're seeing a 2.5ms cost for a single blit on a 1080? Unless you're rendering at 16K or something I don't see how it's possible. I'm seeing sub-0.5ms empty PPL here on a 980 @1440p.

**Comment by mikorigames** [comment]
Yes exactly. I don’t know why the PPL has that cost in ms with no effect activated.

**Comment by mikorigames** [comment]
Do you need a screenshot?

**Comment by Chman** [comment]
Sure, add one of the profiler too if you can. What's the screen resolution you're rendering your game at?

**Comment by mikorigames** [comment]
Nvidia 1080

[https://www.dropbox.com/s/gp2b8x79ipjkvzd/Immagine1.jpg?dl=0](url)
[https://www.dropbox.com/s/438emy2f8nig4pa/Immagine2.jpg?dl=0](url)

**Comment by Chman** [comment]
These are CPU profiling screenshots and are not related to your GPU. In any case, I pushed some CPU optimizations recently (and a bigger one today), could you try again using the latest revision?

**Comment by oultrox** [comment]
Just tested here and I'm not seeing a noticeable FPS drop with/without PP. (Even with Motion blur - Bloom - Chromatic aberration - Color Grading - vignette). 

_Nvidia GTX 960M
8 GB RAM
intel i7-7600HQ._

**Comment by mikorigames** [comment]
Just tested the last version....now the color grading effect makes all black and white. PostProcessLayer.OnPreCull() cost 1.5 ms

**Comment by Chman** [comment]
> now the color grading effect makes all black and white if i select "high definition" and all black if i select "low definition"

This doesn't reproduce for me, color grading still works fine in both modes. Can you send me a repro-project I can look at?

**Comment by slime73** [comment]
Deep profiling mode does not give accurate or reliable results for CPU function call times.

From Unity's manual:

> Note that Deep Profiling incurs a very large overhead and uses a lot of memory, and as a result your game will run significantly slower while profiling.

**Comment by mikorigames** [comment]
Ok, disabling Deep Profiling the PPL costs only 0.22, so there is a false framerate drop. Thanks

**Comment by zinkins** [comment]
> Just tested the last version....now the color grading effect makes all black and white if i select "high definition" and all black if i select "low definition".

I got the same on the latest commit after script update. Found that **ReplaceData** in the **PostProcessManager** causes it. Tried to reimport all, changing the color space, nothing works. 
Using Unity 2017.2.0f3 on win7-64

**Comment by Chman** [comment]
Yeah I _just_ noticed the same thing in a test scene, for some reason it didn't happen before. I'll look into it asap.

**Comment by Chman** [comment]
Ok it should be fixed in the latest commit.

**Comment by zinkins** [comment]
yes, it works, thanks!

**Comment by mikorigames** [comment]
It works and the framerate is higher now
