### ISSUE TITLE
Motion Blur won't work for me, everything else seems fine.

### ISSUE THREAD

**Issue by teichhorst** [Unity-Technologies/PostProcessing#398]
I can't get motion blur to work.  Are there any kind of settings that need to turned on or off for this?

Right now I'm running Color grading, motion blur, AO and bloom.  No matter what settings I use for motion blur, there is no effect.

using 2017.2.0f3, forward rendering, HDR, MSAA, Single camera setup and just pulled the stack again today with no change.  Thanks!  Awesome stuff so far.

**Comment by Chman** [comment]
What's the target platform? What are your motion blur settings?

Motion blur only works in the game view while in play mode. It doesn't support VR (in case you're using VR) and won't work on most mobile platforms (lack of motion vectors support).

**Comment by teichhorst** [comment]
Target platform is Windows, I have tried various motion blur settings.  Our game is both VR and non-VR, could that be the problem somehow?  I definitely don't want it to work in VR, but it would be great if it worked when VR isn't initialized.  Motion blur worked well for us in V1 of the post processing stack.

**Comment by teichhorst** [comment]
Got it to work by checking for VR through one of our game controller scripts.  Works well!
