### ISSUE TITLE
Unity PP-Stack ||  Graphics does not contain a definition for Blit / DrawTexture

### ISSUE THREAD

**Issue by NAWTom** [Unity-Technologies/PostProcessing#400]
When importing Unitys Post-Processing-Stack I immediatly get a few errors saying: "Graphics doesnt contain a definition for Blit." I have seen a lot of people having the same problem and I have already searched a custom Graphic class in my project. I didn`t find one so I was wondering what the problem is.

System: Windows 10 64Bit; Unity 5 2017.2

Edit: To the Moderators: After the first guy will reply me to search more please dont close this issue. I have searched everywhere and everything.

**Comment by Chman** [comment]
What version of the post-processing stack? v1 or v2?

In any case, `Graphics` is a [standard Unity class](https://docs.unity3d.com/ScriptReference/Graphics.html). The error you're getting clearly indicates that you have a conflict somewhere, and there isn't much we can do to help you out unless you send your project over.

So... I'm sorry to say that you do have to keep searching for a custom Graphics class in the global namespace (it could come from your project or an asset from the store, maybe even from a pre-compiled asset DLL).

**Comment by NAWTom** [comment]
Thanks for your help but I already fixed it. Since I could not find a graphics class I changed "Graphics.Blit" to "UnityEngine.Graphics.Blit"  in the Post-Processing scripts . I know that this would say that there has to be a custom Graphics class but there is no.
