### ISSUE TITLE
[V2] Post Processing not working at all after Disabling and re enabling camera GameObject

### ISSUE THREAD

**Issue by nicobella** [Unity-Technologies/PostProcessing#402]
this happens in one of the latest commits, I think I dowloaded from github [this](https://github.com/Unity-Technologies/PostProcessing/commit/9280902f5776feafcc8b5b797d874cbd818abc2e) commit.

when I disable any of the cameras that should use the Stack (the camera has a PostProcessLayer component and a PostProcessVolume component with a profile assigned, camera object is set to a specific layer that is the same as the PostProcessLayer set under Volume Blending.

if I disable the camera gameobject I can see how the 4 command buffers in the camera inspector are gone, but then when I enable the GO again they are not created back, so I guess the issue comes from there probably.

NOTE: if I remove the post process layer component from the camera and add it again, the command buffers get created.

**BEFORE DISABLING GAME OBJECT**
![before](https://user-images.githubusercontent.com/4840513/34179213-cc2fe0a8-e4e8-11e7-9716-7662de70914b.jpg)

**AFTER DISABLING AND RE ENABLING GAME OBJECT**
![after](https://user-images.githubusercontent.com/4840513/34179240-e0657c0e-e4e8-11e7-9e29-cd94e8a417df.jpg)

**Comment by Chman** [comment]
Fixed in the linked commit.
