### ISSUE TITLE
[V2] HDR Color Grading does not work in OpenGL Core (4.5)

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#404]
If the HDR Grading effect is present on any active volume / profile in the scene, the screen will render all grey. Tested with latest commit: 7cb1b88d4f59d057fd31a45501af5edc908fbd97

**Comment by Chman** [comment]
Fix in 36c8a82. It's not a proper fix but until I can get the time to fully track down the reason it's failing this will do the trick (after a quick peek in RenderDoc it seems like something's off in the GLCore version of the grading compute shader, so for now it'll fall back to the non-compute version).
