### ISSUE TITLE
[V2] GC allocations on PreCull()

### ISSUE THREAD

**Issue by oultrox** [Unity-Technologies/PostProcessing#406]
## Hello there! 

First of all I'm really thankful that this post-processing stack exist! is really awesome and the stack v2 seems to be really comfortable and optimal to work with.

But I did notice something with my profiler, the `OnPreCull()` method is generating some garbage (even without a `Post-Process Volume` attached.)

![gc_2](https://user-images.githubusercontent.com/10330846/34273100-bae75f62-e671-11e7-81e2-627290fefe1d.png)

![gc_1](https://user-images.githubusercontent.com/10330846/34273076-a87614e0-e671-11e7-932d-f7f3783b43eb.png)

I also tried in a empty scene, just attaching a `post-process layer`, creating a layer for the post-processing and that's it I believe.

Doing some tests I figured out that the method that is generating garbage per frame is `BuildCommandBuffers()`

I don't experience this issue in V1 as well. My suspect is that is getting some components every frame (I have 0 knowledge about this subject tho.) and that's causing allocations, perhaps some caching if it's doable?

Thanks again and hope we can sort this out.

**Comment by apkd** [comment]
Hey, it happens that I just started a pull request that fixes a GC issue. I think that might be it, but feel free to check. By the way, the Deep Profile feature really helps in nailing the source of problems with GC.

https://github.com/Unity-Technologies/PostProcessing/pull/407

**Comment by oultrox** [comment]
@apkd  You're right, forgot to share/use it here.
![image](https://user-images.githubusercontent.com/10330846/34297938-cf2a19f0-e6f9-11e7-9eb1-3ee8a2b3898a.png).

Checking your PR then! I'll let you know if I find any issue or if the allocation  is no longer generating here in my end.

**Comment by oultrox** [comment]
Just noticed that in the latest version (without your PR) I'm not getting any GC allocation. can you confirm @apkd ?

**Comment by apkd** [comment]
You're right - it looks like they've already fixed this issue in commit https://github.com/Unity-Technologies/PostProcessing/commit/4b7975c6e976e797596f948f702b589df56dd81e and my PR was totally unnecessary. My bad for not staying up to date.

**Comment by oultrox** [comment]
Alright then, thank you for letting me know! 
Closing up.
