### ISSUE TITLE
Cant import .cube file, wrong table size

### ISSUE THREAD

**Issue by zerocold64** [Unity-Technologies/PostProcessing#408]
I get this when i try to import my lut, made with photoshop:
Invalid data on line 8
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr).
Wrong table size - Expected 35937 elements, got 0
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets(String[], String[], String[], String[], String[])
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr).

**Comment by zerocold64** [comment]
Well i resolved it. It seems that .Net 4.6(Experimental)'s TryParse works in other way(or doesn't work at all). I just downgraded scripting API in unity to .Net 3.5 and it worked for me.

**Comment by Chman** [comment]
Any chance you could post the "broken" .CUBE file so I can take a peek?
