### ISSUE TITLE
[V2] Blank screen on Mali-T720 and PowerVR G6430 GPUs

### ISSUE THREAD

**Issue by ANTONBORODA** [Unity-Technologies/PostProcessing#410]
Hello,
I've ran into a problem with Post Processing stack v2.
Whenever I try to add color grading effect to a stack, I get a blank screen. This affects Mali-T720 and PowerVR G6430. There are probably other devices affected by this, but I don't have much hardware to test it.
Setup is basic, linear light, HDR is enabled both in Graphics and in Camera.
HDR mode is R11G11B10. Using FP16 leads to the same result.
I've hosted a sample project to reproduce here: https://we.tl/WSyXTBGF8o

**Comment by hkr** [comment]
Thanks for the repro project, I have been able to reproduce this.
I pushed a workaround to f537ac4.

**Comment by Chman** [comment]
Note: that fix has been merged into the main branch.
