### ISSUE TITLE
Subpixel Morphological Antialiasing = "mad" no matching overloaded function found

### ISSUE THREAD

**Issue by AugustDG** [Unity-Technologies/PostProcessing#411]
![image](https://user-images.githubusercontent.com/33916325/34469985-32443ac6-eef6-11e7-9895-1e79153a7ed0.png)

41 errors concerning this specific shader and this specific function. Only happens when any type of AA is applied on the post process layer.

**Comment by Chman** [comment]
Fixed in d6acfed.
