### ISSUE TITLE
[V1] The Stack eats up 30ms of the CPU on Nvidia Shield (Tegra X1)

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/PostProcessing#415]
We found out that that Stack was responsible for the low FPS we have on the Nvidia Shield. 

At first we noticed that both the CPU and GPU appeared to be at 30+ FPS, but the game was only running at ~22. After further investigation, the low FPS was due to the Render Thread taking 30 to 40ms to compute.

We then deactivated Multithreaded Rendering, and it revealed a whooping 20 to 30ms being taken by the Stack alone. We currently use Eye Adaptation, Bloom and Anti-aliasing.

Is there anything we should know about the stack to optimize its CPU footprint? For now we'd be better stripping it out and replacing it with individual effects (that would save us 10ms+).

Cheers!

**Comment by AlexandreFiset** [comment]
Looks like the culprit is EyeAdaptation. How could that eat up this much of the CPU? 

Will try to achieve that through another script outside the stack.

**Comment by Chman** [comment]
[This line](https://github.com/Unity-Technologies/PostProcessing/blob/v1/PostProcessing/Runtime/Components/EyeAdaptationComponent.cs#L109) is most likely the culprit, it can be quite slow depending on the architecture. This has been changed in v2 but unfortunately I don't have the time to backport it to v1 right now. I'm curious, is there any reason why you're working with v1 instead of v2?

**Comment by AlexandreFiset** [comment]
Well we have two projects running; one on 2017.3 with Stack v2 scheduled for 2019, and another on 5.6.3 with Stack v1 released a year ago with 90K+owners. The oldest one is quite complex and runs on PC, Mac, Linux, Xbox One, PS4, Switch and VR. Moving from Stack v1 to v2 would require weeks of testing and rewiring stuff. Anyway, we'll use Beautify on Android for now as it saves us 20ms on the CPU.

**Comment by Chman** [comment]
Should be fixed in 10ef870.
