### ISSUE TITLE
[V1} Build Failed. Unity 2017.3

### ISSUE THREAD

**Issue by justinwasilenko** [Unity-Technologies/PostProcessing#418]
When trying to build with Unity 2017.3p1 I get the following build errors:
*VR enabled, Single Pass Instance rendering,

`Shader error in 'Hidden/Post FX/Fog': undeclared identifier 'sampler_CameraDepthTexture' at line 63 (on d3d11)
Shader error in 'Hidden/Post FX/Screen Space Reflection': undeclared identifier 'sampler_CameraDepthTexture' at line 129 (on d3d11)
Shader error in 'Hidden/Post FX/Motion Blur': undeclared identifier 'sampler_CameraDepthTexture' at Assets/PostProcessing/Resources/Shaders/MotionBlur.cginc(90) (on d3d11)
Shader error in 'Hidden/Post FX/Builtin Debug Views': undeclared identifier 'sampler_CameraDepthTexture' at line 31 (on d3d11)
Shader error in 'Hidden/Post FX/Uber Shader': undeclared identifier 'sampler_CameraDepthTexture' at line 191 (on d3d11)
Shader error in 'Hidden/Post FX/Ambient Occlusion': undeclared identifier 'sampler_CameraDepthTexture' at Assets/PostProcessing/Resources/Shaders/AmbientOcclusion.cginc(107) (on d3d11)
Shader error in 'Hidden/Post FX/Ambient Occlusion': undeclared identifier 'sampler_CameraDepthTexture' at Assets/PostProcessing/Resources/Shaders/AmbientOcclusion.cginc(312) (on d3d11)
Shader error in 'Hidden/Post FX/Temporal Anti-aliasing': undeclared identifier 'sampler_CameraDepthTexture' at Assets/PostProcessing/Resources/Shaders/TAA.cginc(70) (on d3d11)
`

**Comment by OneOfHaze** [comment]
I had the same errors when using the Single Pass _Instance_ rendering method. Changing it to Single Pass solved the problem.

**Comment by AaronVictoria** [comment]
I'm having this same issue in 3 projects I work on, One uses the initial 2017.3 release. The others both use 2017.3.0p3. What's more interesting is that I resolved the issue in the patch 3 projects by simply installing and leaving the folder in the Assets/ directory. That did not work in the case of the project using the initial 2017.3 release.

Just thought I'd share that.

**Comment by Chman** [comment]
Single Pass Instanced rendering isn't currently supported. There are plans to support it on v2 but not on v1 at this point.

**Comment by timendez** [comment]
@Chman what is the difference between Single Pass Instanced rendering and Single Pass rendering? I only see the option for Multi Pass rendering (which breaks Google VR stuff for me), and Single Pass (which causes this error). Can I not use post processing with Single Pass rendering in conjunction with VR?

**Comment by timendez** [comment]
I was able to get it to compile the shaders in Single Pass rendering mode by following the advice here: https://answers.unity.com/questions/1348919/bug-cant-use-postprocessing-with-single-pass-stere.html

In case that's unclear, in all shaders that it shows an error for: manually go into the shader file, or .cginc file, and replace `sampler2D_float _CameraDepthTexture;` with `UNITY_DECLARE_DEPTH_TEXTURE(_CameraDepthTexture);`
