### ISSUE TITLE
[V2] MSVAO with Single Pass is shifted in scene view

### ISSUE THREAD

**Issue by soraryu** [Unity-Technologies/PostProcessing#420]
In edit mode, everything looks alright; when going into Play mode (and thus the SteamVR camera being activated), it looks wrong in Scene View:

![msvo_bug_sceneview](https://user-images.githubusercontent.com/2693840/35007654-a6186642-fafa-11e7-9dbc-a5e8e4629a5b.PNG)
(the black stuff on the right is the AO pass with very high intensity to demonstrate the effect)

When moving the scene view around, it seems that the double-wide rendering for Single Pass is somehow also active in the scene view and thus the AO pass is double-wide and doesn't match.

**Comment by robbiesri** [comment]
When I was working on adding additional XR support to the stack, MSVAO appeared in the middle of my dev cycle, and I didn't have time to go over the implementation.

I'm supposed to pop in again to do some work for Single-pass Instancing.  If I have a bit of time, I'll try to take a look at the MSVAO implementation, but I'm afraid I likely won't have time.

**Comment by Chman** [comment]
Merging this issue with #370 as the source issue & fix are related.
