### ISSUE TITLE
[V2] [BUG] [MOBILE] Fail to build on Android when using FXAA

### ISSUE THREAD

**Issue by positlabs** [Unity-Technologies/PostProcessing#422]
Build fails with errors in the console when I try using FXAA on Android. Strangely, I'm seeing errors that point to SMAA.

> Shader error in 'Hidden/PostProcessing/SubpixelMorphologicalAntialiasing': 'mad' : no matching overloaded function found at Assets/PostProcessing/Shaders/Builtins/SubpixelMorphologicalAntialiasing.hlsl(1210) (on gles)
> 
> Compiling Vertex program
> Platform defines: UNITY_NO_DXT5nm UNITY_NO_RGBM UNITY_ENABLE_REFLECTION_BUFFERS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_NO_CUBEMAP_ARRAY UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 SHADER_API_MOBILE UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_LIGHTMAP_DLDR_ENCODING

Building for Pixel, running Android 8.1. Min API 24, target 25.

**Comment by robbiesri** [comment]
I think @chman just fixed this with d6acfed.  It came up as part of Issue #411 as well.  Have you pulled this changeset?

**Comment by positlabs** [comment]
That did it! Thanks!
