### ISSUE TITLE
post exposure Override has no effect

### ISSUE THREAD

**Issue by shaderbytes** [Unity-Technologies/PostProcessing#429]
I followed the tutorials and using the : \\ m_Volume = PostProcessManager.instance.QuickVolume(LayerMask.NameToLayer("pp_volume_2"), 100f, settings);

one of the settings is color grading, im setting this via a menu action : 

var s = PostProcessController.instance.colorGradingModel;
 s.postExposure = new FloatParameter { value = val };
Debug.Log("s_ColorGrading.postExposure " + s.postExposure.value);
s is just a returned pointer to the color grading object i created using ScriptableObject  as per your Vignette example..

in the console i can see it is indeed setting the value on this object, but nothing is changing visually??  

What am i doing wrong here

**Comment by Chman** [comment]
> ```
> s.postExposure = new FloatParameter { value = val };
> ```

That's not what the [tutorial](https://github.com/Unity-Technologies/PostProcessing/wiki/%28v2%29-Scripting-the-stack) says. No need to create a new `FloatParameter` when one already exists. And when you create a new `ParameterOverride` its `override` field is set to false by default.

Use:

```
s.postExposure.Override(val);
```

Or:

```
s.postExposure.value = val;
s.postExposure.overrideState = true;
```
