### ISSUE TITLE
Commit "NaN obliteration - Switch compatible" breaks D3DX9

### ISSUE THREAD

**Issue by GuidC0DE** [Unity-Technologies/PostProcessing#432]
Commit [910a744d9b1758bf72251251e4234ceb066ec227](https://github.com/Unity-Technologies/PostProcessing/commit/910a744d9b1758bf72251251e4234ceb066ec227) on v1 breaks D3DX9 build because of missing asuint().

**Comment by Chman** [comment]
Fixed in 56dd8cd.
