### ISSUE TITLE
[V2] Excluding a camera render from the PostProcessing

### ISSUE THREAD

**Issue by oultrox** [Unity-Technologies/PostProcessing#434]
### Hello there!

Hope somebody could help out with this issue: We have a dynamic minimap, showing the locations of the rooms procedurally generated.

This is utilized by a second camera which is orthographic and looks at the scene from above (Everything it's 2D anyway).

In the minimap, I don't want to see the post-process global volumes, say vignette for an example. Is there a way to avoid this? I tried setting the camera in different post-process layers but no luck. 

![image](https://user-images.githubusercontent.com/10330846/35337326-9e833cea-00f9-11e8-86bc-873a05d9aead.png)
_The red thingie is the render texture of the minimap used by another camera that doesn't have any post-process global volume attached._

I've read something like this before but I'm not sure if there's a better, optimized way: https://gamedev.stackexchange.com/questions/138311/how-do-i-disable-fog-on-specific-camera-s

Thanks in advance!

**Comment by Chman** [comment]
To do that you need a multi-camera setup. Let say you have two cameras, A and B. The setup would be the following:

- Camera A
  - `Depth` set to 0
  - Has a `Post Process Layer` component
  - Renders the game without the minimap (not sure how your minimap is rendered but the standard layer system can help in this case)
- Camera B
  - `Depth` set to 1
  - No `Post Process Layer` component
  - Only renders the minimap (same as before, layer system can help)

And that will do it, post-processing will only be applied to Camera A and Camera B will be rendered on top of it. If you're having trouble I should be able to find some time to setup a quick project to show it off.

**Comment by oultrox** [comment]
Hello Thomas,

Thanks for the super quick response! 

Just tested what you've mentioned and **it works properly** IF I'm not using a render texture since the render texture needs to be rendered in the MainCamera (Camera A), so I think there's no way out in that case. I'm going to modify the logic of my minimap in order to avoid a quad that actually will be rendered in the main camera. 

![image](https://user-images.githubusercontent.com/10330846/35401279-d1e2f3f8-01d7-11e8-82a6-a931c974b484.png)
_Two cameras without a render texture._

Unless you have another idea regards rendering with that system? I'll let you here a Dropbox of my tests if you're willing to take a look!
https://www.dropbox.com/s/kx87qb2rtsw17i2/CamMapTest.zip?dl=0

**Comment by Chman** [comment]
That's one of the best way to do it without having to setup a render loop & rendering each camera yourself.

As for the render texture being rendered in Camera A, rendering it in a quad on Camera B should do the trick (unless I misunderstood you)!

An other good and even easier solution would be to use your minimap render texture as a texture input for a UI Image object with your Canvas `Render Mode` set to `Screen Space - Overlay`. That way you won't need the dual camera setup and your minimap will just be a UI element on top of everything.

**Comment by oultrox** [comment]
Oh I was thinking about that, tho I'll still need the Camera, since the map sprites are generated in the game plane and not in UI stuff. That's why it's on discussion but for now the technique shown in the scene `TestCameraLayers` is the one that Implemented just now.

![image](https://user-images.githubusercontent.com/10330846/35402407-4450b940-01db-11e8-87b4-8bd7b0e07906.png)
it's working flawlessly. You can see the second camera B rendering the proper stuff and Camera A just rendering the game itself. 

Thank you again!

**Comment by oultrox** [comment]
Closing up. We're good :)
