### ISSUE TITLE
Post Processing Bloom + TextMeshPro = NaN pixels and artifacts

### ISSUE THREAD

**Issue by khalv** [Unity-Technologies/PostProcessing#437]
So, i saw an issue earlier stating that NaN values will cause the bloom effect to go haywire and produce a massive white blob surrounding any pixels with NaN values, and as a result to this, the "stop NaN propagation" flag was added. Despite this, using the Beta5 release, i still get the same artifact from NaN values. These are caused when viewing TextMeshPro texts from oblique angles, and you can clearly see the black pixels. 

![bloom](https://user-images.githubusercontent.com/16840336/35432642-f7ce6490-0280-11e8-88ed-d93078aeb384.jpg)

**Comment by Chman** [comment]
Could you check if the latest commit did anything? We had an issue with the NaN checker and I pushed a fix yesterday.

**Comment by khalv** [comment]
Still happens, unfortunately :(

**Comment by khalv** [comment]
Latest commit solved this, thanks.
