### ISSUE TITLE
[V2] ColorGrading turns Editor screen to gray when using OpenGLES3 on Windows.

### ISSUE THREAD

**Issue by KelSolaar** [Unity-Technologies/PostProcessing#439]
Hi,

A picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/99779/35536157-e999782e-05aa-11e8-875b-68c16a65f153.png)

![image](https://user-images.githubusercontent.com/99779/35536271-4346cdd6-05ab-11e8-9ffb-cb3b0811f4d3.png)

The following warning is being emitted: 

```
Shader warning in 'MultiScaleVODownsample1.compute': Buffer count exceeding default GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS. Shader might not work on all hw. Consider combining separate buffers into one containing struct elements. at kernel main (on gles3)
```

Cheers,

Thomas

**Comment by KelSolaar** [comment]
I should have precised that I'm using https://github.com/Unity-Technologies/PostProcessing/tree/2.0.0-b5.

@hkr: I will try with the commit you are referring to.

I'm confirming that using `Low Definition Range` fixes the issue.

**Comment by KelSolaar** [comment]
@hkr: So using f537ac4e34030f9da4c7a4c31b95cd245194c160, the editor is not gray anymore but I have now a weird offset color offset/clamp which I have seen on some devices and could be the same issue or related to #442.

**Color Grading On**

![image](https://user-images.githubusercontent.com/99779/35593534-05155d64-0675-11e8-8eca-c364b4d634c8.png)

**Color Grading Off**

![image](https://user-images.githubusercontent.com/99779/35593389-ab297268-0674-11e8-8327-08f3d2fb3ae2.png)

**Comment by hkr** [comment]
Thanks for the detailed report.

I just pushed bb31daf that disables the compute/3D texture code path for OpenGL ES 3.0 in ColorGrading.
