### ISSUE TITLE
[V2] ACES and natural Tonemapping mode does not distance blend gracefully 

### ISSUE THREAD

**Issue by bjporter** [Unity-Technologies/PostProcessing#444]
Both ACES and natural Tonemapping are abrupt, and not usable as a volume, unless there's a use case of an instant tone change. Would be nice to be able to mix into the tonemapping mode as well.

**Comment by Chman** [comment]
You're not supposed to blend them. Generally you"ll want to choose one as a color grading base and stick with it. The change is abrupt because it's not possible to lerp between different tonemap operators efficiently (especially ones as complex as ACES).
