### ISSUE TITLE
The type Bloom does not contain definition. 

### ISSUE THREAD

**Issue by MaciekBugajski** [Unity-Technologies/PostProcessing#445]
I've tried installing PP in my new project started in Unity 2017.2.0f3 and it doesnt work. Ive tried adding the catalogue as new catalogue in assets, ive tried replacing old postproces stack in different ways, it didnt worked. screencapture with console window in link
[https://drive.google.com/file/d/1eatIe694joLpCr7JzGHugvYTk6luKkrf/view?usp=sharing](url)

**Comment by Chman** [comment]
You have another "Bloom" script in your project in the global namespace. That's why it's failing. Either you need to remove it or namespace it properly.
