### ISSUE TITLE
[v1]SSR with occlusion culling sometimes trows up too many errors and crashes window

### ISSUE THREAD

**Issue by Mrunpredictable** [Unity-Technologies/PostProcessing#446]
#####SSR with occlusion culling sometimes trows up too many errors and crashes window

**Comment by Chman** [comment]
Can you post the actual errors?

**Comment by Mrunpredictable** [comment]
odd thing is that whenever that bug happens my debug window stops responding

**Comment by Chman** [comment]
The suspicious thing about this is that Occlusion Culling doesn't have anything to do (in _any_ way) with post-processing or SSR... It's completely separated (like audio vs physics). My guess is this is a weird occlusion bug in 2018.1b4 that, in your specific case, happens to break rendering in some way in the post-processing chain. And SSR being the first effect to kick in the stack (assuming you have AO/Ambient-only disabled) it's the one that looks impacted :/

I'll ask around but considering how odd this is and how setup dependent this probably is, I'll probably need a repro-project to investigate.

**Comment by Chman** [comment]
Also, seeing as you're running 2018.1beta, have you tried v2/ssr instead of v1/ssr?
When running on the latest versions of Unity we recommend people to switch to v2 as v1 is moving to maintenance mode.

**Comment by Mrunpredictable** [comment]
will try v2 to see if this bug is caused again

 I switched back to v1 because of issues i was facing in v2

**Comment by Chman** [comment]
Closing as it works in v2 and we don't intend to support v1 in 2018.1.
