### ISSUE TITLE
[V2] Attempting to JIT compile method...

### ISSUE THREAD

**Issue by LoBlanc** [Unity-Technologies/PostProcessing#447]
##### What happened?
(Filename: (PARENT FOLDERS REMOVED)/PostProcessing-2/PostProcessing/Runtime/Utils/TextureFormatUtilities.cs Line: 77)
ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-managed) UnityEngine.RenderTextureFormat[]:System.Collections.Generic.IEnumerable`1.GetEnumerator ()' while running with --aot-only.
##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity3D 2017.2.1p2, Windows 10, Target Platform: XBoxOne

**Comment by Chman** [comment]
Hi, can you try the latest commit? I can't run on Xbox One right now so I couldn't test this potential "fix" but according to the manual you're getting this error because it can't properly infer the enumeration type by itself so forcing it "should be enough".

**Comment by LoBlanc** [comment]
Hi, this bug is still happening to me on the latest commit
