### ISSUE TITLE
[V2] Using hdr with bloom effect makes flickering white squares appear

### ISSUE THREAD

**Issue by mmalek06** [Unity-Technologies/PostProcessing#448]
What happened:

The title says it all - I'm not able to use HDR and Bloom effects together. Lowering bloom intensity only makes the squares smaller, but they are still there. Also - depending on the quality settings, the white squares stay visible after the camera has stopped moving (when using high quality settings) or they disappear after the movement has stopped (lower qs).
And yes - stop nan propagation checkbox is checked.

Post-processing stack version: v2

Unity version: Unity 2018.1.0b4 (64-bit) (but it's happening even under the last stable version)
Operating system: Windows 10
Target platform: standalone windows

I'm attaching a screenshot of this happening:

![bez tytulu](https://user-images.githubusercontent.com/12412949/35766265-482fcd84-08d5-11e8-8def-0ffa2788aeb7.png)

**Comment by Mrunpredictable** [comment]
did you download latest stack v2?

**Comment by mmalek06** [comment]
Yes, I've just pulled from github v2 branch, so I guess I have the most up to date version.

**Comment by Mrunpredictable** [comment]
I meant #440

**Comment by khalv** [comment]
I can confirm that this still happens as of the most recent version (pulled last friday). You can actually "paint" the screen black with NaN pixels when you have the bloom effect active.

**Comment by Chman** [comment]
Related to #337 (not exactly a duplicate but it's the same issue).
