### ISSUE TITLE
[v2] Strange black ooze overtaking everything when using black skybox

### ISSUE THREAD

**Issue by TheRealCatherine** [Unity-Technologies/PostProcessing#449]
While upgrading my Post Processing Stack from v1 to v2 (still in progress, right now both are present but v1 only still used for Motion Vector debug view) I noticed that when setting a black (or I think any solid color) skybox a creeping black ooze seems to overtake everything in the scene. It doesn't happen with normal skyboxes, only with solid colors. This is (AFAIK) something new and was not present when using v1.

**UPDATE** It seems directly related to the Temporal Anti-Aliasing in the PostProcessLayer script set on the main camera. Choosing another Anti-aliasing type makes it go away.

Here is a video showing the issue and how to reproduce it in the project (works in Editor or Standalone build): https://www.youtube.com/watch?v=ArKCiR9jZeE

Project source code: https://github.com/TheRealCatherine/StageMechanic
(relatively small as far as real world in-progress projects go, and only 1 scene with a handful of objects at start, 1 camera, 2 lights, and very simple default global effects processing)

Current revision: 31d0a21281f284099a84a853be050860ef860253 (first revision where issue was noticed, also the revision where v2 was added)

The stage file loaded in the demo video can be obtained here: https://raw.githubusercontent.com/TheRealCatherine/StageMechanic/master/StageMechanic/Stages/Testing/Cathy1/Easy/1-1.json

Relevant scene objects:
StageView/GlobalEffects/Main Stage Post Processing Volume
StageView/Main Camera
Stage View/Managers/Visual Managers

Relevant scripts:
Assets/Managers/VisualEffectsManager

Relevant assets:
Assets/3rd Party/Skyboxes/Black
Assets/PostProcessing-2/Profiles/Global Post Processing Volume Profile
Assets/PostProcessing/Nothing
Assets/PostProcessing/Motion Debug

As a side note - its actually kind of a cool effect that would make for a neat game mechanic! So maybe you can fix it but also make it a feature ;-) <3 <3 <3

##### Post-processing stack version (v1, v2)?

v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

2018 beta 4, Windows 10 Standalone and in Unity Editor

**Comment by TheRealCatherine** [comment]
Some images of Inspector settings that might or might not be helpful

![image](https://user-images.githubusercontent.com/31754592/35774656-942ab3c8-093b-11e8-860b-62b4c61ad07c.png)

![image](https://user-images.githubusercontent.com/31754592/35774662-b26b476c-093b-11e8-93e5-08b0c3b937bf.png)

![image](https://user-images.githubusercontent.com/31754592/35774668-c1f15500-093b-11e8-8fe6-0103ac5aa1c2.png)

![image](https://user-images.githubusercontent.com/31754592/35774670-cdf41d7e-093b-11e8-83b3-b167d75aacec.png)

![image](https://user-images.githubusercontent.com/31754592/35774680-ee4bf754-093b-11e8-86cd-4dbb9074bca8.png)

![image](https://user-images.githubusercontent.com/31754592/35774685-0c40f39a-093c-11e8-9d9c-67e438e9f8a7.png)

![image](https://user-images.githubusercontent.com/31754592/35774687-2e78c8e8-093c-11e8-8040-0dd942f5da91.png)

**Comment by TheRealCatherine** [comment]
**UPDATE** It seems directly related to the Temporal Anti-Aliasing in the PostProcessLayer script set on the main camera. Choosing another Anti-aliasing type makes it go away.

**Comment by woistjadefox** [comment]
This issue is already reported:
https://github.com/Unity-Technologies/PostProcessing/issues/337

**Comment by Chman** [comment]
Thanks for the project, I was (finally) able to reproduce this.

The good news is, using the latest commit (b40105b) the NaN killer will work properly and avoid any kind of "TAA goo spread".

The bad news is, this isn't TAA-related, the "black spreading goo" is a side-effect of TAA being a temporal effect. The problem lies deeper, in your case I was able to track it down to the ProceduralSky shader when MSAA is enabled. A RenderDoc capture confirms this, NaNs are created by the skybox pass at the horizon on one of MSAA's subsample buffer when Atmospheric Thickness is set to 0 (and then spread out by TAA). That's not fixable in Post-processing (although the Stop NaN Propagation option will now work correctly using the latest commit), I'll make a smaller repro case and open an internal ticket.

**Comment by woistjadefox** [comment]
@Chman oh cool, thanks for the fix! Just to clarify, if we don't enable MSAA the fix should work, right?

**Comment by Chman** [comment]
The fix should work regardless, NaNs should be stopped before post-processing kicks in (assuming you have `Stop NaN Propagation` enabled). They'll still be here before post-processing but won't affect bloom, TAA etc anymore.

**Comment by woistjadefox** [comment]
Nice, works like a charm! Stopped the black spreading goo in our case, thanks!

**Comment by TheRealCatherine** [comment]
return (x < 0.0 || x > 0.0 || x == 0.0) ? false : true;

is interesting looking code, I would have thought if(x == float.NaN) would work :-O 
testing the fix now...

**Comment by TheRealCatherine** [comment]
Can confirm that it is now fixed for our use case! <3

Fix applied to our project in revision https://github.com/TheRealCatherine/StageMechanic/commit/66e3b50c747f284507ab2e5701c8aaa1025d7551

**Comment by Chman** [comment]
This is hlsl, there's no `float.NaN` you're thinking about C# :)

The reason we test NaNs this way in HLSL is because:

- The `isnan` intrinsic isn't available on all platforms.
- `isnan` calls are skipped by our shader compiler on some platforms that support it (like DX11 because we don't toggle `/Gic` on FXC).

Finally, these three tests could be reduced to only two (`return (x <= 0.0 || x >= 0.0)`) but it just didn't work for some reasons (it would let NaNs through).

**Comment by Chman** [comment]
Also bear in mind that although this stops NaNs from creeping up with TAA, it doesn't remove them. Your skybox has an atmospheric thickness of 0 which is creating a thin NaN line at the horizon.

**Comment by TheRealCatherine** [comment]
Oh duh of course I didn't even look at what kind of code it was haha. That's interesting about isnan and good to know!

Going by the top of my head in the original code it wasnt:

 (return (x <= 0.0 || x >= 0.0)) 

but

 (return (x <= 0.0 || x <= 0.0)) 

doing the same test twice.

**Comment by Chman** [comment]
Nope, [it was](https://github.com/Unity-Technologies/PostProcessing/blob/36bd0734e7c201cda4206cc81aaf67a182c9e9a7/PostProcessing/Shaders/StdLib.hlsl#L153):

```
return (x <= 0.0 || 0.0 <= x)
```

**Comment by TheRealCatherine** [comment]
Oh you are right indeed
