### ISSUE TITLE
(v2) Including Editor scripts in build

### ISSUE THREAD

**Issue by Factoid** [Unity-Technologies/PostProcessing#451]
##### What happened?
Our Jenkins builds started failing because the Editor scripts from PostProcessing v2 were being included in the build, in spite of them being in the Editor folder. Our work around was to add UNITY_EDITOR ifdef wrappers around each of the scripts, but we're puzzled because this shouldn't be happening. None of our other editor scripts seem to be exhibiting this issue.
 
##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.3.0p1, Windows10, standalone windows build target.

**Comment by Chman** [comment]
This may have something to do with the recent introduction of `asmdef`. Could you try removing [this file](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Editor/com.unity.postprocessing.Editor.asmdef) and [this one](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/com.unity.postprocessing.Runtime.asmdef) and start a new build?

**Comment by Factoid** [comment]
This resolved the issue, thanks!

**Comment by Chman** [comment]
Is there any chance we could get a log file of a failed Jenkins build when these two asmdef files are in? We're trying to figure out why this happened in the first place and if we can fix it (assuming it's on our side).
