### ISSUE TITLE
Strange Artifacts with the bloom effect

### ISSUE THREAD

**Issue by elsioneto1** [Unity-Technologies/PostProcessing#452]
##### What happened?
We're having issues with some strange artifacts (flickering squares) appearing on screen when the bloom effect is on. We have bone animated sprites (Spine) receiving lighting information. One thing that was noticed it's that the issue happens when we have the sprites with lighting information overlapping each other.  
##### Post-processing stack version (v1, v2)?
v1
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
5.6.4p1, Windows 8, Switch

**Comment by Chman** [comment]
Seems to me that it's the same issue as #356 (NaNs in your scene are causing Bloom to blow out, this isn't caused by post-processing but because a shader in your scene is failing and is throwing NaN values).
