### ISSUE TITLE
[v2] LUT Contribution Slider

### ISSUE THREAD

**Issue by digiwombat** [Unity-Technologies/PostProcessing#458]
##### What happened?
Using a global Volume in c0da412 (or 2.0.0-Beta5) there is no LUT Contribution slider in the Low-End Color Grading. The Weight slider is either hard on with any value over 0 and at 0 it's hard off.

Is this intended? Is the contribution slider gone for LUTs? Or have I missed a feature somewhere in my setup?

**Comment by Chman** [comment]
That's a limitation of the current system for blending textures in volumes, the default state for the LUT texture is null (as in "no texture") and blending from "null" to "texture" isn't currently supported.

The workaround is to have a global volume with a lower priority that your actual volume, add a Color Grading effect, override the LUT field and put the NeutralLdrLut texture in it, that way it will have an actual texture to fallback to when weight isn't 1.

**Comment by Chman** [comment]
A recent commit (09aafe8) made this possible so a contribution slider has been added in fbd5f19.
