### ISSUE TITLE
ES 3.0 Support?

### ISSUE THREAD

**Issue by miketucker** [Unity-Technologies/PostProcessing#46]
Using Unity 5.5.0 on Windows 10...
Shader error in 'Hidden/Post FX/Uber Shader': failed to open source file: 'Bloom.cginc' (on gles3)
Shader error in 'Hidden/Post FX/Uber Shader': failed to open source file: 'ColorGrading.cginc' (on gles3)

**Comment by Kink3d** [comment]
Hi,

Apologies for the lack of response during the holiday period. I have tried to reproduce this issue with no luck, I can use the editor and build correctly in GLES 3.1AEP. Have you tried re-importing the whole `PostProcessing` folder in Unity? Have you tried pulling the repository again? 

If you continue to get the error it would be very helpful if you could send us a project (as small as possible) that reproduces the issue so we can debug it.

Thanks

**Comment by Kink3d** [comment]
Closed due to inactivity
