### ISSUE TITLE
Expose SMAA quality levels

### ISSUE THREAD

**Issue by dbastien** [Unity-Technologies/PostProcessing#463]
We're currently using your excellent v2 post effects system in Magic the Gathering: Arena.

It would be amazing if you could expose some of the SMAA settings.

**Comment by Chman** [comment]
Exposed Low, Medium and High in 88ef4c9. This should cover most use cases. If you need more granularity you'll unfortunately have to tweak the shader as we can't expose all settings without introducing a performance impact (uniforms vs constants).
