### ISSUE TITLE
Post Processing v2 not working with VR.

### ISSUE THREAD

**Issue by spaez18** [Unity-Technologies/PostProcessing#464]
##### What happened?
I'm working building a VR game (with the GvrViewerMain asset applied to my scene). I tried to apply the post processing layer to my main camera, and the post processing volume to some game objects to get a bloom effect, when I'm on the scene tab it looks perfect with the effect applied to all game objects but in the "Game" tab when I try to see how it looks when the game is running it look like none of the effects were applied at all. When it's running the GvrViewerMain asset turns my main camera into 2 separate cameras.
The Game tab looks like this:
![gamelook](https://user-images.githubusercontent.com/33185934/36216957-336a5674-117e-11e8-8123-89d20fe76c3d.png)
The Scene tab looks like this:
![scenelook](https://user-images.githubusercontent.com/33185934/36216958-338299be-117e-11e8-8f3f-860fce521f42.png)

##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity Version: 2017.3.0f3, Operating system: Mac, Target platform: Android

**Comment by robbiesri** [comment]
My initial XR support was for single-pass double-wide.  I didn't have time to add instancing (for PC) and multi-view, and planned to transfer it to another engineer, but that didn't work out.  So it's back to me.  I hope to take a crack at it next week, so sorry :(

**Comment by jcowles** [comment]
Kind of tangential, but if this is for a mobile device, post effects are probably not going to work anyway (assuming you want to hit 60 FPS). A single no-op blit in the Unity post effects chain will destroy performance on a mobile GPU.

**Comment by spaez18** [comment]
Oh.. Okay, I'm kinda new developing in unity. Thanks for the clarification @jcowles
