### ISSUE TITLE
Build Warning - m_RenderingInSceneView never assigned

### ISSUE THREAD

**Issue by CBS-pcaporicci** [Unity-Technologies/PostProcessing#47]
Not a huge issue, but there is a script warning when you make a build

Assets/External/PostProcessing/Runtime/PostProcessingBehaviour.cs(30,14): warning CS0649: Field `UnityEngine.PostProcessing.PostProcessingBehaviour.m_RenderingInSceneView' is never assigned to, and will always have its default value `false'

**Comment by Kink3d** [comment]
Hi,

Apologies for the lack of communication over the holiday period. This issue should be fixed by [This PR](https://github.com/Unity-Technologies/PostProcessing/pull/52). Just waiting for review.

Thanks for submitting.
