### ISSUE TITLE
cannot build: shader error Hidden/PostProcessing/Debug

### ISSUE THREAD

**Issue by VeniVidiGavi** [Unity-Technologies/PostProcessing#471]
UPDATE: There was an incompatibility with another shader in the project. With a brand new project, Unity can build. 
-----------------------------
##### What happened?
cannot build
Build completed with a result of 'Canceled'
UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
Shader error in 'Hidden/PostProcessing/Debug/Waveform': failed to open source file: '../StdLib.hlsl' at line 7 (on d3d11)

Compiling Vertex program with UNITY_SINGLE_PASS_STEREO
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING
Shader error in 'Hidden/PostProcessing/Debug/Vectorscope': failed to open source file: '../StdLib.hlsl' at line 7 (on d3d11)
Shader error in 'Hidden/PostProcessing/Debug/LightMeter': failed to open source file: '../StdLib.hlsl' at line 8 (on d3d11)
Shader error in 'Hidden/PostProcessing/Debug/Overlays': failed to open source file: '../StdLib.hlsl' at line 6 (on d3d11)
Shader error in 'Hidden/PostProcessing/Debug/Histogram': failed to open source file: '../StdLib.hlsl' at line 7 (on d3d11)

##### Post-processing stack version (v1, v2)?
v2 taken from GitHub on 18 February 2018

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Windows10  2017.3.1f1

**Comment by JeremyVansnick** [comment]
I have the same issue, you say you removed a shader and it fixed the issue. How did you figure out which  one it was?
