### ISSUE TITLE
[V2] [2017.3.0f3] [XR] Effects not displaying in HMD when Single Pass Stereo is enabled

### ISSUE THREAD

**Issue by k0091601** [Unity-Technologies/PostProcessing#473]
Effects not displaying in singlepass,

V2

2017.3.0f3 Windows 10 Vive

**Comment by Chman** [comment]
Duplicate of #468.

**Comment by 01GOD** [comment]
How was this closed? None of this functions properly in single pass stereo rendering on mobile VR. 

This issue is MAJORLY unresolved and is a MAJOR problem for the Unity mobile VR platform right now.

**Comment by Chman** [comment]
Closed as a duplicate. Read the previous post.
