### ISSUE TITLE
Null Reference Exception for Fog.IsEnableAndSupported 

### ISSUE THREAD

**Issue by walaoRIKI** [Unity-Technologies/PostProcessing#474]
##### What happened?
Run the game in editor and get spammed with NullReferenceException error for the Fog

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.Fog.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Imported Asset/Post Processing/PostProcessing v2/Runtime/Effects/Fog.cs:24)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Imported Asset/Post Processing/PostProcessing v2/Runtime/PostProcessLayer.cs:521)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/Imported Asset/Post Processing/PostProcessing v2/Runtime/PostProcessLayer.cs:568)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/Imported Asset/Post Processing/PostProcessing v2/Runtime/PostProcessLayer.cs:324)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/Imported Asset/Post Processing/PostProcessing v2/Runtime/PostProcessLayer.cs:295)

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.5p1. Windows 10 64 bits, standalone windows

Edit:
The error gone after I remove and add the PostProcessLayer component again. Copy paste component will not solve the error, had to add and tweak manually

**Comment by Chman** [comment]
Same issue as #467.
