### ISSUE TITLE
(v2) Exception on PlayStation 4

### ISSUE THREAD

**Issue by SmallJJ** [Unity-Technologies/PostProcessing#479]
##### What happened?

00:32:50	ExecutionEngineException: Attempting to JIT compile method '(wrapper managed-to-managed) UnityEngine.RenderTextureFormat[]:System.Collections.Generic.IEnumerabl
00:32:50	e`1.GetEnumerator ()' while running with --aot-only.
00:32:50	
00:32:50	  at UnityEngine.Rendering.PostProcessing.TextureFormatUtilities..cctor () [0x001e0] in G:\Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\Utils\Texture
00:32:50	FormatUtilities.cs:77
00:32:50	Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UnityEngine.Rendering.PostProcessing.TextureFormatUtilities
00:32:50	  at UnityEngine.Rendering.PostProcessing.AmbientOcclusion.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) [0x0006
00:32:50	8] in G:\Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\Effects\AmbientOcclusion.cs:80
00:32:50	  at UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) [0x00035
00:32:50	] in G:\Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\PostProcessLayer.cs:510
00:32:50	  at UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) [0x0006b] in G:\
00:32:50	Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\PostProcessLayer.cs:565
00:32:50	  at UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () [0x00068] in G:\Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\PostPr
00:32:50	ocessLayer.cs:321
00:32:50	  at UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () [0x00096] in G:\Protoform2017_PS4\Assets\Plugins\PostProcessing\Runtime\PostProcessLayer
00:32:50	.cs:292 

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity3d 2017.2.1f1 ,  PlayStation 4 SDK 5.008.031

**Comment by Chman** [comment]
This is already fixed in master. See #447.
