### ISSUE TITLE
Color Grading not working on Android

### ISSUE THREAD

**Issue by Liviuss76** [Unity-Technologies/PostProcessing#48]
Project is built with Unity 5.5.0p3 tested on Samsung Galaxy S5 Android 6.0.1
In profile only Bloom and Color Grading is enabled. Project is built with GLES2.0, Forward, Gamma.

Console output: 
`12-26 14:20:58.648  11166-11199/? E/Unity﹕ TextureFormat 17 is not supported on this platform
    (Filename:  Line: 460)
12-26 14:20:58.653  11166-11199/? I/Unity﹕ UnityException: Failed to create texture because of invalid parameters.
            at UnityEngine.Texture2D..ctor (Int32 width, Int32 height, TextureFormat format, Boolean mipmap, Boolean linear) [0x00000] in <filename unknown>:0
            at UnityEngine.PostProcessing.ColorGradingComponent.GetCurveTexture () [0x00000] in <filename unknown>:0
            at UnityEngine.PostProcessing.ColorGradingComponent.GenerateLut () [0x00000] in <filename unknown>:0
            at UnityEngine.PostProcessing.ColorGradingComponent.Prepare (UnityEngine.Material uberMaterial) [0x00000] in <filename unknown>:0
            at UnityEngine.PostProcessing.PostProcessingBehaviour.TryPrepareUberImageEffect[ColorGradingModel] (UnityEngine.PostProcessing.PostProcessingComponentRenderTexture`1 component, UnityEngine.Material material) [0x00000] in <filename unknown>:0
            at UnityEngine.P`

**Comment by Kink3d** [comment]
Hi,

I have successfully reproduced the issue. As implied by the message, the texture format used for the internal colour correction calculations isn't supported on GLES2 and unfortunately that graphics API is just too old for us to support. 

Can I ask why you are targeting GLES2? Our effects are tested and (mostly) working on GLES3, which should run fine on your hardware, If you are targeting phones old enough to require GLES2 I would suggest disabling Post Processing when that API is enabled.

Thanks

**Comment by Liviuss76** [comment]
Hi,
First, i have already a project on the store and i have started to update it and implement new stuff, the project is built with GLES2.0. Why GLES2.0? because of device coverage https://developer.android.com/about/dashboards/index.html#OpenGL 41% of the market is still GLES2.0 only devices.
Second, i use in my project ColorSuite tool from Keijiro and it work wery well. https://github.com/keijiro/ColorSuite I have updated to PostProcessing package becasuse Color Grading it's more versatile and you have a nice bloom in the place but didn't expected the GLES3+ restriction.
I suggest you to update the documentation docs where it should be clearly stated that it's only GLES3+ compatible.

Thanks

**Comment by Liviuss76** [comment]
I just tested Color Grading with GLES3.0 on the same device(Galaxy S5) and get this error:

`E/Unity﹕ RenderTexture.Create failed: format unsupported - 2.
    UnityEngine.Graphics:Internal_BlitMaterial(Texture, RenderTexture, Material, Int32, Boolean)
    UnityEngine.Graphics:Blit(Texture, RenderTexture, Material, Int32)
    UnityEngine.PostProcessing.ColorGradingComponent:GenerateLut() (at /../Assets/PostProcessing/Runtime/Components/ColorGradingComponent.cs:378)
    UnityEngine.PostProcessing.ColorGradingComponent:Prepare(Material) (at /../Assets/PostProcessing/Runtime/Components/ColorGradingComponent.cs:388)
    UnityEngine.PostProcessing.PostProcessingBehaviour:TryPrepareUberImageEffect(PostProcessingComponentRenderTexture`1, Material) (at /../Assets/PostProcessing/Runtime/PostProcessingBehaviour.cs:437)
    UnityEngine.PostProcessing.PostProcessingBehaviour:OnRenderImage(RenderTexture, RenderTexture)`

**Comment by Kink3d** [comment]
Thanks so much for the information on both these issues, well be looking in to these asap.

**Comment by Kink3d** [comment]
Yes I'm afraid as you can see below this device doesnt support RGBAHalf.

http://opengles.gpuinfo.org/gles_listreports.php?extensionunsupported=GL_EXT_color_buffer_half_float

For devices that don't support this format you're going to have to create a fallback LUT in image editing program and use "User LUT" when the format isn't supported. We are discussing options for improving the workflow for this but it is very problematic with other features we are currently working on.
