### ISSUE TITLE
unable to add rendering features

### ISSUE THREAD

**Issue by benblo** [Unity-Technologies/PostProcessing#480]
Unity 2018.1.0b9 (Windows, DX11), pulled the Postprocessing stack 2.0.0-beta using the Package Manager, tried to follow the quickstart: added a PostprocessLayer to the camera... but then I don't see any way to add "Rendering features" as the doc says. Wut?

![image](https://user-images.githubusercontent.com/574187/36624090-543c6c04-190b-11e8-8fd8-5a89aedbb6d9.png)

**Comment by Chman** [comment]
"Rendering features" are only available/needed when working with the standard unity deferred pipeline (basically it's only Fog at this point, SSR and AO have been moved to volumes).

I'll update the quickstart guide (proper, more complete documentation is being written right now and will come with the release of 2018.1).
