### ISSUE TITLE
[V2] Assembly definition files recently added to V2 stack break solution generation in 2017.3

### ISSUE THREAD

**Issue by artyom-zuev** [Unity-Technologies/PostProcessing#481]
##### What happened?
Ever since .asmdef files were added to V2, I've been getting the following error on project recompiling:

`ArgumentException: Value does not fall within the expected range.
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.LanguageOf (SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit unit) (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits (System.String method) (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.CompilationUnit.CompilationUnits () (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder..ctor () (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectSystem.UnitySolutionBuilder.CreateSolutionFromAssetDatabase () (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilesGenerator.GenerateProject () (at <d459da3fb7b54c3291cd57d1330a7d06>:0)
SyntaxTree.VisualStudio.Unity.Bridge.ProjectFilePostprocessor.OnPreGeneratingCSProjectFiles () (at <d459da3fb7b54c3291cd57d1330a7d06>:0)`

This error doesn't seem to prevent Unity from finishing project compilation, so in-Editor execution of everything continues to work fine - but this breaks solution in VS, making everything open as mixed files, disabling code completion, breaking navigation to definitions between files etc. Removing both .asmdef files from the local clone of the repo completely solves the issue.

##### Post-processing stack version (v1, v2)?
V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.0f1
Windows 10 x64 (build 16299)
Visual Studio 2015

**Comment by Chman** [comment]
This is a deeper Unity/VS issue that affected all packages on 2017.3 and 2018.1 - post-processing included. Updating [VSTU](https://marketplace.visualstudio.com/items?itemName=SebastienLebreton.VisualStudio2015ToolsforUnity) will fix it.

Relevant threads on the forums:
- [Example Project - Assembly Definition Files](https://forum.unity.com/threads/example-project-assembly-definition-files.482313/)
- [Issues with Visual Studio + Unity](https://forum.unity.com/threads/issues-with-visual-studio-unity.514304/#post-3401707)
