### ISSUE TITLE
Adding Post Process Layer to (VR) camera throws multiple NullReferenceException

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/PostProcessing#484]
Hi I've just downloaded the latest v2-beta-branch version and tried to integrate, but when adding component PostProcessLayer to our (SteamVR) camera, I'm getting

> NullReferenceException: Object reference not set to an instance of an object
> UnityEngine.Rendering.PostProcessing.Fog.IsEnabledAndSupported (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/Effects/Fog.cs:24)
> UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetLegacyCameraFlags (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:522)
> UnityEngine.Rendering.PostProcessing.PostProcessLayer.SetupContext (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:569)
> UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:324)
> UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:292)

My Unity version is 2017.02.0f3, Win64, PC target. Screenshot below. I'm probably making a noob error, not an expert on PostProcess stack (though I got it to work in the past when evaluating which filters already worked in VR). Thanks!

![screen](https://user-images.githubusercontent.com/1754503/36726169-24dd752e-1bb9-11e8-9c45-a90b42f4d702.png)

**Comment by Chman** [comment]
This happens when the resource file is null on `PostProcessLayer`, either due to a bad import, a broken meta file or when you instantiate `PostProcessLayer` via scripting.

If you switch to debug view in the inspector (click the small menu icon next to the lock icon at the top right of the inspector), what's in the `Resources` field of your `PostProcessLayer`?

Also, by v2-beta-branch do you mean `v2` or the `2.0.0-beta` tag?

**Comment by JPhilipp** [comment]
In regards to the branch, I just clicked Download at https://github.com/Unity-Technologies/PostProcessing/ and ended up with the files which, in the package.json, read "version": "2.0.0-beta".

Will try to answer the other question soon, thanks!

**Comment by ThanhWilliamLe** [comment]
I have the same issue, my Resources field is none
![image](https://user-images.githubusercontent.com/30400570/36742112-6feb0120-1c19-11e8-8315-1ddf6756f74c.png)

I tried to set it to either 2 but it just won't change
![image](https://user-images.githubusercontent.com/30400570/36742129-7ada55e0-1c19-11e8-8af9-adf41371203f.png)

**Comment by JPhilipp** [comment]
It's working for me now after a fresh try. Not sure what was different this time, perhaps some of the files I originally excluded from integrating into the project to keep it lean (like the documentation) where necessary.

As far as I'm concerned the issue can be closed, but I guess that depends on if it's fixed for Thanh too.

**Comment by ThanhWilliamLe** [comment]
I've reverted back to Post Processing V1 for now since that problem still persist for me

**Comment by Chman** [comment]
This was an issue with the automatic shader stripping process we put in place. It's been completely removed last week and reverted back to the way it was so make sure to grab the latest version. Note that you'll have to delete & recreate your PostProcessLayer component for the fix to be applied.
