### ISSUE TITLE
How to include StdLib.hlsl when using the stack from the package manager?

### ISSUE THREAD

**Issue by demonixis** [Unity-Technologies/PostProcessing#485]
##### What happened?
I'm writting a custom image effect for the stack V2 using Unity 2018.1b8. The stack is loaded from the package manager because I use the Lightweight pipeline. I can't import the file `StdLib.hlsl` because the post processing stack v2 is not located in my project.

##### Post-processing stack version (v1, v2)?
V2.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.1b8

Thank you!

**Comment by Chman** [comment]
This has been fixed in the repository but you'll have to wait for the next package version to be pushed to take advantage of it (soon).

In your shaders you'll just have to add:

```
#include "PostProcessing/Shaders/StdLib.hlsl"
```

**Comment by demonixis** [comment]
Whoo thank you ;) Do you know when it'll be updated?

**Comment by Chman** [comment]
Cutoff is on Friday I believe, so probably in the next few days.

**Comment by demonixis** [comment]
Great thanks again!

**Comment by FlavioRodriguez** [comment]
Hello Guys, 

Have you managed to fix that? I bought a Post-processing plugin today, 06/03/2018, I'm facing the same problem, each time I open the shader editor, it automatically writes #include line back with the wrong path, I'm also using the lightweight pipeline.

**Comment by Sroka** [comment]
Anyone have any workaround? Same for me as for @FlavioRodriguez Unity overwrites the #include every time I open it

**Comment by PCoelho** [comment]
I'm using 2019.1.7 and version 2.1.7 and it's still a problem
