### ISSUE TITLE
[V2]Bloom performance 

### ISSUE THREAD

**Issue by Mrunpredictable** [Unity-Technologies/PostProcessing#487]
##### I recently compared performance between bloom image effects from stack v2 vs unity image effects downloaded from their bit bucket repo https://bitbucket.org/Unity-Technologies/cinematic-image-effects

I noticed a massive performance gain using the bloom effect from the bitbucket version with same settings

You can compare it with by frame debugger or profiler
i was using unity 2018 and post processing stack v2

**Comment by Chman** [comment]
Use "Fast Mode" on bloom to have comparable quality and performances to the older one. It's slower because it's also higher quality, unless you toggle "Fast Mode".

**Comment by Mrunpredictable** [comment]
even with fast mode the performance is terrible compared to that

**Comment by Chman** [comment]
I don't see any report about performances on these screenshots. You're showing frame debugger views...

> i'm getting same results with older version

You'll get similar visual results in some situations but the one in v2 is able to deal with a lot more edge-cases that would failed with the old one. It's not all about what you see in a single case...
