### ISSUE TITLE
[V2] Custom effect has different result between PC and PS4

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#488]
##### What happened?
I write a custom effect and it works fine on pc, but no effect on PS4. So I made a small project to find the issue. It seems like a RWStructuredBuffer can't be shared between multi-kernel on PS4.
screenshot on PC (count numbers which is bigger than 50, then write the result into a render texture):
![pc editor](https://user-images.githubusercontent.com/18855621/36853402-66684fc2-1da9-11e8-9e14-6f6d376ee751.PNG)

screenshot on PS4 (the render texture is all Black):
![ps4](https://user-images.githubusercontent.com/18855621/36853456-88542020-1da9-11e8-93f5-fee367ed9112.PNG)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.2.1f1, win10 dx11, ps4.

**Comment by silentlamb1991** [comment]
This is the project to reproduce this issue:
[BugOnPS4.zip](https://github.com/Unity-Technologies/PostProcessing/files/1771769/BugOnPS4.zip)

**Comment by Chman** [comment]
This is not a post-processing bug, please use the official channel to send bugs like these.

With that said, I just tested it on PS4 and I get the correct result (on 2018.1 but it's probably been fixed in a previous version).
