### ISSUE TITLE
PostProcessStrippingConfig.Asset is generated on Windows & causes Inconsistency Detected Error (V2) (Unity 2018.1.0b8 & b9)

### ISSUE THREAD

**Issue by MrT3D** [Unity-Technologies/PostProcessing#489]
PostProcessStrippingConfig.Asset is generated on Windows & causes Inconsistency Detected Error on other computers. Constantly requires re-importing assets and may only be fixed by deleting the asset.

<img width="407" alt="screen shot 2018-02-28 at 12 51 24 pm" src="https://user-images.githubusercontent.com/1016972/36925903-1640bf6c-1e43-11e8-9914-381be17dc591.png">

(V2)

Unity 2018.1.0b8 & b9 - PC and OSX

**Comment by Chman** [comment]
This file and the logic around it has been removed last week. Please update to the latest revision.

**Comment by MrT3D** [comment]
Thanks!
