### ISSUE TITLE
NullReferenceException while mixing volumes and global volumes.

### ISSUE THREAD

**Issue by felinearts** [Unity-Technologies/PostProcessing#498]
##### What happened?
Create a profile and a volume, make it global.
Create a 2nd volume with a 2nd profile

Start the scene with the camera inside the non global volume makes the post process stack fail to render until you get out of the volume, getting inside again blends perfectly.

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.TextureLerper.Lerp (UnityEngine.Texture from, UnityEngine.Texture to, System.Single t) (at Assets/PostProcessing/Runtime/Utils/TextureLerper.cs:131)
UnityEngine.Rendering.PostProcessing.TextureParameter.Interp (UnityEngine.Texture from, UnityEngine.Texture to, System.Single t) (at Assets/PostProcessing/Runtime/ParameterOverride.cs:229)
UnityEngine.Rendering.PostProcessing.ParameterOverride`1[T].Interp (UnityEngine.Rendering.PostProcessing.ParameterOverride from, UnityEngine.Rendering.PostProcessing.ParameterOverride to, System.Single t) (at Assets/PostProcessing/Runtime/ParameterOverride.cs:59)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OverrideSettings (System.Collections.Generic.List`1[T] baseSettings, System.Single interpFactor) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:499)
UnityEngine.Rendering.PostProcessing.PostProcessManager.UpdateSettings (UnityEngine.Rendering.PostProcessing.PostProcessLayer postProcessLayer, UnityEngine.Camera camera) (at Assets/PostProcessing/Runtime/PostProcessManager.cs:358)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.UpdateSettingsIfNeeded (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:584)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:327)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Assets/PostProcessing/Runtime/PostProcessLayer.cs:292)

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
editor, 2017.1.2p2

**Comment by Chman** [comment]
Fixed in 4cd8808.
