### ISSUE TITLE
AO duplicates/triplicates the number of tris in the scene

### ISSUE THREAD

**Issue by dgsantana** [Unity-Technologies/PostProcessing#499]
##### What happened?
When using the AO, the number of tris changes. With MSVO, it duplicates and with SAO triplicates. This for mobiles is a no-no.
##### Post-processing stack version (v1, v2)?
v2.
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.1f1, Windows 10 Pro, iOS/Android.

Without AO
![image](https://user-images.githubusercontent.com/2750212/37215354-a12e4e84-23af-11e8-839b-96a6cabffd7b.png)
With MSVO
![image](https://user-images.githubusercontent.com/2750212/37215379-b0446da4-23af-11e8-977d-79da4f57bdbf.png)
With SAO
![image](https://user-images.githubusercontent.com/2750212/37215395-bd89281a-23af-11e8-97af-e676ca4c2fa5.png)

**Comment by Chman** [comment]
All AO techniques require at least a depth map to be available (and in the case of SAO, normals as well). You're running the forward rendering path which means Unity _has to_ do another pass to render these maps, thus pushing the triangle count higher. The deferred rendering path doesn't do this additional pass as these maps are already available (and in the case of normals, higher detailed as well).

This is not a "bug", it's just the way it works in Unity. For what it's worth, we don't recommend using AO on mobile at all (and MSVO won't work on Android, it can run on iOS but it's way too heavy for it and is exclusively targeted and optimized for consoles & PCs).
