### ISSUE TITLE
Color Grading Effect with default settings affects image.

### ISSUE THREAD

**Issue by KelSolaar** [Unity-Technologies/PostProcessing#5]
Hi,

I have verified that to be happening on Windows and Mac Os X, the *Color Grading Effect* with default settings and the tonemapper sets to _None_ still affects the viewport non linearly:

**Color Grading Effect Disabled**
![image](https://cloud.githubusercontent.com/assets/99779/19382939/cf2c3532-925e-11e6-84b4-0440af1796b3.png)

**Color Grading Effect Enabled**
![image](https://cloud.githubusercontent.com/assets/99779/19382923/bf9f66fc-925e-11e6-87ad-716f6294e15f.png)

This issue is created by the call to `YrgbCurve` in [LutGen.shader#L87](https://github.com/Unity-Technologies/PostProcessing/blob/master/PostProcessing/Resources/Shaders/LutGen.shader#L87)

I wouldn't mind some explanations on how the curve lookup works here: `half mr = tex2D(curveTex, half2(c.r, 0.75)).a;`

Cheers,

**Comment by Chman** [comment]
Thanks for the report !

The way color curves work is by baking each curve into a 1D texture and sampling them using the current pixel color.

The issue you're seeing should be fixed in a26774e. Can you please test it ?

I don't see any more shifts in the darks using this fix, only a very, _very_ slight shift in the extreme highlights.

**Comment by KelSolaar** [comment]
Hey Thomas,

Thanks! I'll try the commit, I understand how the lookup would work in a 1D context, I should have been clearer. It is actually the 0.75 constant that I don't get and why it has this value, likely a side effect of having the 1D curve in a 2D array?

Cheers,

Thomas

**Comment by Chman** [comment]
The curve texture actually holds 8 curves (1 per channel in a 128x2 texture, so 4 per lines). The first line contains the 4 secondary color correction curves (`Hue VS Hue`, etc) and the second line contains the standard YRGB curves.

The reason for the `0.75` value is to make sure it samples the center of the pixel to avoid any filtering with curves located on the first line (although in the case of a clamped 2 pixels-high texture it could have be `1`). The same goes for the curves stored on the first line, it'll sample at `y = 0.25`.

Hope that helps and let me know once you've tried the latest version !

**Comment by KelSolaar** [comment]
Thanks for the details! It is crystal clear now with the explanation on the layout of the texture.

Confirming that https://github.com/Unity-Technologies/PostProcessing/commit/a26774e35354afbc59bdea5fa662222ebd7254eb fixed the issue!

**Comment by Chman** [comment]
👍
