### ISSUE TITLE
Can not build Windows Store

### ISSUE THREAD

**Issue by KarlozZhang** [Unity-Technologies/PostProcessing#50]
Project is for Windows Store (SDK: Universal 10, Target device: PC, UWP Build Type:D3D), with PostPorcessing, it won't build with error of 'Error building Player because scripts have compile errors in the editor'. Could you please fix this?

**Comment by gokselgoktas** [comment]
Hi there,

Would you have some more information regarding this error? What does the error output in the console say? What scripts are problematic? Which lines and what part of the code?

Cheers,
Göksel

**Comment by KarlozZhang** [comment]
Hi Göksel:
Thank you for your respond.
And yes there are more error about PostProcessing print in the console before that one, which is 'Assets\PostProcessing\Runtime\Utils\ReflectionUtils.cs(81,29): error CS1061: 'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)' along with a warning 'Assets\PostProcessing\Runtime\PostProcessingBehaviour.cs(30,14): warning CS0649: Field 'PostProcessingBehaviour.m_RenderingInSceneView' is never assigned to, and will always have its default value false'

Wish this will be helpful

Cheers,

Karloz

**Comment by Kink3d** [comment]
Hi Karloz,

Thanks for the information. It seems that UWP doesnt support some or all of the reflection we are using. @Chman will take a look at this but it could be very problematic. We will let you know how it turns out.

Regards

**Comment by Chman** [comment]
Reflection is only used in the editor but for some reason one file was out of the Editor folder when it shouldn't. I moved it to its proper location in the latest commit (4ce8688d). Could you grab the current master and make sure that fixes it for you ?

**Comment by Kink3d** [comment]
Assumed fixed due to inactivity. Reopen if still reproduces.

**Comment by Ar7ific1al** [comment]
This has not been resolved.
OS (just in case): Windows 10 1703 15063.296
Unity 5.6.0p1
Latest version of the asset from the Unity Asset Store (v1.0.2, April 25, 2017).
Scripting backend: .NET
Build target: Windows Store (Universal Windows Platform)
Error:
Assets\PostProcessing\Runtime\Utils\ReflectionUtils.cs(81,29): error CS1061: 'Type' does not contain a definition for 'BaseType' and no extension method 'BaseType' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

Please reopen this.
