### ISSUE TITLE
[V2] [2017.1.3p1] Vignetting in VR looks distorted (cross eyed)

### ISSUE THREAD

**Issue by danielcestrella** [Unity-Technologies/PostProcessing#501]
I am trying it to avoid locomotion sickness like in Gorn game, but it doesn't feel ok (I've tryed Single and Multi pass rendering).

This is something similar to what I view inside Vive HMD: [https://imgur.com/a/JU9Ka](https://imgur.com/a/JU9Ka)

Thanks for your help!

**Comment by Chman** [comment]
Probably similar to #421.

**Comment by danielcestrella** [comment]
You are right. Thank you.
