### ISSUE TITLE
Enabling e.g. Bloom via script doesn't do anything

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/PostProcessing#506]
Edit: Solved, please close :)
----

I'm pretty sure I'm just doing it wrong, but don't know where to ask, so thanks for any help! How do I enable e.g. bloom via script if I have it toggled to Off via editor by default? I tried e.g.

```
Bloom bloom = ScriptableObject.CreateInstance<Bloom>();
bloom.enabled.Override(true);
// also no luck if I add: bloom.enabled.value = true;
bloom.intensity.Override(50f);
```

... and while that won't throw errors and indeed set intensity to 50 if I have bloom On already in editor, it does not turn the effect On if it's set to Off at start (neither visually in what the camera shows, nor in the component button, not that I mind the latter). I do have the component tickbox itself enabled, just want it to be Off by default for performance reasons.

----
Update: Ah, it finally works! I was apparently creating a new Bloom instance instead of loading the active one!

```
PostProcessVolume volume = gameObject.GetComponent<PostProcessVolume>();
volume.profile.TryGetSettings(out bloom);
```

**Comment by Chman** [comment]
For future reference, [this part of the doc](https://github.com/Unity-Technologies/PostProcessing/wiki/Manipulating-the-Stack#profile-editing) should be helpful to new readers :)
