### ISSUE TITLE
So...at GDC this year...MULTIPLE NEW mobile HMD products announced...FULLY FUNCTIONAL SINGLE PASS STEREO RENDERING IS A TOP PRIORITY AND NEEDS TO BE COMPLETED ASAP!!! 

### ISSUE THREAD

**Issue by 01GOD** [Unity-Technologies/PostProcessing#509]
Still waiting for fully functional single pass stereo support on Post Processing Stack 2 in every version of Unity 2017...and most likely 2018

[moderator: part of post removed]

Thanks in advance!

**Comment by kwi-dk** [comment]
Thank you for your interest in Unity's Post Processing stack. We've previously asked you to moderate your tone to no avail. Therefore, I now have to specifically ask that you refrain from 1) writing all caps, 2) personal attacks, 3) tangents about unrelated companies and products, 4) tangents about outsourcing and the inferiority of programmers in certain nations, 5) giving us orders on how to run our business. I am closing this issue and have moderated it and several of your previous comments. If this behavior continues, you will be blocked. Thank you.
