### ISSUE TITLE
Screen Space Reflection artifacts with TextMesh Pro

### ISSUE THREAD

**Issue by walaoRIKI** [Unity-Technologies/PostProcessing#510]
##### What happened?
Artifacts issue with TextMesh Pro when SSR is enable

![artifacts](https://user-images.githubusercontent.com/14368362/38064391-5210dce6-3330-11e8-84aa-1c0a46db2bdb.png)

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.5p2. Windows 10. Windows PC

**Comment by Chman** [comment]
I'm not exactly sure what I'm looking at, it looks like a NaN blob?

A few questions:
- Do you have TAA enabled?
- Do you have Stop NaN Propagation enabled on your PostProcessLayer?
- What version of v2 are you working with? Is this the latest one from yesterday or a previous one?

**Comment by walaoRIKI** [comment]
nope, I using fxaa only. 
I disabled nan. 
Not the latest version, I downloaded around 1 weeks ago

**Comment by crookookoo** [comment]
@Chman I have TAA on and it's causing artifacts on TMPro, is this a known issue?

**Comment by khalv** [comment]
I have also have issues in the past with TextMeshPro producing NAN pixels, which tend to screw up post processing effects. Unity closed my bug rerport sinnce they could not reproduce it, would be great if you could send them this scene.

**Comment by walaoRIKI** [comment]
> I have also have issues in the past with TextMeshPro producing NAN pixels, which tend to screw up post processing effects. Unity closed my bug rerport sinnce they could not reproduce it, would be great if you could send them this scene.

I already submitted a bug report with test scene that I manage to reproduce the artifact

**Comment by Chman** [comment]
> I already submitted a bug report with test scene that I manage to reproduce the artifact

Do you have the bug ID so I can look it up?

**Comment by walaoRIKI** [comment]
> Do you have the bug ID so I can look it up?

Here you go, 1023977

**Comment by Chman** [comment]
Thanks. So I just tried the project, and it doesn't have much to do with post-processing unfortunately. Even completely removing post-processing from the project still exhibits the issue because TextMeshPro is outputting NaN.

This is without post-processing:
![image](https://user-images.githubusercontent.com/849090/38604402-89ad3736-3d70-11e8-9366-adca5f82234d.png)

I'll add a comment on 1023977 to explain the issue and hopefully redirect it to the team in charge of TextMesh Pro because there isn't anything I can do on my end.

**Comment by walaoRIKI** [comment]
> Thanks. So I just tried the project, and it doesn't have much to do with post-processing unfortunately

Wait, have you download the package and replace the file?

**Comment by Chman** [comment]
As I explained, TextMeshPro is outputting NaNs when it shouldn't and this breaks everything afterwards, post-processing included. Also, **please toggle on "Stop NaN Propagation"** on your post-process layer as it helps reduce the issue (NaNs pixels will still be there and that's for the TextMeshPro team to fix, I can't really "invent" missing pixels from the framebuffer). It's off in your scene.

**Comment by walaoRIKI** [comment]
ok, thanks :D
