### ISSUE TITLE
TAA sharpen filter produce NaNs and "black holes"

### ISSUE THREAD

**Issue by Anton-Tril** [Unity-Technologies/PostProcessing#511]
Hi!
I have a problem with Sharpen filter of TAA. This line of code
color += (color - (corners * 0.166667)) * 2.718282 * _Sharpness;

Produce such results on HDR particles:
![2018-03-31_100012](https://user-images.githubusercontent.com/25489578/38160770-6e557280-34cb-11e8-9e0d-cd3742ff19c5.png)

Original image without TAA sharpen issue:
![2018-03-31_100015](https://user-images.githubusercontent.com/25489578/38160776-7aae5d26-34cb-11e8-83e9-b22636fe76ef.png)

This is also a reason why NaN propagation happens.

Why it`s important? Take a look at unpleasant black pixels inside explosions in [our video](https://youtu.be/rjDsR-Bdq-w?t=40)

##### Post-processing stack version (v1, v2)?
v2

**Comment by Chman** [comment]
Have you tried updating to the lastest version? We pushed a few fixes to TAA (79350d3) that fixed this specific issue in all of our repro cases.

**Comment by Anton-Tril** [comment]
nope, will check, thank you
