### ISSUE TITLE
Fog settings missing (proposed solution)

### ISSUE THREAD

**Issue by OndrejPetrzilka** [Unity-Technologies/PostProcessing#512]
##### What happened?
Fog settings are missing in post processing stack. Only global settings are used which limits the usage.
It's not possible to have different fog for different cameras or use predefined fog profiles, blending etc.

**Proposed solution:**

1. Implement Fog effect, parameters: color, density, start/end distances, mode, exclude skybox
2. Remove Fog settings from camera
3. PostProcessLayer.OnPreCull - copy fog settings into RenderSettings
4. PostProcessLayer.OnPostRender - restore original fog RenderSettings
5. Otherwise ignore fog values in RenderSettings

I've done some tests and this seems to work well.
Would there be any obvious issue? (e.g. during light baking, Enlighten etc...)

see #514 for implementation

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity2017.3.1p2, Windows 7 x64, Standalone windows

**Comment by Chman** [comment]
Comment posted on the PR itself. See #514. Let's bring the discussion over there :)

I'm closing this one to avoid having two places to discuss this.
