### ISSUE TITLE
Shader loses vertex colour on device (iOS)

### ISSUE THREAD

**Issue by Votrubec** [Unity-Technologies/PostProcessing#517]
I created the shader graph as shown in the image. The purpose is to be able to use the vertex colour information in the model, exported by our artist as an FBX from Blender.

As can be seen by the shader preview, it's picking up the colour information. The Scene and Game views also display the colour correctly. The Editor has The Graphics Emulation set as Metal / Tier 3. 

But when I test it on an iPhone, the colour information is ignored. Everything else seems to work correctly. There are no errors in building, and no indication that there was any problem found.

I have reworked the Standard Shader found in 2018.1.b13 to include the vertex colour information (so much fun...), which works as intended, so I know it's not an iOS issue. But it would ultimately be so much easier to use the Shader Graph in future.

Is Vertex Colour something that the Unity team simply refuses to accommodate? Hahaha...

PPS V2 (installed from Package Manager)
SRP-LW (installed from Package Manager)
2018.1.b13
Windows 10 Development
iOS 11 / iPhone X Target

iOS target platform
Forward Rendering
Linear Colour Space

![vertexcolourshadergraph](https://user-images.githubusercontent.com/6911496/38342938-9c975fee-38c4-11e8-9091-99875596336e.png)

**Comment by Chman** [comment]
Hi,

This is the post-processing stack repository, you'll want to post this on the [ShaderGraph repository](https://github.com/Unity-Technologies/ShaderGraph/issues).

**Comment by Votrubec** [comment]
You're absolutely correct, sorry.
