### ISSUE TITLE
changes by code disable editor changes

### ISSUE THREAD

**Issue by ghiboz** [Unity-Technologies/PostProcessing#521]
##### What happened?
Hello!
I have this issue on the changes by code: for example the colorgrading stuff:
from the code I preset some values: with this code:
```csharp
_ppProfile.TryGetSettings(out _grading);
_grading.tonemapper.Override((Tonemapper)2);
_grading.postExposure.Override(2.5f);
```
and with this code, the changes works, but if I go on the editor, I can't see these values changed and the other canges aren't affected.

seems like that when I try to get the settings, the editor loses the link

##### Post-processing stack version (v1, v2)?
pp v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
win 10 64 bits unity 2017.3.1f1

**Comment by Chman** [comment]
How did you grab your `_ppProfile` instance?

**Comment by ghiboz** [comment]
hi @Chman!

here is my code:

```csharp
_ppVolume = centerCam.GetComponent<PostProcessVolume>();
_ppProfile = _ppVolume.profile;
_ppSettings = _ppProfile.settings;

 _ppProfile.TryGetSettings(out _dof);
 _ppProfile.TryGetSettings(out _ao);
 _ppProfile.TryGetSettings(out _bloom);
 _ppProfile.TryGetSettings(out _grading);
 _ppProfile.TryGetSettings(out _exp);
```

**Comment by Chman** [comment]
By doing:

```
_ppProfile = _ppVolume.profile;
```

You're instancing an internal copy of the profile asset for editing, the same way materials work. If you want to work on the asset itself, like materials, you'd use:

```
_ppProfile = _ppVolume.sharedProfile;
```

[This section of the scripting doc](https://github.com/Unity-Technologies/PostProcessing/wiki/Manipulating-the-Stack#profile-editing) should help you out on this :)

**Comment by ghiboz** [comment]
thanks @Chman I'll try! 👍
