### ISSUE TITLE
List of workarounds to force single pass stereo to function with at least TAA...and hopefully bloom. 

### ISSUE THREAD

**Issue by 01GOD** [Unity-Technologies/PostProcessing#522]
Making this so that all involved can collectively list whatever workarounds are known to make single pass stereo rendering possible with the Unity Post Processing Stack (any version). This includes edits of files, settings recommendations, and so on. 

Thanks in advance for any replies that make it function properly. 

##### What happened?
Been waiting a loooooooong while for single pass stereo to function properly with PostProcessing Stack. 
##### Post-processing stack version (v1, v2)?
Both. 
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2017.x, Win 10, Oculus mobile

**Comment by cameronoltmann** [comment]
Most of v2 works with single pass.  TAA and reflections are notable exceptions.  Bloom works in Forward, [but not deferred](https://github.com/Unity-Technologies/PostProcessing/issues/392).
