### ISSUE TITLE
Rendering to Render Texture in LWRP + PPSv2 causes flipping

### ISSUE THREAD

**Issue by beinteractive** [Unity-Technologies/PostProcessing#523]
If a target of a camera set to Render Texture and that camera has Post-processing Layer, rendered image on the Render Texture is flipping. This issue is not happened when Post-processing Layer is disabled, or SRP is not LWRP.

See this minimal reproduction project:
https://github.com/beinteractive/PostProcessingStackv2-RenderTextureFlippingIssue

Reproduced in:
Unity 2018.1.0b13 + Lightweight Render Pipeline 1.1.2-preview + Post-processing Stack 2.0.3-preview
macOS / iOS (I didn't confirm other platforms)

**Comment by Chman** [comment]
Fixed on LWRP side in [this PR](https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1163). It also applies to HDRP, fixed in [this separate PR](https://github.com/Unity-Technologies/ScriptableRenderPipeline/pull/1164).
