### ISSUE TITLE
Misleading color grading?

### ISSUE THREAD

**Issue by RamiroOliva** [Unity-Technologies/PostProcessing#527]
After testing some LUTs and further investigating I'm seeing a problem with how Post Processing Stack v2 applies color grading, specially LUTs.
The issue is that color grading is applied at the end of the stack - this can lead to wrong color translations - for instance bloom should be applied after the colors have been translated producing a smooth effect over the new tones.
As it's, color grading is applied over the gradients generated by bloom which depending on the LUT textures produce weird results.
LUT/Color grading should be applied during a previous stage to remain correct, then the rest of effects.

**Comment by Chman** [comment]
This is incorrect.

Bloom is a lens artifact (light is diffracted and convoluted with an airy disk). Grading & tonemapping have to happen _after_ the scene is rendered and properly exposed. If you were to grade before the bloom pass you would in fact change the luminance values of your picture which would impact the bloom strength and it would be hard to calibrate your colors properly unless you working on static shots. Even worse, using a tonemapper before bloom would compress the luminance range and de facto kill the bloom effect, you would have to revert back to using a low threshold value to simulate LDR bloom, and that would look aweful.

Think about it this way: when you take a picture with your camera and then import it in Photoshop or Lightroom to tweak the colors... The bloom effect is already baked into the picture. And you're grading & tonemapping on top of it.

The same goes for the movie industry. When they import raw footage that they shoot earlier into their post-prod pipeline bloom is already in the footage. And they grade on top of it.

And if you're still not convinced, just look at how other engine post-processing pipelines are setup. Color grading and tonemapping (or the other way around depending on the workflow) is always done near the end of the chain, after bloom & auto exposure has been applied.

Bloom is a lens defect. Color grading is an image effect.

**Comment by RamiroOliva** [comment]
Makes sense although maybe I'm after another kind of effect. Thanks.

I hope to illustrate the issue with this example.
Say I want to apply an ink style effect using a bitonal or black and white palettized  LUT.

If I apply LUT after the bloom effect, the bloom can't spread smoothly - white pixels won't glow smoothly because the LUT is applying a threshold to the framebuffer.

However, if I apply LUT before bloom, the glow is preserved. In this case the color transformation must be done in HDR of course to preserve bright spots. I'm just changing the hues and not the brightness. That's why I say maybe I'm looking after a different effect.

**Comment by Chman** [comment]
If you need a custom color swapping effect to happen before bloom then you can actually do it [via a custom effect](https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects). Make sure to inject it `BeforeStack` and it'll work the way you want.
