### ISSUE TITLE
Pure transparency in image becomes visible with Ambient Occlusion

### ISSUE THREAD

**Issue by JPhilipp** [Unity-Technologies/PostProcessing#529]
Using PostProcessing stack v2, when Scalable Ambient Obscurance is used, e.g. quad mesh surfaces which have images with transparency and the "Fade" rendering mode in the standard shader picked, get colored in with a visible shade where they should be invisible as it's full alpha -- see the green rings/ quads in below image:

![1](https://user-images.githubusercontent.com/1754503/38742647-6fdba53a-3f3d-11e8-861c-485f6b19e238.png)

Using Multiscale Volumetric Obscurance, the issue disappears (but that's also giving a bit of a different look for the ambient occlusion):

![2](https://user-images.githubusercontent.com/1754503/38742652-72908cbe-3f3d-11e8-8b1a-44d3367c58b6.png)

Thanks for the great PostProcessing module!

PS: Is there an official documentation on the differences between the two methods? I'd greatly appreciate knowing.

**Comment by Chman** [comment]
I'm not able to reproduce this issue on my side. Screenshot using SAO and a fade material:

![image](https://user-images.githubusercontent.com/849090/38743532-99511a24-3f3f-11e8-9074-3f0f6f156fd9.png)

I'm gonna need more infos:
- Unity version
- Rendering path (forward, deferred)
- HDR on/off
- Gamma/Linear

**Comment by JPhilipp** [comment]
Thanks for the fast reply!

- The Unity version is 2018.1.0b10, the same as in the screenshots
- The Rendering Path is Forward
- "Allow HDR" is ticked on the camera, not sure if that means it's on
- Color space is Linear

The shader rendering mode is set via script using (we're hoping to match "Fade"):

```
material.SetInt( "_SrcBlend", (int)UnityEngine.Rendering.BlendMode.SrcAlpha );
material.SetInt( "_DstBlend", (int)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha );

material.DisableKeyword("_ALPHATEST_ON");
material.EnableKeyword("_ALPHABLEND_ON");
material.DisableKeyword("_ALPHAPREMULTIPLY_ON");

material.SetFloat("_Metallic", 0f);
material.SetFloat("_Glossiness", 0.25f);
```

Thanks!

**Comment by JPhilipp** [comment]
Good news -- the issue disappears if we manually set Rendering Mode to "Fade". There must be something missing in above runtime settings to get it into Fade mode?

**Comment by JPhilipp** [comment]
Update: It all works once

`material.SetOverrideTag("RenderType",` "Fade");

is used, presumably PostProcessing2 checks against this in logic, so all great now!

I'm closing this issue, thanks!
