### ISSUE TITLE
shader compile error on Vulkan

### ISSUE THREAD

**Issue by sunxdc15** [Unity-Technologies/PostProcessing#531]
Shader error in 'GaussianDownsample.compute': '' : compilation terminated at kernel KMain at line 68 (on vulkan)
Shader error in 'GaussianDownsample.compute': 'assign' : cannot convert from 'temp highp float' to 'temp highp int' at kernel KMain at line 68 (on vulkan)
Post-processing stack version (v1, v2)?
v2

Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 5.6.5f1,  Windows 7 64bit, Android(Vulkan)

there is a same issure in unity2017 which already fixed, but not for Unity5.6

**Comment by Chman** [comment]
This is a bug in the shader compiler for Vulkan on 5.6. Considering that this version is nearing end-of-life and Vulkan is marked as Experimental there (which means you're not supposed to use it for production work) I wouldn't expect the team working on Vulkan to do a backport for the fix that was introduced in 2017.1 (if it's even possible, a lot happened between these two versions).
