### ISSUE TITLE
2D DOF

### ISSUE THREAD

**Issue by neoneper** [Unity-Technologies/PostProcessing#533]
there is forecast for 2D resource compatibility?
In expecion DOF!

**Comment by Chman** [comment]
DoF expects a depth map, 2D doesn't have one, being 2D (and most sprites being rendered as transparent). So no, unless you provide a custom depth map DoF won't work in 2D. You could potentially fake it by layering your 2D elements and compositing DoF passes but this is quite a specific use case and would benefit strongly from a custom scriptable render pipeline for performance reasons.
