### ISSUE TITLE
Wiki/components don't explicitely say layer needs to be set regardless if global or not

### ISSUE THREAD

**Issue by m4a4** [Unity-Technologies/PostProcessing#537]
##### What happened?
Tried setting up v2 for the first time. Read the wiki where the layer info says "so don't forget to change it or **local** volumes won't have any effect." and assumed it doesn't apply to a **global** volume.

Component warning for layer also makes mention of a "trigger", which also led me to assume that global (which doesn't use a trigger) would work.

I suggest clearly labeling wiki/component warning that it will not work until a layer is set regardless if it's global or not.

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
N/A

**Comment by Chman** [comment]
Good catch, thanks. I removed the reference to local volumes and added a quick sentence about the trigger field:

> Setting this field to `None` will disable local volumes for this layer (global ones will still work).
