### ISSUE TITLE
ProjectSettings scriptingDefineSymbols multiple UNITY_POST_PROCESSING_STACK_V2 defines

### ISSUE THREAD

**Issue by svenneve** [Unity-Technologies/PostProcessing#541]
##### What happened?
ProjectSettings.asset file has multiple duplicate scriptingDefineSymbols for UNITY_POST_PROCESSING_STACK_V2
Not a big disaster, but SVN keeps wanting to commit the file when there are no real changes, and reverting doesn't help as the duplicates get added again.

##### Post-processing stack version (v1, v2)?
2.0.4-preview

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2.0f3, Standalone x86-64

**Comment by Chman** [comment]
I'm afraid I can't reproduce this no matter what I do :/

`UNITY_POST_PROCESSING_STACK_V2` should only be added once to the define list as it will just skip it if it already exists.

**Comment by svenneve** [comment]
The problem only manifests in the actual ProjectSettings file, if I remove the extra definitions, they get added again. It doesn't seem harmful, and I'm already short on time, so I'll try to figure out if it is a script on my end when I have the time somewhere in the future.

This is what it looks like in my project settings file : 
`  scriptingDefineSymbols:
    1: AMPLIFY_SHADER_EDITOR;DO_PUSH_OUT;DEBUG_MENU;UNITY_POST_PROCESSING_STACK_V2
    4: UNITY_POST_PROCESSING_STACK_V2
    7: UNITY_POST_PROCESSING_STACK_V2
    13: UNITY_POST_PROCESSING_STACK_V2
    17: UNITY_POST_PROCESSING_STACK_V2
    18: UNITY_POST_PROCESSING_STACK_V2
    19: UNITY_POST_PROCESSING_STACK_V2
    20: UNITY_POST_PROCESSING_STACK_V2
    21: UNITY_POST_PROCESSING_STACK_V2
    22: UNITY_POST_PROCESSING_STACK_V2
    23: UNITY_POST_PROCESSING_STACK_V2
    24: UNITY_POST_PROCESSING_STACK_V2
    25: UNITY_POST_PROCESSING_STACK_V2
    26: UNITY_POST_PROCESSING_STACK_V2
    27: UNITY_POST_PROCESSING_STACK_V2`

**Comment by Chman** [comment]
What you're seeing is actually a list of define per platform (`1`, `4`, `7` etc are platform IDs, this is a Unity thing), not duplicate. Once they're added to the file they should stay that way and not be added anymore (unless you remove them, in which case it'll trigger a re-add).

**Comment by svenneve** [comment]
Aah, so it's just a misunderstanding on my part on Unity's inner workings, not a bug...learned something new today :)
Cheers.
