### ISSUE TITLE
ArgumentException: Invalid shader () in UnityEngine.Rendering.PostProcessing.PropertySheetFactory.Get

### ISSUE THREAD

**Issue by couleurs** [Unity-Technologies/PostProcessing#544]
##### What happened?
Everything works fine in the Editor in Scene and Game modes, but when I build and run my app with my CustomPostProcessor enabled, I get these errors and eventually a crash after 30-60 seconds.

When I build in development mode, the log says:

`ArgumentException: Invalid shader () at UnityEngine.Rendering.PostProcessing.PropertySheetFactory.Get (UnityEngine.Shader shader) [0x0008f] in C:\Users\johanismael\Documents\GitHub\Unity_Experiments\PointCloudEngine\Assets\PostProcessing\Runtime\Utils\PropertySheetFactory.cs:40 
  at CustomPostProcessorRenderer.Render (UnityEngine.Rendering.PostProcessing.PostProcessRenderContext context) [0x00058] in C:\Users\johanismael\Documents\GitHub\Unity_Experiments\PointCloudEngine\Assets\CustomPostProcessing\CustomPostProcessor.cs:106`

Full log: 
[output_log.txt](https://github.com/Unity-Technologies/PostProcessing/files/1944773/output_log.txt)

What I don't understand is that my custom shader seems to compile fine in the Unity Editor (I don't have any warning or error about it), I only see the problem when I build and run. Line 106 of my CustomPostProcessor.cs is:

`
var sheet = context.propertySheets.Get(Shader.Find("Hidden/CustomPostProcessor"));
`

I wonder if for some reason referencing the shader with "Hidden/CustomPostProcessor" works in regular Unity but it's not a proper way to fetch the shader in the build package?

For what it's worth, I get the exact same issue when copy/pasting the Grayscale example from the wiki:
https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects

Thanks for your help!

##### Post-processing stack version (v1, v2)?
v2 pulled on 4/24/2018

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.3.1f1, Oculus VR, Windows Razor laptop

**Comment by couleurs** [comment]
I wonder if for some reason referencing the shader with "Hidden/CustomPostProcessor" works in regular Unity but it's not a proper way to fetch the shader in the build package?

**Comment by couleurs** [comment]
I think I figured it out thanks to the Shader.Find documentation. More specifically:

"Note that a shader might be not included into the player build if nothing references it! In that case, Shader.Find will work only in the editor, and will result in pink "missing shader" materials in the player build. Because of that, it is advisable to use shader references instead of finding them by name. To make sure a shader is included into the game build, do either of: 1) reference it from some of the materials used in your scene, 2) add it under "Always Included Shaders" list in ProjectSettings/Graphics or 3) put shader or something that references it (e.g. a Material) into a "Resources" folder."

After adding my custom shader to "Always Included Shaders" list, the issue is gone. Might be good to add that in the Grayscale example in the wiki so people don't forget to do that when they add a custom post-processor.

Thanks!

**Comment by southrad69** [comment]
I LOVE YOU GUYS!!!!! THANKS A LOT!!
