### ISSUE TITLE
Compatibility with Physical Camera

### ISSUE THREAD

**Issue by vertxxyz** [Unity-Technologies/PostProcessing#555]
##### What happened?
Add a Post Process Layer to a Camera with the new Physical Camera setting enabled and it will force-disable the Physical Camera, making them completely incompatiable with each other.
This is likely because of #546 

##### Post-processing stack version (v1, v2)?
v2

##### Unity version
2018.2.0b3

**Comment by gabgue** [comment]
Two new betas after this issue was reported and the problem continues, any info about when will be fixed? thanks.

**Comment by Chman** [comment]
Fixed in latest merge.
