### ISSUE TITLE
[VR][Singlepass Render Path][V2] Bloom not applied correctly

### ISSUE THREAD

**Issue by m4a4** [Unity-Technologies/PostProcessing#556]
##### What happened?
Bloom in singlepass is not correct, but is correct in multipass.
![untitled](https://user-images.githubusercontent.com/19275489/39830190-a97bbc8e-538e-11e8-9908-bf480996acac.png)

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.2.2p3
Windows 10
Vive using SteamVR Unity plugin

**Comment by nerites** [comment]
Fix is in https://github.com/Unity-Technologies/PostProcessing/pull/671, which has been merged into v2. Closing!
