### ISSUE TITLE
[V2] Bloom is still "wobbling"

### ISSUE THREAD

**Issue by oyvind-stromsvik** [Unity-Technologies/PostProcessing#559]
##### What happened?

The bloom effect is still seemingly following a coarse grid rather than moving smoothly across the screen. I reported this back in 2017 on the forums, but nothing came from it as far as I remember.

If you have an object with bloom and you move the camera the bloom is not moving smoothly with the object, but rather it appears to wobble as if it's jumping from one spot on a grid to another.

I feel like this effect is extremely visible in almost any scene and I avoid the post-processing stack for that reason. I feel like I remember someone commenting that this was caused by the bloom operating on a downscaled resolution or something, and if so I'd like an option for it to not be downscaled.

##### Post-processing stack version (v1, v2)?

Version 2.0.5-preview. This "wobbling" has always been the case with version 2 of the post-processing stack as far as I know.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1.0f2, Windows 10, Windows, but I'm mostly testing in the editor.

**Comment by racarone** [comment]
I was having the same problem - it's unusable in VR. I fixed the problem using different a down-sampling method. I created a pull request for the issue here: #564

**Comment by oyvind-stromsvik** [comment]
> // Do bloom on a half-res buffer, full-res doesn't bring much and kills performances on
> // fillrate limited platforms

Found that in your commit so guess I should be able to test what I'm asking myself. :) Will test your PR when I have some spare time and report back if the issue is fixed as well.

**Comment by racarone** [comment]
> Does that mean it could be used without downsampling as well?

No, that's where the blur happens ;)

> Does that improve the look of the bloom at all?

Here's a comparison with the same settings (box is what's currently used). You can clearly see the stepping in the box blur.

![Bloom Comparison](https://www.dropbox.com/s/2h1bxbjmqspvxl1/Box_v_Gaussian.gif?raw=1)

> Found that in your commit so guess I should be able to test what I'm asking myself. 

That was actually already part of the code, I just left it.

**Comment by oyvind-stromsvik** [comment]
> That was actually already part of the code, I just left it.

Yeah, I know, I just meant that the code seemed understandable enough that I could test with a full resolution buffer myself to see if I could see a difference or not. I'm not sure if we're talking about the same thing, but then again I may not understand how this works at all, which is very likely. :p I was thinking I could change those lines below that comment to run the bloom on a full-res buffer and thus get a higher quality bloom at a performance cost. And further I was thinking this could be a setting in the inspector where you could choose between full-res, half-res, quarter-res etc. But now I'm talking about something I have no experience with, so I will have to fiddle with this first to see how it all fits together.

Your example captures the wobble nicely. This artefact has been so noticeable for me that it almost seemed odd anyone could use this asset for anything other than still images. Can't wait to try out your changes and hopefully this will be fixed in the master branch soon enough.

**Comment by oyvind-stromsvik** [comment]
Tried it out in a couple of my projects now and first impressions are that it looks really nice. It never wobbles or flickers and it just overall looks as good as the best blooms I've tried for Unity. Miles better than the default implementation in this package to say the least, which wobbles even if you change it to run at full resolution.

It also looks a lot better than the default bloom as it has a very squarish appearance while this one is perfectly round and smooth.

It does make the bloom a fair bit bigger though, as shown in your example, but I don't mind, that just requires some minor tweaks to the intensity and/or diffusion.

This was the part I talked about with the downsampling:
https://github.com/Unity-Technologies/PostProcessing/pull/564/commits/364834d7cca0bd43bea7ff411e9bdc27643adb49#diff-abfe8dc778f999596bb7b16ff716b0dbR114

In some scenes I could even reduce it to a quarter size or even an eight size and it still looked nicer than the default bloom at full size. Which is why I feel this should be a setting allowing us to configure in the inspector the quality vs performance in terms of the resolution size for the bloom. This is of course unrelated to your changes, but I just feel it's weird how someone has hardcoded a seemingly random value like 1/2 in there and the only way to change it is to change the source code.

**Comment by Chman** [comment]
Hey,

A few notes:
- Current bloom isn't box unless you toggle "fast mode". Non-fast is box13 on downsampling + tent9 on upsampling, which results in a gaussian. That doesn't mean it won't wobble though. An anti-flicker pass would help but add to the cost. TAA helps a lot as well but mostly in non-VR.
- We can't use the gaussian pyramid (and thus can't merge your PR @racarone) because it would make bloom dependent on compute shaders and unfortunately we need to support a lot of platforms that can't use them (most of the mobile market & webgl come to mind). I'd love to though, especially in HDRP where a gaussian pyramid is already available (that would make bloom "free") but the reality is that we have a set of constrains on v2 at the moment and we can't go full-on compute **_yet_**.
- Proper VR support is, sadly, not fully there yet. I don't have much bandwidth left unfortunately but VR people have plans for it.

**Comment by oyvind-stromsvik** [comment]
That's disappointing to hear. I even feel like the example above is a very mild example of the problem and that it's much more visible in a some of my actual projects.

I use TAA in all my projects and don't feel like it helps at all to alleviate this problem. The wobble has nothing to do with tiny bright pixels or shimmer which I feel TAA handles well, but rather it's just the blur itself which doesn't look smooth in motion. The bigger and brighter the bloom the more noticeable the wobble, ie. very noticeable for something like a sun disc or a bright lamp.

Increasing the buffer size to full resolution helps a bit though so I feel like this setting should be exposed in the inspector rather than being hard-coded to be half resolution.

**Comment by racarone** [comment]
> Current bloom isn't box unless you toggle "fast mode". Non-fast is box13 on downsampling + tent9 on upsampling, which results in a gaussian. That doesn't mean it won't wobble though. An anti-flicker pass would help but add to the cost. TAA helps a lot as well but mostly in non-VR.

Well the point was mainly it isn't working ;) Unfortunately none of these will really solve the issue either...

> We can't use the gaussian pyramid (and thus can't merge your PR @racarone) because it would make bloom dependent on compute shaders and unfortunately we need to support a lot of platforms that can't use them

Why not add checks for compute shader support and a quality option? I wasn't expecting a merge, but wanted to throw the code out there as an option for a quick and dirty fix. Either way the current implementation needs work.

>  I'd love to though, especially in HDRP where a gaussian pyramid is already available (that would make bloom "free") but the reality is that we have a set of constrains on v2 at the moment and we can't go full-on compute yet.

First thing I thought of before seeing the SSR implementation! ;)

> Proper VR support is, sadly, not fully there yet. I don't have much bandwidth left unfortunately but VR people have plans for it.

The stereo fix in the PR still applies to the current version, which isn't working on a double wide texture, which is what #556 is referencing. `PostProcessRenderContext` doesn't seem to be returning double wide texture sizes in single pass stereo.

**Comment by Invertex** [comment]
> Why not add checks for compute shader support and a quality option? I wasn't expecting a merge, but wanted to throw the code out there as an option for a quick and dirty fix. Either way the current implementation needs work.

I'm guessing, like with the V1, they'd rather focus on getting this post-processing working solid and in a "finished" state so they can move onto a "v2.5" "NextGen PostProcessing" package that doesn't need all those checks and the spaghetti work slowdown.

**Comment by sasa42** [comment]
Any news on the Bloom wooble in SinglePassStereo from the VR team. 
You could change the name from Bloom to Stroboscop  if SinglePassStereo for fast fix.

**Comment by nerites** [comment]
Hey sasa42, I started looking at this yesterday and I don't have a fix yet, but you can try this:
https://github.com/Unity-Technologies/PostProcessing/compare/v2_stereo_bloom

It doesn't fix the flicker, but it makes it less obvious for similar reasons as the buffer resolution increase mentioned earlier.

The number of times we downsample is calculated in part based on the width of the texture, and since the single-pass stereo texture is twice as wide as the image you'd see in each eye, we were downsampling too much relative to the image width.

**Comment by nerites** [comment]
Hey, the fix for the wobble issue is now available here: https://github.com/Unity-Technologies/PostProcessing/pull/671

Since this is my first PP fix I'm gonna wait until chman takes a look before merging it. (: Thanks for your patience.

**Comment by nerites** [comment]
PR has made it into V2- closing issue.
