### ISSUE TITLE
FXAA anti-aliasing is applied after grain effect

### ISSUE THREAD

**Issue by LKGames** [Unity-Technologies/PostProcessing#56]
FXAA seems to be applied after the entire Uber shader, meaning that all effects taking place inside it will be smoothed out, which is a problem for effects such as Grain and Dithering. TAA doesn't seem to do that.

**Comment by Chman** [comment]
There's a PR in review for this issue (#96 or you can check the [aa-fixes](https://github.com/Unity-Technologies/PostProcessing/tree/aa-fixes) branch), feel free to try it and let us know !

**Comment by Kink3d** [comment]
This has been merged to master
