### ISSUE TITLE
[V2] SetVector expect VectorX not VectorXParameter

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/PostProcessing#567]
##### What happened?

- SetVector will happily take Vector2 but can't take Vector2Parameter.
- From code it seems GetValue should return Vector2, but likely because it can't do a Vector2 to Vector4 auto conversion.
- This isn't really a bug, just an inconsistency with how the document portray Parameter. In this case Vector2Parameter.value is necessary.

##### Post-processing stack version (v1, v2)?

V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1 (latest stable)

**Comment by Chman** [comment]
That's a language limitation (although I'm not sure if it's Unity/Mono specific or applies to even the most recent C# release).

Basically, `Vector2Parameter` can be implicitly converted to `Vector2`, and `Vector2` can be implicitly converted to `Vector4` but it seems like you can't have a double implicit cast (`Vector2Parameter` -> `Vector2` -> `Vector4`). This would work:

```
sheet.properties.SetVector("_MyVec2", (Vector2)settings.vec2Param);
```

With that said, we can easily work around it by adding implicit conversions from `Vector2Parameter` to `Vector3` and `Vector4`. I'll leave this opened so I don't forget about it.

**Comment by Chman** [comment]
Workaround pushed in f3b7537.
