### ISSUE TITLE
Effects are being applied to the Scene viewport

### ISSUE THREAD

**Issue by rsodre** [Unity-Technologies/PostProcessing#57]
If It's a camera effect, should be applied only to the camera, not to the Editor Scene viewport.
Even gizmos and canvases are affected, as seen on the screenshot.
![screen shot 2017-01-05 at 22 19 46](https://cloud.githubusercontent.com/assets/229161/21702856/384e20d0-d395-11e6-8617-82facec7232f.png)

**Comment by LKGames** [comment]
You can turn them off:
![image-effects-toggle](https://cloud.githubusercontent.com/assets/8087208/21703013/7227a71c-d3af-11e6-87a5-0931bde2d486.png)

**Comment by rsodre** [comment]
Cool, never noticed that. Thanks.
