### ISSUE TITLE
Dont work with 2018

### ISSUE THREAD

**Issue by WarheadDesignz** [Unity-Technologies/PostProcessing#570]
##### What happened?
Just doesn't work at all. (literally), just doesn't do anything. Even selected "Everything" for the layers, etc.

##### Post-processing stack version (v1, v2)?
v2, however v1 Color Correction doesn't work. Complains about something missing.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.0.1f1 and 2018.1.1f1 (OS) - Windows for V2, and Windows and Xbox One for v1.

**Comment by alaslipknot** [comment]
Same exact issue.

**Comment by Chman** [comment]
Have you followed [this guide](https://github.com/Unity-Technologies/PostProcessing/wiki/Quick-start)?

It works fine in all our tests here on 2018.1 and 2018.2. If you really can't make it work, please post your project so we can take a look at it.

**Comment by WarheadDesignz** [comment]
You must be good luck, because now it randomly works. Perhaps my old project was corrupted from it some how. Well, it still didn't appear to work at first this time, everything was zeroed out and had no working settings. So I had to enable everything just to get it a setting that even showed a changed result.

Is this supposed to be superior to Post Stack V1? Because wow, just added some random values and it looks even more AAA than having a perfectly setup PStack V1 lol.

**Comment by WarheadDesignz** [comment]
I'm having trouble understanding this though.

If I leave layer to "everything" it works, but if I give it a dedicated layer. It just stops working.
How's it supposed to put the effect on things it can't see?

**Comment by Chman** [comment]
I really recommend going through the [quickstart guide](https://github.com/Unity-Technologies/PostProcessing/wiki/Quick-start):

> **Layer**: a mask of layers to consider for volume blending. It allows you to do volume filtering and is especially useful to optimize volume traversal. You should always have your volumes in dedicated layers instead of the default one for best performances. By default it's set to `Nothing` so don't forget to change it or volumes won't have any effect.

So, layers are used to filter volumes to be used for a given PostProcessLayer so you can have multiple volumes only affect some cameras and not others. It relies on the existing layer system in Unity so if you never used them I recommend [looking at the doc](https://docs.unity3d.com/Manual/Layers.html) on this subject as it gives a nice overview :)

**Comment by WarheadDesignz** [comment]
Thank you I got it working now :)
