### ISSUE TITLE
Writing custom effects and library path question

### ISSUE THREAD

**Issue by RamiroOliva** [Unity-Technologies/PostProcessing#571]
Hi,

I'm translating some image effects to the new PPS2 architecture and I need to include the libraries from PPS2. The following line is included in my shader:

#include "PostProcessing/Shaders/StdLib.hlsl"

Is there any methodology to properly setup the include folders? Because currently custom image effects and PPS2 can be deployed anywhere (when imported from Github). So I wonder if there's anyway to get the installation path as a global macro inside Unity Editor.

More generally speaking, what's the safe way of including the PPS2 libraries in custom written image effects that can be stored anywhere in the project?

**Comment by Chman** [comment]
In 2018.1 you can use the [`ShaderIncludePath`](https://docs.unity3d.com/2018.1/Documentation/ScriptReference/ShaderIncludePathAttribute.html) attribute. It is [already used in Post-processing](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Editor/Utils/PostProcessShaderIncludePath.cs) so you won't need to do anything to make it work.

Basically, it should already work out-of-the-box for you no matter where Post-processing is in the Assets folder as long as you use:

```
#include "PostProcessing/Shaders/StdLib.hlsl"
```

in your shaders and not hardcoded absolute/relative paths. Post-processing is already added to the global shader include path. This only works starting with 2018.1 though, if you need it for an earlier version of Unity you will have to hardcode the path unfortunately.

Let me know if you have any problem with it as this. This is quite a recent feature but it's been proven to work well for SRPs already.
