### ISSUE TITLE
post processing v2 pipline

### ISSUE THREAD

**Issue by odiecc** [Unity-Technologies/PostProcessing#575]
where can i find out the post-processing v2 pipline

**Comment by Chman** [comment]
Not sure I understand the question but I assume you're looking for a "download" button? Here's the [documentation page](https://github.com/Unity-Technologies/PostProcessing/wiki/Installation) about it.

**Comment by odiecc** [comment]
I'm looking for something like this picture
![image](https://user-images.githubusercontent.com/30138784/40928452-05b02d08-6854-11e8-9f2c-c92dc8531561.png)

this is UE4 post processing pipline
I want to find out about Unity

**Comment by Chman** [comment]
We don't have any UML shot like that for the current pipeline, you'll have to dig through the source code I'm afraid. Specific mobile optimizations are still being worked on.
