### ISSUE TITLE
Transition from Package Manager release to Git release breaks profiles

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/PostProcessing#577]
##### What happened?

I was trying to replace the Post Processing V2 installed by Package Manager with the latest Git release.

- My steps involves adding the git version into my project, and then remove the package manager install via UI.
- All existing post-processing script and profile breaks.
- Even though I don't have any errors in console, Unity still doesn't allow me to select a script for profiles, hence they remained broken.
- I have tried restarting Unity, problem remains.

<img width="374" alt="screen shot 2018-06-01 at 2 08 39" src="https://user-images.githubusercontent.com/1484279/40799713-eadc7b6e-6540-11e8-9e6d-3fccd3bb6da3.png">

##### Post-processing stack version (v1, v2)?

v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1 + macOS 10.13.4

##### EDIT

I also saw this error being thrown repeatedly when I click on the broken profiles.

But there are no console errors from my code.

```
NullReferenceException
UnityEditor.InspectorWindow.HasLabel (UnityEngine.Object target, System.String assetPath) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:646)
UnityEditor.InspectorWindow.GetInspectedAssets () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:656)
UnityEditor.InspectorWindow.DrawPreviewAndLabels () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:678)
UnityEditor.InspectorWindow.OnGUI () (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:448)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:291)
UnityEditor.HostView.Invoke (System.String methodName) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:284)
UnityEditor.HostView.InvokeOnGUI (Rect onGUIPosition) (at /Users/builduser/buildslave/unity/build/Editor/Mono/HostView.cs:251)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by realJakubSmaga** [comment]
Have you tried right clicking on those profiles and re-importing them?

**Comment by bitinn** [comment]
- Re-import: didn't fix it
- Deleting PostProcessing folder and adding it again: fixed it.

Weird, but I will take it

**Comment by Chman** [comment]
> My steps involves adding the git version into my project, and then remove the package manager install via UI.

This is the main issue here (and it's an interesting workflow 'gotcha'). If you add the git version before you remove the package one then you'll get a meta-file collision as you'll end up with post-processing being imported twice into your project. It's exactly as if you'd import post-processing twice in two separate folders.

The correct way to do it would be to:

1. Remove the package (don't worry about your profiles, they'll still be serialized properly)
2. Import the git version
3. Profit
