### ISSUE TITLE
Is calling DisableKeyword required to select the correct shader variant?

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/PostProcessing#578]
##### What happened?

I am trying to make my multi_compile post processing shader work, my code is something like following:

in shader

```
	#pragma multi_compile __ _FOGMACHINE_DEBUG_OFF _FOGMACHINE_DEBUG_DEPTH _FOGMACHINE_DEBUG_VOLUME _FOGMACHINE_DEBUG_GRADIENT _FOGMACHINE_DEBUG_STEP _FOGMACHINE_DEBUG_SCATTER
```

in renderer

```
			var sheet = context.propertySheets.Get(_ActiveShader);

			var debugMode = this.settings._DebugMode.value;
			if (debugMode == DebugModeType.Depth) {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_DEPTH");
			} else if (debugMode == DebugModeType.Volume) {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_VOLUME");
			} else if (debugMode == DebugModeType.Gradient) {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_GRADIENT");
			} else if (debugMode == DebugModeType.Step) {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_STEP");
			} else if (debugMode == DebugModeType.Scatter) {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_SCATTER");
			} else {
				sheet.EnableKeyword("_FOGMACHINE_DEBUG_OFF");
			}
```

And here is my problem:

- I find myself need to manually call `DisableKeyword` for all other keyword, otherwise `_FOGMACHINE_DEBUG_OFF` remains on.

- I tried a few shader pragma variation, including not using `__` or omit the `OFF` variant, but couldn't find a workaround where I don't have to call `DisableKeyword` to overwrite existing value.

- However, no built-in effects actually use `DisableKeyword`, leading me to believe I am missing something.

What's the trick here?

##### Post-processing stack version (v1, v2)?

v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

macOS 10.13.4 + Unity 2018.1 + Metal API

**Comment by Chman** [comment]
You should call `DisableKeyword` because shader variant states on materials have always been global in Unity.

With that said, there's indeed a faster way as you noticed. Simply call `ClearKeywords()` on your property sheet before setting keywords. [Here's how it looks in the ColorGrading](https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Runtime/Effects/ColorGrading.cs#L318) effect for instance.

**Comment by bitinn** [comment]
Thx! `ClearKeywords` is right in front of me yet I missed it.
