### ISSUE TITLE
Lens flares not showing up in game view.

### ISSUE THREAD

**Issue by VladErc** [Unity-Technologies/PostProcessing#579]
##### What happened?
I have an empty scene on which I've only added a sky box, directional light and single camera. On the directional light I've configured Unity's lens flare component which works great in the "Scene View" tab.

As soon as I add the post processing volume in the scene and/or the component on the camera, the flare doesn't appear in "Game view" anymore whilst still being visible in the "Scene view". Even if I disable the components, I have to completely remove them in order to have the flare show in game.

##### Post-processing stack version (v1, v2)?
Post processing stack version 2.

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version 2017.2 on Standalone Windows 10.

**Comment by VladErc** [comment]
I see there's no way to delete this. I'm sorry for creating it but after four days I've finally figured out that some of my code went missing and the Flare Layer wasn't getting attached to the right camera. So sorry.

**Comment by idchlife** [comment]
@VladErc did you encounter lately same issue with 2018.2.2f1? I'm using standard assets lens flare and problem is the same, but there is no solution as for now. Reproduce is as simple as in your OP post.

**Comment by DeepInMind12345** [comment]
Now i am working on 2019.2.2, it do on scene view, but it not working on game view.
