### ISSUE TITLE
Option to apply effects before or after canvases

### ISSUE THREAD

**Issue by rsodre** [Unity-Technologies/PostProcessing#58]
Please, let us choose if the Post Effects will be applied before or after canvases in "Screen Space - Camera" more. Currently it will always be applied after, including the canvas. Usually a HUD don't need the same effects as the game itself.

I know that if set the canvas to "Screen Space Overlay" I will get the same result, but working with Screen Space Camera is waaaaay much better, because we can have a very nice and clear notion on where the canvas elements are positioned relative the the game scene. When using Overlay, the canvas is a huge useless mess inside the Scene viewport, and there's no Plane Distance and sorting order.

Currently to achieve this result, I set my canvas to Camera (so I can work nicely with it in the Editor), and attach a small script that changes it to Overlay when the game starts.

**Comment by Kink3d** [comment]
Hi,

The recommended way to achieve this in Unity is to use separate cameras at different depths and use Layers and the Camera's Culling Masks to tell each camera what to render.

See: [https://docs.unity3d.com/Manual/Layers.html](https://docs.unity3d.com/Manual/Layers.html)

Please reply to reopen the issue if you require further assistance

Thanks
