### ISSUE TITLE
The nested type `MonitorSettings' does not exist in the type `UnityEngine.PostProcessing.PostProcessingProfile'

### ISSUE THREAD

**Issue by JeromeJ** [Unity-Technologies/PostProcessing#581]
##### What happened?

After messing with some Editor script (I tried automating building), I get this error twice. It persists until Unity is restarted.

    The nested type `MonitorSettings' does not exist in the type `UnityEngine.PostProcessing.PostProcessingProfile'
    error CS0426: Assets/PostProcessing/Editor/Monitors/HistogramMonitor.cs(7,49)

    The nested type `MonitorSettings' does not exist in the type `UnityEngine.PostProcessing.PostProcessingProfile'
    error CS0426: Assets/PostProcessing/Editor/PostProcessingMonitor.cs(6,78)

##### Post-processing stack version (v1, v2)? 

v1.0.4

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Win10.

**Comment by Chman** [comment]
> After messing with some Editor script

What did you mess with exactly? Did you customize the post-processing code?

**Comment by JeromeJ** [comment]
Well, I removed it because I wasn't requiring Post Processing Stack yet and I was blocked because of the error.

I tried reproducing it, did a fresh install of PPS and the error didn't happen anymore. I'm closing the issue.

(I did not modify it and I was merely using `BuildPipeline.BuildPlayer`, after executing it, the error would raise even though nothing apparently got modified - git status was empty)

**Comment by laurentg-nvizzio** [comment]
Got the exact same issue on one of our build machines at work.
Suspecting that the Library folder was containing corrupt data (as it sometimes does), I launched a Reimport All which promptly caused Unity to fail upon trying to move a file...

This really looks like a Library consistency issue.
