### ISSUE TITLE
[V2] Debug overlay shader for depth visualization, add normalized depth (ie. Linear01Depth)

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/PostProcessing#585]
##### What happened?

I think it would be great to have a normalized depth visual overlay. Due to platform differences, most people probably work with normalized depth. Looking at a non-linear depth probably isn't as useful.

ref:

https://github.com/Unity-Technologies/PostProcessing/blob/v2/PostProcessing/Shaders/Debug/Overlays.shader#L24

##### Post-processing stack version (v1, v2)?

V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1 + macOS + Metal.

**Comment by Chman** [comment]
Good call. Done in a57e7bb, I made it optional.
