### ISSUE TITLE
Will we have Focus point solution for DoF

### ISSUE THREAD

**Issue by wdw89** [Unity-Technologies/PostProcessing#588]
When doing cinematic, a focus point is very useful to auto change Dof effect. Because the distance value is hard to change in realtime. There is continuous auto focus function in real world camera. So I wish we can have a solution for v2 in the end.

**Comment by Chman** [comment]
Unity doesn't support referencing scene objects in assets, and post-processing profiles are assets so no, we can't directly link objects from the scene in depth-of-field. Note that this wouldn't be correct anyway as a focus point has to be aligned with the camera and an object could be located outside of its frustum (or worse, behind it).

You have a focus distance parameter instead, which is easily controlled via scripting if you really want to control it using a distance between an object and the camera.
