### ISSUE TITLE
Uber shader too havy 10 mb and run time 50 mb!!!

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#59]
Hi
Uber.shader have too many defines, as result in build ed game, take 10 mb:
 
 9.7 mb	 18.6% Assets/Plugins/PostProcessing/Resources/Shaders/Uber.shader

i think will be better just set empty (2x2)texture, if some features not used, it will have not performances impacts, and can ignore so big shader file

or not?

and please pay attention on run time size because it takes 50 mb run time! Its extremely huge, on iPhone 6 available only 600 mb.

**Comment by Kink3d** [comment]
This is due to the way our shader compiler works. Its not perfect and is currently being worked on but you wont see fix until 5.7+.

**Comment by fdsagizi** [comment]
as i understand in unity 5.7+ will improve work with big amount of combination shader ?

**Comment by andrew-grischenko** [comment]
Hey @Kink3d , it's still problem for me in Unity 2017.1.1 - I have this line in my build:
 11.3 mb	 21.6% Assets/PostProcessing/PostProcessing/Resources/Shaders/Uber.shader 
How can I reduce it?

**Comment by ErEllison** [comment]
me too , 
it is almost 
11.3 mb	 12.2% Assets/PostProcessing/Resources/Shaders/Uber.shader

what the hell is this !!!!!
