### ISSUE TITLE
[V2] Measuring performance without GPU profiler

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/PostProcessing#590]
##### What happened?

Unity GPU profiler support on macOS is problematic, we haven't been able to get it to work with Intel GPU. It's a bit ironic as Intel GPUs are exactly the ones we need to profile performance issues.

I known we can use `BeginSample()` and look at `OnPreCull()` in CPU profiler, but I believe they both only measure CPU time?

If I want to measure just how much time my custom image effect takes, without GPU profiler, is there a workaround using CPU profiler?

##### Post-processing stack version (v1, v2)?

V2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.1 + Metal + macOS 10.13.4

**Comment by Chman** [comment]
`BeginSample()` and the likes are CPU, yes. You can't use the CPU profiler to profile the GPU, so there's no "workaround".

My experience with MacOS X is quite limited to be honest, so hopefully someone else will jump in and give a good solution. Maybe there's some tool in Xcode you can use to analyse a frame capture... ?

But on Windows I mostly use Nsight (for Nvidia), Intel GPA (when running on an Intel IGP) and Razor (PS4) as they provide very precise numbers and very extensive details about what's truly going on the GPU compared to the builtin Unity profiler.

**Comment by bitinn** [comment]
Thx! I finally bite the bullet and try Intel GPA on macOS, and I have to say it's quite pleasant to use.

I think this answers my question so I am closing it.

<img width="640" alt="screen shot 2018-06-16 at 14 28 22" src="https://user-images.githubusercontent.com/1484279/41496408-fb72eac0-7171-11e8-92a7-ec77a3e0f2bc.png">
