### ISSUE TITLE
PostProcessEffectSettings activation doesn't work via script

### ISSUE THREAD

**Issue by sampaiodias** [Unity-Technologies/PostProcessing#593]
##### What happened?
Tried to make a C# script to get a Vignette from a profile, change its color and manually activate it. The color is modified correctly, but the activation part didn't. I tried using active = true and enabled.value = true but they don't activate the Color override from false to true. Without the activation via script, the color change will only be visible if I manually activate it via Inspector.

##### Post-processing stack version (v1, v2)?
v2 (downloaded the repository)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2017.1.1f1, Win7 64bits, targeting Android

**Comment by Chman** [comment]
Could you attach your script?

**Comment by sampaiodias** [comment]
using UnityEngine;
using UnityEngine.Rendering.PostProcessing;

public class BugPPSettingActivation : MonoBehaviour
{
    public PostProcessVolume volume;
    public Color color = Color.red;
    public int activationMethod = 0;

    [ContextMenu("Activate Vignette")]
    public void ActivateVignette()
    {
        var setting = volume.profile.GetSetting<Vignette>();
        setting.color.value = color;

        //None of these work when trying to activate a parameter that is currently deactivated
        switch (activationMethod)
        {
            case 0:
                setting.active = true;
                break;
            case 1:
                setting.enabled.value = true;
                break;
            case 2:
                setting.enabled.Override(true);
                break;
            case 3:
                setting.enabled.overrideState = true;
                break;
            case 4:
                setting.enabled = new BoolParameter() { value = true, overrideState = true };
                break;
            default:
                Debug.Log("Invalid Activation Method");
                break;
        }
    }
}

**Comment by sampaiodias** [comment]
To use the script above, attach it to a GameObject, modify the value of activationMethod (from 0 to 4), right-click the component and select Activate Vignette

**Comment by Chman** [comment]
Use `sharedProfile` unless you want to edit an instantiated copy for this specific volume. [Here's the doc](https://github.com/Unity-Technologies/PostProcessing/wiki/Manipulating-the-Stack#profile-editing) about scripting & postfx.

You're also confusing "enabling the overrides" and "overriding the enabled state of the effect in the stack". This is described [at the very end of this page](https://github.com/Unity-Technologies/PostProcessing/wiki/Quick-start) in the manual.

And finally, unless you already have marked `Color` to be overridden in the profile, don't use `setting.color.value` but `setting.color.Override()` so it'll mark it as overridden at the same time.

This works fine:

```csharp
using UnityEngine;
using UnityEngine.Rendering.PostProcessing;

public class Blah : MonoBehaviour
{
    public PostProcessVolume volume;

    Vignette GetVignette() { return volume.sharedProfile.GetSetting<Vignette>(); }

    [ContextMenu("Change Vignette Color")]
    public void ChangeVignetteColor()
    {
        GetVignette().color.Override(Random.ColorHSV());
    }

    [ContextMenu("Activate Vignette")]
    public void ActivateVignette()
    {
        GetVignette().enabled.Override(true);
    }

    [ContextMenu("Deactivate Vignette")]
    public void DeactivateVignette()
    {
        GetVignette().enabled.Override(false);
    }

    [ContextMenu("Enable Vignette Overrides")]
    public void EnableVignetteOverrides()
    {
        GetVignette().active = true;
    }

    [ContextMenu("Disable Vignette Overrides")]
    public void DisableVignetteOverrides()
    {
        GetVignette().active = false;
    }
}
```

**Comment by sampaiodias** [comment]
The method I'm building NEEDS direct access to the color variable, so I can't use the Override method. Also, I do want to use _profile_ instead of _sharedProfile_. I finally found a solution that works for me:

setting.color.overrideState = true;
return DOTween.To(() => setting.color.value, x => setting.color.value = x, color, duration);
