### ISSUE TITLE
Detecting installation of PPS

### ISSUE THREAD

**Issue by RamiroOliva** [Unity-Technologies/PostProcessing#595]
I would like to deactivate some shader code depending on whether PostProcessing is installed or not. Ideally it would be a compiler macro so I can do:

#if UNITY_PPS
...
#endif

So we can prevent errors when importing a package with effects based on PPS until it's properly installed. Is it possible?

**Comment by Chman** [comment]
Whenever Post-processing is importing into the project it'll set `UNITY_POST_PROCESSING_STACK_V2` so you can use that. That's what Cinemachine does to look for post-processing actually. Keep in mind that this flag isn't removed if the user manually remove post-processing from his project.

**Comment by RamiroOliva** [comment]
Unfortunately that flag is not available or recognized inside HLSL code - it only works in C#.

**Comment by Chman** [comment]
Yes it only works in C# because we didn't want to eat one more shader keyword for something a lot of people won't need as their amount is quite limited. To expose a define to a shader you need to create a variant which means you need to set it yourself on your shaders. [This page from the manual](https://docs.unity3d.com/Manual/SL-MultipleProgramVariants.html) gives a good overview of it.

**Comment by RamiroOliva** [comment]
Yeah, no more variant please. I meant an engine macro, which will be either set on any shader or not set. Like those defined here: https://docs.unity3d.com/Manual/SL-BuiltinMacros.html

**Comment by Chman** [comment]
We can't add engine macros from userland, and packages live in userland. So it won't be possible until the package manager allows us to set global macros.

**Comment by RamiroOliva** [comment]
> We can't add engine macros from userland

I guess you guys need to talk to someone else but this feature can make a lot (I mean a lot) easier for asset publishers to release assets that target builtin and SRPs in the same package.
