### ISSUE TITLE
Full ACES tonemapper is broken on Mac OS X.

### ISSUE THREAD

**Issue by KelSolaar** [Unity-Technologies/PostProcessing#6]
The full ACES tonemapper is broken on Mac OS X when using `#define TONEMAPPING_USE_FULL_ACES 1`, this might be an Open GL related issue although I couldn't verify it by comparing on Windows (where it works with Direct X 11) as changing the renderer to Open GL on that platform crashes the whole application.

**Fitted ACES Tonemapper on Mac OS X**
![image](https://cloud.githubusercontent.com/assets/99779/19407708/64dcf45c-9306-11e6-9164-5e084934096f.png)

**Full ACES Tonemapper on Mac OS X**
![image](https://cloud.githubusercontent.com/assets/99779/19407714/6bbd54b0-9306-11e6-8486-4a171e012bbb.png)

Cheers,

Thomas

**Comment by Chman** [comment]
Good catch, it may very well be an OpenGL issue as it hasn't been tested with this API yet. I'll try and take a look at it but at this point I can't say for sure that we'll fix it as it's not really supposed to be used in production (given how expensive it is), we only used it internally for reference purposes.

I'll leave this issue open anyway.

**Comment by Chman** [comment]
Fixed in 457db7c.
