### ISSUE TITLE
Depth of Field blur strength bound to kernel size

### ISSUE THREAD

**Issue by JohannesDeml** [Unity-Technologies/PostProcessing#60]
This is kind a follow up to issue #29.
The Depth of field is not only dependent on the resolution, but also on the kernel size. I do understand that a smaller kernel will blur less if applied to the same image, but it would be possible to apply the blur on a downscaled image in order to create a similar effect. This would make sense in my eyes, because the only logical reason to choose a smaller kernel is to save performance. If you now want to use different quality settings, I would think that I just change the kernel size, but the effect stays pretty much the same. Right now with this implementation it is not possible to create a strong blur with a small kernel size.

Did you try to downsample the image, but were disappointed by the flickering result? If so, is there a possibility to look at that version. Or is this implementation bound to other thoughts I didn't grasp so far?

**Comment by Kink3d** [comment]
I have moved your question to #29 and broadened the scope of that question.

Please check there for a response
