### ISSUE TITLE
Post-processing Stack 2.0.0-Beta5 on black background rgba (0,0,0,0) using no antialiasing and temporal antialiasing changed to r,g,b= random small number, a=0.

### ISSUE THREAD

**Issue by Mutimir** [Unity-Technologies/PostProcessing#603]
##### What happened?
Just adding  Post Process Layer to Main camera using Clear flags Solid color with rgba (0,0,0,0) with no effects used in Post Process Volume will change the rgb values of seemingly random pixels to small numbers between 1 and 12. On each pixel r=g=b. It happens with Anti-aliasing modes: No Anti-aliasing and Temporal Anti-aliasing.
##### Post-processing stack version (v1, v2)?
Post-processing Stack 2.0.0-Beta5
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version is Unity 2018.1.6f1, operating system is windows 10 pro.

**Comment by slime73** [comment]
The post processing stack applies dithering to the screen to help prevent banding artifacts, I believe.

**Comment by Mutimir** [comment]
You are right. It is using it. Thanks for the quick info.
