### ISSUE TITLE
Ambient Occlusion is not coloured correctly with Deferred Shading

### ISSUE THREAD

**Issue by cancinconn** [Unity-Technologies/PostProcessing#604]
The Ambient Occlusion effect does not produce the right colour when used with a camera set to use the Deferred rendering path. The effect produces a yellowish tint in a default Unity scene. It seems impossible to make it black, despite the colour being set to black. Changing the colour property does change the colour, but not as expected. The problem goes away if the camera is switched to the Forward rendering path.

The problem seems to be tied to the colour of the directional light in the scene (The AO colour changes with the light's colour - which by default has a yellow tint. With deferred shading, black AO seems possible only with a black directional light).

To reproduce: Add 2 cubes close enough to each other to observe the AO effect in the default Unity scene. Set the main camera's rendering path to Deferred.

Example: (pink directional light + high intensity black AO, behaves as expected in Forward but not in Deferred)
![ppsv2aobug](https://user-images.githubusercontent.com/20382418/42122913-2751c1e6-7c41-11e8-9ad0-d8b45406eb9a.png)

Post-processing stack version: v2

Unity version 2018.1.1f1, OS: Windows 10, Target platform: Standalone Windows

**Comment by Chman** [comment]
Looking at the UI, "Ambient-only" is enabled. You'll want to uncheck it to get black AO regardless of the current lighting in your scene.

**Comment by cancinconn** [comment]
Ah, apologies, I had mistakenly thought the ambient-only would be off since the "master checkbox" to the left was off. I really should have caught that before submitting a report. Thanks!
