### ISSUE TITLE
[V2] Stretched reflections when using SSR

### ISSUE THREAD

**Issue by reunono** [Unity-Technologies/PostProcessing#613]
##### What happened?
Basically everytime I try to use Screen Space Reflections I get (what I think are) weird results, with reflections being "stretched" instead of looking like a more or less mirror image of the actual scene.

It looks like this : 
![image](https://user-images.githubusercontent.com/2212831/42536655-a44db11a-8460-11e8-852c-6ca87bc6fec1.png)

Here I've got a plane with a simple texture, metallic to 0, smoothness to 1. Cube reflections are more or less ok, but as soon as I put a slightly more complex model it just stretches weirdly like that. Am I missing some obvious setting somewhere?

Ground plane shader settings : 
![image](https://user-images.githubusercontent.com/2212831/42536671-b103e01e-8460-11e8-940f-90666b72cc23.png)

Camera + post processing setting : 
![image](https://user-images.githubusercontent.com/2212831/42536689-bb1e9d50-8460-11e8-8c85-3a933aeb3e0e.png)

Quality settings : 
![image](https://user-images.githubusercontent.com/2212831/42536744-e62ff5a2-8460-11e8-82f8-b002c6aeab03.png)

##### Post-processing stack version (v1, v2)?
Stack v2.0.7 preview installed via the Package Manager

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.1.6f1 on PC (problem is the same on different machines), PC build target

**Comment by CustomPhase** [comment]
Thats just how it works unfortunately. You can read more about it here:
#368

**Comment by reunono** [comment]
Alright. Thanks for the info.
Not sure in what situation this would have any value though.

**Comment by AaronMeyers** [comment]
For a lot of us, the performance gain is negligible because it looks heinous with any objects that aren't just big blocks, fully connecting to the ground. Any character on a shiny floor looks terrible with this method.

I'm not against Unity offering a more performant variation, but we need an option to have more accurate SSR.
