### ISSUE TITLE
Stack ordering issues

### ISSUE THREAD

**Issue by amartinez-cg** [Unity-Technologies/PostProcessing#62]
What is the recommended way to modify the ordering of the post processing stack?

I find some of the decisions made with respect to the order of operations are not acceptable for my intended use.  For example, I believe grain should be after vignette.  In real-world cameras, grain is a function of the film-stock or sensor, and vignette is an effect of the lens/housing before light hits the film back.  I also think AA should come after shading effects such as ambient occlusion and screen space reflection.

Also would it eventually be possible to insert components into the stack?  For example, I want to insert sun rays before depth of field, so that the volumetric effects are integrated into the look.   It seems like I would have to make significant modifications to allow this.

**Comment by Chman** [comment]
> I find some of the decisions made with respect to the order of operations are not acceptable for my intended use. For example, I believe grain should be after vignette. In real-world cameras, grain is a function of the film-stock or sensor, and vignette is an effect of the lens/housing before light hits the film back. I also think AA should come after shading effects such as ambient occlusion and screen space reflection.

Vignette is already done before Grain (and before tonemapping) and AA does happen after AO and SSR.

> Also would it eventually be possible to insert components into the stack? For example, I want to insert sun rays before depth of field, so that the volumetric effects are integrated into the look. It seems like I would have to make significant modifications to allow this.

It depends. If you do your sun rays before the transparency pass then you don't have anything to do, DoF being done after transparency. If you're doing sun rays after transparency, you can either do it in a separate pass/component and put it before the PostProcessingBehaviour component in the inspector or you can modify the behaviour code to add the effect where you want it to be (it doesn't require significant modifications, look at how current effects are handled to get an idea).

**Comment by amartinez-cg** [comment]
Thanks for the explanation, I was thrown by the order it shows up in the UI.
