### ISSUE TITLE
AO wrongly applied when using Standard Tesselation shader

### ISSUE THREAD

**Issue by Hoodad** [Unity-Technologies/PostProcessing#63]
Expected behavior is to apply the AO where the tesselated grass surface hits the curtains. Please see attached images.

The material used can be found at https://www.gametextures.com/wp-content/uploads/2016/11/Foliage_PlainMossCover_Substance.zip

![no_ao](https://cloud.githubusercontent.com/assets/232197/21843670/1c63219e-d7ec-11e6-9d7a-fd68c2df3874.png)
![with_ao](https://cloud.githubusercontent.com/assets/232197/21843674/1dffccaa-d7ec-11e6-870c-d6803e50ae4b.png)

**Comment by Chman** [comment]
Unless the material isn't writing to the depth & normal buffer correctly tessellation should work fine with AO. Could you post screenshots of debug views for Depth & Normal ?

**Comment by Hoodad** [comment]
Sorry for the late reply. Good tip! Here is the same scene with without AO, with AO, normals and depth. 
Just looking at it it seems like the tesselated plane is not rendered to the normals. I'm using the same material (_Image/Effects/Tessellation/Bumped Specular (displacement)_) on the sphere as on the floor.

![unity_2017_01_19_09_57_58_509](https://cloud.githubusercontent.com/assets/232197/22100052/2b1af142-de2e-11e6-97b3-86ad541c101f.png)
![unity_2017_01_19_09_58_00_315](https://cloud.githubusercontent.com/assets/232197/22100051/2b195864-de2e-11e6-8b12-9a6cab981096.png)
![unity_2017_01_19_09_58_04_294](https://cloud.githubusercontent.com/assets/232197/22100054/2b1ee78e-de2e-11e6-882c-3c3237246350.png)
![unity_2017_01_19_09_58_07_790](https://cloud.githubusercontent.com/assets/232197/22100053/2b1bfec0-de2e-11e6-90ec-43181cdd38fd.png)

**Comment by DuckyDuckling** [comment]
I just want to add in that I've also had this issue on tessellation shaders.

I'd send normals and depth, but it's more or less the same as seen above.

**Comment by Chman** [comment]
What happens when you switch to the deferred rendering path ?

**Comment by Hoodad** [comment]
Below is how the scene looks like with deferred rendering path. Please note that this is VR application using SteamVR 1.1.1.

![deferred_none](https://cloud.githubusercontent.com/assets/232197/22421404/3d91d90a-e6e7-11e6-857a-67af90dd68af.png)
![deferred_depth](https://cloud.githubusercontent.com/assets/232197/22421410/3fe61a54-e6e7-11e6-8f6d-7d74808668a0.png)
![deferred_normals](https://cloud.githubusercontent.com/assets/232197/22421413/413624d0-e6e7-11e6-9ef5-62a2c82eca36.png)

**Comment by Chman** [comment]
Normals are all wrong here, so AO won't work correctly. It looks like something's gone bad on the Steam VR side (unrelated to post-processing). You should report this on the official forums or send a bug request via Unity.

**Comment by Hoodad** [comment]
Alright thank you!
