### ISSUE TITLE
Depth of Field does not work with Forward rendering and MSAA (Unity 5.5.0p2)

### ISSUE THREAD

**Issue by JohannesDeml** [Unity-Technologies/PostProcessing#64]
Just pulled the last commit (8713baa51e9810c04a21194f99fb3aa4660e4f56) from the repo. Sadly the depth of field effect just creates a black output for forward rendering (it does with deferred rendering). This happens with MSAA enabled in the quality settings.
![animation](https://cloud.githubusercontent.com/assets/4518980/21892436/2c1708a8-d8d7-11e6-92e0-4715ae268fa9.gif)

[Project download](https://drive.google.com/file/d/0ByTO3RP9DQI0QUlESlJfOHFwSmc/view?usp=sharing) (It is really just the post processing stack with the calibration scene)

Edit: I just notice that this is due to MSAA. I will however still leave the issue open, because that case is not noted in the [known issues](https://github.com/Unity-Technologies/PostProcessing/wiki#known-issues) so far.

**Comment by Chman** [comment]
I edited the known issues section to add Depth of Field to the list, thanks !
I'm closing this as it's fixed in Unity 5.6 (it's too risky a change to bring to 5.5 at this stage unfortunately).
