### ISSUE TITLE
How to downsample maintex to improve performance?

### ISSUE THREAD

**Issue by ifurkend** [Unity-Technologies/PostProcessing#647]
I am new to post-processing and want to write my own effect with pps v2, but I don’t know how to downsample the maintex. I looked at bloom’s fast mode, but the code is too complicated for me to skim through. Is it possible to show a much simplified code for downsampling the fx?

**Comment by zworp** [comment]
I ended up doing like this (seems to work)

		var cmd = context.command;

		float downScale = 2f;

		int width = Mathf.FloorToInt(context.screenWidth / downScale);
		int height = Mathf.FloorToInt(context.screenHeight / downScale);

		//make temp downsampled texture and do effect
		context.GetScreenSpaceTemporaryRT(cmd, downScaleRtId, 0, context.sourceFormat, RenderTextureReadWrite.Default, FilterMode.Bilinear, width, height);
		cmd.BlitFullscreenTriangle(context.source, downScaleRtId, sheet, 0);

		//upsample to screen using simple shader
		sheet = context.propertySheets.Get(simpleBlitShader);
		cmd.BlitFullscreenTriangle(downScaleRtId, context.destination, sheet, 0);



my simpleBlitShader is just:

		float4 Frag(VaryingsDefault i) : SV_Target
		{
			return SAMPLE_TEXTURE2D(_MainTex, sampler_MainTex, i.texcoord);
		}

**Comment by ifurkend** [comment]
I finally get the basic of progressive resampling blur in PPS2 after reading all the tutorials and docs of the traditional PP.


	using System;
	using UnityEngine;
	using UnityEngine.Rendering.PostProcessing;

	[PostProcess(typeof(BlurRenderer), PostProcessEvent.AfterStack, "Hidden/Custom/Blur")]

	public sealed class Blur : PostProcessEffectSettings
	{
		[Range(1,40)] public IntParameter _iterations = new IntParameter { value = 8 };
		[Range(1,32)] public IntParameter _downsampling = new IntParameter { value = 4 };
	}
	public sealed class BlurRenderer : PostProcessEffectRenderer<Blur>
	{
		public override void Render(PostProcessRenderContext context)
		{
			var sheet = context.propertySheets.Get(Shader.Find("Hidden/Custom/Blur"));
			var cmd = context.command;
			
			int width = Screen.width;
			int height = Screen.height;
			
			context.GetScreenSpaceTemporaryRT(cmd, 0, 0, context.sourceFormat, RenderTextureReadWrite.Default, FilterMode.Bilinear, (int)(width / (settings._downsampling)), (int)(height / (settings._downsampling)));
			cmd.BlitFullscreenTriangle(context.source, 0, sheet, 0);
			
			//Downsampling:
			for (int i = 0; i < (settings._iterations - 1); i++) {
				context.GetScreenSpaceTemporaryRT(
					cmd, (i + 1), 0, context.sourceFormat, RenderTextureReadWrite.Default, FilterMode.Bilinear, 
					(int)(width / (settings._downsampling + i + 1)), 
					(int)(height / (settings._downsampling + i + 1))
				);
				
				cmd.BlitFullscreenTriangle(i, (i + 1), sheet, 0);
			}
			
			//Upsampling:
			for (int i = (settings._iterations - 1); i > 0; i--) {
				cmd.BlitFullscreenTriangle(i, (i - 1), sheet, 0);
			}
			
			cmd.BlitFullscreenTriangle(0, context.destination, sheet, 0);
		}
	}
