### ISSUE TITLE
Bloom and creating Cubemaps

### ISSUE THREAD

**Issue by justinwasilenko** [Unity-Technologies/PostProcessing#65]
I am using Unity also for content creating and the new PostProcessing stack is awesome!

I'm creating scenes, (in my case space scenes) and then using the [360 Panorama Capture](https://www.assetstore.unity3d.com/en/#!/content/38755) asset to render out to a 6 sided cubemap to be used as a Skybox for the game.

When using Bloom both a 6 sided cubemap and horizontal (seen below) have issues with bloom when it's captured in this manner. You can see the visible lines in the Bloom effect.

![cubemap_bloom_issue](https://cloud.githubusercontent.com/assets/11709400/21965282/e662a122-db5c-11e6-98ac-ab16ec0a25b2.jpg)

Not sure if this is possible but would be awesome to be able to capture the Bloom in this manner.

**Comment by Chman** [comment]
The "lines" you see are actually cubemap face borders. The reason it does that is because the glowing star is only present on one of the faces, so when it's rendering other faces bloom won't do much there. Bloom only knows about what's on screen (in the frustum of a camera).

Unless you're very low on available GPU resources, I would recommend not trying to bake bloom into the skybox. Render a HDR cubemap and any bloom applied to the game will apply to the cubemap as well. Note that this will only work correctly with Unity 5.5+.

**Comment by justinwasilenko** [comment]
Yeah the game is on Gear VR and Daydream, so GPU is extremely limited. Although I haven't tried it I already know Image Effects come at too great a cost for mobile VR. 

I'm guessing their is no way for a 'World Space' Bloom type filter?

**Comment by Chman** [comment]
Bloom is a post-processing effect. It affects pixels on screen (and only knows about these pixels). There's no concept of "world-space", at least not the way you're thinking.

If you're pre-processing your skybox anyway, why not do your own bloom in Photoshop ?

**Comment by justinwasilenko** [comment]
Too save time, I'm using 6 sided Skyboxs because they have been providing much better image quality compared to a LatLong cubemap at much lower texture memory usage.

With the 6 sided cubemap it's very time consuming to stitch and rotate and flip each side to match. If it was just one skybox it's not such a big deal, but when you have 20 to do, it takes forever.

Thanks for the responses though!

**Comment by KelSolaar** [comment]
> Too save time, I'm using 6 sided Skyboxs because they have been providing much better image quality compared to a LatLong cubemap at much lower texture memory usage.

Are you really saving time here? You could do that in The Foundry Nuke (or Photoshop as suggested by @Chman) and process all the images in a script using the SphericalTransform node to recombine them as a LatLong image for example.

**Comment by justinwasilenko** [comment]
Don't have Nuke, I did it in Photoshop before, but it was time consuming lining up all the edges.

**Comment by KelSolaar** [comment]
If you are in Photoshop, you can use Flexify (http://www.flamingpear.com/flexify-2.html) to perform space change for your image from whatever is your input to LatLong and back. Worst case scenario you can wrap that in Action(s) to make it easy.

There is a free non commercial edition of Nuke (https://www.thefoundry.co.uk/products/non-commercial/) that should work fully for what you intend to do.

My point being that you should have no edge lining up to do, you would prepare the Photoshop Action(s) / Nuke scripts once and that is it.

**Comment by justinwasilenko** [comment]
Thanks for the suggestions! I'll take a look into them.
