### ISSUE TITLE
SSR not work on PS4

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#67]
SSR not work on PS4

**Comment by Chman** [comment]
Hi, can you send us more details ? Do you get any error in the console ? How does it "no work" exactly ?

**Comment by silentlamb1991** [comment]
Hi, I'll send you details tomorrow.

**Comment by silentlamb1991** [comment]
Sorry there is no any build error or runtime error, this is all log after app running:
[All.txt](https://github.com/Unity-Technologies/PostProcessing/files/715743/All.txt)

This is a screenshot on PC:
![qq 20170119125557](https://cloud.githubusercontent.com/assets/18855621/22094544/22387d90-de49-11e6-9790-22538019a784.png)

And This is a photo on PS4, can't see SSR effect:
![qq 20170119125311](https://cloud.githubusercontent.com/assets/18855621/22094602/7093e7ae-de49-11e6-8ace-b370d0ebde42.jpg)

**Comment by Chman** [comment]
Thanks, I'll look into it in the coming days. According to the log you're running Unity 5.4, is that correct ?

**Comment by silentlamb1991** [comment]
Yes.

**Comment by Chman** [comment]
I haven't been able to reproduce this. SSR works fine with `Unity 5.4.2f2 - PS4 SDK 4.010.001`.

You should probably update Unity to the latest 5.4 version as yours is a bit out of date and let us know if it works any better for you.

**Comment by Kink3d** [comment]
Closed due to inactivity
