### ISSUE TITLE
v2.0.15 breaks custom effects in 2018.3

### ISSUE THREAD

**Issue by Jonny10** [Unity-Technologies/PostProcessing#676]
In v2.0.15 the _[ShaderIncludePath]_ attribute was disabled for 2018.3, apparently due to a warning.

Unfortunately, in its absence, custom effects cannot locate the StdLib.hlsl file anymore.

https://github.com/Unity-Technologies/PostProcessing/commit/8912a1c081e4364a4c5bfc8d31a8dd120f107c59#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

Is this a temporary workaround during the development of 2018.3?

**Comment by Chman** [comment]
`[ShaderIncludePath]` has been disabled in 2018.3 as it's deprecated (to be removed) on the engine side.

You have to use the full path to the package, the way it's done with SRPs:
```
"Packages/com.unity.postprocessing/PostProcessing/Shaders/StdLib.hlsl"
```

This should do the trick, I'll have to update the doc as well, good catch.

**Comment by Jonny10** [comment]
Thanks for the clarification @chman!
