### ISSUE TITLE
Debug component isn't doing anything.

### ISSUE THREAD

**Issue by keenanwoodall** [Unity-Technologies/PostProcessing#677]
##### What happened?
I added the "Post Process Debug" component to the global post processing volume in the sample scene so I could test the depth debug overlay. I dragged the main camera onto the post process layer field. It didn't work. I pressed play and it still didn't work.
##### Post-processing stack version (v1, v2)?
v2 (the one that ships with hdrp)
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
2018.2.11f1 Windows 10

![image](https://user-images.githubusercontent.com/9631530/46931416-a7ea3b80-d010-11e8-8fff-c4bfcba23ff1.png)

**Comment by keenanwoodall** [comment]
Not sure if this is relevant, but I opened the Post Process Debug component in Visual Studio and the code within `#if UNITY_EDITOR` is greyed out. I don't think it is getting run even though I'm in the editor.
![image](https://user-images.githubusercontent.com/9631530/46965118-8e2c1100-d06f-11e8-9fe9-9e1b2ae9e6c5.png)

**Comment by eugenegoncharov** [comment]
Did you manage to fix this issue? Because I got the same problem

**Comment by MaXDon** [comment]
+1

**Comment by ShuchangXu** [comment]
Same problem occurred to me. Did anyone know how to fix it? Thanks!
