### ISSUE TITLE
The design is not good for animation

### ISSUE THREAD

**Issue by silentlamb1991** [Unity-Technologies/PostProcessing#68]
Now all data is stored in profile and no copy in runtime, if modify data via script would change profile. The solution is cloning a profile in memory and set to PostProcessingBehaviour, but I think there should be a better way to do that.

**Comment by fdsagizi** [comment]
i think too, 
and if we want change some values, for graphics settings example, its ugly too

**Comment by rsodre** [comment]
Another problem with the current workflow is that by cloning the profile in run time there's no way to tweak it while the game is playing

**Comment by Chman** [comment]
Duplicate of #11.
