### ISSUE TITLE
Custom Effect (Failed to open source file StdLib.hlsl)

### ISSUE THREAD

**Issue by antpaw** [Unity-Technologies/PostProcessing#687]
##### What happened?
I've created a new project, enabled the LWRP, installed the PostProccing package via Package Manager. Included the two files (.cs and .shader) from your [wiki tutorial](https://github.com/Unity-Technologies/PostProcessing/wiki/Writing-Custom-Effects). Now I'm stuck with this error:
```
Shader error in 'Hidden/Custom/Grayscale': failed to open source file: 'PostProcessing/Shaders/StdLib.hlsl' at line 7 (on metal)
```

##### Post-processing stack version (v1, v2)?
v2

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2018.3.0b6, editor, mac mojave 

**edit**: super small example project https://ufile.io/qja5w (30 days link)

**Comment by netarc** [comment]
I encountered this issue as well recently, but later discovered the include usage has changed from:

```#include "PostProcessing/Shaders/StdLib.hlsl"```

to the following:

```#include "Packages/com.unity.postprocessing/PostProcessing/Shaders/StdLib.hlsl"```

**Comment by greggregolon** [comment]
Facing the same issue here, but even your solution didn't worked.
I'm using 2018.2.13f1.

**Comment by antpaw** [comment]
thanks it worked!

**Comment by noio** [comment]
@greggregolon 

In **Unity 2018.2** I had to use

`#include "PostProcessing/Shaders/StdLib.hlsl"`

In **Unity 2018.3** I am back to:

`#include "Packages/com.unity.postprocessing/PostProcessing/Shaders/StdLib.hlsl"`

**Comment by AGamlin** [comment]
2019.1.0f2 with lwrp(5.13.0) this problem still occurs on two shaders in PP package.

Fortunately netarc's original suggestion fixes it.

**Comment by stuGaming** [comment]
Having this issue still with 2018.3.14f. Was able to fix most of the issues except for one shader ScreenReflections which i had to remove completely.
