### ISSUE TITLE
big run time size on iOS

### ISSUE THREAD

**Issue by fdsagizi** [Unity-Technologies/PostProcessing#70]
Hi! If we use post processing, just one item - like color filter on iOS

it takes 50 mb run time! Its extremely huge, on iPhone 6 available only 600 mb.

**Comment by gokselgoktas** [comment]
You have the exact same issue reported previously #59. Pretty please, stop creating duplicates of issues that have already been reported previously.

We will evaluate the open issues in due time and get back to you as soon as we humanly can.
