### ISSUE TITLE
Unity becomes unresponsive when Alt-Tabbing

### ISSUE THREAD

**Issue by justinwasilenko** [Unity-Technologies/PostProcessing#77]
With the Post-Processing stack added into the project and enabled on a camera in the scene, Unity becomes unresponsive when alt tabbing between other open Unity instances running.

This is happening in Unity 5.4.3p1 on Windows 10. 

Unity doesn't crash, but maintains a 12% cpu usage and trying to come back to the Unity window doesn't work. Have to use TaskManager to close. No error messages shown.

**Comment by Kink3d** [comment]
Hi,

I haven't been able to reproduce this issue. You are referring to multiple editor instances right? What versions are they running? Is there any other information you can give me to help reproduce this? Perhaps it is specific to your project also.

Thanks

**Comment by justinwasilenko** [comment]
Hi Matt, it could be my project, but not sure why.

It has happened to me yesterday as well with just one instance of Unity
running. Using Unity 5.4.1p1, and 5.5.0p4.

When it happened yesterday it was using 5.4.1p1. It doesn't happen all the
time. For example yesterday I switched to Photoshop, tried to come back to
Unity and couldn't. Had to open task manager to close Unity. Only happened
Post-Processing FX turned on. Maybe a driver issue? Running a Nvidia 1070
gtx with 376.33 drivers on Win 10.

**Comment by Kink3d** [comment]
Ok this may be difficult to track down. Next time this happens can you send your editor log please. (User > Appdata > Local > editor.log). There may be clues in there...

**Comment by Kink3d** [comment]
Closing due to lack of response
