### ISSUE TITLE
Depth of field is broken on Android, iOS, TVOS, Switch

### ISSUE THREAD

**Issue by NuclearCookie** [Unity-Technologies/PostProcessing#783]
##### What happened?
I create a postprocessing volume with depth of field as shown in the next screenshot

![image](https://user-images.githubusercontent.com/5354914/55090422-5eb61180-50af-11e9-96d0-416cfe225ca8.png)

On normal targets, the result looks like this:
![image](https://user-images.githubusercontent.com/5354914/55090510-89a06580-50af-11e9-80e8-ac84ef7a7609.png)

on switch, it looks like this:
![image](https://user-images.githubusercontent.com/5354914/55090470-7392a500-50af-11e9-8770-b34f042edf0e.png)

##### Post-processing stack version (v1, v2)?
Latest: 2.1.4, 2.1.5
The bug does not appear on 2.1.3

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?

Unity 2018.3.5f, 2018.3.9f, Windows, Targetplatform Switch

**Comment by NuclearCookie** [comment]
The difference seems to be that the switch was previously using 

`var colorFormat = RenderTextureFormat.DefaultHDR;` in DepthOfField.cs
but now it's using
`var colorFormat = context.sourceFormat;`.

This changes the colorFormat from `DefaultHDR` to `RGB111110Float`

**Comment by NuclearCookie** [comment]
The change is caused by this function which does not return `DefaultHDR` on switch.

```
/// <summary>
        /// Gets the default HDR render texture format for the current target platform.
        /// </summary>
        public static RenderTextureFormat defaultHDRRenderTextureFormat
        {
            get
            {
#if UNITY_ANDROID || UNITY_IPHONE || UNITY_TVOS || UNITY_SWITCH || UNITY_EDITOR
                RenderTextureFormat format = RenderTextureFormat.RGB111110Float;
#if UNITY_EDITOR
                var target = EditorUserBuildSettings.activeBuildTarget;
                if (target != BuildTarget.Android && target != BuildTarget.iOS && target != BuildTarget.tvOS && target != BuildTarget.Switch)
                    return RenderTextureFormat.DefaultHDR;
#endif // UNITY_EDITOR
                if (format.IsSupported())
                    return format;
#endif // UNITY_ANDROID || UNITY_IPHONE || UNITY_TVOS || UNITY_SWITCH || UNITY_EDITOR
                return RenderTextureFormat.DefaultHDR;
            }
        }
```

**Comment by wowaaa** [comment]
I have exactly the same broken DoF effect targeting Android and within Editor on Unity 2018.3.6f1. Both 2.1.4 and 2.1.5 version has it since the `context.sourceFormat` was introduced. And actually, the pointed up `defaultHDRRenderTextureFormat `was introduced [a quite long time ago](https://github.com/Unity-Technologies/PostProcessing/pull/475), so don't know if the expected behavior changed since then, or no-one has seen that because of the hardcoded `RenderTextureFormat`, if that is the origin of this issue.

**Comment by AtomicJoe1** [comment]
I can confirm this is happening to me on an Android Vulkan project both in editor and in build.
Changing line 164 in DepthOfField.cs to force a true HDR buffer fixes it:
`			var colorFormat = RenderTextureFormat.DefaultHDR;// context.sourceFormat;`

**Comment by NuclearCookie** [comment]
@Chman 
When do you plan to fix this? 

Or can you point is in the right direction of what's wrong here so the community can fix this?

**Comment by NuclearCookie** [comment]
After 1 month, I reported this issue through the bug reporter:
https://fogbugz.unity3d.com/default.asp?1149314_65hrck39d9q67566

**Comment by NuclearCookie** [comment]
The issue is now tracked here:
https://issuetracker.unity3d.com/issues/darker-post-processing-effect-when-platform-is-set-to-ios-or-android

**Comment by FMS-Cat** [comment]
`FragBlur` pass uses the alpha channel and `FlagCombine` attempts to use the channel,
Then it fails under `B10G11R11` buffers...

**Comment by NuclearCookie** [comment]
Hopefully fixed in https://github.com/Unity-Technologies/PostProcessing/commit/997e0c143ebfc817521a7f65170bb95dabb5e9b7

**Comment by FMS-Cat** [comment]
yeah I think so

**Comment by NuclearCookie** [comment]
Confirmed as fixed
