### ISSUE TITLE
TAA quality issue

### ISSUE THREAD

**Issue by asdfgasdfsafgsdfa** [Unity-Technologies/PostProcessing#79]
Hey,

coming from [this thread](https://forum.unity3d.com/threads/temporal-anti-aliasing.412482/page-4).
TAA doesn't work well for me.
Here's a video and some screenshots:

Video (50mb): https://mega.nz/#!gBBRzQqA!5DfJXSD8fJam9qaCBHdu0IXiojGca4KlYMhXgewqTaE
No AA: http://i.imgur.com/Q09xFW9.png
SMAA: http://i.imgur.com/nu0FO0S.png
TAA: http://i.imgur.com/Xrrtfnq.png

And a demo scene: 
"scene1" (35mb): https://mega.nz/#!8VA3GAoA!ulT8omF3fDGptqM2qt-JznZmFv9ZuUYagBPkdO0dJvI

Unity Version: **5.5.0f3**

Seems to happen when transparent stuff and/or skybox and/or UI elements are involved.

More TAA examples:
TAA On: http://i.imgur.com/lb9NC4u.png
No AA: http://i.imgur.com/9OAm8bY.png

Now I could reduce spread, stationary and motion all to <0.4, then turn up sharpen to fix it a bit:
Like this: http://i.imgur.com/Ig3Ce6f.png
But the then - as you can see - edges are jagged as hell, Text is more blurry than before...

It seems likely that you guys will only address the extreme "ghosting" artifacts.
But I'd like to put emphasis on another problem as well:
Panokani on the unity forums said:
"To the contrary, so far our empirical evidence shows that TAA is vastly superior in comparison to SMAA we have had."

But I have to disagree. I managed to somehow fix the ghosting (after half an hour of randomly messing around in the settings, disabling and re-enabling things),
after that I still didn't get the same level of edge-smoothing as SMAA provides.

I don't know what empirical evidence you have but I'd like to see it:

Lets see what we can do with only **NO** motion is involved so we can bypass the strange blending issues mentioned above:

Static Camera and geometry, grass can be ignored.

no aa: http://i.imgur.com/ezuEVJ6.png
smaa: http://i.imgur.com/bGb7W3o.png
taa @ default (0.75, 0.95, 0.85, 0.3): http://i.imgur.com/ex609Lt.png
and finally everything disabled + 8xMSAA in forward mode: http://i.imgur.com/PpHD2cG.png

I don't know about you, but TAA does not look "vastly superior". Even saying it is on the same level as SMAA would not be true. Just look at the screenshots.
SMAA looks indistinguishable from a lot like 8xMSAA, while TAA combines the worst of both worlds: blurry grass + jaggy edges :P 

Not trying to talk your work bad here! I just want to see at which comparisons TAA comes up as the winner (that empirical evidence).

I hope there's something that can be done about this.
You guys already have an excellent SMAA implementation, why not add it to the PostProcessing stack as an option, so people can chose what they think looks best? That'd be a huge step in the right direction imho.

**Comment by Chman** [comment]
> Not trying to talk your work bad here! I just want to see at which comparisons TAA comes up as the winner (that empirical evidence).

Any PBR scene with any sort of specular highlights or reflections. SMAA will not work at all in cases like that and is slower than TAA. MSAA won't help either with specular aliasing. From the same thread you linked:

[No AA](http://i.imgur.com/MWt1h6n.png)
[SMAA](http://i.imgur.com/DRydgDY.png)
[TAA](http://i.imgur.com/ksXk7hc.png)

These were taken with an older version of our TAA. The current one is sharper on that very same scene.

> I don't know about you, but TAA does not look "vastly superior". Even saying it is on the same level as SMAA would not be true. Just look at the screenshots.

Yes, just look at the screenshots :)

Another advantage to TAA is the effect it has on sample-based effects (e.g. AO). Thanks to the temporal nature of the effect, you can reduce the sample count of other effects and get results as good as higher quality settings while getting more performances (samples will be accumulated over frames).

**Comment by gokselgoktas** [comment]
Also, would it be possible for you to share that scene with the house in it? It looks very very wrong with TAA. To the point, what you're seeing isn't even close to what you should be seeing. I'd like to verify a few things.

**Comment by asdfgasdfsafgsdfa** [comment]
@Chman agreed, looks much better with taa in those screenshots.
@gokselgoktas not sure if i can its difficult, but i'll see what i can do.

**Comment by asdfgasdfsafgsdfa** [comment]
https://mega.nz/#!0Mh3Bazb!XdXArjnxBOGhrv7HuGht1poQeHu11pAdg4GikdmIZ_A

**Comment by asdfgasdfsafgsdfa** [comment]
Another issue with temporal AA appears when using projectors:

https://streamable.com/8elwi

Simply disabling TAA, or switching to another anti aliasing method (SMAA or FXAA) fixes it.
Surprisingly "Spread" has no effect on the intensity of the problem at all!

The projector in the video uses a custom shader, however its still present when using the normal unity Light and Shadow projector shaders.

**Comment by asdfgasdfsafgsdfa** [comment]
@gokselgoktas @Chman 

Another issue with temporal AA appears when using projectors:

https://streamable.com/8elwi

Simply disabling TAA, or switching to another anti aliasing method (SMAA or FXAA) fixes it.
Surprisingly "Spread" has no effect on the intensity of the problem at all!

The projector in the video uses a custom shader, however its still present when using the normal unity Light and Shadow projector shaders.

**Comment by gokselgoktas** [comment]
@asdfgasdfsafgsdfa I am sorry but how is it a good demonstration of brokenness if you're purposefully breaking the algorithm and then claiming it is broken? You set spread to 0.1 (it should almost never be), both of the blending factors to 1 (they MUST never be both 1) and the sharpen to its maximum value of 3, and claim that it doesn't look good... Did you expect it to look good? This isn't exaggerating anything, it's just purposefully breaking the algorithm.

I just set the values to their defaults (0.75, 0.95, 0.85, 0.3), and took two screenshots.
Here's SMAA: <img width="991" alt="house-smaa" src="https://cloud.githubusercontent.com/assets/3808106/22403800/1de4c854-e62b-11e6-9680-24dbd9d3c622.png">

Here's TAA: <img width="991" alt="house-taa" src="https://cloud.githubusercontent.com/assets/3808106/22403797/1882b5ba-e62b-11e6-9100-6e06f63e2299.png">

You tell me which one looks more antialiased, and which one is missing half of the aliasing in high frequency regions?

I am not saying you're not experiencing a problem. But looks like something else is very broken for you somewhere else, and it'd be nice if we could find it.

**Comment by Chman** [comment]
@asdfgasdfsafgsdfa I wonder... Using that same house scene and putting TAA settings to their default values (0.75, 0.95, 0.85, 0.3) could you build a player a see if there's any difference with what you're seeing in the editor game view ?

Also, what's your platform & graphics api ? Windows/Mac/Linux ? DirectX/OpenGL/Metal ?

**Comment by asdfgasdfsafgsdfa** [comment]
@gokselgoktas 
You misunderstood me. I wasn't claiming taa is broken. I was wondering if thats the result one should get from the extreme settings, or if its a hint that something else is broken. I never said I expected the algorithm to work fine with those settings.

In your two screenshots TAA looks better in 90% of the cases, however here its not:  http://i.imgur.com/kV5jasl.png
I wonder why? It does such a good job basically everywhere in your example, but at the top of the house it somehow produces "harder" edges than SMAA, why?

@Chman 
Will try later.
Platform: Windows, Api: Dx11

**Comment by gokselgoktas** [comment]
@asdfgasdfsafgsdfa I am quite confused. Your original screenshots were taken as if you're experiencing a horrible output / bug with TAA using reasonable settings. Was this not the case?

The reason you're seeing slightly harder edges in TAA is due to the default sharpen value we use. TAA functions by reprojecting historically accumulated subpixel information into the current frame. In some (most) cases this leads to a soft and "blurry" image. One inherent part of almost all TAA algorithms is a sharpen filter in order to counter this blurriness at least a little.

Here, I disabled sharpen for you: <img width="991" alt="screen shot 2017-01-30 at 08 59 28" src="https://cloud.githubusercontent.com/assets/3808106/22414812/41d16ef2-e6cb-11e6-862f-d8bf310b8f91.png">

And here's the exact same shot with SMAA once again for the sake of completeness: 
<img width="991" alt="screen shot 2017-01-30 at 09 04 43" src="https://cloud.githubusercontent.com/assets/3808106/22414815/4e503e1a-e6cb-11e6-8e10-d2700ec16bd9.png">

See, with no sharpen TAA is actually even smoother than SMAA when it comes to the top edge of the house, but now you lost quite a bit of detail in the rest of the image. That's because while SMAA is an edge-based AA algorithm, TAA is not; it operates on the full framebuffer. This is why SMAA misses most of the aliasing in the images while TAA is able to deal with the situation rather well.

It's a game of compromises.

**Comment by gokselgoktas** [comment]
@asdfgasdfsafgsdfa As for the extreme settings... Extreme settings are there for people who know what they're doing.

If you are jittering only 10% of the texel size to generate your subpixel information (read: not generating much) while trusting 100% of the history for both the stationary fragments and fragments in motion (pixel trails everywhere), all the while applying 300% sharpening on the output, you really shouldn't be expecting AAA eye candy.

Your car can also probably hit around 300km/h, doesn't mean you should drive it at that speed.

I feel maybe we weren't able to communicate what the parameters do. I'll take a look at the documentation.

**Comment by asdfgasdfsafgsdfa** [comment]
> Your original screenshots were taken as if you're experiencing a horrible output / bug with TAA using reasonable settings. Was this not the case?

It was (and still is) the case. At default settings I'm getting unreadable UI text (in a worldspace canvas).


Your explanation on how taa works is great and should be included in the documentation, along with what each parameter does.

Again: I was not expecting `AAA eye candy` at all with these parameters. I was just trying to visualize the UI problem more (text in worldspace is unreadable, even at default settings).

I think we had a misunderstanding because I was commenting on multiple things at the same time, the main problem (ui text), as well as general TAA to SMAA comparisons, my apologies.

**Comment by cameronoltmann** [comment]
TAA is horrible for UI text.  If I'm using TAA, I put text on a separate camera.

**Comment by gokselgoktas** [comment]
TAA is very good at getting rid of specular and peak aliasing, which usually manifest itself as flickering / fast moving strokes of high contrast points and lines in the image, which is exactly what your fast moving, tiny world space text is.

TAA is doing what it's good at and getting rid of what it identifies as a source of aliasing. Usually games deal with this by overlaying their world space text onto the scene and applying a different post-processing stack to that part of the render pipeline. You might elect to use TAA again with different parameters than the one you use to AA your scene, or you might not. Up to you really.

This is a nonissue.

As for your TAA to SMAA comparisons, I have to say it was quite misleading. You compared a well-configured SMAA to a purposefully broken TAA with handpicked values to make it look its worst and claimed TAA is inferior based on that. I don't get the point.
