### ISSUE TITLE
Render To Camera Target prevents game view from updating at all (black screen or frozen screen)

### ISSUE THREAD

**Issue by efruchter** [Unity-Technologies/PostProcessing#795]
##### What happened?
Render to Camera Target prevents game/headset screen from updating when in VR mode. If Render to camera target is turned off, the resulting image in game view will update, but be blurry (perhaps it is not full-res, or lacks MSAA? The exact problem is unclear).

##### Post-processing stack version (v1, v2)?
v2
##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity 2019.1.0f2 PC VR Enabled, Tested on an Oculus Rift.

**Comment by caioc2** [comment]
I'm having the same problem, using the options "directly to camera target" gives a black screen.

**Comment by SoulSharedGames** [comment]
I am also having this problem when I updated to Unity 2019.

My game can be played in VR or normally using a FPS controller (UFPS).  Both modes have the black screen issue and I have found some work arounds for now.

**FPS Mode** (I'm using UFPS)
My FPS setup is using two cameras. A World Camera (clear flag: Skybox) and Weapon Camera (clear flag: Depth Only). I found when I set the X on the Viewport Rect to 0.0001 on the World Camera (Skybox) the problem went away.

**VR Mode** (Using VRTK)
I could only get VR working by disabling the "diectly to camera target" option.

**Comment by hass101** [comment]
Hi, I am also having exactly the same issue using SteamVR and an HTC Vive.

**Comment by tchapman222** [comment]
Same exact issue using latest OculusSDK from the package manager (1.29.1) in Unity 2019.1.0f2.

**Comment by Timeswitch** [comment]
Same problem :(
Everything was working fine on 2018.3, updating to 2019.1 broke the whole stack for me.
Directly to Camera doesn't work at all and without it everything looks like it's rendering at half the resolution.

Something else I noticed: turning off HDR and MSAA on the Camera fixes the blur, but creates this nice effect: [Screenshot](https://imgur.com/NwO3WYd)
The Image seems to break in CommandBuffer.BeforeImageEffects -> Post-processing -> Draw Dynamic.

All of this happens in a fresh Unity project with nothing but SteamVR, no fancy rendering pipelines.

**Comment by Zynek90** [comment]
Hello, 
similiar issue. I am using this in combination with Pixel Perfect Camera. It started after Unity update 2018.3.7 -> 2019.1.3f1.
On Mac the screen appears frozen or black when "Directly To Camera Target" is ON.
On Windows the screen appears frozen or black when "Directly To Camera Target" is OFF.

**Comment by Inspyro** [comment]
Same here, post processing + world space canvas in overlay camera seem to cause the first camera to only render a black screen (where the post-process layer is on)

**Comment by capitaljmedia** [comment]
Same here, if I turn off Directly to Camera Target it works but everything is a bit soft.

**Comment by cyecp** [comment]
same problem on unity2019.1.5f1

**Comment by justgos** [comment]
managed to fix the blurriness after setting "Directly To Camera Target" to Off by commenting out the
`xrDesc.width /= 2;` line in _PostProcessing\Runtime\PostProcessRenderContext.cs_

some visual artifacts remain though, like colored after-images of some objects bleeding through the other, transparent ones

**Comment by Timeswitch** [comment]
> managed to fix the blurriness after setting "Directly To Camera Target" to Off by commenting out the
> `xrDesc.width /= 2;` line in _PostProcessing\Runtime\PostProcessRenderContext.cs_
> 
> some visual artifacts remain though, like colored after-images of some objects bleeding through the other, transparent ones

That works great! I removed ` //screenWidth /= 2;` at around line 81 as well. Looks like it used to on 2018.3/4 (I only use bloom for now), but who knows what this will break :(

By experimenting, I noticed that this bug does not occur with multipass rendering. I really hope the Unity team will fix this soon.

**Comment by tmould1** [comment]
v2
2019.1.7f1, Windows 10, Pc,

This results in a system that is unusable for my team.
Please bump up in priority.

**Comment by efruchter** [comment]
> > managed to fix the blurriness after setting "Directly To Camera Target" to Off by commenting out the
> > `xrDesc.width /= 2;` line in _PostProcessing\Runtime\PostProcessRenderContext.cs_
> > some visual artifacts remain though, like colored after-images of some objects bleeding through the other, transparent ones
> 
> That works great! I removed ` //screenWidth /= 2;` at around line 81 as well. Looks like it used to on 2018.3/4 (I only use bloom for now), but who knows what this will break :(
> 
> By experimenting, I noticed that this bug does not occur with multipass rendering. I really hope the Unity team will fix this soon.

Can any Unity developers speak to whether there are there any side effects to this fix? It can be a bit difficult to discern graphical bugs with the naked eye.

**Comment by dpggit** [comment]
The problem is still in Unity 2019.2.01f. I dont see blurriness but an artifact using htc vive, something like the pic shown by Timeswitch

**Comment by efruchter** [comment]
Closing this issue. We are encouraged to submit bugs in Unity packages through the unity bug reporter.
