### ISSUE TITLE
Build gets stuck on 'Packaging Assets - Resources.assets' [5.6.0b5]

### ISSUE THREAD

**Issue by danielmus100** [Unity-Technologies/PostProcessing#81]
My Unity is freezing when building as soon as it gets to the 'Packaging Assets - Resources.assets' stage on my 5.6.0b5 project, it works fine if I do not have the Post Processing pack in my assets.

Edit: Specifically the Shaders folder, it works fine without that folder.

**Comment by Chman** [comment]
Are you sure it's frozen ? Right now, the first build will take a long time depending on your hardware (see my reply to #39) so this may very well be what you're experiencing.

**Comment by danielmus100** [comment]
Hmm, possibly, I'm on an SSD though with some pretty high spec hardware, and I'm sure I've built it before, I'll leave it running for a lot longer though and see if it gets anywhere.

**Comment by danielmus100** [comment]
Oh, holy cow it actually did it, after 20 minutes! Ignore post :D

**Comment by Hyder61112** [comment]
Try To Turn Off Autobuild For Lighting. It Worked Fine Here. unity 5.6.1

**Comment by amitchai** [comment]
Same works for me. Thanks!
