### ISSUE TITLE
Build Failed: type or namespace name 'XR' does not exist in the namespace

### ISSUE THREAD

**Issue by ruidazeng** [Unity-Technologies/PostProcessing#820]
I am having this issue when I tried to use setup my antilatency hardware. Normally it opens to version "2017.2.0" but when I imported package, the version seems to be changing to "5.5.2". I am new to Unity, is there a standard way of solving this? Or likewise, has anyone else experienced this and has figured out a solution already?

Note: I did go through past issues but was only able to find a closed issue that did not include a solution.

This is the compilation error:

`Assets/Antilatency/Integration.Oculus/Scripts/AltTrackingOculus.cs(6,19): error CS0234: The type or namespace name XRSettings' does not exist in the namespace UnityEngine'. Are you missing an assembly reference?`

**Comment by ruidazeng** [comment]
Version of Unity.

**Comment by mniami** [comment]
What version is the correct one? I have it the same
