### ISSUE TITLE
Motion Blur effect remain after object stop move.

### ISSUE THREAD

**Issue by nestg** [Unity-Technologies/PostProcessing#83]
When i move a platform and stop de movement the motion blur effect remain in this object, the object appear blurred, please fix this problem.  aditional info: Unity 5.6b4 (the error happens in other versions too), DX9 and DX11 with linear / forward rendering.

**Comment by Kink3d** [comment]
Please see #80 

This is a bug in new Transform code with regards to updating the Motion Vector texture. As you can see in that thread the issue has been sent to the engine developers for resolution.

**Comment by nestg** [comment]
thanks.
