### ISSUE TITLE
NullReferenceException on RuntimeUtilities.get_copyStdMaterial in editor after every re-compile

### ISSUE THREAD

**Issue by zoeesilcock** [Unity-Technologies/PostProcessing#862]
##### What happened?
I just updated from version 2.1.6 to 2.2.1 and now every time Unity compiles my code I get error spam whenever the Game view is redrawn in the editor. Entering playmode or opening a different scene fixes the issue until I compile anything again. Everything else seems to work apart from previewing PostProcessing effects while the error spam is happening.

It appears that `s_Resources` is null on `RuntimeUtilities`. I saw that others have had issues with the `Resources` reference on the `PostProcessLayer` being null on older versions so I tried the fixes for that (make sure it has a reference, reset the `PostProcessLayer`, remove and add a new `PostProcessLayer`), none of those things helped. The reference was never null on my `PostProcessLayer`. Resetting and re-creating the `PostProcessLayer` did fix the issue until the next re-compile though. Re-compiling inside a scene without PostProcessing and then switching to a scene that has it does not cause the error spam.

The error spam consists of the following two errors repeated over and over again.

Error 1:
```
Assertion failure. Value was Null
Expected: Value was not Null

Appears to refer to: PostProcessing/Runtime/Utils/RuntimeUtilities.cs:268
```

Error 2:
```
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.Rendering.PostProcessing.RuntimeUtilities.get_copyStdMaterial () (at Library/PackageCache/com.unity.postprocessing@2.2.1/PostProcessing/Runtime/Utils/RuntimeUtilities.cs:269)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.BuildCommandBuffers () (at Library/PackageCache/com.unity.postprocessing@2.2.1/PostProcessing/Runtime/PostProcessLayer.cs:605)
UnityEngine.Rendering.PostProcessing.PostProcessLayer.OnPreCull () (at Library/PackageCache/com.unity.postprocessing@2.2.1/PostProcessing/Runtime/PostProcessLayer.cs:440)
```

Screenshot of my `PostProcessLayer`:
![inspector_debug](https://user-images.githubusercontent.com/554766/69332662-6e462400-0c57-11ea-94b0-3e7863666aec.png)

This issue seems similar to #861 but I made a separate issue as I am not using custom effects, I am only using ColorGrading so far.

##### Post-processing stack version (v1, v2)?
v2 (2.2.1)

##### Unity version, operating system, target platform (standalone windows, mac, iOS, PS4...)?
Unity version: 2018.4.12f1
OS: Windows 10 Pro, version: 1903, build: 18362.476
Target platform: Standalone Windows

**Comment by JesseTG** [comment]
I have this, too.  Unity 2019.3.0f1, on Ubuntu 19.10.

**Comment by zoeesilcock** [comment]
Yesterday I updated to the latest version (2.2.2) but the issue persists.

**Comment by zoeesilcock** [comment]
I went from 2.2.2 to 2.3.0 and now it's fixed.
