### ISSUE TITLE
If you use projectionMatrix it will not render properly

### ISSUE THREAD

**Issue by fine-matsumoto** [Unity-Technologies/PostProcessing#87]
Always thank you for a wonderful job!

I changed the value of the camera matrix for tilt and tilt correction.
Using "Post Processing Behavior" resulted in unintended results.
I will attach a screenshot.

![image](https://cloud.githubusercontent.com/assets/11779621/22721060/e4b2a546-edf1-11e6-803c-09a1841aecb2.png)

--
OS : windows7
GPU : GeForceGTX960 with 372.90 drivers
Unity : 5.5.0f3

**Comment by Chman** [comment]
The stack resets the projection matrix on every frame at the moment (required for TAA). We're looking into supporting custom matrices but right now we don't support them.

**Comment by fine-matsumoto** [comment]
Thank you very much for your reply.

It is a pity that TAA can not be used, but my project requires a custom matrix.
I would like to think of other methods.

**Comment by Kink3d** [comment]
The stack now only resets the projection matrix if TAA is enabled. In the future we intend to look into supporting custom matrices for TAA.

**Comment by Chman** [comment]
Just to clarify: supporting custom projection matrices for TAA isn't possible right now as we have no way of knowing how your custom matrix is supposed to be jittered. You'll have to provide your own jittered projection matrix for TAA using [this callback](https://github.com/Unity-Technologies/PostProcessing/blob/master/PostProcessing/Runtime/PostProcessingBehaviour.cs#L19).
