### ISSUE TITLE
Weird "burnt-out" look in dark areas with tonemapping enabled

### ISSUE THREAD

**Issue by CustomPhase** [Unity-Technologies/PostProcessing#9]
Basically subj. Heres the picture to illustrate what im talking about (enlarge the image to see better, near the edges of the light). All the settings are the same in both cases. Is it how its supposed to be?
Unity 5.4.2, deferred, hdr, linear.
![unitytonemapping](https://cloud.githubusercontent.com/assets/10864826/19623104/46150b56-98d6-11e6-9781-214a54152800.jpg)

**Comment by Chman** [comment]
Looks like a duplicate of #5 (fixed in current trunk). Are you working with the pre-built unity package ?

**Comment by CustomPhase** [comment]
Yes, beta3 package. Sorry, my bad, didnt see the tab with fixed issues. Just downloaded the newest repository, used it, and everything is fine there.
